### ISSUE TITLE
Smelting procs talents and trinket effects.

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1022]
Originally reported by: **Duninn (Bitbucket: [Duninn](https://bitbucket.org/Duninn), GitHub: Unknown)**

---

Smelting ore into bars seems to triggers talents or spell effects.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1025

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/1875
