### ISSUE TITLE
[Fish] "Your fish got away"

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1039]
Originally reported by: **chop88 (Bitbucket: [chop88](https://bitbucket.org/chop88), GitHub: Unknown)**

----------------------------------------

When fishing it usually happens : "Your fish got away", but though I'm really fast when fish proc and I have the right level for zone.

Could you fix it ?

Thx

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1043

**Comment by Saltgurka** [comment]
#1715
