### ISSUE TITLE
Corrections for my previous SQL commit

### ISSUE THREAD

**Issue by Schaka** [Looking4Group/L4G_Core#105]
Made some mistakes in my previous pull request (see comments).
Already deleted the core and everything, so making a new pull request would be too much effort.
@Pbeitelmann 

```
-- Incorrect ID for Silent Resolve Rank 1
DELETE FROM `spell_affect` WHERE entry = 14532 AND effectId = 1;
INSERT INTO `spell_affect` VALUES(14523, 1, 24368649060719);

-- Forgot Regrowth and Nature's Grasp for Druid's
UPDATE `spell_affect` SET `SpellFamilyMask`='12965527034267474' WHERE (`entry`='17118') AND effectId = 1;
UPDATE `spell_affect` SET `SpellFamilyMask`='12965527034267474' WHERE (`entry`='17119') AND effectId = 1;
UPDATE `spell_affect` SET `SpellFamilyMask`='12965527034267474' WHERE (`entry`='17120') AND effectId = 1;
UPDATE `spell_affect` SET `SpellFamilyMask`='12965527034267474' WHERE (`entry`='17121') AND effectId = 1;
UPDATE `spell_affect` SET `SpellFamilyMask`='12965527034267474' WHERE (`entry`='17122') AND effectId = 1;

```

**Comment by robinsch** [comment]
They don't even check what they are merging.

**Comment by Xadras** [comment]
Is this already live? Or did nobody recognize it? xD

**Comment by AnonXS** [comment]
not live yet, am not able to recheck this yet. (exp with spellmask tool etc)

**Comment by robinsch** [comment]
@AnonXS https://github.com/robinsch/SpellMaskCreator

**Comment by Saltgurka** [comment]
Is this still relevant or can it be closed?

**Comment by Schaka** [comment]
It's still relevant, unless someone has executed those queries

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3176/commits/6464567fee0207d97072a6137cf99bc7b043c9eb
