### ISSUE TITLE
Arelion's Mistress Quest

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1069]
Originally reported by: **Anonymous**

---

After travelling to buy the wine to give to her, she does begin to walk away, however another person happened to do it at the same time as me and the quest was not instanced so what went on for me, also went on for the other person, so when the other person casted the scroll, it ruined the quest for me since i couldn't cast my scroll and the blood elf (npc for the quest) died and the quest was completed for the other person but I can't complete my quest anymore since the npc is dead due to the other person's action. 

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1073

**Comment by moonsti** [comment]
The quest item can turn you into a rat, and you can supposedly re-apply it, and take damage in the form.
