### ISSUE TITLE
Omor shield wall

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1078]
Originally reported by: **hitpoint (Bitbucket: [hitpoint](https://bitbucket.org/hitpoint), GitHub: [hitpoint](https://github.com/hitpoint))**

---

Omor the Unscarred should be using his shield wall ability at 20% health. Instead he is using it when he's almost full health.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1082

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3205
