### ISSUE TITLE
Who are They?

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1086]
Originally reported by: **Anonymous**

----------------------------------------

When you start the quest "Who are they?", you get the buff called Shadowy Disguise. However when this buff is gained you should be friendly for all the npc's in Gragol'var Village except the shadowy Hunter. However the Succubus Minion's that are also located there remain hostile making it impossible to do the quest.

http://www.wowhead.com/quest=10040/who-are-they

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1090

**Comment by Saltgurka** [comment]
#2956
