### ISSUE TITLE
Odd names on npc?

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1087]
Originally reported by: **Kristoffer Christensen (Bitbucket: [Bagan95](https://bitbucket.org/Bagan95), GitHub: Unknown)**

----------------------------------------

In the horde area where you buy pvp gear in orgrimmar.

They have german/dutch names! :)

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1091

**Comment by Saltgurka** [comment]
Fix pending
