### ISSUE TITLE
Profession trainers speaks german

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1094]
Originally reported by: **Anonymous**

---

All profession trainers (what I have seen) in international servers speaks German in train window. The texts: "Hello xxx". 'Train me' are in English but inside of Train me, above the skills, there is German text.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1098

**Comment by Saltgurka** [comment]
Not something I've experienced. Clear cache if you played on a german server before.

Make individual reports if this happens for specific npcs

Closing
