### ISSUE TITLE
Greater Blessing of Sanctuary

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1100]
Originally reported by: **josh (Bitbucket: [Zyph](https://bitbucket.org/Zyph), GitHub: [Zyph](https://github.com/Zyph))**

----------------------------------------

Greater Blessing of Sanctuary (level 60 skill) for some reason requires Blessing of Sanctuary rank 5. Which is a level 70 spell here. It is supposed to require rank 4 of BoS as rank 2 of GBoS requires rank 5. And i know for a fact you can have greater blessing of sanctuary at level 60, since it was a vanilla spell. 

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1104

**Comment by AnonXS** [comment]
#2689
