### ISSUE TITLE
"Evil Draws Near"

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1106]
Originally reported by: **Anonymous**

---

Two issues with the quest.

1) Players are supposed to collect 20 Doom Skulls from mobs and use them with a provided item to summon Teribus the Cursed at the Writhing Mound. However, there are multiple Terebus mobs sitting around at the Writhing Mounds.

2) After pulling and killing one of them, the quest registers the kill and is marked as 'completed' in the quest log. However, it can not be turned in despite being marked as 'completed'.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1110

**Comment by Saltgurka** [comment]
Fixed next update

```
-- Group completion for Evil Draws Near
UPDATE `creature_ai_scripts` SET `action1_type`='26',`action1_param1`='10923' WHERE  `id`=2244103;
```
