### ISSUE TITLE
It's not possible to chain cast Eagle Eye

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1189]
Originally reported by: **Zarant (Bitbucket: [Zarant](https://bitbucket.org/Zarant), GitHub: Unknown)**

----------------------------------------

When using the /cast !Eagle Eye macro, it doesn't work after the second time you cast that spell, a comment in wowhead indicates that this macro worked on patch 2.1.3.

http://www.wowhead.com/spell=6197/eagle-eye#comments

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1171

**Comment by AnonXS** [comment]
#1248
