### ISSUE TITLE
Cant loot items

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1229]
Originally reported by: **Anonymous**

----------------------------------------

From time to time when Im in a party, I win and item by rolling but cant loot it and it says :"item  is till beeing rolled for" . But everyone rolled alrdy and I won it. Happens on normal loot (cloth/trash) also.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1158

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/1165
