### ISSUE TITLE
Seal of Blood

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1270]
Originally reported by: **Anonymous**

---

Seal of Blood deals more backlash damage then the 10% it is supposed to do. Could be a similar issue as it was on retail.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1208

**Comment by Saltgurka** [comment]
Solved when https://github.com/Looking4Group/L4G_Core/pull/3049 goes live.

It will not scale from JotC, but it will scale from Sanctity.
