### ISSUE TITLE
Minor display issue on Voidspawns

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1281]
Originally reported by: **Mark Turchik (Bitbucket: [Cringe95](https://bitbucket.org/Cringe95), GitHub: Unknown)**

---

When they cast mind sear their right hand lights up but the beam extends from the left.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1187

**Comment by Saltgurka** [comment]
Invalid
https://youtu.be/pDotPz_wm7U?t=36s
