### ISSUE TITLE
Priest - "Mind Controll"

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1357]
Originally reported by: **Anonymous**

---

When mind controll monsters, there is no monster abillities to use, also cannot attack other monsters with it

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1262

**Comment by Saltgurka** [comment]
Spells are probably missing in creature_template then. Bug reports like these are useless because you didn't give a single example of npc's this happens for. 

Closing
