### ISSUE TITLE
Group loot doesn't work

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1363]
Originally reported by: **Anonymous**

---

The group loot doesn't give corpses 50/50 between me and my friend. I can loot corpses which I shouldn't be able too

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1268

**Comment by Saltgurka** [comment]
https://github.com/Looking4Group/L4G_Core/issues/715
