### ISSUE TITLE
Warrior - Enrage(Talent) and Blood Craze(Talent) spell_proc_event

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1365]
Originally reported by: **Shal (Bitbucket: [Shalovski](https://bitbucket.org/Shalovski), GitHub: [Shalovski](https://github.com/Shalovski))**

---

Warrior's Enrage ability does not always activate when you are the victim of a critical strike (tested with 0 resilience and 0 bonus defense), whereas Blood Craze still does work in those cases.
This happens more frequently when multiple enemies are hitting you; and works properly most of the time against a single opponent.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1270

**Comment by Saltgurka** [comment]
I'm unable to reproduce the issue. Reopen if video proof is provided
