### ISSUE TITLE
Berserking

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1376]
Originally reported by: **Anonymous**

---

Troll's racial ability constantly gains 10% haste rating (should vary from 10% to 30% in accordance with hp, low hp - 30% haste, full hp - 10% haste)

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1281

**Comment by AbaddonL4G** [comment]
with a change spellhaste working but meele haste not (its just random and often the % of haste is way to high). i think it is related to 

Effect 0:
Id: 6 (SPELL_EFFECT_APPLY_AURA)
**BasePoints = 10 to 31**
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Aura Id 138 (**SPELL_AURA_MOD_HASTE**), value = 10, misc = 0 (0), miscB = 0, periodic = 0
Effect 1:
Id: 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 5
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Aura Id 140 (SPELL_AURA_MOD_RANGED_HASTE), value = 5, misc = 0 (0), miscB = 0, periodic = 0
Effect 2:
Id: 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 5
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Aura Id 65 (SPELL_AURA_MOD_CASTING_SPEED), value = 5, misc = 0 (0), miscB = 0, periodic = 0

**Comment by AbaddonL4G** [comment]
https://github.com/cmangos/issues/issues/1194
