### ISSUE TITLE
spamming bugs out many mechanics

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1389]
Originally reported by: **Anonymous**

---

couple things i've noticed happens when you spam different things. couple of examples
1. many quests that need you to use a quest item on a mob or something, if you spam will give you credit multiple times
2. spell queing doesnt seem to work. 
3. spammimng "create all" messes up when doing profession stuff like if i hit create all many times when smelting it creates problems

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1294

**Comment by Saltgurka** [comment]
1. Create a separate issue for each quest bugged in this way.
2. Was this a thing in TBC? If so, create a new issue with proof.
3. https://github.com/Looking4Group/L4G_Core/issues/1215

In general never put several issues in the same post.
Closing this
