### ISSUE TITLE
Server lag/delay all of a sudden

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1398]
Originally reported by: **Anonymous**

---

I'm simply asking here since you dont have a shit yet (Rework?),

Anyways, the first day you launched and the day after that, there was not server lag/delay whatsoever, and now and yesterday there's been a lot of server delay/lag, is this being worked on or?

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1303

**Comment by Rapth** [comment]
this problem solved?
