### ISSUE TITLE
The Softest Wings

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1423]
Originally reported by: **Strugcity (Bitbucket: [Strugcity](https://bitbucket.org/Strugcity), GitHub: Unknown)**

----------------------------------------

The moths you need to kill for their wings only a couple of their spawns seem to be working and you can see a bunch of moths flying around in the area they're supposed to but they are untargetable.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1328

**Comment by Saltgurka** [comment]
#1978
