### ISSUE TITLE
To Legion Hold

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1431]
Originally reported by: **Anonymous**

----------------------------------------

I, as a Draenei, start with the quest "To Legion Hold", which is the 3rd quest in the chain. My friend as a human, start with the first quest normally, but for me its the 3rd part instantly.This way I miss the EXP from the first 2 quest.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1336

**Comment by Saltgurka** [comment]
Can't confirm. On PTR I start with the same quest whether Draenei or Human.
