### ISSUE TITLE
Rich Adamantite Ore Rare Gem Droprate

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1434]
Originally reported by: **Anonymous**

---

I have mined probably over 70 stacks of Adamantite Ore and haven't gotten a single rare/blue gem out of regular or rich veins.  The only one's that are dropping correctly are Fel Iron Veins.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1339

**Comment by AnonXS** [comment]
http://db.looking4group.eu/?object=181556 , http://db.looking4group.eu/?object=181569 , http://db.looking4group.eu/?object=181570 , http://db.looking4group.eu/?object=181555 , http://db.looking4group.eu/?object=185877

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2996/commits/564ae9b4b84465020d9b16596a0a832f0e1352cb
