### ISSUE TITLE
Hunter pet receiving too less experience

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1455]
Originally reported by: **Tering Leier (Bitbucket: [Redzinx](https://bitbucket.org/Redzinx), GitHub: Unknown)**

---

I have a lvl 20 pet, I kill a lvl 60 mob, He hardly gains any exp.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1360

**Comment by AnonXS** [comment]
Config
