### ISSUE TITLE
Spell: Demoralizing Roar - No threat

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1473]
Originally reported by: **Rooik (Bitbucket: [rooik](https://bitbucket.org/rooik), GitHub: Unknown)**

---

The spell causes no threat

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1377

**Comment by cnolimes** [comment]
Bump, a year later this bug still exists. It's really crippling as a feral to not be able to regain instant aggro when someone body/asspulls in an instance.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/3779, better Issue with sources.
