### ISSUE TITLE
Enchanting in trade window seriously bugged.

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1487]
Originally reported by: **Anonymous**

---

When someone enchants an item on the "not traded" slot, the enchant will apply instantly and the enchanter will lose the materials without the need to actually accept the trade (and therefore making it possible for ppl to scam enchanters to get their enchants for free). also where in the fuck are my terocones jesus christ dude

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1391

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/270
