### ISSUE TITLE
Checking "Usable Items" in AH malfunctioning

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1499]
Originally reported by: **Overtime (Bitbucket: [0vertime](https://bitbucket.org/0vertime), GitHub: [0vertime](https://github.com/0vertime))**

---

Seems to do completely the opposite.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1403

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2422
