### ISSUE TITLE
shadow form

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1521]
Originally reported by: **Anonymous**

----------------------------------------

sometimes shadow form get stuck and it say spell is not ready  yet and have to relog to alow me to use it again 

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1425

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/304
