### ISSUE TITLE
Shadow focus

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1533]
Originally reported by: **teddys (Bitbucket: [teddys](https://bitbucket.org/teddys), GitHub: [teddys](https://github.com/teddys))**

---

does not increase chance to hit with shadow spells ..
resisting incredible amount of spells vs low level creatures/players

http://db.hellground.net/?spell=15330

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1437

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2489
