### ISSUE TITLE
RESISTS

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1544]
Originally reported by: **Evolve (Bitbucket: [Evolveuwotm9](https://bitbucket.org/Evolveuwotm9), GitHub: Unknown)**

---

Im resisting every 2nd(no im not joking, its literally every 2nd) spell against levels 60(players) as a level 70 priest with 5/5 shadowfocus(10% hit rating) and 4.5% spell hit from gear....

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1448

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2489
