### ISSUE TITLE
The Art of fel Reaver Maintenance - Horde side bugged

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1557]
Originally reported by: **Larde (Bitbucket: [Larde](https://bitbucket.org/Larde), GitHub: Unknown)**

---

All the horde side mobs are just not there, you have to go to the alliance side to kill the doctor and open the chest.
But on the alliance side the mob spawns to a wrong position

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1461

**Comment by AnonXS** [comment]
#2245
