### ISSUE TITLE
Combat with fire bug

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1576]
Originally reported by: **Galen Knazz (Bitbucket: [Downieboy](https://bitbucket.org/Downieboy), GitHub: Unknown)**

---

If you take damage/walk close to any fires you will enter combat and leave combat right away. This bug is huge because if you are a stealthed rogue this will take you out of stealth and put it on cd.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1480

**Comment by AbaddonL4G** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3018
