### ISSUE TITLE
Quest Dimensius the All-Devouring (quest=10439) Credit for Captain

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1580]
Originally reported by: **A Buescher (Bitbucket: [BuschaZ](https://bitbucket.org/BuschaZ), GitHub: Unknown)**

---

Only the person actually talking to Captain Saeed (npc=20985) is awarded with the credit for talking to him while the whole party in range should get it, resulting in the quest being not done by finishing the event.

Proof: http://imgur.com/9MFzEsV

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1484

**Comment by Saltgurka** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3405
