### ISSUE TITLE
Mote of shadow drop rate in Netherstorm

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1585]
Originally reported by: **Overtime (Bitbucket: [0vertime](https://bitbucket.org/0vertime), GitHub: [0vertime](https://github.com/0vertime))**

---

npc=18869, npc=18870

Drop rate should be around 30% for these two, currently around 1%.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1490

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3614/commits/6bf602e4539d61a96c51e98dd1f536fc9a928fd7
