### ISSUE TITLE
Seed of Corruption

### ISSUE THREAD

**Issue by azmanomer** [Looking4Group/L4G_Core#16]
Warlocks' seed of corruption should, if we read the description, explode if the dargent takes 1044 total damage OR DIES. The problem is that when the target dies from something else than the seed of corruption before taking 1044 damage, the seed does NOT explode. This is really annoying because when you put seeds of corruption on multiple mobs and one seed on one mob kills another mob with another seed, this other seed won't explode. Also when u seed multiple targets and 1 of them explode it doesnt trigger other seeds even seeded targets get more then 1044 damage. Im assuming aoe damage dont count for total 1044 damage.

**Comment by AnonXS** [comment]
https://bitbucket.org/looking4group_b2tbc/looking4group/issues/1527/seed-of-corruption

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/1622
