### ISSUE TITLE
Spirit tower resetting after server crash.

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1601]
Originally reported by: **lol mcrofl (Bitbucket: [Suka_McBlyat](https://bitbucket.org/Suka_McBlyat), GitHub: Unknown)**

---

This

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1506

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/253
