### ISSUE TITLE
Pet cannot attack ghosts in shadowmoon valley

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1630]
Originally reported by: **Bulldoze (Bitbucket: [Legitcow](https://bitbucket.org/Legitcow), GitHub: Unknown)**

---

when u equip [spectrecles](http://www.wowhead.com/item=30721/spectrecles) your pet cannot attack ghost that u can see. they also evade if you try to kite them. Therafore all gorefiend's quests are  impossible to do as a hunter.

Ghost are:

[Cleric of karabor](http://www.wowhead.com/npc=21815/cleric-of-karabor)

[Ghostrider of karabor](http://www.wowhead.com/npc=21784/ghostrider-of-karabor)

[Vhelkur](http://www.wowhead.com/npc=21801/vhelkur)

[Shadowmoon zealot](http://www.wowhead.com/npc=21788/shadowmoon-zealot)

And probably also: [Karsius the Ancient Watcher](http://www.wowhead.com/npc=21877/karsius-the-ancient-watcher)

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1535

**Comment by AnonXS** [comment]
https://bitbucket.org/Xadras/tbcpvp/commits/05429ffb714c6a68997243da25b1439033d66307

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3442/commits/e381142339c305f4eb43f97186a6928bdeaf8ab1
