### ISSUE TITLE
Dust Covered Chest despawning (Karazhan)

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1690]
Originally reported by: **Anonymous**

----------------------------------------

After chess event, Dust Covered Chest despawning because of leaving combat with trash mobs, even if all loot was inside.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1595

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/6951aec458d81e586860b5e851b1baf597975e6e
