### ISSUE TITLE
Auctionhouse filter setting not working

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1699]
Originally reported by: **Anonymous**

---

checking the "Useable Items" filter doesnt work

setting "Level Range" without minimal level doesnt work

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1604

**Comment by AnonXS** [comment]
Dubliacte https://github.com/Looking4Group/L4G_Core/issues/2422
