### ISSUE TITLE
Righteous Fury / Imp RF Not Working Properly

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1701]
Originally reported by: **Anonymous**

---

In the last 24 hours Prot Paladin Threat (with RF and imp RF on) has changed.  48 hours ago I was running with guildies doing 500-700 single target and holding threat vs them on a full threat rotation quite easily.  In the past 24 hours I haven't been able to hold threat vs 300 DPS on max threat rotation single target, the threat is everywhere but me with much lower damage than I am use to.  

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1606

**Comment by AnonXS** [comment]
Linked to https://github.com/Looking4Group/L4G_Core/issues/2437
