### ISSUE TITLE
Mass dispel resist

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1708]
Originally reported by: **Evolve (Bitbucket: [Evolveuwotm9](https://bitbucket.org/Evolveuwotm9), GitHub: Unknown)**

---

Mass dispel is resisting against paladin bubbles. It should have 0% resist chance. Mass dispel started resisting since wotlk.

Gamebreaking

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1613

**Comment by AnonXS** [comment]
Patch 2.2.0 (25-Sep-2007): Has a chance to be resisted when dispelling immunity effects. This will be displayed in the combat log. In addition, it will no longer cause rogues and druids in Cat Form to lose Stealth. The flashing area graphic has been removed.

http://wowwiki.wikia.com/wiki/Mass_Dispel
