### ISSUE TITLE
priest shadow form passively creates aggro

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1722]
Originally reported by: **Anonymous**

---

what the tittle says, i dont know how to test it but evrything aggroes on me from my mates.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1627

**Comment by AnonXS** [comment]
easy to test, if what you say is true, go into combat with a mob let your mate do a little threat and then wait without doing anything, if shadowform is passively creating threat you should pull from him in a certain timeframe.
