### ISSUE TITLE
Quest: Seek Out Naltharku - Unavailable?

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1738]
Originally reported by: **Anonymous**
---

Completed the quest "Kindness" to feed 8 Netherwings, handed in quest to Mordenai (while he was fighting something) And he didnt have his follow up quest to talk to Naltharku. Not sure if its missing or just not out because of the 'patch' we are on.

There have been several server resets since, and he still doesnt give his follow-up quest.
---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1643

**Comment by AnonXS** [comment]
I think this is in until the followup to fly to the netherwing ledge, which will be released in 2.1.
