### ISSUE TITLE
Spirit shards: No drop

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1739]
Originally reported by: **Luthvina (Bitbucket: [Luthvina](https://bitbucket.org/Luthvina), GitHub: Unknown)**

---

Hey,

alliance controls all 5 towers right now, still bosses in sethekk dont drop spirit shard.

Afaik they should drop 100% once you control the towers, 2 for each boss in SL, Sethekk, 1 for MT and AC.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1644

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2955
