### ISSUE TITLE
Bat Rider Guards

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1750]
Originally reported by: **Bulldoze (Bitbucket: [Legitcow](https://bitbucket.org/Legitcow), GitHub: Unknown)**

----------------------------------------

above thrallmar. Should be protecting the town from alliance. Should be flying around, aggro to alliance that come close to them with a flying mount, and use their abilities.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1655

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2878/commits/df09c1dea6998759fb812f646ba6fa5f72e45c06
