### ISSUE TITLE
Shadow Labyrinth final room

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1753]
Originally reported by: **Anonymous**

----------------------------------------

Murmurs Room is full of enemies. on retail TBC most of these would be killed off by Murmur before the players reach them, but on this server they just stand there. Murmur does not kill any of them. this makes the dungeon very annoying to clear, as players have to kill tons of additional mobs compared to retail shadow labs.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1658

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2856
