### ISSUE TITLE
Quest: Fire At Will!

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1774]
The northern canon are bugged, not completeable. The canon bugs out as soon as you use Naturalized Ammunition. This is pretty huge, when in the end of the chain a BiS pre raid neck awaits.

http://db.looking4group.eu/?quest=10911

**Comment by AnonXS** [comment]
Seems to have been a misplacement issue by deleted out spawns and incorrect reimplementation at some point.
