### ISSUE TITLE
Cast bar stutters?

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1775]
Originally reported by: **Anonymous**

---

While casting nearly anything the bar does not fill smoothly, it fills almost as if it fills in chunks rather than just slides. Pretty weird

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1680

**Comment by Evolvee** [comment]
It is client-side.

I managed to fix it by randomly enabling/disabling castbar addon....
Idk why its caused by that tho.

**Comment by AnonXS** [comment]
ty 4 info, it seems alot of stuff is calculated client side which we are not really able to influence.
like controlled player pathing etc (info come from vwow)
