### ISSUE TITLE
Chess Event silence aura

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1799]
Originally reported by: **Overtime (Bitbucket: [0vertime](https://bitbucket.org/0vertime), GitHub: [0vertime](https://github.com/0vertime))**

----------------------------------------

It should disappear after you beat the chess game, currently whole room has silence after beating it.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1704

**Comment by AbaddonL4G** [comment]
somehow hook this

https://github.com/Looking4Group/L4G_Core/blob/5db29dcb30ef0d336e467f61334d8474108b09fa/src/scripts/scripts/zone/karazhan/chess_event.cpp#L4114

to this

https://github.com/Looking4Group/L4G_Core/blob/0ce936f15b056ce96ac528d88cae91b34adec61b/src/scripts/scripts/zone/karazhan/instance_karazhan.cpp#L288


(kinda remove the silence after the chess is done / when the exit door opens)

**Comment by AbaddonL4G** [comment]
or just despawn the status npc casting the aura after event is done?

**Comment by AnonXS** [comment]
```
// https://github.com/Looking4Group/L4G_Core/blob/5db29dcb30ef0d336e467f61334d8474108b09fa/src/scripts/scripts/zone/karazhan/chess_event.cpp#L4114
if (pInstance->GetData(DATA_CHESS_EVENT) == DONE)
        {
                me->RemoveAurasDueToSpell(39331);
        }

```

**Comment by AbaddonL4G** [comment]
@https://github.com/Looking4Group/L4G_Core/pull/2913

**Comment by AbaddonL4G** [comment]
https://github.com/Looking4Group/L4G_Core/commit/f79550e751820c72e5b96ca50f7fb04c393d9712
