### ISSUE TITLE
Shadowform "fizzled"

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1805]
Originally reported by: **Evolve (Bitbucket: [Evolveuwotm9](https://bitbucket.org/Evolveuwotm9), GitHub: Unknown)**

---

when you stay on 1 place without moving and you are ressurected by BGs spirit healer you cannot use shadowform instantly, it says fizzled until you move slightly. same with stuns etc

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1710

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/304
