### ISSUE TITLE
Vanilla Quest: The Attack!

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1817]
Stormwind - "Attack!" is bad scripted - the guardians of city are takes agro to quests mobs through textures and kill them

http://db.looking4group.eu/?quest=434

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3364/commits/8afb85d7b376c80b6ab00a973a0651333a380bb2
