### ISSUE TITLE
Update time diff (Recent sever lag?)

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1830]
Originally reported by: **Melody (Bitbucket: [Momohx](https://bitbucket.org/Momohx), GitHub: Unknown)**

---

last 2-3 days constantly peak eu time the server is laggy as shit

https://ln.steamy.moe/szabzg.png

On server launch it was smooth at 2.3k~ players.

what's going on?

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1735

**Comment by Rapth** [comment]
is this problem solved? friend?
