### ISSUE TITLE
[Fish] Outlands zone - max skills - miss

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1835]
Originally reported by: **chop88 (Bitbucket: [chop88](https://bitbucket.org/chop88), GitHub: Unknown)**

----------------------------------------

I'm 375 fish and 5 with fishing pole => 380

But 99% of my fish throw are missed in Nagrand zone

Could you fix this plz ?

(I think it could be the same with Outlands region)

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1740

**Comment by Saltgurka** [comment]
#1715
