### ISSUE TITLE
[visual] windfury buff stays on the weapon after the totem is gone

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1836]
Originally reported by: **Bulldoze (Bitbucket: [Legitcow](https://bitbucket.org/Legitcow), GitHub: Unknown)**

---

Get a shammy in your group, tell him to put wf totem down and then remove it. -> WF 'visual' stays on your weapon.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1741

**Comment by hitbutton** [comment]
That's how it was on live too. Unlike other totems where the effect disappeared as soon as the totem was removed, Windfury Totem pulsed a 10 second duration weapon enchant buff every 5 seconds. TBC shaman took advantage of that characteristic of wf totem to provide windfury + another air totem by dropping 2 totems every 10 seconds. This was known as "totem twisting".

This cached EJ thread talks about twisting: http://web.archive.org/web/20080811071236/http://elitistjerks.com/f47/t20765-shaman_enhancement/#Totem_Twisting

**Comment by AnonXS** [comment]
thx
