### ISSUE TITLE
Hearthglen Lumber Mill (Scarlet Workers)

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1862]
Originally reported by: **Pomf (Bitbucket: [Pomfpomf](https://bitbucket.org/Pomfpomf), GitHub: [Pomfpomf](https://github.com/Pomfpomf))**
---

Npc's around the Hearthglen Lumber Mill are all of a sudden bugged, i used to farm the area a lot and now they are moving around while in a frost nova, as of now it's only the npc's around the lumber mill, i can also instantly ress at my corpse if i die to them
edit: los seems broken as well, npc's aggroing through walls
---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1767

**Comment by AnonXS** [comment]
As pathing is reenabled, they only evade through objects, other than that normal pathing, no movement in frost nova
