### ISSUE TITLE
Release spirit - Durnholde - old hillsbrad foothills

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1864]
So, wiped - released spirit, end up in Hillsbrad foothills on eastern kalimdor. Makes the corpserun a b*tch.

https://gyazo.com/b93bb89ab712a7d093775b8ef6f41c84

**Comment by AnonXS** [comment]
Can someone confirm? Maybe depended to the location in the dungeon where the player died.
