### ISSUE TITLE
Dismounting Spells - not functional

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1888]
http://db.looking4group.eu/?spell=18396

The spell does not dismount the player, it only knockbacks.

The spell is used by, among others  [Thrallmar Wolf Riders](http://www.wowhead.com/npc=16599/thrallmar-wolf-rider), Honor Hold Defender etc

Keeps doing dismounting blast after you are off mount. -> Change AI

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1793

**Comment by Saltgurka** [comment]
Solved with https://github.com/Looking4Group/L4G_Core/commit/9c8234cf6b443917b16522631fbfc1754e2af3bd
