### ISSUE TITLE
Twin Spire Blessing in BG/maybe Arena?

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1894]
Originally reported by: **Evolve (Bitbucket: [Evolveuwotm9](https://bitbucket.org/Evolveuwotm9), GitHub: Unknown)**

---

![WoWScrnShot_051216_192519.jpg](https://bitbucket.org/repo/B8qqer/images/2814409770-WoWScrnShot_051216_192519.jpg)

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1799

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3288
