### ISSUE TITLE
Amish Wildhammer

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1905]
Originally reported by: **Bulldoze (Bitbucket: [Legitcow](https://bitbucket.org/Legitcow), GitHub: Unknown)**

----------------------------------------

Has a flying point icon above his head(and on minimap) for horde players.

[Pic](http://i.imgur.com/6aO4PWE.jpg)

Probably same goes for alliance vice versa.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1810

**Comment by AnonXS** [comment]
ea15ee34d522301bb6b64e5b73879e1f1f3108a7
