### ISSUE TITLE
Disrupt the Reinforcements spelling error

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1932]
Originally reported by: **Anonymous**

----------------------------------------

The quest objectives for Disrupt the Reinforcements in Hellfire Peninsula list the two portals as being named Port Xilus and Port Kruul, while they should be named Portal Xilus and Portal Kruul, respectively.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1837

**Comment by Saltgurka** [comment]
Invalid. Alliance version always said "Port": http://www.wowhead.com/quest=10208/disrupt-their-reinforcements
