### ISSUE TITLE
Craghide Basilisk

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1943]
Originally reported by: **Anonymous**

----------------------------------------

Once aggroed Craghide Basilisks (Netherstorm between Manaforge and Celestial Ridge) are able to charge and stunn players while they are in the air(more then 5yards away). took me few trys to reproduce

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1848

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2891/commits/1e8b51786415d261f3357fcfd3f2a22470ae4f97
