### ISSUE TITLE
The Smallest Creatures (Quest)

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1958]
Originally reported by: **Jani Jyrkkärinne (Bitbucket: [noutis](https://bitbucket.org/noutis), GitHub: Unknown)**

----------------------------------------

Using Kodohide Drum and you turn into a ghost, without operating the marmot.
didnt happen to all at first but after a while our group of 4 didnt get anymore marmots after many tries.
Also marmots are Neutral and can be killed at the area where the kegs are.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1863

**Comment by AnonXS** [comment]
#885
