### ISSUE TITLE
Durability loss in EOS

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1977]
Originally reported by: **Evolve (Bitbucket: [Evolveuwotm9](https://bitbucket.org/Evolveuwotm9), GitHub: Unknown)**

---

when u fall down

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1882

**Comment by AnonXS** [comment]
http://wowwiki.wikia.com/wiki/Eye_of_the_Storm?oldid=1555714 , http://wow.gamepedia.com/index.php?title=Eye_of_the_Storm&oldid=1555714

Info about Durability Loss by Falling into the Void was added on July 19, 2009

http://wowwiki.wikia.com/wiki/Eye_of_the_Storm?oldid=1951737

**Comment by AnonXS** [comment]
Was it like this in TBC?
