### ISSUE TITLE
(South of Vekhaar strand) Mature silk wings just resting in the air. Not able to be pulled

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1978]
Originally reported by: **Anonymous**

----------------------------------------

You cant pull them down.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1883

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2891/commits/fdf98213b2bae8913dff1cfd077b8dcf6226fbe9
