### ISSUE TITLE
Herbalism Nodes

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#1993]
Originally reported by: **Anonymous**

---

Seems like nodes are not re-spawning properly or re-spawning at all.  Seems like the only time you can find nodes is after a server crash.  Please fix this issue quickly highly annoying.

Thanks

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1898

**Comment by AnonXS** [comment]
Delete Outland Herbs, Port Outland Herbs and their Pool Linking from CoronaDB

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/991
