### ISSUE TITLE
Windows unable to compile ？

### ISSUE THREAD

**Issue by mynew4** [Looking4Group/L4G_Core#2]
game.lib(World.obj) : error LNK2019: unresolved external symbol "void __cdecl dtAllocSetCustom(void * (__cdecl*)(unsigned int,enum dtAllocHint),void (__cdecl*)(void *))" (?dtAllocSetCustom@@YAXP6APAXIW4dtAllocHint@@@ZP6AXPAX@Z@Z)，The symbol in the function "public: void __thiscall World::SetInitialWorldSettings(void)" (?SetInitialWorldSettings@World@@QAEXXZ) it was cited
3>game.lib(MoveMap.obj) : error LNK2019: unresolved external symbol "public: unsigned int __thiscall dtNavMesh::init(struct dtNavMeshParams const *)" (?init@dtNavMesh@@QAEIPBUdtNavMeshParams@@@Z)，The symbol in the function "private: bool __thiscall MMAP::MMapManager::loadMapData(unsigned int)" (?loadMapData@MMapManager@MMAP@@AAE_NI@Z) it was cited
3>game.lib(MoveMap.obj) : error LNK2019: unresolved external symbol "public: unsigned int __thiscall dtNavMesh::addTile(unsigned char *,int,int,unsigned __int64,unsigned __int64 *)" (?addTile@dtNavMesh@@QAEIPAEHH_KPA_K@Z)，The symbol in the function "public: bool __thiscall MMAP::MMapManager::loadMap(unsigned int,int,int)" (?loadMap@MMapManager@MMAP@@QAE_NIHH@Z) it was cited
3>game.lib(MoveMap.obj) : error LNK2019: unresolved external symbol "void * __cdecl dtAlloc(unsigned int,enum dtAllocHint)" (?dtAlloc@@YAPAXIW4dtAllocHint@@@Z)，The symbol in the function "public: bool __thiscall MMAP::MMapManager::loadMap(unsigned int,int,int)" (?loadMap@MMapManager@MMAP@@QAE_NIHH@Z) it was cited
3>game.lib(MoveMap.obj) : error LNK2019: unresolved external symbol "public: unsigned int __thiscall dtNavMesh::removeTile(unsigned __int64,unsigned char * *,int *)" (?removeTile@dtNavMesh@@QAEI_KPAPAEPAH@Z)，The symbol in the function "public: bool __thiscall MMAP::MMapManager::unloadMap(unsigned int,int,int)" (?unloadMap@MMapManager@MMAP@@QAE_NIHH@Z) it was cited
3>game.lib(MoveMap.obj) : error LNK2019: unresolved external symbol "public: unsigned int __thiscall dtNavMeshQuery::init(class dtNavMesh const *,int)" (?init@dtNavMeshQuery@@QAEIPBVdtNavMesh@@H@Z)，The symbol in the function "public: class dtNavMeshQuery const * __thiscall MMAP::MMapManager::GetNavMeshQuery(unsigned int,unsigned int)" (?GetNavMeshQuery@MMapManager@MMAP@@QAEPBVdtNavMeshQuery@@II@Z) it was cited
3>game.lib(PathFinder.obj) : error LNK2019: unresolved external symbol "public: unsigned int __thiscall dtNavMeshQuery::closestPointOnPoly(unsigned __int64,float const *,float *,bool *)const " (?closestPointOnPoly@dtNavMeshQuery@@QBEI_KPBMPAMPA_N@Z)，The symbol in the function "private: unsigned __int64 __thiscall PathFinder::getPathPolyByPosition(unsigned __int64 const *,unsigned int,float const *,float *)const " (?getPathPolyByPosition@PathFinder@@ABE_KPB_KIPBMPAM@Z) it was cited
3>game.lib(PathFinder.obj) : error LNK2019: unresolved external symbol "public: unsigned int __thiscall dtNavMeshQuery::findNearestPoly(float const *,float const *,class dtQueryFilter const *,unsigned __int64 *,float *)const " (?findNearestPoly@dtNavMeshQuery@@QBEIPBM0PBVdtQueryFilter@@PA_KPAM@Z)，The symbol in the function "private: unsigned __int64 __thiscall PathFinder::getPolyByLocation(float const *,float *)const " (?getPolyByLocation@PathFinder@@ABE_KPBMPAM@Z) it was cited
3>game.lib(Level2.obj) : error LNK2001: unresolved external symbol "public: unsigned int __thiscall dtNavMeshQuery::findNearestPoly(float const *,float const *,class dtQueryFilter const *,unsigned __int64 *,float *)const " (?findNearestPoly@dtNavMeshQuery@@QBEIPBM0PBVdtQueryFilter@@PA_KPAM@Z)
3>game.lib(PathFinder.obj) : error LNK2019: unresolved external symbol "public: unsigned int __thiscall dtNavMeshQuery::findPath(unsigned __int64,unsigned __int64,float const *,float const *,class dtQueryFilter const *,unsigned __int64 *,int *,int)const " (?findPath@dtNavMeshQuery@@QBEI_K0PBM1PBVdtQueryFilter@@PA_KPAHH@Z)，The symbol in the function "private: void __thiscall PathFinder::BuildPolyPath(class G3D::Vector3 const &,class G3D::Vector3 const &)" (?BuildPolyPath@PathFinder@@AAEXABVVector3@G3D@@0@Z) it was cited
3>game.lib(PathFinder.obj) : error LNK2019: unresolved external symbol "public: unsigned int __thiscall dtNavMeshQuery::findStraightPath(float const *,float const *,unsigned __int64 const *,int,float *,unsigned char *,unsigned __int64 *,int *,int,int)const " (?findStraightPath@dtNavMeshQuery@@QBEIPBM0PB_KHPAMPAEPA_KPAHHH@Z)，The symbol in the function "private: void __thiscall PathFinder::BuildPointPath(float const *,float const *)" (?BuildPointPath@PathFinder@@AAEXPBM0@Z) it was cited
3>game.lib(PathFinder.obj) : error LNK2019: unresolved external symbol "public: struct dtMeshTile const * __thiscall dtNavMesh::getTileAt(int,int,int)const " (?getTileAt@dtNavMesh@@QBEPBUdtMeshTile@@HHH@Z)，The symbol in the function "private: bool __thiscall PathFinder::HaveTile(class G3D::Vector3 const &)const " (?HaveTile@PathFinder@@ABE_NABVVector3@G3D@@@Z) it was cited
3>game.lib(PathFinder.obj) : error LNK2019: unresolved external symbol "public: unsigned int __thiscall dtNavMesh::getOffMeshConnectionPolyEndPoints(unsigned __int64,unsigned __int64,float *,float *)const " (?getOffMeshConnectionPolyEndPoints@dtNavMesh@@QBEI_K0PAM1@Z)，The symbol in the function "private: unsigned int __thiscall PathFinder::findSmoothPath(float const *,float const *,unsigned __int64 const *,unsigned int,float *,int *,unsigned int)" (?findSmoothPath@PathFinder@@AAEIPBM0PB_KIPAMPAHI@Z) it was cited
3>game.lib(PathFinder.obj) : error LNK2019: unresolved external symbol "public: unsigned int __thiscall dtNavMeshQuery::getPolyHeight(unsigned __int64,float const *,float *)const " (?getPolyHeight@dtNavMeshQuery@@QBEI_KPBMPAM@Z)，The symbol in the function "private: unsigned int __thiscall PathFinder::findSmoothPath(float const *,float const *,unsigned __int64 const *,unsigned int,float *,int *,unsigned int)" (?findSmoothPath@PathFinder@@AAEIPBM0PB_KIPAMPAHI@Z) it was cited
3>game.lib(PathFinder.obj) : error LNK2019: unresolved external symbol "public: unsigned int __thiscall dtNavMeshQuery::moveAlongSurface(unsigned __int64,float const *,float const *,class dtQueryFilter const *,float *,unsigned __int64 *,int *,int)const " (?moveAlongSurface@dtNavMeshQuery@@QBEI_KPBM1PBVdtQueryFilter@@PAMPA_KPAHH@Z)，The symbol in the function "private: unsigned int __thiscall PathFinder::findSmoothPath(float const *,float const *,unsigned __int64 const *,unsigned int,float *,int *,unsigned int)" (?findSmoothPath@PathFinder@@AAEIPBM0PB_KIPAMPAHI@Z) it was cited
3>game.lib(PathFinder.obj) : error LNK2019: unresolved external symbol "public: unsigned int __thiscall dtNavMeshQuery::closestPointOnPolyBoundary(unsigned __int64,float const *,float *)const " (?closestPointOnPolyBoundary@dtNavMeshQuery@@QBEI_KPBMPAM@Z)，The symbol in the function "private: unsigned int __thiscall PathFinder::findSmoothPath(float const *,float const *,unsigned __int64 const *,unsigned int,float *,int *,unsigned int)" (?findSmoothPath@PathFinder@@AAEIPBM0PB_KIPAMPAHI@Z) it was cited
3>game.lib(Level2.obj) : error LNK2019: unresolved external symbol "public: unsigned int __thiscall dtNavMesh::getTileAndPolyByRef(unsigned __int64,struct dtMeshTile const * *,struct dtPoly const * *)const " (?getTileAndPolyByRef@dtNavMesh@@QBEI_KPAPBUdtMeshTile@@PAPBUdtPoly@@@Z)，The symbol in the function "protected: bool __thiscall ChatHandler::HandleMmapLocCommand(char const *)" (?HandleMmapLocCommand@ChatHandler@@IAE_NPBD@Z) it was cited

**Comment by boom8866** [comment]
confirm

**Comment by Looking4Group** [comment]
In visual studio rightclick on the detour project in solution tree and set outputdirectory to ../source/bin/win32_release/lib/

Path is maybe wrong. The lib used to be in the lib folder within the release folder.

**Comment by boom8866** [comment]
No effect is still a problem

**Comment by Micha2903** [comment]
I will fix build next week. I have to focus on new recast implementation and maybe new mmap version.
