### ISSUE TITLE
Quest Gauging the Resonant Frequency

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2003]
Originally reported by: **seraish (Bitbucket: [seraish](https://bitbucket.org/seraish), GitHub: [seraish](https://github.com/seraish))**

---

Oscillating Frequency Scanners  can be set but there is nothing that

http://www.wowhead.com/quest=10594/gauging-the-resonant-frequency

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1908

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3573

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3364/commits/f5f4c7594bc1a743a784c4429b787a3d741e65c6
