### ISSUE TITLE
A Time for Negotiation...

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2008]
Originally reported by: **Anonymous**

---

The quest mob Overseer Nuaar haven't spawned a single time in last hour. And because can't find that mob it causes seize in questin as it releases 3 quests.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1913

**Comment by Russet0** [comment]
Is this still working? Myself and a friend have been checking this NPCs patrol route off and on for a few hours now and haven't spotted him once even with a /target macro.

Blade's Edge is pretty empty too so I really doubt he has been getting killed constantly.
