### ISSUE TITLE
Ironhide devilsaur

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2012]
Originally reported by: **Bulldoze (Bitbucket: [Legitcow](https://bitbucket.org/Legitcow), GitHub: Unknown)**

----------------------------------------

cant range it, cant melee it. saying out of range. tested as hunter

actually minor cuz who cares and its not tbc contenct

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1917

**Comment by AnonXS** [comment]
Fixed with Ruberbanding Update, They have far moving Waypoints, which made them visually bug out.
