### ISSUE TITLE
Shadowmeld "Ability not ready yet"

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2018]
Originally reported by: **Anonymous**

----------------------------------------

I've been playing my NE hunter for a while, Shadowmeld has been working as normal, but suddenly it just broke, saying "Ability not ready", and the icon is grayed out.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1923

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/304
