### ISSUE TITLE
Murkblood Scavengers Population

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2026]
Originally reported by: **discept (Bitbucket: [discept](https://bitbucket.org/discept), GitHub: Unknown)**

----------------------------------------

You need 40 Murkblood Scavengers for the quest Once Were Warriors in Nagrand at the Sunspring Post.
In retail they spawn in groups of 3. On Hellfire they got the right spawnpoint, but theres only 1 of them spawning, what makes the quest last longer especially when there are many ppl around.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1931

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/blob/77e74de874906cddb3095c1dfbab6a4e62ea810c/sql/updates/world/009_updates_byAnonX3.sql
