### ISSUE TITLE
Netherspite Nether Exhaustion

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2028]
Originally reported by: **hitpoint (Bitbucket: [hitpoint](https://bitbucket.org/hitpoint), GitHub: [hitpoint](https://github.com/hitpoint))**

---

There are two problems with Nether Nether exhaustion on this server which make the fight much simpler and easier than it ever was on retail.

Problem 1. Nether Exhaustion should begin after the beam buff fades, not before. In this video Nether Exhaustion is applied to TSW as soon as the other tank steps into the red beam. The 90 second Nether Exhaustion debuff should be applied only **after** his 20 second Perseverance buff fades.

https://youtu.be/VJ86USUHEt0?t=130

From the wiki:
"Once a buff "ticks out" (player leaves the beam long enough to lose the debuff — 8-20 sec), another debuff is applied to the player called Nether Exhaustion, which prevents him from intercepting that color beam for the next 1 minute and 30 seconds."

Problem 2. You don't get the Nether Exhaustion debuff if you are in the beam before the banish phase. Shown in this video. The phase switches and this warrior never gets Nether Exhaustion, allowing him to take the beam immediately next phase when he should be locked out.

https://youtu.be/VJ86USUHEt0?t=247

Here are three videos showing the beam buff fading, and then Nether Exhaustion being applied. The first video is right before a banish phase and he still gets Nether Exhaustion.

https://youtu.be/4TYEslAiorQ?t=272

https://youtu.be/E_6_vk9pSyM?t=131

https://youtu.be/k6OZrCgKRrM?t=253

This next video from 2009 shows that the spell continued to behave the same way even through later patches. As each buff fades, Exhaustion for each beam is received, even in banish phase.

https://youtu.be/6Y8LLlEulwk?t=84

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1933

**Comment by AnonXS** [comment]
Clears out the most important issues left with this encounter: https://github.com/Looking4Group/L4G_Core/pull/3877
