### ISSUE TITLE
Too many tin nodes in Jasperlode Mine

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2039]
Originally reported by: **Anonymous**

---

There seem to be way too many tin nodes spawning in Jasperlode Mine. The mine is overcrowded with them.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1944

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/blob/master/sql/updates/world/088_03_02.17.sql
