### ISSUE TITLE
Master of deception

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2048]
Originally reported by: **Nicki Schandorff Andersen (Bitbucket: [schandri](https://bitbucket.org/schandri), GitHub: [schandri](https://github.com/schandri))**

----------------------------------------

master of deception doesnt work. and it ruins the gameplay of a rogue, as rogues rely on stealth and treachery

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1953

**Comment by AnonXS** [comment]
Its not the Talent that is causing problems as this issue is strongly mitigated by MoD. 

There were already hugh improvements to this issue.
