### ISSUE TITLE
Bladespire Ogres not using abilities!

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2051]
Originally reported by: **Duninn (Bitbucket: [Duninn](https://bitbucket.org/Duninn), GitHub: Unknown)**

---

The Bladespire Ogres I have fought this far are not using any abilities. Each class, even the casters, just prefer to melee me instead. Below is a link of the ogres I have encountered thus far and the abilities they should be using.

http://www.wowhead.com/npc=19998/bladespire-shaman#abilities

http://www.wowhead.com/npc=19995/bladespire-brute#abilities

http://www.wowhead.com/npc=21296/bladespire-champion#abilities

http://www.wowhead.com/npc=20334/bladespire-cook#abilities

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1956

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/870
