### ISSUE TITLE
Netherspite

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2056]
Originally reported by: **Tr1n1ty (Bitbucket: [Tr1n1ty_](https://bitbucket.org/Tr1n1ty_), GitHub: Unknown)**

---

- [X] 1. Netherspite shoud not be neutral - he shoud be agressive
   -- https://www.youtube.com/watch?v=46wOqfCfVXg

- [X] 2. Netherspite shoud be patroling in the outer Circle of his room
   -- https://www.youtube.com/watch?v=46wOqfCfVXg

- [x] 3. Netherspite shoud cast his Netherbreath random TARGETED @players (he does cast it random but he keeps the tank as target all the time - which makes the strategy to stay on him and avoid his breath by smart movement kinda hard, doesn't make the fight impossbile but still not blizzlike )
   -- https://www.youtube.com/watch?v=46wOqfCfVXg (you can see him switching targets, trying to cast Netherbreath but not being able to cast it due to LoS/out of Range)

- [x] 4. Netherspite shoud reset his aggro table after every Banish Phase and having his normal aggro table untill the portals pop up a few seconds later ( this making the fight a bit harder because the tank has to pick it up again instead of just still having aggro from Portal Phase )
   -- https://priestlyendeavors.wordpress.com/2007/11/05/against-netherspite/
   -- http://wow.gamona.de/das-spiel/instanzen-und-raids/burning-crusade/karazhan/nethergroll/
- [x] 5. (minor) the spells 30468 30466 30467 shoud be Buffs on him not Debuffs ( which he gets when the portals reach him instead of the player (Wrong https://youtu.be/46wOqfCfVXg?t=2m10s)

- [x] 6. (minor) the spell 30522 (Nether Burn buff) shoud be invisible on him (but ofc still be in effect)

- [x] Additionally, his Nether Exhaustion debuff is not working correctly on players. Making handling the beams much easier than it should be. https://github.com/Looking4Group/L4G_Core/issues/2028

**Comment by AnonXS** [comment]
He also had a few other prenfer things to do, like his damage aura should dissapear during his crazed phase.

- Netherspite will no longer cast Nether Burn while crazed.

**Comment by AnonXS** [comment]
Clears out the most important issues left with this encounter: https://github.com/Looking4Group/L4G_Core/pull/3877
