### ISSUE TITLE
Karazhan - Terestian Illhoof Portal not spawning Imps

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2061]
Originally reported by: **Rubapowa (Bitbucket: [Rubapowa](https://bitbucket.org/Rubapowa), GitHub: Unknown)**

---

Portal Mechanic sometimes stops working.

Today after giving a lot of tries to Terestian Illhoof encounter and failing over and over in two of maybe 20 tries to the boss the mechanic of spawning Imps from the portals didnt work , the sacrifice and other mechanics worked but we just did the both encounter without adds, even after that we still wiped both times .

I dont know exactly how reproduce the bug or how happened , the only thing in common came to my mind is one of the Elite Imps in the same room of Terestian Illhoof respawned at the same time or few seconds after we engage the boss.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1966

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/559
