### ISSUE TITLE
Quest: Escape from the Stagin Ground

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2069]
Originally reported by: **Anonymous**

---

the quest giver itself is bugged, after he fights the gladiator and you help him, he just stands there for awhile and then dies 

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1974

**Comment by Saltgurka** [comment]
```sql
INSERT IGNORE INTO `creature_questrelation` VALUES (20763,10425);
UPDATE `creature_template` SET `MovementType`=0 WHERE `entry`=20763;
```
