### ISSUE TITLE
Taking portals resets your bg que time

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2079]
Originally reported by: **teddys (Bitbucket: [teddys](https://bitbucket.org/teddys), GitHub: [teddys](https://github.com/teddys))**

----------------------------------------

and going to halls of legends does the same

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1984

**Comment by AnonXS** [comment]
#2456
