### ISSUE TITLE
Ancestral Spirit Wolf is attackable by horde

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2080]
Originally reported by: **Jeff Harris (Bitbucket: [Mrputts](https://bitbucket.org/Mrputts), GitHub: [Mrputts](https://github.com/Mrputts))**

----------------------------------------

For the quest A Spirit Guide in Hellfire Peninsula

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1985

**Comment by AnonXS** [comment]
Set unit_flag 2

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2891/files#diff-2fa1c8b0cb91a31beb1778949a8b4a52
