### ISSUE TITLE
Shaman elementals not leashing properly

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2084]
Originally reported by: **Duninn (Bitbucket: [Duninn](https://bitbucket.org/Duninn), GitHub: Unknown)**

---

The shaman elementals (Earth and Fire) are not leashing properly when entering combat. Usually just entering combat would cause the elementals to come to the shamans aide. However, right now we have to kite any mob back into the elemental for it to attack it. Additionally, the elementals will not chain into neutral mobs that attack the shaman.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1989

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/433
