### ISSUE TITLE
Quest Warlord's Command - unable to turn in

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2092]
Originally reported by: **Nope Nope (Bitbucket: [Koraru](https://bitbucket.org/Koraru), GitHub: Unknown)**

---

The quest is not able to be turned in. It remains gray even when 'complete' in the quest log.

This is the first quest in the Mark of Tyranny trinket.

This is vanilla content, yes. However the Mark of Tyranny is quite useful for Bear tanks until T5 content. I have selected 'major' because it is within the top 3 BiS trinkets for bear tanks.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/1997

**Comment by Saltgurka** [comment]
I could turn it in just fine. Are you sure you also looted the required item? (http://db.looking4group.eu/?item=12562)

Closing for now
