### ISSUE TITLE
The Fate of Kagrosh (He is not dead after all!)

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2095]
Originally reported by: **Anonymous**

----------------------------------------

Kagrosh is supposed to be dead when you take his bagpack. Currently he is alive and at a good health in the Deathforge.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2000

**Comment by AnonXS** [comment]
#1212
