### ISSUE TITLE
Shadowsworn Drakonid/Shadowmoon Eye of Kilrogg not patrolling

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2114]
Originally reported by: **meme (Bitbucket: [homemer](https://bitbucket.org/homemer), GitHub: Unknown)**

----------------------------------------

http://www.wowhead.com/npc=22072/shadowsworn-drakonid#comments

http://www.wowhead.com/npc=22134/shadowmoon-eye-of-kilrogg#comments

These mobs should be patrolling around the area, but currently they just stand still. Unfortunately I do not know the exact patrol paths. 

https://youtu.be/QQ3xJ5I9mqU?t=82

https://youtu.be/QQ3xJ5I9mqU?t=87

Those clips together with the comments on the mob pages should be proof enough that they're supposed to patrol.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2019

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2841/commits/b0a443cd1719b27c1b94030ba955e08707830ff6
