### ISSUE TITLE
Kite + Leash Range

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2139]
Originally reported by: **Anonymous**

----------------------------------------

After the Maintaince / Downtime the 21st, the Leash range /Kite range on mobs seem to be around 45-50 Yards. Worked fine before.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2044

**Comment by AnonXS** [comment]
We slightly reduced Leash Range.
