### ISSUE TITLE
Spectrecles quest mobs Shadowmoon Zealots can't be attacked

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2142]
The Quest Spectrecles in Shadowmoon Valley requires you to kill Shadowmoon Zealots.  You cannot kill them unless you are standing right on top of them.  Otherwise they drop combat and heal.

**Comment by RuedigerBITTE** [comment]
This quest is madness for hunters, pet can't attack them, you can't kite them and shoot since they will reset, so you have to melee 12 of them down.. Would appreciate a fix or workaround

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3442/files
