### ISSUE TITLE
Food/Drink generate threat

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2179]
Originally reported by: **Shal (Bitbucket: [Shalovski](https://bitbucket.org/Shalovski), GitHub: [Shalovski](https://github.com/Shalovski))**

----------------------------------------

Drinking and/or eating food causes the player to generate threat when it shouldn't.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2084

**Comment by AnonXS** [comment]
And some spells healing component should not cause extra thread like: Devouring Plague , Siphon Life , Drain Life;

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2040
