### ISSUE TITLE
Harbingers Of Shadowmoon bugged

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2184]
Originally reported by: **Anonymous**

---

Mobs doesnt work. they keep disengaging/evading no matter how i line my attacks (melee/range)

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2089

**Comment by billiamlumbergh** [comment]
They are still pretty buggy. I can't engage them with DoT spells. Have to use physical damage or a spell.
