### ISSUE TITLE
frost nova doesnt fade

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2191]
Originally reported by: **Evolve (Bitbucket: [Evolveuwotm9](https://bitbucket.org/Evolveuwotm9), GitHub: Unknown)**

----------------------------------------

when dmg taken is absorbed

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2096

**Comment by AnonXS** [comment]
From reading sources due to breaking of fear effects, nova root. if damage is absorbed, nova should not break.

**Comment by Evolvee** [comment]
nova should break if dmg is absorbed, where did u read the opposite?
