### ISSUE TITLE
Omor

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2192]
Originally reported by: **Tr1n1ty (Bitbucket: [Tr1n1ty_](https://bitbucket.org/Tr1n1ty_), GitHub: Unknown)**

---

add 

```
#!c++

OrbitalStrike_Timer += 1500
```

after l188

shoud fix the problem that he is canceling his Aura cast to do an Orbital Strike

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2097

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3205
