### ISSUE TITLE
Furious Mr. Pinchy not Hostile!

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2210]
Originally reported by: **Lars Morsing (Bitbucket: [pwnster](https://bitbucket.org/pwnster), GitHub: Unknown)**

---

Yaw, when I use the rare catch Mr. Pinchy, I spawned furious Mr. Pinchy, which im suposed to be able to kill and loot.. pewpew... But, guess what, he wasnt furious at all, he was friendly and couldn't attack him..  now what?

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2115

**Comment by AnonXS** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/25709746/70f77b18-30ea-11e7-9347-f4e448dd9143.PNG)

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3614/commits/a04ae3853adb8ebdeea39108f0cb341dc18af54d
