### ISSUE TITLE
Dropped quest starters not dropping

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2213]
Originally reported by: **hitpoint (Bitbucket: [hitpoint](https://bitbucket.org/hitpoint), GitHub: [hitpoint](https://github.com/hitpoint))**

----------------------------------------

I've noticed while I've been leveling that many dropped quest items which other people are able to loot, simply do not drop for me and I have no idea why. I've deleted my cache, I don't know what else to do.

Just off the top of my head there are these three:

http://www.wowhead.com/item=29590/burning-legion-missive

http://www.wowhead.com/item=25459/count-ungulas-mandible

http://www.wowhead.com/item=30431/thunderlord-clan-artifact

I've killed these NPCs multiple times trying to get the drops with no success. The last of which is the start of a very long chain.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2118

**Comment by AnonXS** [comment]
Pray to Rngesus.
