### ISSUE TITLE
pathfinding in Blades Edge

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2227]
Originally reported by: **Tyler Kauffman (Bitbucket: [tkauffman2](https://bitbucket.org/tkauffman2), GitHub: [tkauffman2](https://github.com/tkauffman2))**

----------------------------------------

I jump off structures/bridges and the mobs glitch/float down to the ground to me.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2132

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2478
