### ISSUE TITLE
Unexpected Results Quest [Eversong Woods]

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2228]
Originally reported by: **Anonymous**

---

This quests summons 3 adds which are supposed to attack the quest NPC (Apprentice Mirveda), but they do not.  You can still go kill them at the location at which they are summoned, though.  One of the adds is a named mob named GHARZUL; the other two adds are ANGERSHADE which also spawn in the area (which are also the name of the regular mobs in the area).  

There was some kind of glitch in the way the quest completion was handled as well.  Upon killing GHARZUL, I was spammed with quest completed messages repeatedly and the person in my party did NOT even get credit for completing the quest.  We had to do it again for them to get completion, and then they were spammed with completion messages as well.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2133

**Comment by Saltgurka** [comment]
Solved with https://github.com/Looking4Group/L4G_Core/pull/3577
