### ISSUE TITLE
Ezekiel broken patrol

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2242]
Originally reported by: **Anonymous**

----------------------------------------

Runs/float thru the wall everytime

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2147

**Comment by AnonXS** [comment]
Also related to Viewdistance.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/a8a81dd96ed1ea7a7e2052f581ffc42662daa262
