### ISSUE TITLE
Big bad wolf should chase more

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2257]
Originally reported by: **hitpoint (Bitbucket: [hitpoint](https://bitbucket.org/hitpoint), GitHub: [hitpoint](https://github.com/hitpoint))**

---

Big bad wolf does not cast Little Red Riding Hood enough. And he should begin the fight by casting it before he does anything else.

It looks like on retail he spends the vast majority of the fight chasing people. He casts it to begin the fight, chases for about 20 seconds, fights for 10 seconds, and then chases for 20 seconds, and then fights for 10 seconds again, etc.... Unless Little Red Riding Hood dies, then he fights until the next cast of the spell. So it looks like he should cast Little Red Riding Hood about every 30 seconds. 

On our server he casts it exactly 30 seconds after the start of the fight and then every 1 minute after that, changing the fight dramatically.

VoDs from L4G:

https://www.twitch.tv/painmachine69/v/68630108?t=01h17m16s

https://www.twitch.tv/warriortsw/v/68925760?t=02h02m12s

https://www.twitch.tv/mandosvk/v/69156242?t=01h07m39s

Videos from retail:

https://www.youtube.com/watch?v=jT9yyVgVoAY

https://www.youtube.com/watch?v=-eQqcYVxNg0

https://www.youtube.com/watch?v=_m3FUDCqMhM

His chase speed or pathing, or damage output may need to be adjusted since his melee damage is buffed here.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2162

**Comment by AnonXS** [comment]
Most Recent Issue that tracked this bug: https://github.com/Looking4Group/L4G_Core/issues/2806
