### ISSUE TITLE
mace stun DR

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2260]
Originally reported by: **Evolve (Bitbucket: [Evolveuwotm9](https://bitbucket.org/Evolveuwotm9), GitHub: Unknown)**

---

Deep Thunder stun should share same DR with Mace Spec Stun

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2165

**Comment by AnonXS** [comment]
Insert all Trigger Auras as Trigger Spells for right diminishing return behavior.

**Comment by Saltgurka** [comment]
Solved with https://github.com/Looking4Group/L4G_Core/pull/3062
