### ISSUE TITLE
Shimmerscale Eel drops no mote of water

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2275]
Originally reported by: **Anonymous**
---

Loot seems to be bugged.

Shimmerscale Eel was dropping a lot of mote of water.
---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2180

**Comment by AnonXS** [comment]
Recheck one more time and close.

**Comment by AnonXS** [comment]
Drop Chance high enough.
