### ISSUE TITLE
Shadow Labyrinth: Unable to zone in while an encounter is in progress.

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2282]
Originally reported by: **Caboose (Bitbucket: [caboose54](https://bitbucket.org/caboose54), GitHub: Unknown)**

---

After wiping on Ambassador Hellmaw (the first boss of the instance), we were unable to reenter the instance, because it said that an encounter was in progress. Everyone in the party had released, so there was no player alive in the instance.

We were also stuck as ghosts, since we could not enter the instance. Leaving the party and entering individually allowed us to come back alive, but the trash had reset, presumably because we were not saved to a lockout (since we did not kill a boss in the instance).

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2187

**Comment by WarriorTSW** [comment]
Still an issue today on Hellfire 2

**Comment by Saltgurka** [comment]
Solved with https://github.com/Looking4Group/L4G_Core/pull/3582 (Not live yet)
