### ISSUE TITLE
Drood root charge

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2322]
Originally reported by: **Anonymous**

----------------------------------------

When u Entangling Roots 3 times a player he becomes imune to bear charge

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2228

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/191/commits/92dfcc58267060ac13de8fe457f2e1371548c9c5
