### ISSUE TITLE
Quest progress within a group

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2325]
Originally reported by: **Loki Silverblade (Bitbucket: [Seraphitas](https://bitbucket.org/Seraphitas), GitHub: [Seraphitas](https://github.com/Seraphitas))**

----------------------------------------

If I want to do the quest with my friends then the progress of the quest does not count for the entire group but everyone has the quest then do yourself .

Like

http://db.hellground.net/?quest=9927

I mean every quest where you have to use an object to complete the task is counting not for the group.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2231

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/11
