### ISSUE TITLE
Shade of Aran missing Dragon's Breath / Blizzard wrong size

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2334]
Originally reported by: **Tr1n1ty (Bitbucket: [Tr1n1ty_](https://bitbucket.org/Tr1n1ty_), GitHub: Unknown)**

---

Shade of Aran used Dragon's Breath pre 2.1 
(http://db.hellground.net/?spell=29964)
-Shade of Aran will no longer cast Dragon's Breath.( 2.1 notes )

Also his Blizzard shoud only be on the outer circle and not as big as it is right now ( But i think it's better here on L4G then on retail, makes it harder )
- https://www.youtube.com/watch?v=A787x4AbWIk
- https://www.youtube.com/watch?v=xperlwL8aok
- https://www.youtube.com/watch?v=l0DB4lzAttw

Also sometimes the Blizzard was cast but didn't appear for us, we coud not reproduce that  tho and it happend maybe 3 times since the we started running Kara (3 Groups/ID)

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2240

**Comment by AnonXS** [comment]
We are post 2.1 now.
