### ISSUE TITLE
Netherstorm mobs invalid targets.

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2338]
Originally reported by: **hitpoint (Bitbucket: [hitpoint](https://bitbucket.org/hitpoint), GitHub: [hitpoint](https://github.com/hitpoint))**

----------------------------------------

Half of the gan'arg mekgineer at forge base oblivion, and all tabulks around stormspire. Cannot be attacked by anyone in my group. They do not agro or attack either.

Also, a Farahlon Breaker.

Probably many more mobs in Netherstorm so I'll stop adding, you get the idea.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2244

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/dcfca2ee0bc27632b8251f6ab40f724856896542
