### ISSUE TITLE
Magtheridon reset on wipe

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2340]
Originally reported by: **Tr1n1ty (Bitbucket: [Tr1n1ty_](https://bitbucket.org/Tr1n1ty_), GitHub: Unknown)**

---

Magtheridon doesn't reset properly on wipe (channeler not channeling -> Mag is there from P1) so you always have to reset him again with FD or sth like that

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2246

**Comment by Saltgurka** [comment]
Should be fixed with https://github.com/Looking4Group/L4G_Core/pull/3119
