### ISSUE TITLE
Deserter

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2350]
Originally reported by: **Evolve (Bitbucket: [Evolveuwotm9](https://bitbucket.org/Evolveuwotm9), GitHub: Unknown)**

----------------------------------------

when u receive deserter, it wont kick you from other queues so you can get BG proc even with deserter debuff

E: queues also dont fade when u get into AFK mode

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2256

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/418
