### ISSUE TITLE
Quest: Bloodfury Bloodline not completable

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2359]
Originally reported by: **Anonymous**

---

Bloodfury Ripper does not drop "Bloodfury Ripper's Remains".
I've tried multiple times, it never drops, dropchance should be 100%.
http://db.vanillagaming.org/?item=16190
I also noticed Bloodfury Ripper is not elite, this might have changed in tbc to be non-elite, but there's no way for me to check.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2265

**Comment by Saltgurka** [comment]
`UPDATE `creature_loot_template` SET `ChanceOrQuestChance`=-100 WHERE `entry`=12579 AND `item`=16190; -- Old: -65`

Wowhead says 80% dropchance, but that is likely wrong. Cmangos have 100% as well, so we'll use that.

We will leave it non-elite even though we are technically not on patch 2.0.0. We simply do not have the time to do patch specific changes on vanilla content too.
