### ISSUE TITLE
By Any Means Necessary

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2382]
Originally reported by: **Anonymous**

----------------------------------------

Guest mob (empoor) isn't spawning. Only his bodyguard spawns

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2288

**Comment by AnonXS** [comment]
Reduced Respawntimer of both npcs, but i guess it can happen that empoor moves alone.

**Comment by Xadras** [comment]
-> creature_linked_respawn correct?

**Comment by moonsti** [comment]
Empoor Bugging out again. He'll patrol, but he makes it to this waypoint when his bodyguard spawns and Shatt guards kill it, causing him to stop, making the quest (almost) impossible to complete.

![empoor](https://cloud.githubusercontent.com/assets/15868285/24841217/6cc5dbcc-1d33-11e7-8be5-997a8c6923cb.jpg)
