### ISSUE TITLE
Forge Camp: Annilihilated

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2383]
Originally reported by: **Anonymous**

---

Unable to target cannons with keys to turn in quest. I have the keys please allow this quest to be completed

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2289

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?quest=10011, npc_fel_cannon

Works Solo, maybe doesnt give loot quest credit.
