### ISSUE TITLE
Cold Blood + Deadly Throw

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2446]
Originally reported by: **Jul1988 (Bitbucket: [Jul1988](https://bitbucket.org/Jul1988), GitHub: Unknown)**

---

"Cold Blood" does not work with in combination with the Spell "Deadly Throw"

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2352

**Comment by AnonXS** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/26217725/aea55d62-3c08-11e7-99c0-d1408a99d5f0.PNG)

https://github.com/Looking4Group/L4G_Core/pull/3755/commits/d05d1366616101725647b0937262a054dccc7656
