### ISSUE TITLE
Cold Blood Spellmod

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2447]
Originally reported by: **Jul1988 (Bitbucket: [Jul1988](https://bitbucket.org/Jul1988), GitHub: Unknown)**

---

"Cold Blood" disappears if the enemy dodges the next damaging ability.
In general it should be staying till the next damaging spell.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2353

**Comment by Saltgurka** [comment]
This seems to have already been fixed. Tested with Cold Blood and Sinister Strike. Sinister Strike was not consumed when enemy dodged
