### ISSUE TITLE
BG "Time in Queue" Reset

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2456]
Originally reported by: **Daniel (Bitbucket: [Surrealist823](https://bitbucket.org/Surrealist823), GitHub: Unknown)**

----------------------------------------

It resets whenever you zone in a portal, whether it's an instance, bg, or portal in shattrath.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2362

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/418
