### ISSUE TITLE
Vanish

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2459]
Originally reported by: **imnotarobot (Bitbucket: [calone](https://bitbucket.org/calone), GitHub: [calone](https://github.com/calone))**

----------------------------------------

Sometimes mobs are not reacting to vanish (especially in melee) and keep attacking the player.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2365

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2601
