### ISSUE TITLE
Blade's Edge Arena Pathing

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2469]
Originally reported by: **Melody (Bitbucket: [Momohx](https://bitbucket.org/Momohx), GitHub: Unknown)**
---

https://streamable.com/n4r2
Similarly for Feral Charge 

For warriors too it seems with charge/intercept/intervene
https://streamable.com/kzik // https://streamable.com/xclr

Fear/horror effects don't move the afflicted target 90% of the time. https://streamable.com/0ds6
---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2375

**Comment by AnonXS** [comment]
Reduce Waypoint length for Fear to produce better Fear Pathing.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/677
