### ISSUE TITLE
All dr for mages (pvp)

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2482]
Originally reported by: **randomscripts (Bitbucket: [randomscripts](https://bitbucket.org/randomscripts), GitHub: [randomscripts](https://github.com/randomscripts))**

----------------------------------------

Roots, stuns and slows share the same dr as mage.

Let's say a war charges my opponent. My novas (from elem or my char, it's the same) will get a dr (root for 4 sec instead of 8), and my slows too.

If i slow my opponent after a root, a slow or a stun (pounce, charge, nova, coc, w/e), the duration will get affected by a dr too. So my cone of cold will last 5s instead of 11, my frostbolt 6sec, etc.

And ofc, after 3 slows/roots/stuns, my opponents are immune to slows/roots (except for blizzard spec's slow, because it's a physical debuff i guess, and it doesn't trigger a dr from frostbite too).

I set is as a critical bug as a frost mage because this spec is just unplayable atm. Any melee class is immune to slows/roots after 4sec of fight, so we can't do any damage(no fb/icelance on freezed target)/control.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2388

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/191/files
