### ISSUE TITLE
Pets cannot eat mage food

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2492]
Originally reported by: **Zarant (Bitbucket: [Zarant](https://bitbucket.org/Zarant), GitHub: Unknown)**

---

Some pet families can eat bread (wind serpent/bear/crab/boar/sporebat) but none of them can eat manna biscuits. I could not test with conjured croissants, but it works with conjured cinnamon rolls.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2398

**Comment by AnonXS** [comment]
> Pets that eat bread can eat food conjured by mages. 

http://wowwiki.wikia.com/wiki/Feed_Pet?oldid=1606988

http://wow.gamepedia.com/index.php?title=Feed_Pet&direction=next&oldid=1586948

**Comment by Saltgurka** [comment]
According to these old comments on an addon, pets should be able to eat Manna Biscuits: http://fizzwidget.com/gfw-feedomatic-2-4-1/

> Metooz Says: 
April 19th, 2008 at 5:53 pm
NVM the above comment. All you have to do is type /fom add (diet) (item link) then you can use the naaru ration or whatever else. You can find more info in the readme that comes w/ the addon. The diet type for manna biscuits and naaru rations is Bread so u would type /fom add bread [Naaru Ration] with that last part being the linked item. Hope this helps

> Wykdd from Moonrunner Says: 
April 13th, 2008 at 3:28 pm
FIZZ! Help! 2.4.1, my boar will not eat Conjured Manna Biscuits without Alt clicking. 🙁 That’s a very important feature… can we fix it?


*Fixed next update:
```
-- Manna biscuits can now be eaten by hunter pets
UPDATE `item_template` SET `foodtype`=4 WHERE `entry`=34062;
```
