### ISSUE TITLE
Fire Shield Incandescent Fel Spark

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2500]
Originally reported by: **Soreox (Bitbucket: [Sorxy](https://bitbucket.org/Sorxy), GitHub: Unknown)**

---

http://imgur.com/lCcXbt7

1 Incandescent Fel Spark hitting me multiple times a second.

Occurs rarely. I'll try to get video footage next time.

Spell id = 35266
Spell id = 38733
Spell id = 38893

https://www.youtube.com/watch?v=14aeWWYdvxw

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2406

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3869/commits/6e957d9c90c71ccbc450ca74cb9ffe6785b6f389
