### ISSUE TITLE
Calculation for CC Spells with Damage Threshold

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2512]
Factors:

- Level of the Caster / Target
- Spells used while the CC Effect is active (which break them with different multiplier Chances to their damage)

1. Mana Burn Effects
2. Direct Damage
3. Dot Damage

+ Heartbeat Resist Chance (confirmed 2.0.1?)

---

**TBC Patch 2.1.0 (2007-05-22):**
"Chance to break crowd control from damage: The increased chance for a spell to break from taking a critical strike has been removed. Instead, all targets over level 60 have a slightly larger chance to break out of crowd-controlling effects when they take damage."

**TBC Patch 2.0.1 (2006-12-05):**
"In PvP, Crowd Control effects will last no longer than 12 seconds instead of the full duration, with a chance of a heartbeat resist."

---

Spells with a break on Damage Threshold are:

Fear should randomly break around 900-1200 dmg. this is how it was implemented on AT.
As of now, currently fear will randomly INSTA break or randomly NEVER break with SO Much dmg going in. 
**Source**: Talking with Schaka. 

http://wowwiki.wikia.com/wiki/Fear

---

http://wowwiki.wikia.com/wiki/Howl_of_Terror

---

http://wowwiki.wikia.com/wiki/Intimidating_Shout AoE Spell Component

---

http://wowwiki.wikia.com/wiki/Psychic_Scream
MC is calcluated seperatly.

---

http://wowwiki.wikia.com/wiki/Turn_Evil

---

http://wowwiki.wikia.com/wiki/Scare_Beast

---
Non Fear Spells

http://wowwiki.wikia.com/wiki/Entangling_Roots http://wowwiki.wikia.com/wiki/Frost_Nova

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/92a47e0c34a76e6815cb6d604f06486e3723e552
