### ISSUE TITLE
Bug arena points

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2516]
Originally reported by: **grainn (Bitbucket: [Grainn](https://bitbucket.org/Grainn), GitHub: Unknown)**

---

Name: Granulée and my mate Exillonna
Problem: We received only 21 arena points

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2422

**Comment by AnonXS** [comment]
Feedback?
