### ISSUE TITLE
Spellstrike set (Hood + Pants) SET BONUS 2/2

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2535]
Originally reported by: **Evolve (Bitbucket: [Evolveuwotm9](https://bitbucket.org/Evolveuwotm9), GitHub: Unknown)**

----------------------------------------

is procing only from direct dmg it seems (mind blast + swd)... it doesnt proc from dots or mind flay.

  It should proc from any harmful spell...

 

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2441

**Comment by AnonXS** [comment]
From what i get from the DB / Core, we are missing a PROC_ON_NEGATIVE_SPELL_APPLICATION_FLAG / PROC_ON_POSITIVE_SPELL_APPLICATION_FLAG

**Comment by robinsch** [comment]
Shaman stuff can be fixed on default core, just a db issue. Otherwise yes such a flag is needed.

**Comment by honeyhoney** [comment]
@AnonXS 
Fix below:
```sql
-- Lesser Spell Blasting (32106) (Spellstrike Set Effect) will now have a chance to trigger from channeled spells and DoT application
INSERT INTO `spell_proc_event` (`entry`,`SchoolMask`,`SpellFamilyName`,`SpellFamilyMask`,`procFlags`,`procEx`,`ppmRate`,`CustomChance`,`Cooldown`)
VALUES(32106, 0, 0, 0, 0, 67108864, 0, 0, 0);
```

This issue can be closed if/when the fix is applied and confirmed to work on the live environment.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2891/commits/24279fb77a85d351466ceb9f3e0ae12aa326070b
