### ISSUE TITLE
Throwing Weapons Are Instant

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2538]
Originally reported by: **Melody (Bitbucket: [Momohx](https://bitbucket.org/Momohx), GitHub: Unknown)**

---

Throw weapon seems to ignore the 0.5s cast time.

Example 1 - https://www.youtube.com/watch?v=6uh741RDOFQ&feature=youtu.be&t=2464

Example 2 - https://youtu.be/lhl-GOLhSew?t=311
Example 3 - https://youtu.be/wlxeZJRv6tg?t=464

---

This is currently how it looks like on L4G - Hellfire realm

https://streamable.com/kygm

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2444

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/665f6c0604bfd4ad07d2af736ace36bbe83b5581
