### ISSUE TITLE
Frost Nova Breaking Early

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2540]
Originally reported by: **Freeznfire (Bitbucket: [Freeznfire](https://bitbucket.org/Freeznfire), GitHub: Unknown)**

---

It's breaking way too fast.  Check heartbeat & chance to break coefficient.  

During BC I could have a rogue beating on a player that is novaed and still get a shatter off, consistently.

On this server my nova breaks on first contact 90% of the time, and ive yet to get a shatter off while a rogue is beating on my mob.

And please fix blink, I blink on the ramp in blades edge and never move, this is important...

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2446

**Comment by AnonXS** [comment]
http://www.arenajunkies.com/topic/140438-frost-nova-concern/ 2010

10% , 16-20% (if the player is shielded the shield has to break + threshhold has to be reached before nova breaks.)

http://www.mmo-champion.com/threads/1244552-Dmg-threshold-thats-why-fear-wont-break 2012

~ 10%

http://www.wowhead.com/forums&topic=170121/entangling-roots-efficiency-cata 2010

http://wowwiki.wikia.com/wiki/Crowd_control

Secondary CC abilities

These secondary abilities can control a mob for some time, but either break easily, need frequent reapplication or have other restrictions which make their continued use impractical, and therefore cannot be generally used to take a mob out of combat indefinitely:

Mage - [Frost Nova] and other frost spells

Patch 2.1.0 (22-May-2007): Changed to crowd control. All targets over level 60 have a slightly larger chance to break out of crowd-controlling effects when they take damage.
Bc icon Patch 2.0.10 (2007-03-06): Increased the chance Frozen effects are broken when the target is critically struck by a spell.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/92a47e0c34a76e6815cb6d604f06486e3723e552
