### ISSUE TITLE
Trap proc range (updated)

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2549]
Originally reported by: **Vegard (Bitbucket: [Pompel](https://bitbucket.org/Pompel), GitHub: [Pompel](https://github.com/Pompel))**

---

https://www.youtube.com/watch?v=m8nOaNMHZIQ - 7:52 / 15:02 / 15:35
https://www.youtube.com/watch?v=VhCI3DDvGGU - 14:50

Trap proc range

After a ton of googling, I still can't find a source for the proc range of Hunter traps in TBC. Instead, I've found several PvP videos from TBC where you can clearly see the absolute insane range traps are supposed to have. The fact of the matter is that not having this range is game breaking for Hunters in Arena. If look at which classes had the most Gladiators at 70, Hunters finished dead last in every single season apart from S4, when Paladins were marginally worse ( http://www.arenajunkies.com/topic/46679-bc-gladiator-breakdown-by-class/ ). This was with traps with crazy proc range, which allowed Hunters to always trap a scatter shot target, even if they walked in a straight line away from the trap (This even happens at 15:02 in the first video, check it out). 

The way traps currently work on Hellfire means that you simply can't use freezing trap, as they fail something like 4/5 times because the person affected with Scatter Shot will walk too far away. You can't gamble on this, so you're forced to just put down a frost trap trap, and hope someone walks in to it. Which they won't because they know approximately where it is, and can simply run around because of the short range.

Traps (and Viper Sting) is what makes Hunters work in Arena. By making traps borderline useless you are nerfing the already statistically worst Arena class into the ground. I'm fairly certain the trap range was the same as melee range, 5 yards. Whatever it was, it was waaaaay longer than it currently is on Hellfire, and this absolutely needs to be fixed asap, especially since you have already launched S1.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2455

**Comment by AnonXS** [comment]
The Range Increase to 4 yards(~about 5yards with bugged bounding radius) seems to have resolved this issue.
