### ISSUE TITLE
i've got a situation here

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2553]
Originally reported by: **Timofei (Bitbucket: [Pandamanga](https://bitbucket.org/Pandamanga), GitHub: Unknown)**

----------------------------------------

http://i.imgur.com/0HJHRam.jpg

As you can see, total games played in this team 68, but i got 70 (2 additional loses from nowhere), its actually 102% of games (lol). The point is to find out why and how is that possible. Personally i cant have more games than team does, logically.

sorry for bad english
WutFace

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2459

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2468
