### ISSUE TITLE
Shade of Aran Blizzard NPC

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2557]
Originally reported by: **hitpoint (Bitbucket: [hitpoint](https://bitbucket.org/hitpoint), GitHub: [hitpoint](https://github.com/hitpoint))**

---

There is an invisible mob balled "Shade of Aran Blizzard" or something like that. After we killed Shade of Aran it kept our whole raid in combat and we couldn't find it. Until a hunter pet finally managed to find and kill it.

This was before the pathing was added back to Kara. It might be fixed now.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2463

**Comment by AnonXS** [comment]
Tryed to solve this via DB, which made NPC unfunctional. The NPC has strange behavior caused by the Core Script.

**Comment by Saltgurka** [comment]
Solved in next update (hopefully). It worked for me locally.
```
-- Make the Blizzard (Shade of Aran) trigger Civilian so it doesn't aggro to players and doesn't fill the whole room with Blizzard.
UPDATE `creature_template` SET `flags_extra`=130 WHERE `entry`=17161;
```
