### ISSUE TITLE
Shade of Aran didn't spawn elementals

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2558]
Originally reported by: **hitpoint (Bitbucket: [hitpoint](https://bitbucket.org/hitpoint), GitHub: [hitpoint](https://github.com/hitpoint))**

---

He correctly spawned them on our first attempt. Then we wiped.

Second attempt he died without spawning any elementals.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2464

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3200
