### ISSUE TITLE
[minor] enter blade's edge arena facing wrong way

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2580]
Originally reported by: **vendetta (Bitbucket: [vendetta43](https://bitbucket.org/vendetta43), GitHub: Unknown)**

---

enter the blade's edge arena facing the wrong way

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2486

**Comment by AnonXS** [comment]
Can someone confirm that Teleporter Point Facing is wrong direction, i think not.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3006/commits/308f61bc7b412fc452469d0d4489b87d0cc3e9dd
