### ISSUE TITLE
Hemo charges being consumed by spells

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2592]
Originally reported by: **Cruize (Bitbucket: [Cruize](https://bitbucket.org/Cruize), GitHub: [Cruize](https://github.com/Cruize))**

---

this was a bug that was fixed in patch 2.3.2 on retail

Hemorrhage: Rank 4 of this ability no longer has its charges consumed by non-physical attacks and spells.

the above line came from http://wowwiki.wikia.com/wiki/Patch_2.3.2

currently, spells are consuming stacks, and not even giving them additional damage on those spells.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2498

**Comment by AnonXS** [comment]
http://db.looking4group.eu/?spell=16511 , http://db.looking4group.eu/?spell=17347 , http://db.looking4group.eu/?spell=17348 , http://db.looking4group.eu/?spell=26864

**Comment by Saltgurka** [comment]
I don't know why this works, because by my logic this procflag should trigger on any spell, but I'm going to choose to not ask questions.

Solution (Live next update):
```SQL
-- Hemorrhage no longer procs on non-melee spells.
DELETE FROM `spell_proc_event` WHERE `entry` IN (16511,17347,17348,26864);
INSERT INTO `spell_proc_event` (`entry`,`SpellFamilyName`,`procFlags`) VALUES
(16511,8,0x000222A8),
(17347,8,0x000222A8),
(17348,8,0x000222A8),
(26864,8,0x000222A8);
```
