### ISSUE TITLE
Omen of Clarity (Proc chance)

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2595]
Originally reported by: **Neil (Bitbucket: [Minkusz](https://bitbucket.org/Minkusz), GitHub: Unknown)**
---

Proc chance on Omen of Clarity is definitely not correct.

Just hit lvl 61 as a feral druid while leveling and unlocked the "Omen of Clarity" Talent. I've leveled for approximately 13 minutes (constantly grinding) and have not received one proc as of yet.

From what I understand a slow attack speed procs at a higher percent than a fast attack speed will. In theory you will average about the same PPM (procs per minute), over a extended period of time.

http://www.wowhead.com/forums&topic=19274/haste-rating-procs-per-minute-in-relation-to-haste

http://www.wowhead.com/forums&topic=30785.7/new-wotlk-druid-info **WOTLK**

These links both lead to me to believe the proc chance should be ~6% if your weapon attack speed is 1.00 or 3.5 PPM.

 3.5 Proc / 60 second /60 seconds = 5.83%

I will find a dummy and record some evidence over a long period of time and update this post. 
---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2501

**Comment by AnonXS** [comment]
http://db.looking4group.eu/?spell=16864

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2975/commits/d0979b5ad34210c06f26ebbdac28058acd921e59
