### ISSUE TITLE
Black Temple Pre Quest

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2598]
Originally reported by: **Martin S (Bitbucket: [Relikss](https://bitbucket.org/Relikss), GitHub: Unknown)**

---

Why are the attunement quests (TK attunemet starting with "The Hand of Gul'dan" and BT attunement starting with "Tablets of Baa'ri") missing which were added in patch 2.0. 

The thing is they give me some good Feral  Tank druid items, like Verdant Gloves http://db.hellground.net/?item=30943, Umberhowl's Collar http://db.hellground.net/?item=30944 and Manimal's Cinch http://db.hellground.net/?item=30942
All Items were available in 2.0.1 and should be here. They are hard to replace because they have bonus armor and are pretty important for getting pre BiS hc gear as a Feral Tank. 

Just close the raids so no one can enter but let the quests be able to make thanks.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2504

**Comment by anonxy** [comment]
So this is now active?

**Comment by AnonXS** [comment]
```
DELETE FROM `creature_questrelation` WHERE `quest` IN (10568,10683);
INSERT INTO `creature_questrelation` VALUES (21402, 10568);
INSERT INTO `creature_questrelation` VALUES (21955, 10683);
```

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3068/commits/52b2c8221d7625be517aebe6a63be03358b4919f
