### ISSUE TITLE
Shaleskin Flayers Taking No Damage

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2599]
Originally reported by: **Anonymous**

----------------------------------------

I was grinding Shaleskin Flayers earlier today with no problems as my spells scorched their souls. However, after the recent update concerning new maps and performance updates, Shaleskin Flayers had this buff that reduces the effect of spells by 50%. Fair enough. But my spells literally do nothing to them, nevermind 50%! Nothing I'm doing is recorded in my combatlog and yet the guards can take them down easily.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2505

**Comment by AnonXS** [comment]
#1493
