### ISSUE TITLE
A time for negotiation

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2611]
Originally reported by: **Anonymous**

----------------------------------------

People says that the npc can be found but I was running around the area where he suppose to patrol for like 30 - 45 minutes and didn't find him. Thought he might be killed but after server restart I still couldn't find him...

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2517

**Comment by Saltgurka** [comment]
This guy was working at some point. I assume his MovementType was mistakenly changed to 1, since the waypoints already exists and is set up in creature_addon.
Fixed in next update.

`UPDATE `creature` SET `MovementType`=2, `spawndist`=0 WHERE  `guid`=76771;`
