### ISSUE TITLE
Battleground AFK report - Does not give Deserter

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2618]
Originally reported by: **Sleazebag (Bitbucket: [Sleazebag](https://bitbucket.org/Sleazebag), GitHub: Unknown)**

----------------------------------------

Players that get removed from the BG due to being AFK do not get deserted.

This is being abused by players to instantly rejoin BGs after getting kicked out and continuing to leech.

In the example image, we had already removed Cerynn once from the game due to being AFK, who instantly rejoined and went AFK again. Once again we reported him, but this time I took screenshots. This isn't the only time I've seen people abusing this either.

![AFK evasion.jpg](https://bitbucket.org/repo/B8qqer/images/831219143-AFK%20evasion.jpg)

Also, consider this a report on Cerynn for AFK evasion too.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2524

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/418
