### ISSUE TITLE
Fire At WIll Quest bugged

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2620]
Originally reported by: **Anonymous**

----------------------------------------

The fire at will quest in Blade's Edge Mountains. No matter where you stand at the North fel cannon you cannot gain control of the cannon. 

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2526

**Comment by AnonXS** [comment]
#1774
