### ISSUE TITLE
Serpentshrine: Trash Mobs

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2639]
## Minor/Trivial Issues: ##

* Serpentshrine Lurker 21863 mushroom only self dmg (Takenout Buggy Spell, implemented workaround)

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2545

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2962
