### ISSUE TITLE
Daily PvP

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2662]
Originally reported by: **Vegard (Bitbucket: [Pompel](https://bitbucket.org/Pompel), GitHub: [Pompel](https://github.com/Pompel))**

----------------------------------------

You get a little over 200 honor (and no money) for doing the daily PvP quest on Hellfire. You're supposed to get 419 honor and 11G 99S.

http://wowwiki.wikia.com/wiki/Burning_Crusade_daily_quests
http://wow.allakhazam.com/wiki/Outlands_Daily_Quests_Guide_(WoW)
http://wow.gamepedia.com/Burning_Crusade_daily_quests

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2568

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/blob/afd5eb9cbc4f67518e5d32eb7227acd130acdea6/sql/updates/world/050_U%2020.08.16.sql#L1127
