### ISSUE TITLE
Rare Spawn Speaker Mar'grom

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2675]
Originally reported by: **Anon  X (Bitbucket: [Anonx](https://bitbucket.org/Anonx), GitHub: [Anonx](https://github.com/Anonx))**

---

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2581

**Comment by ihcTactics** [comment]
So, not related to pathway, but this mob should always drop a BoE rare item like the other rare spawns.

He has NEVER dropped one on this server when i've killed him nor for anyone I've talked to.
http://www.wowhead.com/npc=18693/speaker-margrom
