### ISSUE TITLE
Tremor totem autoattack

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2685]
Originally reported by: **Evolve (Bitbucket: [Evolveuwotm9](https://bitbucket.org/Evolveuwotm9), GitHub: Unknown)**

---

tremor is unattackable most of the time in arena, you have to spend 10 seconds clicking on tremor and standing still to destroy it.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2591

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2312
