### ISSUE TITLE
Omor the Unscarred - Cast Time

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2687]
Originally reported by: **Tr1n1ty (Bitbucket: [Tr1n1ty_](https://bitbucket.org/Tr1n1ty_), GitHub: Unknown)**

---

from the 2.1 patch notes

-Added a 2 second cast time to Omor the Unscarred's Treacherous Aura and Treacherous Bane(?) abilities.

This coud be changed to recreate a more pre nerf state of the encounter.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2593

**Comment by AnonXS** [comment]
We are post 2.1 now.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3205 prenerf > all
