### ISSUE TITLE
Greater Blessing of Sanctuary Lvl 60 Issue

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2689]
Originally reported by: **Adam Frazier (Bitbucket: [Meowzrz](https://bitbucket.org/Meowzrz), GitHub: Unknown)**

----------------------------------------

Hello,
Greater Blessing of Sanctuary is a lvl 60 required skill to learn, however, currently it has an additional requirement of rank 5 Blessing of sanctuary (learned at 70) instead of Rank 4 Blessing of sanctuary (learned at 60).  This makes a level 60 skill unattainable till lvl 70.  

Easy fix just change the requirement for "Greater Blessing of Sanctuary Rank 1" to  require "blessing of sanctuary rank 4."

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2595

**Comment by AnonXS** [comment]
"Easy fix just change the requirement for "Greater Blessing of Sanctuary Rank 1" to require "blessing of sanctuary rank 4 instead of rank 5."
