### ISSUE TITLE
Shamans Toughness Talent Reduces Duration from original Spell Duration not Reduced PvP Spell Duration

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2705]
Originally reported by: **Roman (Bitbucket: [Zacker123](https://bitbucket.org/Zacker123), GitHub: Unknown)**

----------------------------------------

Hello Gm's ! I just want to tell that shamans' talent "Toughness" is not working as it supposed to work.  It must reduce slow effect on 50% on shaman but it does not.  Warriors' hamstring is still 7 seconds but it must be 4 seconds. Hope you will fix that. Thank you.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2611

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2596
