### ISSUE TITLE
When a player runs away and the mob loses aggro, the mob will attack any other players if it encounters on it's way back to it's spot.

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2706]
Originally reported by: **Anonymous**

---

Usually, a mob will not aggro when resetting/returning to it's usual spot after a player has ran out of it's range. IIRC, they also usually evade any attacks at this point also.

Currently, mobs will attack you if you are between them and their usual spot (by that, I mean where they spawn or are patrolling). Their aggro is not in a passive mode during this period, as it should be. They will attack anyone who is near.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2612

**Comment by Anteara** [comment]
This is not fixed,

when a mob enters evade mode, the code currently sets him to aggressive.
