### ISSUE TITLE
Quest - Escape from Coilskar Cistern

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2711]
Originally reported by: **Anonymous**

---

This is an escort quest in Coilskar Cistern that requires the player to escort Earthmender Wilda out of the cave.

However, when you start the quest, she simply turns and walks into the wall and appears to fall through the world.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2617

**Comment by Saltgurka** [comment]
https://github.com/Looking4Group/L4G_Core/issues/697
