### ISSUE TITLE
prayer of mending

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2715]
Originally reported by: **Evolve (Bitbucket: [Evolveuwotm9](https://bitbucket.org/Evolveuwotm9), GitHub: Unknown)**

---

is supposed to jump to lowest hp player in grp

now he jumps to 100% HP...

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2621

**Comment by Saltgurka** [comment]
The info I've found suggests that the spell was changed to use smart targeting at some point, but in TBC it was random:

> By Powaqqatsi (5,781 – 2·16·41) on 2008/01/10 (Patch 2.3.2)		
It's not smart but it does have a short-ish bounce range (20 yards).

As Anonx said the wowwiki page was chaned in wrath, suggesting it was probably random until then.
