### ISSUE TITLE
Flask of the Titans

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2721]
Originally reported by: **Anonymous**

----------------------------------------

In patch 2.0 it must gain 1200 hp and reagents for it must be like vannila, must proofs in google and wowhead.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2627

**Comment by AnonXS** [comment]
We are not changing such things back to patch we are progression on.

Progression is about nonavailability of certain items, raidcontent and arena seasoning.
