### ISSUE TITLE
Cant stealth after a failed attempt in flare

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2724]
Originally reported by: **Shorak339 (Bitbucket: [Shorak339](https://bitbucket.org/Shorak339), GitHub: Unknown)**

----------------------------------------

If a Rogue tries to stealth once inside a flare. Stealth is rendered unusable untill relog or vanish. Happend in arena and bgs, reproduced in duels aswell.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2630

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/304
