### ISSUE TITLE
Soulshatter at 1st boss in MT

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2731]
Originally reported by: **alandrarcy (Bitbucket: [alandrarcy](https://bitbucket.org/alandrarcy), GitHub: Unknown)**

----------------------------------------

hi, i used my soulshatter at 1st boss in MT and he reflected it, but AoE spell should be unreflectable. Thx ;)

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2637

**Comment by AnonXS** [comment]
http://www.wowhead.com/npc=18341/pandemonius , Dark Shell http://db.looking4group.eu/?spell=32358 , Soulshatter http://db.looking4group.eu/?spell=29858
