### ISSUE TITLE
OHF normal - Lookout stop patrolling

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2738]
Originally reported by: **Anonymous**

---

Lookout will stop patrolling when they were pulled once and go back to where they were before. This will cause aggro on adjacent packs if they stay still near those packs.

Don't know where it has anything to do with the pathing re-enabled yesterday.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2644

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3189/commits/9782d529c48550626c999a47a374e75c31e1df42
Change Formation Leader in those patrols resolves the issue.
