### ISSUE TITLE
Distract

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2739]
Originally reported by: **Anonymous**

---

http://db.hellground.net/?spell=1725 Distract Rogue ability

Does not work correctly against Mobs that are patrolling, you cannot force them to face any other direction than which they are walking at the time of distract, all it does is stop them, when it should stop them and turn them towards the Iris of distract.

In PvP and against mobs standing still it works fine.

Just thought i'd report it here. Kudos

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2645

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/d23d2f805acbd2073507f473f37e8938d18cb575

**Comment by Saltgurka** [comment]
https://github.com/Looking4Group/L4G_Core/commit/c5bfadd763b3e19acf96f190eae70a5df265e713
