### ISSUE TITLE
(Shaman)Lightning Overload

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2741]
Originally reported by: **Anonymous**

----------------------------------------

A shaman just did frost shock on me and lightning overload procced on top of that.

Lightning Overload should only procc of Lightning bolt and Chain lightning and no other spells. Probably it's not only Frost shock triggering this spell aswell.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2647

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2701
