### ISSUE TITLE
melee abilities through pillar

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2745]
Originally reported by: **Evolve (Bitbucket: [Evolveuwotm9](https://bitbucket.org/Evolveuwotm9), GitHub: Unknown)**

---

kick, pumel etc can be casted through pillars 

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2651

**Comment by Saltgurka** [comment]
Solved when https://github.com/Looking4Group/L4G_Core/pull/3052 goes live.

Tested with basic attacks and various melee spells including Kick and Pummel. They all require LoS now.
