### ISSUE TITLE
Test Flight: The Zephyrium Capacitorium

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2746]
Originally reported by: **Anonymous**

---

Once you start the test flight  you get stuck and it does not launch you.
You have to relog to get unstuck, and the quest wont complete.
This is the first of a chain of quests

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2652

**Comment by Saltgurka** [comment]
Works fine for me. I guess this was fixed at some point?
