### ISSUE TITLE
Quest: Fire at WIll! Bug

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2747]
Originally reported by: **Anonymous**

----------------------------------------

Whenever I use the Naturalized Amunition targeting Death's Door Fel Canon it says 'Requires Death's Door Fel Canon'. It appearently just fail with the north canon because I did the objetive with the south canon. Please fix this I want the necklace so badly. 

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2653

**Comment by AnonXS** [comment]
#1774
