### ISSUE TITLE
Quest for swift form

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2750]
Originally reported by: **dantor01 (Bitbucket: [dantor01](https://bitbucket.org/dantor01), GitHub: Unknown)**

---

Hey.
I have riding skill 300 but there is no quest from Loganaar in Moonglade so I can start the chain for my swift flight form

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2656

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3117/commits/0527cc9993cbab2ce3cd451004471605bb1bb134
