### ISSUE TITLE
Quest: What Book? I don't See Any Book.

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2755]
Originally reported by: **Sebian (Bitbucket: [Sebian](https://bitbucket.org/Sebian), GitHub: [Sebian](https://github.com/Sebian))**

---

"Dirty" Larry says "Time to teach you a lesson in manners, little boy!" on repeat when talked to, doesn't begin the fight though. Abandoning quest and reacquiring didn't have an effect and closing and reopening client didn't do anything. Seen multiple people having this issue and it's worked in the past.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2661

**Comment by Saltgurka** [comment]
Is this still an issue? I can't reproduce it locally
