### ISSUE TITLE
Eclipsion Hawkstrider

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2756]
Originally reported by: **thomas laene (Bitbucket: [Fluffysteak](https://bitbucket.org/Fluffysteak), GitHub: Unknown)**

----------------------------------------

A while back the Eclipsion Hawkstriders in Shadowmoon Valley would spawn after killing their Cavaliers. Though the hawkstriders don't spawn anymore. Is this intended or bugged? 

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2662

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2846/files#diff-825568eed5df8e8ac4789489879d45dc
