### ISSUE TITLE
Deathfrost Melee Proc Chance

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2763]
Originally reported by: **Citruzzz (Bitbucket: [Citruzzz](https://bitbucket.org/Citruzzz), GitHub: Unknown)**

----------------------------------------

deathfrost is currently not working as intended as a melee enchant.

I've tested this enchant with a single-wielded rogue without poisons. After 1276 Hits (autoattacks + sinisters) i received a total of 41 procs (3,21%).

Depending on the weapon speed of 2,7, results in a ppm value of 0,7.

Calc: 0,7/(60/2,7)

PPM = (60/Weapon Speed) * (Procs / 100)

An old entry from wowwiki reveals us some information:
[Wowwiki Deathfrost](http://wowwiki.wikia.com/wiki/Enchant_Weapon_-_Deathfrost?oldid=1648242)

*Procs off both white and yellow attacks, but uses different mechanics. For procs from spells, the proc rate is 50%, the internal CD is 25s. There is no internal cooldown for melee procs which appear to be 10-12.5%. Can refresh itself but does not stack*.

We all know that all enchantments are always ppm based since the very beginning of wow. So the entry is not very accurate.

Additional to the wowwiki entry i found an old discussion forum with reference to wowwiki and elitist jerks: [Deathfrost Discussion](http://wow.allakhazam.com/forum.html?forum=243&mid=1214255668244128328)

*Over the weekend I heard from a few friends who just got it that the proc rate is 4ppm (approx). But I haven't seen the actual WWS for it as yet. If I had to guess, 4 is a bit optimistic and I'd expect more like 1 or 2ppm. WowWiki has it at 10% (to which I have to ask "10% of WHAT!?"), but it's normalized, so...* 

*Deathfrost is a 2 part enchant, as melee its ppm is a little above 2(2.2-2.3 last i checked on EJs and from my own testing in blasted lands), the casting component of the enchant has an aprox 25sec internal cooldown(which also = aprox 2ppm).*

If we take the ppm rate from EJ with the usual main hand weapon speeds of 2,6 and 2,7 into account, we are receiving the following proc chances:

2,25/(60/2,6) = 9,75%

2,25/(60/2,7) = 10,13%

So the wowwiki entry is nearly met.

Please adjust the proc chance of deathfrost to 2,25ppm for melees.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2669

**Comment by AnonXS** [comment]
-- Item Enchant other table
SELECT * FROM `spell_proc_event` WHERE `entry` = ;

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2837/commits/cf737c5cf4e0288fa9bb200036ccc1db43a18e20
