### ISSUE TITLE
Cloak of Shadows @ Gruul

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2768]
Originally reported by: **Citruzzz (Bitbucket: [Citruzzz](https://bitbucket.org/Citruzzz), GitHub: Unknown)**

---

Currently it is not possible to "cloak" the "gronn lord's grasp"-debuff. A rogue should be able to clean the slow debuff, but the explosion outgoing from the rogue and the damage from other sources should not be avoidable.

https://www.youtube.com/watch?v=R7G-eI031Hc

hope this video from april 2007 is more than sufficient

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2674

**Comment by AnonXS** [comment]
Seems logic as the damage dealt is physical. Was this changed over time?

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3876/commits/9b493fca74101564a15ca102014cce23a456b26a
