### ISSUE TITLE
Magtheridon's Head drop chance

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2769]
Originally reported by: **Anonymous**

----------------------------------------

I've now killed Magtheridon around 5 times - and have yet to see his quest item drop (ie. Magtheridon's Head) - is this item removed? or just not implemented? to my understanding, it should be a 100% droprate..
Would be lovely with some clarification / fixes on this, as the ring from the quest is actually BiS for some

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2675

**Comment by honeyhoney** [comment]
This is not a bug. And will be added when 2.1 content is released.
