### ISSUE TITLE
Zuluhed/Varedis do not use abilities

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2771]
Originally reported by: **hitpoint (Bitbucket: [hitpoint](https://bitbucket.org/hitpoint), GitHub: [hitpoint](https://github.com/hitpoint))**

----------------------------------------

Zuluhed spells:
http://www.wowhead.com/npc=11980/zuluhed-the-whacked#abilities

He should also carry a staff. Right now he punches.

Varedis spells:
http://www.wowhead.com/npc=21178/varedis#abilities

Varedis should also use metamorphosis and change into a demon. This is when you have to use the book of fell names. I did this quest twice and he didn't change into a demon either time.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2677

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2832/commits/78ce2edf11721ea353f4d939972e30badddc89e8
