### ISSUE TITLE
Seal of Justice - raid bosses

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2776]
Originally reported by: **Selphius (Bitbucket: [Selphius](https://bitbucket.org/Selphius), GitHub: [Selphius](https://github.com/Selphius))**

----------------------------------------

Next bug not reported and abused by guilds... I'm really astonished now guys, after using all such despicable methods you later dare to cry to devs "PvE" is too easy.

I didn't experience it firsthand, since I only got this info from some of my trusted friends, so dear GM's if you can test by yourselves which is way faster to check it.

It's about skill called "Seal of Justice" 
https://tbc-twinhead.twinstar.cz/?spell=31895
http://wow.gamepedia.com/Seal_of_Justice

And more accurately about this part from it: 
"Unleashing this Seal's energy will judge an enemy for 20sec, preventing them from fleeing and limiting their movement speed."

My friend said he and his guild killed Magtheridon THIS WAY when their MAIN TANK died. They used this spell on her, and KITED HER which shouldn't be even possible. Seems like this spell particularly has some kind of "backdoor" against bosses and their immunity flag to slow.

So please test it at your own discretion, since you have better means to it. Guild who used this bug "Last Word" from Alliance, you can even question them about it. 

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2682

**Comment by AnonXS** [comment]
-- joj immunity for bosses
UPDATE `creature_template` SET `flags_extra`=`flags_extra`|1073741824 WHERE `rank`=3;
