### ISSUE TITLE
Recipe: Captain Rumsey's Lager

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2782]
Originally reported by: **Anonymous**

----------------------------------------

[Barrel of Fish](http://db.looking4group.eu/?item=33844) and [Crate of Meat](http://db.looking4group.eu/?item=33857) doesnt contain this [recipe](http://db.looking4group.eu/?item=34834).

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2688

**Comment by AnonXS** [comment]
http://wowwiki.wikia.com/wiki/Barrel_of_Fish

Patch 3.2.0 (04-Aug-2009): The recipe for [Captain Rumsey's Lager] can now be randomly found in the quest reward [Crate of Meat 33857], [Barrel of Fish 33844], or [Small Spice Bag 44113] from the cooking dailies.
