### ISSUE TITLE
Hyakiss the Lurker

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2784]
Originally reported by: **hitpoint (Bitbucket: [hitpoint](https://bitbucket.org/hitpoint), GitHub: [hitpoint](https://github.com/hitpoint))**

----------------------------------------

We decided to do the animal boss tonight. It should spawn after all the mobs in the animal wing are cleared. Instead, he was already spawned when we got there, in a pack of 3 spider mobs. Which shouldn't be the case because he should only spawn when all mobs are dead.

"This boss is one of three random bosses that can spawn in the basement (Servants Quarter) of Karazhan once you have killed all of the spiders, bats and hounds in the area. You must kill ALL of them and have the entire area clear, no respawns for one to spawn."

http://www.wowhead.com/npc=16179/hyakiss-the-lurker#comments

Next, we pulled him and his "acidic fang" hit me for 15k nature damage and killed me, then it hit the other tank for 13k nature damage and killed him. His regular melee attack was 5k, this spell shouldn't be doing that much damage.

"By Pseudo (6,986 – 1·11·74) on 2007/02/24 (Patch 2.0.8)		
Hyakiss the Lurker
260k HP
Casts a web on seemingly random party member.. dispellable.. webbed person can't do anything Casts a poison effect... curable.. otherwise it's supposedly stackable, 500dmg/3sec... and reduces armor by 500... per application
tank and spank fight"

http://www.wowhead.com/npc=16179/hyakiss-the-lurker#comments

Here is the spell http://db.hellground.net/?spell=29901

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2690

**Comment by AnonXS** [comment]
Relinking already existing Pathing for Hyakiss the Lurker as long as Core Zone Script is nonexistant.

UPDATE `creature` SET `MovementType`=2 WHERE `guid`=56809;

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2832/commits/e516dae62aa4f1984d69637b80c41d1b720b70e6
