### ISSUE TITLE
Dealer Senzik - Netherstorm Stormspire

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2789]
Originally reported by: **Robustious (Bitbucket: [Robustious](https://bitbucket.org/Robustious), GitHub: Unknown)**

----------------------------------------

http://www.wowhead.com/npc=19538/dealer-senzik#comments

By menasheh (2,267 – 1·22) on 2007/04/24 (Patch 2.0.12)		
The gems he sells for 4g are usually 2-3g on the AH.

Vendor is not supposed to sell those common gems for 90 silver. Their price should be 4g. All our green gems coming from mining have been going into waste due to that. 
Can we have an adjust towards this? Should be easy to fix

http://db.looking4group.eu/?npc=19538

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2695

**Comment by AnonXS** [comment]
UPDATE `item_template` SET `BuyPrice`=40000 WHERE `entry` IN (23095,28595,23113,23106,23097,23105,23114,23100,23108,23098,23104,23099,23121,23101,23103,23116,23109,23096,23110,28290,23118,23111,23119,23120,23094,23115);

**Comment by AnonXS** [comment]
U 14.09.16_Creature_Template_AI
