### ISSUE TITLE
Mag bugs out and randomly aggros if you wipe on phase 1

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2797]
Originally reported by: **Anonymous**

---

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2703

**Comment by AnonXS** [comment]
if it happens, all raid except a hunter logout and feigndeath pull the encounter for it to reset properly, just watch out that magtheridon should not be targetable, if he is, it did not work and you have to retry.

**Comment by Selphius** [comment]
What about trying this then? 

to void Reset()
`me->AddUnitState(UNIT_STATE_STUNNED);`

and to void AttackStart()

`if (!me->HasUnitState(UNIT_STATE_STUNNED))
            ScriptedAI::AttackStart(who);`

**Comment by Saltgurka** [comment]
Fixed with https://github.com/Looking4Group/L4G_Core/pull/3119
