### ISSUE TITLE
Greatfather Aldrimus Missing

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2799]
Originally reported by: **Anonymous**

----------------------------------------

Quest: Everything Will Be Alright (horde) - NPC is not there to turn in quest to.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2705

**Comment by LiamC84** [comment]
I completed the "I See Dead Draenei" chain - that's how I was initially able to accept and do the quest - now the NPC is no longer there to turn the quest in.

**Comment by AnonXS** [comment]
```
sql

-- Greatfather Aldrimus
DELETE FROM `creature` WHERE `guid` = 100047;
INSERT INTO `creature` VALUES (100047, 19698, 530, 1, 0, 0, -3345.28, 5189.06, -100.966, 5.77704, 120, 0, 0, 1, 0, 0, 0);
DELETE FROM `creature_questrelation` WHERE `quest` = 10164;
INSERT INTO `creature_questrelation` VALUES
(19698,10164);
DELETE FROM `creature_involvedrelation` WHERE `quest` = 10164;
INSERT INTO `creature_involvedrelation` VALUES
(19698,10164);

```

Okay, the npc offering the Quest is missing in alot of "public" Databases.

https://github.com/Looking4Group/L4G_Core/pull/2832/commits/820f63a98c71841bdd6e79b955fe91c14421c0f1

**Comment by LiamC84** [comment]
Still not working.. can't see this NPC even though I've completed "I See Dead Draenei"
