### ISSUE TITLE
SSH HC rogue/side packs aggroing randomly

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2800]
Originally reported by: **Snackrat (Bitbucket: [Snackrat](https://bitbucket.org/Snackrat), GitHub: Unknown)**

----------------------------------------

There's a rogue that's positioned at the foot of the steps, before you enter the last boss room.  We had a healer die on the final two champions and, in the time it took him to run back, this rogue respawned 2 or 3 times right on top of us, with that fear noise on spawn.

Also, this seemed like a tricky one to recreate intentionally, but I've been to the dungeon on separate occasions and had the side packs (with the champions that do mortal strike) aggro when no one was anywhere near them. No one had even moved closer to them and they attacked. I think it tended to happen when pulling one of the packs ahead (maybe the houndmaster pat?).

I'm not sure if these issues are exclusive to HC, but that's where I experienced them tonight.

Hope this is at all useful. Thanks for the work you guys are doing!

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/2706

**Comment by AnonXS** [comment]
As the Boss script itself doesnt trigger rogue spawning and we want the groups to do the boss in the correct manner - standing on the grid the 2 rogues befor the last pack were repositioned and set on lower respawn timer. But thanks for pointing out that they dont respawn after engaging the Boss.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/blob/master/sql/updates/world/065_U_14.09.16_Creature_Gameobject.sql#L159
