### ISSUE TITLE
Guild announces cooldown format

### ISSUE THREAD

**Issue by Dekos3** [Looking4Group/L4G_Core#2807]
When you try to send a ".guild ann" and the thing is under cooldown, you get a message saying "Cooldown between messages didn't pass (4294965497 seconds left) :]". In order to correct this, I think you should edit file "L4G_Core/src/game/Level1.cpp" and replace the following line : 

PSendSysMessage("Cooldown between messages didn't pass (%u seconds left) :]",(uint32)(time(NULL) - sGuildMgr.GetGuildAnnCooldown(gId)));

By this one : 

PSendSysMessage("Cooldown between messages didn't pass (%u seconds left)",(uint32) (sGuildMgr.GetGuildAnnCooldown(gId) - time(NULL)));

Indeed, the 2 operands are currently inverted : the first one is smaller than the second one, which results in a negative number number, but since it's stored in an unsigned (i.e. positive) integer on 32 bits, it creates an underflow, which is the reason why we get that huge number actually representing "2^32 - cooldown".

**Comment by Xadras** [comment]
Thanks for this beautiful report+fix :>
