### ISSUE TITLE
SSC Trash Issue - Serpentshrine Sporebat

### ISSUE THREAD

**Issue by ihcTactics** [Looking4Group/L4G_Core#2810]
This NPC: http://www.wowhead.com/npc=21246/serpentshrine-sporebat#comments
[Sort comments by oldest]

Is supposed to be CC'able. Sheep, Hibernate, Fear, Trap, Etc.

What breaks the CC is when the Beast Tamer uses the Enrage (within it's range). This also makes them immune to CC. If the Beast Tamer is brought out of range before he enrages, it won't hit the Sporebats and they remain CC'd.

Also check here:
http://wowwiki.wikia.com/wiki/Serpentshrine_Sporebat

Edit: also, pretty sure they weren't using their Charge Ability: http://www.wowhead.com/spell=38461/charge
There's no listing for the CD of that spell.

**Comment by AnonXS** [comment]
They are using the Charge Ability but it is not animated as most Charge-like Spells.

We agreed on temp. Immunity as long as the beastwithin spell of the beast tamer is missing the despell component.
