### ISSUE TITLE
SSC/Trash - Underbog Colossus

### ISSUE THREAD

**Issue by Selphius** [Looking4Group/L4G_Core#2812]
Spore Quake - can be interrupted by intercept. Didn't test improved kick / shield bash etc. 
It shouldn't be interruptable in the first place since, it's supposed to be outranged - 30y.

**Comment by AnonXS** [comment]
Seems to be only maim and intercept that is able to interrupt somehow, the npc has immunity flags set against interrupt, so it must be some spellcomponent.
