### ISSUE TITLE
SSC/Lurker - Visual Bug

### ISSUE THREAD

**Issue by Robustious** [Looking4Group/L4G_Core#2816]
When he submerges, his body remains on the water and he is visible, although he was downside the water.
He is still acting like he is spouting but he is actually not as he is under the water. 
You can check here around 13:50
https://www.twitch.tv/donrobustious/v/90618380

I guess it's an easyfix.

**Comment by ihcTactics** [comment]
For <Final Exit> the visual bug had him in the middle targeting our MT if he was in melee range.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/blob/master/src/scripts/scripts/zone/coilfang_resevoir/serpent_shrine/boss_lurker_below.cpp#L408

Needs me->SetVisibility(VISIBILITY_OFF);

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/03d438a1ec5c9e9fb8c704e97526f0b33bc26d57
