### ISSUE TITLE
SSC/Vashj - Spore Cloud Damage

### ISSUE THREAD

**Issue by smkrus** [Looking4Group/L4G_Core#2818]
Currently does ~1700 per tick. Study suggests ~3,000 per tick.
https://www.youtube.com/watch?v=OFzbd7udjEU @ 8:55
1/3 of this priests life (likely ~9k) per tick
https://www.youtube.com/watch?v=Udlfkvaq1F8 @ 12:15
3xxx per tick?
https://www.youtube.com/watch?v=O_p7K9WA4pk @ 7:20
hit for ~3k twice in a row
https://www.youtube.com/watch?v=DI72EnXSimQ @ 8:29
-2934

It is/was the same on Feenix. I remember this being crazy on groups of rooted melee.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/blob/7c926f10745fe518f7e18ed4b0d52224ad24841e/src/game/SpellMgr.cpp#L3611

**Comment by smkrus** [comment]
What are you trying to say about this issue with that link?

**Comment by AnonXS** [comment]
This is the point in the core, which modifies the damage of the Spore Cloud Spell from standard value.

**Comment by hitpointt** [comment]
I also remember there being way, way more poisons on the ground at the end of the fight. Maybe Dreamstate just focus the bats more, or 2.4 talents make killing the bats easy. 

But, there might be something wrong with how fast the clouds despawn, or how often they're shot out, or how often bats spawn. Can someone who knows about it look into this?

**Comment by honeyhoney** [comment]
test

**Comment by smkrus** [comment]
https://www.youtube.com/watch?v=Udlfkvaq1F8 @ 10:48 - 11:08 cloud in the center area suggests 20 seconds duration of cloud. Haven't watched any others for that info yet.

**Comment by AnonXS** [comment]
I think both PoVs are speedup, https://youtu.be/XMVV2NgN4Ww?t=4m5s ~ x2  till 4:20 = 30s Duration like Sniffdata in spell.dbc file. To Produce a state which makes it feel more blizzlike, or how we encountered it on retail, i wanted to prolong the despawn to 60sec from 30sec. http://www.wowhead.com/spell=38575/toxic-spores

**Comment by Pbeitelmann** [comment]
I can confirm that the 60 seconds despawn for the void zones is currently not implemented. Prolonging the despawn is in my opinion not the best option (not blizzlike).
I'd prefer adjusting the sporebats themselves; making them cast on spawn is one possibility.

**Comment by Pbeitelmann** [comment]
Increased damage to 3k
