### ISSUE TITLE
SSC/Vashj - Phase 1 visual bug

### ISSUE THREAD

**Issue by hitpointt** [Looking4Group/L4G_Core#2819]
She holds her hands like in a casting animation the whole time until phase 2, despite meleeing and shooting. 

https://www.youtube.com/watch?v=01IPuPiqbHM

Proper behavior: https://www.youtube.com/watch?v=Udlfkvaq1F8

**Comment by hitpointt** [comment]
This wasn't a problem last night.

**Comment by honeyhoney** [comment]
This appears to have been resolved. Should it occur again then we'll re-open this issue.
