### ISSUE TITLE
Quest "bug"

### ISSUE THREAD

**Issue by Zugid** [Looking4Group/L4G_Core#2820]
Quest: Spectrecies
place: Shadowmoon Valley
my Warlock Pet cant attack the Shadowmoon Zealot.

**Comment by AnonXS** [comment]
Because Pets dont get the Buff, the player gets and can therefore not see/attack the Ghosts.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/1630
