### ISSUE TITLE
Draenei Gift of Naruu

### ISSUE THREAD

**Issue by Kyruss190** [Looking4Group/L4G_Core#2825]
at a interrupt in Gift of Naruu, all holy priest spells are on cd, that is buggy and isn't blizzlike. cause it's a people craft and no holy spell.

**Comment by robinsch** [comment]
Proof?

**Comment by AnonXS** [comment]
http://wowwiki.wikia.com/wiki/Gift_of_the_Naaru?oldid=1556896

http://wow.gamepedia.com/index.php?title=Gift_of_the_Naaru&oldid=1556896

Also modified by Holy School Talents.
