### ISSUE TITLE
Morogrim Tidewalker location

### ISSUE THREAD

**Issue by hitpointt** [Looking4Group/L4G_Core#2835]
He's standing in the wrong place. He should be closer to the middle of the room. This makes clearing the adds from either side of him very annoying. You have to clear to him from one direction, and then clear to him from the other.

You can see his correct location here. It shows him between the raid and two objects sticking out of the ground. On our server he is on the far side, with the objects between him and the raid.

https://www.youtube.com/watch?v=jd0R_DBtHSQ

**Comment by AnonXS** [comment]
http://www.wowhead.com/npc=21213/morogrim-tidewalker#screenshots:id=28948 will set him back to http://www.wowhead.com/npc=21213/morogrim-tidewalker#screenshots:id=246875 but where it is still not possible to enter the room from the other side without pulling him.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2814/files , https://github.com/Looking4Group/L4G_Core/pull/2832/commits/4e804cefe2a989a0a1e0719d5e4281bef1a83818
