### ISSUE TITLE
SSC/Vashj - Coilfang-Elite spawn

### ISSUE THREAD

**Issue by AbaddonL4G** [Looking4Group/L4G_Core#2838]
About 1/3 of the coilfang elite (http://db.looking4group.eu/?npc=22055) is not spawning.

timer looks good but some are just complete missing.
´
maybe timers are overlapping

` 
  
        AggroTimer = 19000;

        PulseCombat_Timer = 5000;

        ShockBlast_Timer = urand(1, 60001);

        Entangle_Timer = 30000;

        StaticCharge_Timer = urand(10000, 25000);

        ForkedLightning_Timer = 2000;

        Check_Timer = 2000;

        ParalyzeCheck_Timer = 1000;

        Persuasion_Timer = 30000;

        EnchantedElemental_Timer = 5000;

        TaintedElemental_Timer = 50000;

        **CoilfangElite_Timer = 45000;**

        CoilfangStrider_Timer = urand(60000, 70000);`

**Comment by honeyhoney** [comment]
"Overlapping" timers? This is highly unlikely to cause an issue. Have you tested this to confirm the bug?

**Comment by AbaddonL4G** [comment]
tested on live raid with guild.

seems like random not spawning nagas - but never occured twice in a row.

e.g.:
NAGA - MISSING NAGA - NAGA - MISSING NAGA - NAGA - NAGA

smth like that

**Comment by AbaddonL4G** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2839

should fix this

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2839
