### ISSUE TITLE
SSC/Fanthom Lord Karathress - Cataclysmic Bolt Targeting

### ISSUE THREAD

**Issue by Selphius** [Looking4Group/L4G_Core#2843]
It's about his spell called Cataclysmic Bolt. 
http://www.wowhead.com/spell=38441/cataclysmic-bolt#comments

Yesterday, he used it on our Feral Druid tank, who tanked shaman add.

This spell SHOULDN'T be used on targets who don't have mana pools - druid in bear doesn't have it so he shouldn't be a target of this spell, but right now Fanthom ignores it and uses it on targets without mana pools.

Cataclysmic Bolt: Targets random mana user, deals 50% of target's max HP in shadow damage (increased by The Beast Within), a brief knockdown and a stun. Resistible binary spell. 6 second cooldown. Targets only players with mana bars.

**Comment by Pbeitelmann** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2859
