### ISSUE TITLE
Ogri'la - can't summon bosses

### ISSUE THREAD

**Issue by Selphius** [Looking4Group/L4G_Core#2844]
So my problem is, and not only mine (talked to a lot of people about it), we don't see gossip for summoning the ogri'la bosses. 
In my case I have 1500 shards, and quests for summoning's done. Before, when I had quests on them, I could summon those bosses, after that when I completed the quests, I couldn't summon and still can't to summon a single boss 1 month+ passed since then.

I guess the reason can lay in the "check". 
`if (player->HasItemCount(ITEM_APEXIS_SHARD, large ? 35 : 1) && large ? player->GetQuestStatus(QUEST_GUARDIAN) == QUEST_STATUS_INCOMPLETE : (player->GetQuestStatus(QUEST_APEXIS) == QUEST_STATUS_INCOMPLETE || player->GetQuestStatus(QUEST_EMANATION) == QUEST_STATUS_INCOMPLETE))`

As you can see it checks if player DIDN'T complete the quests, and if he has 35 shards, but it doesn't check if player DID complete the quest. So I would suggest trying to make the code look like this, maybe it will solve our problem:
`if (player->HasItemCount(ITEM_APEXIS_SHARD, large ? 35 : 1) && large ? player->GetQuestStatus(QUEST_GUARDIAN) == QUEST_STATUS_INCOMPLETE : (player->GetQuestStatus(QUEST_APEXIS) == QUEST_STATUS_INCOMPLETE || player->GetQuestStatus(QUEST_EMANATION) == QUEST_STATUS_INCOMPLETE) ||
player->GetQuestStatus(QUEST_GUARDIAN) == QUEST_STATUS_COMPLETE : (player->GetQuestStatus(QUEST_APEXIS) == QUEST_STATUS_COMPLETE || player->GetQuestStatus(QUEST_EMANATION) == QUEST_STATUS_COMPLETE))`

**Comment by AnonXS** [comment]
Yea this was one of my final [questions](https://github.com/Looking4Group/L4G_Core/issues/2779)  in regards of polishing Ogri'la further, thanks for bringing it up.

**Comment by ihcTactics** [comment]
I'm sitting at exalted and can't get the bracers because I can't re-summon any of the bosses except the dragons (who don't drop the crystal).

**Comment by Pbeitelmann** [comment]
Fixed
