### ISSUE TITLE
zangamarsh - marsh lurker

### ISSUE THREAD

**Issue by Slycer01** [Looking4Group/L4G_Core#2845]
![wowscrnshot_092916_170746](https://cloud.githubusercontent.com/assets/5159402/18959740/9246400c-8667-11e6-85c6-df25763db596.jpg)

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2846/commits/b2b273a3a47add9c099702ca22a75158b19c56b5
