### ISSUE TITLE
TK/Kael'thas Sunstrider - Falldamage

### ISSUE THREAD

**Issue by Selphius** [Looking4Group/L4G_Core#2847]
1. 
   Fall dmg in phase 5 doesn't practically exists, which makes gravity lapse easier than normal. Normally you would need to be at kael's chest/head height, but you can be further up 40-50y and take maybe 3k dmg only which is wayyyyy off.

**Comment by AnonXS** [comment]
(2) http://wowwiki.wikia.com/wiki/Conflagration?direction=prev&oldid=301605

**Comment by Selphius** [comment]
AnonXS, you're wrong about conflagration spell, since it really would be a joke not a spell if it deals 3k dmg in 10s. In p3 with mace buff it would be 1500 dmg only. Look at this video 
https://www.youtube.com/watch?v=micyD_ClsMo
and 0:54, you can see paladin with fire aura gets ticked for 900 each second = 10s = 9k dmg. I remember this spell harder, way harder than now. Hellground kael'thas had 9k from the start too.
On L4G now, this spell is srsly a joke, you can stay in 20y range and don't give a shit about this spell since you can bandage yourself up after it ends.

**Comment by hitpointt** [comment]
This is the spell.

http://db.hellground.net/?spell=37018#see-also-ability

**Comment by hitpointt** [comment]
This spell maybe. It's definitely not the 3k one.

http://db.hellground.net/?spell=37018#see-also-ability

**Comment by honeyhoney** [comment]
Conflagration issue should be tracked separately, please keep future discussion to resolving the issue at hand (fall damage).

**Comment by AbaddonL4G** [comment]
@https://github.com/Looking4Group/L4G_Core/pull/2914
