### ISSUE TITLE
Ogri'la - Fel Crystal Prisms

### ISSUE THREAD

**Issue by ihcTactics** [Looking4Group/L4G_Core#2850]
http://www.wowhead.com/object=185927/fel-crystal-prism

You're supposed to be able to repeatedly use these (on a CD timer). At the moment, you can only use them when you do the quest: http://www.wowhead.com/quest=11079/a-fel-whip-for-gahk

Buying items like http://www.wowhead.com/item=32647/shard-bound-bracers require  multiple http://www.wowhead.com/item=32572/apexis-crystal , which should be easily farmable from the summoned demons at the prisms.

Right now, it only seems you can do this is you find someone who hasn't done the ogri'la elite quests.

**Comment by Xadras** [comment]
Isn't this the same as #2844?

**Comment by ihcTactics** [comment]
You're correct. Sorry. I actually looked at that thread ~30 mins prior to making mine. I'm a little tired.
