### ISSUE TITLE
Quest - The Vials of Eternity

### ISSUE THREAD

**Issue by honeyhoney** [Looking4Group/L4G_Core#2851]
The quest The Vials of Eternity / http://db.looking4group.eu/?quest=10445 is currently not available to players.

(hint for @AnonXS `INSERT INTO `creature_questrelation` (id, quest) VALUES (19935, 10445);` to next migration? Check ids etc.)

**Comment by Pbeitelmann** [comment]
Put live. @AnonXS  will add it to his next migration.
