### ISSUE TITLE
TK/Kael'thas Sunstrider - Conflagration

### ISSUE THREAD

**Issue by Selphius** [Looking4Group/L4G_Core#2852]
Grand Astromancer Capernian conflagration spell dmg is off, players affected by it take too low dmg in 10s current - 3k, when it should be 9k over 10s As proof look at this video:
https://www.youtube.com/watch?v=micyD_ClsMo
and at 0:54, you can see paladin with fire aura gets ticked for 900 each second = 10s = 9k dmg.
On L4G now, this spell is srsly a joke, you can stay in 20y range and don't give a shit about this spell since you can bandage yourself up after it ends, so why care even to stay out of range, if all you take is measly 3k dmg which is not even 30% of total hp for most classes.

**Comment by AnonXS** [comment]
Source Gathering:

https://www.youpak.com/watch?v=micyD_ClsMo

http://wowwiki.wikia.com/wiki/Conflagration?direction=prev&oldid=301605

http://web.archive.org/web/20090419171828/http://wow.gamona.de/das-spiel/instanzen-und-raids/burning-crusade/festung-der-stuerme-das-auge/prinz-kael-thas-sonnenwanderer

http://web.archive.org/web/20100915144152/http://hordeguides.de/Schlachtzug/TBC/Boss/19622/Kaelthas-Sonnenwanderer/index.htm

**Comment by Selphius** [comment]
http://wow.gamepedia.com/Grand_Astromancer_Capernian
http://www.wowhead.com/npc=20062/grand-astromancer-capernian
http://www.slashcry.fora.pl/pve,32/the-eye-taktyki,170.html
http://www.skryer.com/index.php?art/id:436

**Comment by honeyhoney** [comment]
@Selphius I'd just like to extends my thanks to you for creating this issue to separate the Kael'thas issues you've encountered. It really helps us keep things organised and track distinct issues more effectively.

**Comment by Selphius** [comment]
@honeyhoney No problem, happy to be of help.

**Comment by Selphius** [comment]
Some of the issues here, really take to long to fix - especially the easy ones (timers, immunities etc.). For this one I assume it's only a spell replacement (correct spell id)? Since on Hellground this was never bugged, from 2011 year+, and from my knowledge you use 2014 hg version?

**Comment by AbaddonL4G** [comment]
Spell is working as it should dealing 900dmg per second.
