### ISSUE TITLE
Spell: Dismounting Blast does not dismount the player

### ISSUE THREAD

**Issue by Saltgurka** [Looking4Group/L4G_Core#2858]
http://db.looking4group.eu/?spell=18396

The spell does not dismount the player, it only knockbacks. 

The spell is used by, among others [Thrallmar Wolf Riders](http://www.wowhead.com/npc=16599/thrallmar-wolf-rider)

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/1888
