### ISSUE TITLE
Serpent-Coil Braid Mana Gem Increase

### ISSUE THREAD

**Issue by Zulky** [Looking4Group/L4G_Core#2861]
The Mage class trinket from Morogrim Tidewalker named "Serpent-Coil Braid" does not correctly increase the mana gained from Mana gems by 25%. It is correctly applying the spell power buff.  

This is an integral component to be able to raid as Arcane in t5!

Thanks.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/blob/dcfca2ee0bc27632b8251f6ab40f724856896542/src/game/SpellEffects.cpp#L3678

**Comment by Xadras** [comment]
I'm going to test first.. It worked well on quel'thalas...

**Comment by Xadras** [comment]
![wowscrnshot_100416_162541](https://cloud.githubusercontent.com/assets/12048181/19078457/77ce353a-8a50-11e6-99f7-eb90018553a9.jpg)

![wowscrnshot_100416_162431](https://cloud.githubusercontent.com/assets/12048181/19078472/856aca50-8a50-11e6-88ff-e5d0031081e1.jpg)

**Comment by AbaddonL4G** [comment]
Never forget - tooltips are clever :P

**Comment by Xadras** [comment]
btw @AnonXS:
the web database is not very accurate for spell dev things. The Effect0 AuraID provided there is simply wrong.
QtSpellwork is much more better for spell things -> SPELL_AURA_ADD_PCT_MODIFIER is provided there correctly.
