### ISSUE TITLE
Fathom-Guard Tidalvess timers are wrong

### ISSUE THREAD

**Issue by hitpointt** [Looking4Group/L4G_Core#2862]
He is the shaman add in the Fathom-Lord Karathress fight. 

This mobs timers for dropping totems are wrong. He is dropping spitfire totem way too late, and way too infrequently. Tonight he dropped 3 totems total for us tonight. A poison cleansing totem at 60% health, a spitfire at 30% health, and another poison cleansing also at 30%.

See this video for how quickly he should be dropping totems. At 30 seconds into the video he already has all 3 of them down at the same time.

https://www.youtube.com/watch?v=siCBD90IJ7k

**Comment by AnonXS** [comment]
This is how [https://github.com/cmangos/mangos-tbc/blob/master/src/scriptdev2/scripts/outland/coilfang_reservoir/serpent_shrine/boss_fathomlord_karathress.cpp#L374](mangos-tbc core) handles this. Timers can and should be discussed and researched with old videos.
