### ISSUE TITLE
Warlock/Talent - Soul Link

### ISSUE THREAD

**Issue by Adwean** [Looking4Group/L4G_Core#2863]
Played some arenas today with a comp of Elemental Shaman + PoM Pyro mage. We met a team of soul link lock(8k hp blue geared) + resto druid which is common. The fun part was when we focus the lock with his pet out and litteraly pop everything on him. I am the best geared shaman on the server (PvP wise) and critted him for 600 chain lightning crit (300 crit to his pet) and my mage who is pretty much bis geared aswell crit him with pyroblast for 1032 damage. Its either Soul Link bug that every warlock is abusing or there is something else involved. Maybe other tallent. Do you mind testing it out and review all of their protection tallents in case there is a major bug that every warlock is abusing in PvP. This is ridiculous.
The PvP scene is almost dead but seeing even starter geared warlocks abusing tallent spec to gain raiting is making it even worst.

That is his current tallent spec -> http://calculators.iradei.eu/talents/warlock?3500222012231110000002052010133250101511300000000000000000000000

Enlighten me since when a chain lightning that is supposed to hit for 2.5k - 3k crit got reduced to 600 damage? Thats more like 200% to me not 20% from Soul Link.

Also the mage is hitting me with his Pyroblast for 3500 normal (I am with 311 resilience) cast it on the warlock who has aprox 50 resilience for 1032 crit. So from aprox pyro crit that is supposed to be 6k+ it got reduced to 1032 damage. Sounds like pure abusing in PvP.

**Comment by AbaddonL4G** [comment]
http://db.looking4group.eu/?spell=25228

**Comment by honeyhoney** [comment]
Thanks for the report.

> Do you mind testing it out and review all of their protection tallents in case there is a major bug that every warlock is abusing in PvP.
This would take an inordinate amount of time for thr dev. team to carry out. Perhaps yourself and some others would be willing to carry out some testing and provide a slightly more comprehensive bug report.

**Comment by honeyhoney** [comment]
@Adwean is this a valid issue?

**Comment by Adwean** [comment]
Tested it out with Beefjurkey it seems its either bug abuse of something or proc of a tallent that is causing the huge amount of damage reduction. Here is a screenshot of my testing with Beef. 
![beef test](https://cloud.githubusercontent.com/assets/22595427/19055057/cb44d0ec-89ca-11e6-92fb-fb46486603a1.jpg)

Please investigate the character : Ellectron , that is the person who I think is abusing something in his advantage to gain rating in 2v2 arenas.

**Comment by bk187** [comment]
Just simply try doing dmg on Soul Link + Resi gear vs dmg on Soul Link without Resi gear = elimination method, so you can see if it's SL giving wrong numbers in combination with the any amounts of resilience or it's simply being broken no matter what.

**Comment by Adwean** [comment]
Did it with and without tons of resilience already. He had his SL up so it was pointless to test it without SL up. If any other warlock is up for testing /w Adwena anytime. I am pretty much online 24/7 :D

**Comment by Adwean** [comment]
Finnaly got the abuser : http://imgur.com/a/ucT7G

**Comment by Xadras** [comment]
Would be interesting to know, what he is doing to get those values xD

**Comment by thunderbla** [comment]
maybe u use rank 1 Chain Lightning ? :D

**Comment by Adwean** [comment]
Yeah maybe half of the server is casting rank one spells on hit because we are good people and like to give out free ratings :)

**Comment by AbaddonL4G** [comment]
Gonna check his char today

**Comment by AbaddonL4G** [comment]
Looks like abuse of smth. SL reduce looks fine

**Comment by Xadras** [comment]
Then simple tactic: 
1. perm ban
2. he should explain what he had abused in which way
3. if he do so: remove perm ban
4. time ban of X + arena reset for him

**Comment by teddys** [comment]
maybe he is just better than you (:

**Comment by honeyhoney** [comment]
Closing this, thanks for the contributions.

**Comment by teddys** [comment]
thanx for deleting my post even on bugtracker
lmfao
what a bunch of retards
