### ISSUE TITLE
Ravenous Windroc does Eagle Claw while stunned

### ISSUE THREAD

**Issue by bk187** [Looking4Group/L4G_Core#2866]
So what happened is that I stunned the npc for 6 sec, went straight for healing by spamming flash of light and got kill 2 sec after, he simply used his claw ability while being stunned.

![bugzorr](https://cloud.githubusercontent.com/assets/22599561/19047717/4b77512c-89a3-11e6-8c91-be6fa674bbb4.jpg)

**Comment by AnonXS** [comment]
Maybe linked to https://github.com/Looking4Group/L4G_Core/issues/741, but seems rather spell related. (no triggerflag)

**Comment by AnonXS** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/23826032/3df39e2e-0695-11e7-9af6-5149de92350e.PNG)

its the dot.
