### ISSUE TITLE
Quest in Tausend Nadeln

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#287]
MMAPS Issue

In Tausend Nadeln buggen einige Grimmtotem oben auf den "Nadeln". Mit den Hängebrücken stimmt was nicht. Man fällt manchmal einfach durch, mobs despawnen und die Begleitquest kann nicht abgeschlossen werden, weil der npc seit 3h trotz ausloggen an der gleichen Stelle bugt. Abbruch der Quest ändert nichts.

**Comment by Saltgurka** [comment]
Someone please translate the issue to english

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2817
