### ISSUE TITLE
Losing Gracefully - Quest problem

### ISSUE THREAD

**Issue by Adwean** [Looking4Group/L4G_Core#2900]
The quest -> http://db.hellground.net/?quest=10169 was working perfectly few days ago , its a simple quest where you have to go next to the bowl and use the quest item to complete. Sadly one of my guildmates had a problem today because the bowl is missing or deleted by accident. 
http://i.imgur.com/vEab573.jpg Screenshot on the spot with the missing quest object.

Could you please add the bowl. Here is a video of the quest on retail -> https://www.youtube.com/watch?v=vteHbRWZ0Ts  its fun to watch this mini event but adding the bowl of soup is enough :) 

Thanks!

**Comment by AnonXS** [comment]
Oh shit, i thought this is a sunwell gameobject only. /tonight.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2891/commits/14ce88f24f5ee3756ffad431165836c5c4880453
