### ISSUE TITLE
Terokkar Forest Empoor Bug

### ISSUE THREAD

**Issue by Sully92** [Looking4Group/L4G_Core#2904]
Empoor's body guard is bugged in one spot and does not patrol the road in Terokkar with him.

**Comment by AnonXS** [comment]
I think they dont move together because of faction and or death of Empoor / Empoor's Bodyguard.

https://github.com/Looking4Group/L4G_Core/blob/master/src/scripts/scripts/zone/terokkar_forest/terokkar_forest.cpp#L2221

```

-- Empoor's Bodyguard 18483
UPDATE `creature_template` SET `faction_H`='35',`faction_A`='35' WHERE `entry` = 18483; -- 7

```

https://github.com/Looking4Group/L4G_Core/issues/609

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2920/commits/96e4e67f83392ee996b12edafde1f77d06a1e768
