### ISSUE TITLE
Bug report from 3 quests

### ISSUE THREAD

**Issue by DjeyFR** [Looking4Group/L4G_Core#2908]
Dear Game Masters,

I encountered some difficulties with the following quests  :

- Against all odds (from npc Altruis in Nagrand) : Xeleth doesn't show up when the imbued silver spear is planted at Portal Clearing

- Frankly, it makes no sense... (Shadowmoon Valley) : couldn't take control of any arcano-unit

- Body of evidence (Nagrand) : after the ogres have planted the bodies, nothing happen.

Kind regards,

Djey

**Comment by AnonXS** [comment]
Please split them up in an Issue for each quest, discribing what the actual problem is and if you are kind you also deliver links to wowhead, videos on youtube on how it **should** work.

**Comment by DjeyFR** [comment]
Concerning the quest Against all odds, the npc named Xeleth doesn't show up when we use the item "Imbued silver spear" which is required to make him pop, like in this video (1'23" for the second one) : 

http://www.wowhead.com/quest=10669/against-all-odds#videos

Nothing happened, as I tried every place around Portal Clearing
