### ISSUE TITLE
Quest - Frankly, It Makes No Sense...

### ISSUE THREAD

**Issue by DjeyFR** [Looking4Group/L4G_Core#2910]
In this quest, we have to click on a controller that allowed the player to take control of an arcano-unit, like at 1'25" in this video from GitGudGuides on 2015/04/09 : 

http://www.wowhead.com/quest=10672/frankly-it-makes-no-sense#videos

Unfortunately, it actually doesn't work.

**Comment by AnonXS** [comment]
```

#QUEST, Frankly, It Makes No Sense 
insert into `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) values (37867,37868,1,'Arcano-Scorp Control');
insert into `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) values (37892,37893,1,'Arcano-Scorp Control');
insert into `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) values (37894,37895,1,'Arcano-Scorp Control');
update `creature_template` set `spell1`='37919',`spell2`='37918',`spell3`='37917',`spell4`='37851',`spell5`='0' where `entry`='21909';
insert  into `spell_script_target` (`entry`,`type`,`targetEntry`) values (37868,1,21909);
insert  into `spell_script_target` (`entry`,`type`,`targetEntry`) values (37893,1,21909);
insert  into `spell_script_target` (`entry`,`type`,`targetEntry`) values (37895,1,21909);

go: 185010 needs script
```
https://bitbucket.org/oregon/oregoncore/issues/1006/frankly-it-makes-no-sense-10672

https://github.com/TrinityCore/TrinityCore/issues/3749

https://www.youtube.com/watch?v=ebySnNcXSnU

http://www.wowhead.com/quest=10672/frankly-it-makes-no-sense

**Comment by Saltgurka** [comment]
https://bitbucket.org/oregon/oregoncore/issues/1006/frankly-it-makes-no-sense-10672

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3549
