### ISSUE TITLE
Quest - Against All Odds

### ISSUE THREAD

**Issue by DjeyFR** [Looking4Group/L4G_Core#2911]
Concerning the quest Against all odds, the npc named Xeleth http://db.looking4group.eu/?npc=21894 doesn't show up when we use the item Imbued silver spear http://db.looking4group.eu/?item=30853 

Plant into the ground at Portal Clearing near Marshlight Lake to awake the demon who sleeps by the sunken portal.
Send Event (14139)

which is required to make him pop, like in this video from WoWGnGP on 2016/06/13 at 1'23" : 

https://youtu.be/9QaFufUk0WI?t=1m23s

Nothing happened, as I tried every place around Portal Clearing

**Comment by Saltgurka** [comment]
Can't reproduce this. He spawns correctly for me every time
