### ISSUE TITLE
Blade's Edge Mountain quests.

### ISSUE THREAD

**Issue by whiteey** [Looking4Group/L4G_Core#2912]
After doing "The stones of Vekh'nir" quest there should be 2 more follow ups from the same guy named "Dertrok": 'Trial and error' and 'Ruuan Weald'. The problem is those 2 quests are not there, like they are not in the game.

http://wowwiki.wikia.com/wiki/Quest:The_Stones_of_Vekh%27nir
http://wowwiki.wikia.com/wiki/Quest:Trial_and_Error
http://wowwiki.wikia.com/wiki/Quest:Ruuan_Weald

These are the links to the quest. I completed the first one but the follow ups are not there.

--------------------------------------------------------------------------------------------

The second problem is a little bug with quest 'A boaring time for Grulloc'.

http://wowwiki.wikia.com/wiki/Quest:A_Boaring_Time_for_Grulloc

Here is the link and the problem is that Grulloc is not chasing the Boar, I did it when my friend helped me distract the Grulloc so I can loot the quest item next to him. SO it is doable, but it's a group quest with this bug. :)

Thx in advance.

**Comment by Saltgurka** [comment]
Thank you for the reports! We will look into it as soon as possible :)

Please refer to the existing posts regarding these issues: #1642 and #886
