### ISSUE TITLE
TK/Alar: Melting Armor Debuff shouldn't be in the game

### ISSUE THREAD

**Issue by Woomz** [Looking4Group/L4G_Core#2923]
http://wowwiki.wikia.com/wiki/Al%27ar?diff=prev&oldid=664783 (search for Melt)

Prior to Patch 2.1:
While being on the ground, he will occasionally spawn flame patches on random people that work in a similar fashion to void zones. People need to be aware and move away from the fire trails as soon as possible. Moreover, he can charge people for 300-400 damage leaving them momentarily stunned.

After Patch 2.1:
While being on the ground, he will occasionally spawn flame patches on random people that work in a similar fashion to void zones. People need to be aware and move away from the fire trails as soon as possible. Moreover, he can charge people for 300-400 damage leaving them momentarily stunned and he has a "Melt Armor" debuff that likes to put on the tank hitting him (which means that tank switching is essential once this happens).

https://www.youtube.com/watch?v=Xd7TvStTiw4

So in fact, as you can see in the video above, when Al'ar was still a pure dmg race, as you obviously want to have it, he was tankable by only one tank.

**Comment by hitpointt** [comment]
This is world first Al'ar kill from retail. And he is using the melt armor. Look at Kungen's debuffs.

https://youtu.be/NE4jewlF9WA?t=243

Is a wiki entry your only source? Your video shows a late version Al'ar who is also using melt armor.

**Comment by Woomz** [comment]
I should look into that again I guess - I had it in mind differently from back then. Something just doesn't feel right about the fight. You can close this for now, I will investigate tomorrow or so if I can find something.
