### ISSUE TITLE
Halloween Treat Bag sometimes empty

### ISSUE THREAD

**Issue by ihcTactics** [Looking4Group/L4G_Core#2924]
MINOR bug, but posting it nonetheless because it's annoying.

http://www.wowhead.com/item=20393/treat-bag has been empty over half the time I've received them.

**Comment by AbaddonL4G** [comment]
http://db.looking4group.eu/?item=20393#contains

so the dropchances in the live DB look similar.
so it seems you had only badluck

**Comment by Qingle** [comment]
Closest thing I can find
http://wowwiki.wikia.com/wiki/Treat_Bag

**Comment by honeyhoney** [comment]
Kinda frustrating and not very "in the spirit of things" to get an empty treat bag... just because it was "blizz-like" doesn't mean it was good or the right thing to do!! Free treats for everyone :100:

**Comment by ihcTactics** [comment]
If it's blizz-like that's fine. I don't remember empty bags, but it's fine, can't get mount or pet from them anyway in TBC if I recall, only Wrath.
