### ISSUE TITLE
TK/Grand Astromancer Solarian - Void phase (p2)

### ISSUE THREAD

**Issue by Selphius** [Looking4Group/L4G_Core#2929]
During this phase any ranged dps can kite her and she can't catch her target and kill it.
Our tank died around 25% of boss HP, what happened next is Mage took aggro, since he was second on threat, boss was reduced to 20% changed to Void and was walking towards the mage slowly. Mage easily kited it for entire void phase until boss died. 

(If solarian can't meele hit in void form (8k meele+ because she can't catch her target) then her only way of damaging someone is void bolt for 4k, which is easily survivable.

What to do: Fix her speed on Void Phase, so players can't kite her.

**Comment by AnonXS** [comment]
As solarian [only changes model](https://github.com/Looking4Group/L4G_Core/blob/master/src/scripts/scripts/zone/tempest_keep/the_eye/boss_astromancer.cpp#L439), further increasing her normal speed should resolve this.

Other than that, researching the creature_model_info of 18988 could be good.

```

UPDATE `creature_template` SET `speed`='3' WHERE `entry` = 18805;

```

**Comment by AbaddonL4G** [comment]
I ding actually know if it was possible on retail xD but yop looks stupid if rdd can tank p2

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2975/commits/aeb6637a1c3e708ab83806c187113251652d0547
