### ISSUE TITLE
SSC/Lady Vashj: Summon SporeBats timer

### ISSUE THREAD

**Issue by Selphius** [Looking4Group/L4G_Core#2930]
Sporebats are summoned too long, they should be summoned faster meaning raid should be overwhelmed after 4min max. of entering into phase 3. 

You can see here https://www.youtube.com/watch?v=SYypbzs9d44 
Method started phase 3 at 9;00 and lasted till 12;49 (3min 49s and how overwhelmed they already were by bats).

Here is some additional info: 
http://kots-excaliburwow.shivtr.com/forum_threads/1057935
"After about four minutes of Phase 3, raid members usually start dying from poison. "

https://forum.twguild.org/index.php?topic=5218.0
"They come slowly at first, but gradually their number increases to the point where it becomes very hard to avoid the AoE poison. This usually occurs at around 4 minutes into the Phase."

Now how this works on L4G currently. Raid starts getting overwhelmed after 6min++ which is way too long. I will use Inquisition kill as proof here since they have it fresh (yesterday).

Look: https://www.twitch.tv/dualityinq/v/95352577
Phase 3 starts at 2;56;00 and when they kill Vashj It's 3:01:00 - 5min. Now look how many toxic spore you had on the ground and compare it to Method video. If Inquisition didn't kill Vashj during 5min they would get overwhelmed only after 6min+ by bats which is wrong.

**Comment by Maple7** [comment]
Keep in mind that we assigned 2 ranged dps to deal with the bats. On an earlier attempt where we only had 1 ranged on bats we did struggle with poison

**Comment by Selphius** [comment]
@Maple7 All guilds do so - kill sporebats to not hinder them for first minutes. 
Like my previous sources say, people start to die after 4min tick, since there is a lof of bats. On L4G my guild had maybe 2-3 bats in that time, which is still trivial. 
After 5 min. tick we still didn't had trouble, when on retail most guilds already were wiped during that minute. 
Only after 6-7 minute on L4G it's slowly becoming like it should, which is way too late, since Vashj mostly dies during 3-5min.

**Comment by AnonXS** [comment]
Well, i think the spawntime is very good already, but the sporebat ai timers need to be changed.

https://github.com/Looking4Group/L4G_Core/blob/master/src/scripts/scripts/zone/coilfang_resevoir/serpent_shrine/boss_lady_vashj.cpp#L882

Initial Timer 5.5sec, Repeated Timer 10-15sec. We need source on how often they should cast this spell.

**Comment by AbaddonL4G** [comment]
So reducing the initial timer to 22 should do it.

**Comment by honeyhoney** [comment]
I am happy with the balance at the moment.

**Comment by Selphius** [comment]
@honeyhoney 
Well I agree, vashj is the best scripted here out of all released tbc server at the moment :P 
But if you're going for proper pre-nerf bosses, then those things still need to be fixed, unless you aren't going into 2.0 state of bosses, except maybe few things which were encounter breaking.

**Comment by hitpointt** [comment]
I do think we're able to keep sporebats at low number for too long. They should spawn quicker than they do here, as time goes on.

**Comment by Selphius** [comment]
@hitpointt 
That's exactly why I reported it too, since it doesn't work corectly after all.

**Comment by honeyhoney** [comment]
@Selphius see my thoughts regarding "pre-nerf"/"blizzlike" and such here: https://github.com/Looking4Group/L4G_Core/issues/2922#issuecomment-254074508

**Comment by hitpointt** [comment]
I think the implications of this corking incorrectly, are more serious than you acknowledge. They are supposed to put a timer on the fight. Right now, it's possible to just sit a few hunters on them and kill them indefinitely. Making it possible to stay in the last phase for as long as you need to kill her.

**Comment by AnonXS** [comment]
I think so too, the silent enrage after 5-6mins doesnt work, but reducing the sporebat spawn timer is the wrong way to go about it as this defines after what time we have the endless 1 sec repeated sporebat spawn = enrage.

at 1 = 325 time passed 
25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 1 1 1 1 1 1 1 1 1 1 1

What comes in handy at the moment for groups that task some members to kill the bats is the sporebat ai, it is slow as fuck making focusing an extremly efficient way to take stress of the rest of the raid.

https://github.com/Looking4Group/L4G_Core/blob/master/src/scripts/scripts/zone/coilfang_resevoir/serpent_shrine/boss_lady_vashj.cpp#L882

Initial Timer for Toxic Spores = 5.5sec

Repeated Timer for Toxic Spores 10-15sec. 

We need source on how often they should cast this spell, as i think this is where the script is still bad.

https://github.com/Looking4Group/L4G_Core/pull/2803

From gut i would say Initial 2-4sec, Rep 5-10sec.

**Comment by Selphius** [comment]
You can experiment with timers to find appriopriate one for it, if something would be wrong either I or some other people would report it anyway.

**Comment by hitpointt** [comment]
"but reducing the sporebat spawn timer is the wrong way to go about it as this defines after what time we have the endless 1 sec repeated sporebat spawn = enrage."

Why is that wrong though? Can't you make them endlessly repeat at 5 or 4 seconds instead? I agree that the numbers you posted seem unreasonable, but why does it have to be those numbers exactly?

**Comment by Selphius** [comment]
Would be good if you fixed it by now, since it's only timer. Too many guilds kill her now, which makes later fix for it not even needed since they will be overgeared for her anyway.

**Comment by AnonXS** [comment]
We do not have any proper sources to just change the AI Timers, the Sporebat Spawntimer seems about right.

**Comment by Selphius** [comment]
@AnonXS It may seem that way, but it's obviously working wrong, read hitpointts post up. You can just kill them nonstop which gives you 6-8 min. on p3 which is too much, if you look at videos from retail first kills.
