### ISSUE TITLE
[Quest]: Shizz Work

### ISSUE THREAD

**Issue by Justabeckee** [Looking4Group/L4G_Core#2931]
Quest ID: 10629
Fel Guard Hound ID: 21847
Video for Reference: https://www.youtube.com/watch?v=G_EJ1s7lFBM 
Currently, there are a few bugs, these include the debuff you SHOULD get called Stanky (37695), see 0:51 in the video, additionally to this there should be an eating animation for the Fel Guard Hound when feasting on the boar, this is seen in the video at 0:44. The Fel Guard Hound currently doesn't despawn after the quest has been completed;  this can be seen in the video at 2:30. I also found out that sometimes the Fel Guard Hound doesn't produce droppings sometimes after killing the boars, but it only occured once or twice at most.

**Comment by Saltgurka** [comment]
Not live yet, but will be soon: https://github.com/Looking4Group/L4G_Core/pull/3475
