### ISSUE TITLE
[Misc] The Stairs of Destiny

### ISSUE THREAD

**Issue by Justabeckee** [Looking4Group/L4G_Core#2933]
A few issues I've seen here, first of all you can attack Honor Hold Defenders (16842), this should not be able to be done, I will check later if the same can be done with Thrallmar Grunts(16580). See image below.
Additionally,  you can use certain abilities on players; not anything harmful that I've seen so far, but like taunts, etc. This again shouldn't be done.
![wowscrnshot_101616_211843](https://cloud.githubusercontent.com/assets/15911731/19436243/e18a2bb2-9466-11e6-90d3-bd79a7fbd86a.jpg)
![wowscrnshot_101716_103416](https://cloud.githubusercontent.com/assets/15911731/19436253/ee744808-9466-11e6-8362-e2b10778a051.jpg)

**Comment by AnonXS** [comment]
```

-- Stairs of Destiny NPCs should not be attackable
UPDATE `creature_template` SET `unit_flags`=`unit_flags`|2 WHERE `entry` IN (XXX,YYY);

```
