### ISSUE TITLE
Karazhan/Shade of Aran - Soft Enrage(low mana)

### ISSUE THREAD

**Issue by Selphius** [Looking4Group/L4G_Core#2934]
Shade of Aran upon reaching low mana 10-20%, casts mass polimorph on raid, sits and drinks to get 100% mana and then casts mass pyroblast. 

What's wrong on L4G: he uses it, but it deals too low dmg, to do any threat at all, it was somewhere around 2-4k max.

How it should work: 
http://wowwiki.wikia.com/wiki/Shade_of_Aran
"At 20% mana or less (about 30k), Aran mass Polymorphs the entire raid, conjures some water, and starts drinking. After about ten seconds, or if his drinking is interrupted, the polymorph breaks and Aran does a pyroblast for 7000-7500 fire damage on the whole raid. "

http://muppets.wikidot.com/aran
Mass Pyroblast: Aran polymorphs the entire raid, sits down to drink, then casts a Mass Pyroblast dealing 7k-7.5k fire damage to everyone. The polymorph is not dispellable and affects characters that are normally immune to it.

**Comment by AnonXS** [comment]
Please always get history version befor [October 14, 2008](http://wowwiki.wikia.com/wiki/Patch_3.0.2#).

http://wowwiki.wikia.com/wiki/Shade_of_Aran?oldid=1591262

https://github.com/Looking4Group/L4G_Core/blob/master/src/scripts/scripts/zone/karazhan/boss_shade_of_aran.cpp#L65

http://www.wowhead.com/npc=16524/shade-of-aran#abilities

http://www.wowhead.com/spell=29978/pyroblast

Seems we have the right spell, but with nerfed dbc damage values.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3200
