### ISSUE TITLE
Blue Ogre brew

### ISSUE THREAD

**Issue by Robustious** [Looking4Group/L4G_Core#2944]
https://github.com/Looking4Group/L4G_Core/issues/2791

It's closed but people are still able to use it. 

Perhaps because people already had one in their bags and they prevent from not being able to use it by always having 1 stored in bank or bag.

Please make it so that nobody can use it outside blade edge.

**Comment by AnonXS** [comment]
Well, i dont know, https://github.com/Looking4Group/L4G_Core/commit/383d62255789afe6145fb50b118b0e859b9750ea seemed to be fine, if this doesnt work i only know that we can make the db delete the item as soon as you leave Blade Edge. by setting map value in the `item_template`.

**Comment by Robustious** [comment]
It was reported again that they can't use it anymore, perhaps it was the trick I described or the fact that they had em before the fix. 
Either way, you can close this issue for now
