### ISSUE TITLE
Boss damage scaling, in regards to attack power (with interactions explained)

### ISSUE THREAD

**Issue by Kraftig** [Looking4Group/L4G_Core#2949]
As requested by Anteara I'm making an entry about this. Perhaps this is already implemented correctly.

In preparation for 25 mans for my guild, I was considering the use of Curse of Recklessness (CoR) to boost our physicals, and it made me wonder if the interaction between 5/5 imp demo shout (IDS, warrior talent) and CoR works as it did on retail. This is fundamentally an issue of boss AP scaling. Here's a short rundown of my understanding of the retail mechanic at the time:

Bosses have their physical damage enhanced by their attack power just like other mobs. Most (perhaps all) bosses had 350 attack power. A normal demo shout reduces AP by 300, bringing boss AP to 50 and reducing damage by a lot. With a 2/5 IDS, reduction is 348 AP - for all practical purposes putting the boss at 0 and hence achieving maximum damage reduction. Under normal circumstances, hence, more than 2/5 IDS were a waste for raiding purposes. CoR use changed this.

CoR increases attack power of the target by 135, putting the boss mob at 485 AP. This is very sizeable. However, with 5/5 IDS, the reduction is 420, putting the boss at 65 AP, that is much more manageable. This was the primary reason for any warrior to spec 5/5 IDS.

The purpose of this "bug" entry is to inform about the mechanics that were in place during retail, since it's very significant when considering how to build and buff a raid. If the bosses already do have this type of AP scaling with correct numbers, there is no issue.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2268
