### ISSUE TITLE
[NPC][Spell] Keleth - Mark of War

### ISSUE THREAD

**Issue by Wixyz** [Looking4Group/L4G_Core#2954]
The melee attack power buff should scale 30/50/70/100 increasing as your rep increases. Currently I receive a 50 AP buff when exalted. (Has been like this forever but I haven't spoke up).

**Comment by AnonXS** [comment]
Source

**Comment by Wixyz** [comment]
does this work? http://db.hellground.net/?spell=31812

**Comment by AnonXS** [comment]
http://www.wowhead.com/npc=17901/keleth#comments:id=151914
