### ISSUE TITLE
Pet pathfinding in arena

### ISSUE THREAD

**Issue by Huntardsrise** [Looking4Group/L4G_Core#2957]
Hey dear devs, 
the pets still seem to be abled to run through pillars, getting stuck in objects and running the worst paths imaginable.

I'm gonna try to record some content the next days, but I guess you already know what the issue is, or have seen it already.

Most of the remaining pvp community would be glad to see a fix regarding this issue.

Greetings Skip

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/140
