### ISSUE TITLE
Hunter Pet Gone 2.0

### ISSUE THREAD

**Issue by Goandkill** [Looking4Group/L4G_Core#2958]
My level 70 boar is gone after I got it from the stable. Active pet was a level 70 ravager.

**Comment by Goandkill** [comment]
now the lvl 70 ravager is also gone. stable masters don't work. this is shit guys

**Comment by Anteara** [comment]
Was your pet unhappy when you stabled him?

**Comment by Goandkill** [comment]
no, none of them.

**Comment by Saltgurka** [comment]
What is your ingame character-name?

**Comment by Goandkill** [comment]
name is also Goandkill

**Comment by Saltgurka** [comment]
https://github.com/Looking4Group/L4G_Core/issues/3044
