### ISSUE TITLE
Felmist

### ISSUE THREAD

**Issue by Caladhield** [Looking4Group/L4G_Core#2960]
Hey i've noticed you changed the spawn points from the Felmist since you added Windy clouds in nagrand, Tho in your database you still show the old spawn points. Not sure if this was intentional?

What it used to be:
http://db.looking4group.eu/?npc=17407

What it is now:
http://www.wowhead.com/maps?data=3520:614587614592487207568464466470573743522210525222384419389420642466650361518208467521581455495330420426469537214327533341349344622631649612466378430490560540300450620374542506450380350450280360431729570190328378342412512524446627607477566376363370363491621213651304

http://puu.sh/rTNdl/155cbe703c.jpg

**Comment by AnonXS** [comment]
Well, blizzlike you should not be able to see them http://de.wowhead.com/npc=17407.
