### ISSUE TITLE
Leotheras agro reset bugged

### ISSUE THREAD

**Issue by hitpointt** [Looking4Group/L4G_Core#2961]
Very frequently after a whirlwind, or even when he comes out of banish at the start of the fight, he ignores the threat I hit him with and goes after someone else. It's also worth noting that at least half of the time it seems to work correctly.

I think with the redundancy of multiple tanks in a raid all trying to pick him up, and how easy the boss is, this bug can go almost unnoticed sometimes to anyone except the tanks. However when we tried 1 tanking, it was very obvious that there was a problem. 

Shield slam + HS lands but he goes after two healers:
https://clips.twitch.tv/hitpointstarcraft/EnchantingGuanacoDatSheffy
So despite a perfect situation for me, where both HS and shield slam land, he kills a disc priest and then attacks a holy priest before transitioning to demon form.

Shield slam and an auto attack, again kills a priest:
https://clips.twitch.tv/hitpointstarcraft/SmilingYakNotATK

SS lands and he kills a resto shaman:
https://clips.twitch.tv/hitpointstarcraft/UnsightlySpiderRuleFive

SS lands and he goes after a priest, then a warlock:
https://clips.twitch.tv/hitpointstarcraft/DelightfulGaurDansGame

SS and autoattack crit, kills a warlock:
https://clips.twitch.tv/hitpointstarcraft/DrabFlyMcaT

SS miss and HS crit for 792, he ignores the other prot warrior also and goes after 3-4 other people:
https://clips.twitch.tv/hitpointstarcraft/PricklyJayPeoplesChamp

I can only speculate as to what is causing this. If I had to guess, I would say he sometimes randomly switches targets and then clears aggro, even after he has already begun meleeing people. So maybe he is still using his whirlwind aggro behavior for a second or two, after he is done whirlwinding.

Although this does not explain the issue right at the start of the pull after a shield slam lands and he kills a random resto druid for no reason: https://clips.twitch.tv/hitpointstarcraft/CuriousStorkTooSpicy

Anyone who plays a warrior can tell you that the shield slams landing alone are at least 1.4k threat, and if he was dropping agro at the end of the WW phase then these situations couldn't happen. In some of these clips he is chasing healers, especially this one, which I think is the strongest evidence that something is wrong with him. https://clips.twitch.tv/hitpointstarcraft/EnchantingGuanacoDatSheffy

I have many more examples but I think you get the picture. All of these clips are from one night, and he behaves like this every single week that we kill him. It's frustrating because timing a shield slam properly seems to just guarantee that he will be harder to pick up when threat is actually working correctly. Keeping people alive often times seems to rely on well timed intervenes, and battle res rather than snap agro, which shouldn't be the case.

http://wow.gamepedia.com/Leotheras_the_Blind

"Whirlwind:
12 sec duration
Leotheras spins around the room (similar to Sartura in Ahn'Qiraj)
~3000 damage instant (mitigated by armor) plus a 15s bleed for 2500 per 3s tick (no mitigation)
15 sec cooldown
**Randomly switches targets during, and resets threat at the end**

The aggro wipe can be overcome with a hunters  [Misdirection]. Other tricks include having someone place  [Gnomish Flame Turret]/ [Searing Totem] on the tanking spot (Leotheras will aggro this, allowing the MT to get aggro back easily). Bleeds or any other tank DoTs also help them gain aggro immediately when they tick after the aggro wipe. Having a Paladin main tank this encounter is also a good idea because he doesn't have to chase down Leotheras, but can simply throw an Avenger's Shield. Like most raid bosses, Leotheras is immune to taunt."

**Comment by tyler200100** [comment]
Could we get a response on this issue? It couldn't be more clear that its bugged

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2821
