### ISSUE TITLE
Serpentshrine Lurker Mushrooms do no damage

### ISSUE THREAD

**Issue by hitpointt** [Looking4Group/L4G_Core#2962]
The mushrooms (Underbog Mushroom) should do damage when they explode, forcing you to move away from them or kill them. Currently they do nothing.

http://wowwiki.wikia.com/wiki/Serpentshrine_Lurker

http://www.wowhead.com/npc=21863/serpentshrine-lurker#comments

I'm pretty sure the trash linking in Leo's room and in the tunnel before it, is all wrong. Some of these lurkers should be linked with other mobs like the shield bearers. Instead they are all solo pulls. I have no source for this besides memory so I won't write a separate report. But anyone who pulls the room can tell you linking looks and feels broken.

**Comment by AnonXS** [comment]
Same Script/Spell is used in the Underbog Mushrooms at first boss. 

Rancid Mushroom 22250 - Copy Script and use the right Spell: 38652, or might be able to do this with EventAI.

https://github.com/Looking4Group/L4G_Core/issues/2326

https://github.com/Looking4Group/L4G_Core/blob/5db29dcb30ef0d336e467f61334d8474108b09fa/src/game/SpellEffects.cpp#L6637

https://github.com/Looking4Group/L4G_Core/blob/5db29dcb30ef0d336e467f61334d8474108b09fa/src/scripts/scripts/zone/coilfang_resevoir/underbog/boss_hungarfen.cpp#L95

**Comment by hitpointt** [comment]
I think the reason players don't take damage from them, is because mobs do.

The cloud is stacking a dot on mobs that are in it, but not the players.

**Comment by AnonXS** [comment]
ding dong.

**Comment by AbaddonL4G** [comment]
should be fixed
