### ISSUE TITLE
Defiance, Protection Warrior Talent not working fully

### ISSUE THREAD

**Issue by WarriorTSW** [Looking4Group/L4G_Core#2964]
Hey all,

http://db.looking4group.eu/?spell=12789
This talent is meant to grant 6 expertise.
See screenshot.
http://i.imgur.com/FUR7Kmg.jpg

Edit:
The problem doesn't seem to persist.
See screenshot taken this morning after a client restart.
http://i.imgur.com/lEQFrSS.png

**Comment by hitpointt** [comment]
The +6 exp is working on my prot warrior so the talent itself isn't broken for everyone.

I've seen reports of this with other talents, usually respecing and putting in the points again will fix it.

**Comment by Selphius** [comment]
Just to make sure, were you in defensive stance on first screen? since this talent only works for def stance not battle or zerk. Lots of ppl make this mistake and aren't in def stance so they think talent doesn't work.

**Comment by WarriorTSW** [comment]
I think you're right Selphius. 
Are warriors meant to log in in battle stance? Because regardless of which stance you log out in, you always log in i Battle. And iirc ive logged off several times on my druid while in flight form to only log in and im falling out of form. Is this intentional?

**Comment by Selphius** [comment]
Can't really sure, since I don't remember this. But if I were to tell then I would say it works good for stance's, except maybe druid forms.

**Comment by AbaddonL4G** [comment]
Can't reproduce i'll close here
