### ISSUE TITLE
Terokkar

### ISSUE THREAD

**Issue by djjurg1** [Looking4Group/L4G_Core#2965]
Is anything being done with the pathfinding in Terokkar foest? 
Tried doing some pvp, but the message "Target is not in line of sight" keeps popping up and pet is running the longest detour in order to get to the target. The problem seem to be worst in Skettis.
This is by far the worst problem with this server atm, besides PvP. Needs to be fixed asap.

**Comment by AbaddonL4G** [comment]
https://github.com/Looking4Group/L4G_Core/issues/460

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2817
