### ISSUE TITLE
 Do not send mail

### ISSUE THREAD

**Issue by Letarg86** [Looking4Group/L4G_Core#2967]
Good evening. Do not send mail to your other character (located on 1 account), and an error :(
![wowscrnshot_102816_215100](https://cloud.githubusercontent.com/assets/23127028/19818765/e7d185a0-9d59-11e6-871f-a70a6431611b.jpg)
Cache all cleared

**Comment by AnonXS** [comment]
That normally happens if the postbox if full on the other char.
