### ISSUE TITLE
League of Arathor Emissary

### ISSUE THREAD

**Issue by Robustious** [Looking4Group/L4G_Core#2971]
I am able to kill them as horde on Shattrath. I am 100% sure I am not supposed to, even though I hate alliance, they shouldn't be able to get hit by any horde player in sanctuary city.
http://db.looking4group.eu/?npc=14991

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2959/commits/08b14a0747159e6f82e86c36f604b065a60c7d0a
