### ISSUE TITLE
Formula: Enchant Bracer - Major Defense unavailable

### ISSUE THREAD

**Issue by AntilaT** [Looking4Group/L4G_Core#2972]
I have a reason to believe that Ethereum Nullifier's (nor Ethereum Researchers) drop this recipe. According to comments in wowhead Ethereum Nullifiers were added in patch 2.1 and this recipe was moved to their loot table from the loot table of Ethereum Researchers. The recipe seems to drop from neither of these mobs.

**Comment by AnonXS** [comment]
Well they do, but this is missing from all dbs:
 
-- add Formula: Enchant Bracer - Greater Dodge to Ethereum Jailor Loottable
DELETE FROM `creature_loot_template` WHERE `entry` = 23008 AND `item` = 22530;
INSERT INTO `creature_loot_template` VALUES 
(23008, 22530, 1.0, 0, 1, 1, 7, 333, 1);

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2975/commits/6383f7ff4310d63fdf102e7d28a3ad3d57222086
