### ISSUE TITLE
Pve, ranged mobs are still standing still once los

### ISSUE THREAD

**Issue by Huntardsrise** [Looking4Group/L4G_Core#2974]
So ranged mobs are still freezing once you run out of los, instead of chasing you.

**Comment by AnonXS** [comment]
state id e.g: http://db.looking4group.eu/?npc=18481

**Comment by AnonXS** [comment]
Can someone provide entrys of npcs which still dont behave correctly?

**Comment by AnonXS** [comment]
No further answers.
