### ISSUE TITLE
Furies Deck Trinket

### ISSUE THREAD

**Issue by shaszun** [Looking4Group/L4G_Core#2976]
When I did a quick check into the server database I saw the drop rates of the cards are limited to a very small number of npc and the chance is low. I'm not sure the db stats are accurate, so can you check them.

http://www.wowhead.com/item=31907/furies-deck#created-by-spell

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2975/commits/0a71db4875343082454cb5aa2fb5f2b81ac17f2b
