### ISSUE TITLE
Respawn timer rare NPC: Chief Engineer Lorthander (ID: 18697)

### ISSUE THREAD

**Issue by Scipios** [Looking4Group/L4G_Core#2982]
Hey,

in the last couple of days I'm trying to kill Chief Engineer Lorthander in Netherstorm as often as possible. 

At the moment it's only possible to find him at his spawn points right after server restart. His respawn timer should be 8 hours http://wowwiki.wikia.com/wiki/Chief_Engineer_Lorthander?oldid=697224

When I checked https://raw.githubusercontent.com/Looking4Group/L4G_Database/master/world/creature.sql I saw that his 'spawntimesecs' is set from 75600s to 115200s. That's 21 - 32 hours.

Am I missing something? I was checking his spawn points all day (killed him right after server restart) and server uptime is now at 13hours.

If he's supposed to have a higher spawn time...don't mind the ticket.

**Comment by AnonXS** [comment]
He now has his correct different spawn points.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2975/commits/7ccc27ec8485c81f51276594cdfd8e37f89f9ef8
