### ISSUE TITLE
Respawn Talonsworn Forest-Rager and Ethereum Jailor

### ISSUE THREAD

**Issue by Kruszek** [Looking4Group/L4G_Core#2983]
Npc Talonsworn Forest-Rager and Ethereum Jailor respawning dead already. Sometimes there is about 5 npcs and after killing them respawning only 2 alive, rest are dead or just dont respawn. 

http://www.wowhead.com/npc=23029/talonsworn-forest-rager#comments
http://db.looking4group.eu/?npc=23029#drop
http://www.wowhead.com/npc=23008/ethereum-jailor#comments

**Comment by AnonXS** [comment]
yea the problem is the heavy farming, i think the pooling system just cant handle that kind of situation.

dead corpses of mobs lying around on despawntimer after killed. (guid is still active)

pool trying to spawn new guid but when checking, maxlimit of possible spawns are still active (corpses)

**Comment by Kruszek** [comment]
My proposition is to make a Talonsworn spawn (for example 4 npcs) every 10 minutes. Same thing about Jailors (lets say 5 more) in exact places, spawning everu 5/10 minutes.

Through last hour, while I was farming Jailors I managed to kill like 10-12 of them. More than 25 Jailors were dead since spawned.

**Comment by ihcTactics** [comment]
Any work on this yet? Annoying to fly around Skettis for ~30 minutes and find 6-8 dead spawned trees. There's already the herbalism issue with not having enough spawn points and throwing this on top adds to the issue.

**Comment by Kruszek** [comment]
nothing change, i think herbalism and clouds too disappears after spawned. I dont have any video, but few time when i flew around Terrokar i saw on map respawn terocone and disappears in 1s, there was no one around to quickly gather + 1-2 minion was on herb. In my opinion everything has random spawn is bugged here :((. I know its hard to fix, but maybe try other solution ? for example only first appearance should be random, and later on to the next restart everything should be in the same places, it will help people farm staff. Only after restart you can found 5 elites in Skettis, 5 Jailor, about 30 spawned terocone. Time is getting harder about it. sorry for my English, I hope that I was able to convey all right.
greetings from the best Herbalist :)

**Comment by AnonXS** [comment]
https://bitbucket.org/Xadras/tbcpvp/commits/8de566ea88d1d8f410bf34d991ec6edaae54c069
https://bitbucket.org/Xadras/tbcpvp/commits/4c98645436fe178893e7935562853b60ae2aafac

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2717
