### ISSUE TITLE
[Quest]:Ending Their World

### ISSUE THREAD

**Issue by Slycer01** [Looking4Group/L4G_Core#2984]
Quest ID: 9759

Its a low lvl quest in bloodmist isle and the one of the chain quest  for Tabard of the Hand ( http://db.looking4group.eu/?item=24344 ).. 

In the quest the NPC Demolitionist Legoso ( http://db.looking4group.eu/?npc=17982 ) doesn't want to do his job just stands there. Doesn't attempts to destroy the Vector Coil and slay Sironas. I waited 15-20min but nothing happened. It would be great if this would be makeable because its a great tabard :)

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2344
