### ISSUE TITLE
[Spell] Shaleskin - Shaleskin Flyer

### ISSUE THREAD

**Issue by Selphius** [Looking4Group/L4G_Core#2988]
This spell is totally bugged [Shaleskin](http://www.wowhead.com/spell=36576/shaleskin) from this mob [Shaleskin Flyer](http://www.wowhead.com/npc=20210/shaleskin-flayer#abilities). 

How it works on L4G: spell is used, but when this mob has it HE IS IMMUNE TO ALL MAGIC SPELLS for entire duration of this spell, which makes this mob an insane hindrance when trying to do quest with them, since only classes who can dispel it can kill it. Also worth mentioning is that it should be only up for 1 spell casted, but here it doesn't matter how many spells you will cast, it won't disappear.

How it should work: Reduce magic damage done to NPC who has it by 50% for 1 cast.
http://www.wowhead.com/spell=36576/shaleskin

**Comment by AbaddonL4G** [comment]
Duplicate of @https://github.com/Looking4Group/L4G_Core/issues/1493

**Comment by AbaddonL4G** [comment]
#https://github.com/Looking4Group/L4G_Core/issues/1493
