### ISSUE TITLE
Warlock Imp's Blood Pact

### ISSUE THREAD

**Issue by Talmorious** [Looking4Group/L4G_Core#2993]
The warlock minion, the imp, Blood Pact's ability seems to ONLY be affecting the imp and not the warlock or party members.
![wowscrnshot_110616_212407](https://cloud.githubusercontent.com/assets/23251247/20044485/60e86648-a467-11e6-8b0e-b6a45ec2407b.jpg)

**Comment by AnonXS** [comment]
relog after first pet usage as warlock, as the pet is not correcrtly registred as your pet the first time you use it, you can see it as the pet is named Imp.

**Comment by Rushor** [comment]
> oiwrtjwiorgjwriogjawior

best name xD

**Comment by AnonXS** [comment]
^^

**Comment by Talmorious** [comment]
Thanks. Will check when I log in. :)

**Comment by AnonXS** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/20440411/40a63c86-adc0-11e6-9cfc-4c455f2c95af.PNG)

Works after relog, pet is now named and behaves as intended.
