### ISSUE TITLE
[Item] Eye of magtheridon

### ISSUE THREAD

**Issue by Dolpiff** [Looking4Group/L4G_Core#2999]
itemID 28789

Does not proc when applied debuffs resist
resulting in 33% of retail procrate for a SP.

At hitcap u have only 1% chance to proc on the spell itself (which sucks cause you lose dmg then), and not when you apply a debuff such as Shadow Weaving or Misery (and it resists, of course).

I remenber on retail using it on frost mage and it procced way more than currently on l4g.
Only other source i could find was the top comment from the WowHead page : http://www.wowhead.com/item=28789/eye-of-magtheridon#comments
I think even partial resists triggered it, but I couldn't find any source for that.

I see 2 probable causes:
either spelltype spelldebuff isnt put in the item event triggering the proc
or
spell debuffs never resist on l4g? I'll try to check this one but its probably more likely the first option.

The bug also effect any caster class with "auto-debuffs" (Winter's chill, scorch debuff improved shadow bolt, ...) on their spells, and make this hard to obtain trinket almost weaker than the free brewfest trinket/badge one.

**Comment by Dolpiff** [comment]
Steps on how to replicate:
spec a shadow priest for 5/5 misery and 5/5 shadow weaving
use zero hit gear (faster to notice)
fight against boss dummy in ironforge

Notice the difference between 'yellow text' resists and 'white text' resists.
I think white text resists are when one of 2 debuffs resist.

Notice also how the trinket doesn't proc on the latter, when you have both equipped.

**Comment by AnonXS** [comment]
http://www.wowhead.com/spell=34749/recurring-power

```
--
34749	0	0	0	0	8	0	0	0
```

**Comment by Dolpiff** [comment]
well maybe shadow weaving and misery have the wrong type then?
need me to film those white resists text that dont proc the trinket?

**Comment by Evolvee** [comment]
I dont think talent triggered debuffs should be able to resist when the spell that triggers them doesnt. Unless there is some resist factor(slow from frostbolt --> hunters talent Surefooted etc.)

**Comment by Dolpiff** [comment]
i think evolve put the finger on the problem : on L4G (and probably also on hellground, shadow vulnerability (effect from shadow weaving talent) and misery effect both cannot resist if the spell resist. However i think it should:

list of potential sources:
wowwikia articles of several spells from other class with associated vulnerability effects:
http://wowwiki.wikia.com/wiki/Winter's_Chill 

"Notes:The debuff has a separate resist from the spell; a frost spell that hits the target for full damage may still have the debuff resisted."

also the wowhead comment that i quoted above mention it

it seems on this core all those effects cannot resist,
therefore no procs and eye sux rly hard

**Comment by AnonXS** [comment]
Linked to https://github.com/Looking4Group/L4G_Core/issues/3240

**Comment by AnonXS** [comment]
Closing this as its not the item/item linked spell that causes the issue, if any.
