### ISSUE TITLE
[NPC - Questing] "Akuno" Faction ID

### ISSUE THREAD

**Issue by Cymbia** [Looking4Group/L4G_Core#3002]
**BUG ON THE SERVER:**
The NPC "Akuno" (ID=22377) linked to the quest "Escaping the Tomb"(ID=10887) got the wrong factionID.
When we are activating the escort, Akuno becomes beatable.
If by mistake, we hit him, he is fighting us and stop the escort until he is dead, or we. (Except for Rogues or Hunters who can Vanish / FD).

**HOW IT SHOULD WORK:**
The NPC should be "friendly" (we are not supposed to fight him). 
His faction should be "Lower City" (FactionID=1818).

**HOW TO REPRODUCE THE BUG:**
Do the quest if not done yet and see !

**SOURCE SHOWING THAT IT SHOULD WORK THIS WAY (video, patchnote, etc ...):**
https://www.youtube.com/watch?v=tPY_UEs6Dds
The video isn't TBC (couldn't find a TBC one), but it should work the same way !

**COMMENT:**
It can leads to a lose of time when we are questing ! That's very frustating !

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/blob/master/src/scripts/scripts/zone/terokkar_forest/terokkar_forest.cpp#L2206

**Comment by Cymbia** [comment]
What am I supposed to do with this link ?

**Comment by Saltgurka** [comment]
Thank you for taking the time to report this issue, and for providing all necessary information. It really helps us to have well structured bug reports, thanks for that :)

The issue is solved with https://github.com/Looking4Group/L4G_Core/pull/3004
