### ISSUE TITLE
Steamvault (normal mode) - Mekgineer Steamrigger

### ISSUE THREAD

**Issue by Selphius** [Looking4Group/L4G_Core#3008]
Adds which he summons, should go and heal him. It worked before, but when i was today on SV norm farm, everytime adds were summoned, they were just stuck near the console not doing anything, not moving or healing boss.

**Comment by honeyhoney** [comment]
Working fine for me.

**Comment by Selphius** [comment]
Yeah, it's weird though. When I went heroic mode on it, it worked fine, but on normal mode not (4 times). Maybe server dc fixed it or something.
