### ISSUE TITLE
Freezing Band

### ISSUE THREAD

**Issue by damagesponge** [Looking4Group/L4G_Core#3021]
Hi i just wanted to report a bug, i am using 2x Freezing Band rings and when it procs, it is not counting my target as frozen (my ice lances are not doing triple damage and im not getting benefit from Shatter talent) it is supposed to act basically like deep freeze from wotlk, except its un-blinkable.

Thanks

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2060
