### ISSUE TITLE
Paladin Stoicism Talent

### ISSUE THREAD

**Issue by VVarbandit** [Looking4Group/L4G_Core#3023]
It does not work. 100% chance to get dispelled or spellstealed.

**Comment by AnonXS** [comment]
What Paladin Buffs?

**Comment by VVarbandit** [comment]
Everything, Divine shield, Righteous Fury, Seals, Blessings. All of them have a 100% chance 2 be dispelled or spellstealed without any resists showing up.

**Comment by VVarbandit** [comment]
Tested by having a mage and priest spam spellsteal and dispell.

**Comment by VVarbandit** [comment]
After retesting the talent after a respecc it seemed 2 work properly, but it didn't before so it might've been a talent bugg. Not entirely sure.
