### ISSUE TITLE
Paladin Eye for an Eye talent bugged

### ISSUE THREAD

**Issue by VVarbandit** [Looking4Group/L4G_Core#3025]
Doesn't deal back damage to hostile units that crit you with spell abilities

**Comment by VVarbandit** [comment]
Correction, doesn't seem to work on all abilities, which it should.

**Comment by Kryolithos** [comment]
Do you talk about PvE? In TBC there are no spell crits possible from NPCs, so there shouldnt be any possibility in PvE to trigger this talent or am I missing something out? Could you provide some screenshot.

**Comment by VVarbandit** [comment]
Was at the same time I made stoicism talent issue, it was most likely something with the talents not entirely sure.
