### ISSUE TITLE
Shadowmoon Harbringers combat

### ISSUE THREAD

**Issue by Thud29** [Looking4Group/L4G_Core#3026]
I'm playing a rogue doing the quest: Harbringers of Shadowmoon. When I open on one of the harbringers with cheap shot they immediately reset as if I ran far away from them. Also after fighting a few of them, I used gouge on one when they had about a third of quarter health left. This gouge caused the harbringer to reset too. Seems like it might be because of cc, stun or incapacitates. Character name is Hence on alliance fyi. Good luck

**Comment by Thud29** [comment]
Actually I just noticed that harbringers reset even when I use garrote to open up on them. No idea how that would cause it to happen. When I just start auto attacking or use my thrown weapon to aggro them there is no problem with them resetting.

**Comment by Thud29** [comment]
I just used blade flurry to hit 2 mobs at once and the mob I was not attacking kept resetting and evading my hits so something wierd is going on

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2142
