### ISSUE TITLE
some problem with Event 70 lvl

### ISSUE THREAD

**Issue by mick21rus** [Looking4Group/L4G_Core#3028]
have used event and leveled up to level 70 my mage is level 64.but that's the reputation with honor hold and Cenarion decreased from honored to friendly( could you correct this situation?
![wowscrnshot_112016_233044](https://cloud.githubusercontent.com/assets/23619677/20466057/73a55ece-af7c-11e6-9192-f1f9fd675757.jpg)
character name is Grais
what other information do you need from me?

**Comment by AnonXS** [comment]
Write Ingame Ticket.
