### ISSUE TITLE
A Necessary Distraction quest not working.

### ISSUE THREAD

**Issue by crunchytoastly** [Looking4Group/L4G_Core#3031]
The Aldor quest in Shadowmoon Valley called A Necessary Distraction(ID of the quest:10637) who you get from Exarch Onaala(ID of NPC: 21860) is not working. You can pick up the quest item to free Azaloth and free him. It says Objection Completed on the screen but when you go to Quest Log it's actually not completed. When I go to the NPC to complete it, it still shows it's not completed.

**Comment by Saltgurka** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2169
