### ISSUE TITLE
Casting spells while moving

### ISSUE THREAD

**Issue by Templeton1** [Looking4Group/L4G_Core#3033]
If I make a macro with my spell and trinkets and press that macro, I can move sideways while casting the spell.

#showtooltip Incinerate
/use Starkiller's Bauble
/use Ancient Draenei Arcane Relic
/cast Incinerate

I have tested this with several spells and it works with almost any spell!

**Comment by honeyhoney** [comment]
I am unable to re-produce this.

**Comment by Saltgurka** [comment]
Unable to reproduce. Please record it happening and we'll reopen the issue.
