### ISSUE TITLE
Build and instant 60 error

### ISSUE THREAD

**Issue by maikale** [Looking4Group/L4G_Core#3036]
![default](https://cloud.githubusercontent.com/assets/1087826/20648564/5b4a0cf8-b4b3-11e6-8498-c2bea8b3b13d.png)

instant npc not work :(

**Comment by Saltgurka** [comment]
There's a problem with the instant 70 script when building on windows. 

For now you can just comment out the following lines:

- https://github.com/Looking4Group/L4G_Core/blob/aa0997b2287e6b186d328e7110f287ae832b3759/src/scripts/system/ScriptLoader.cpp#L24

- https://github.com/Looking4Group/L4G_Core/blob/aa0997b2287e6b186d328e7110f287ae832b3759/src/scripts/system/ScriptLoader.cpp#L658

**Comment by maikale** [comment]
instant 60 will work there thanks

**Comment by Rushor** [comment]
good old vs 2010 :D

**Comment by maikale** [comment]
vs 2012 does not work
