### ISSUE TITLE
Zeth' Gor Must Burn!  quest issue

### ISSUE THREAD

**Issue by Zraebiel** [Looking4Group/L4G_Core#3039]
- [ ]  attempted to do this quest at lvl 61, in a group with 2 other players.  I quickly got 3 of the 4 torches I needed for the quest which were dropped by blood hallow peons.  I used them on 1 of the 4 structures needed for the quest and the whole stack of 3 disappeared.  

Afterward I tried to farm them again.  I got 1 more torch immediately.  I also did another quest at the same time.  It's the one where you have to capture the eye's energy and take it to the cauldron (forget name).  I continued on Zeth' Gor Must Burn!  I farmed peons for another 30 minutes and got no more torches.  I dropped the quest and another player shared it with me.  I still got nothing.  I then went back to the quest giver at Spinebreaker Post and was able to pick up the quest again even though it was still active from the player that shared it.  I ended up wasting over an hour trying to figure this one quest out and was unable to complete it... Please, look into it.  Thank you.

**Comment by AnonXS** [comment]
Ok normally you can only carry one torch at at time, that they also disappear makes this "handy" fix irrelevant. will revert to one torch only so this behavior cant be recreated.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3030/commits/d17a1e3447e4c36bfe5e2c2117dd40e74926dc7c
