### ISSUE TITLE
Blessing of Freedom

### ISSUE THREAD

**Issue by Zraebiel** [Looking4Group/L4G_Core#3040]
It just doesn't work at all.  I had BoF cast on me while slowed, stunned, feared.  BoF worked on nothing.

**Comment by honeyhoney** [comment]
We're going to need a few more details to troubleshoot this issue. Which slows/stuns/feared? Under what circumstances? etc.

We'll need to be able to reproduce this in order to fix any issues with it.

**Comment by Zraebiel** [comment]
I don't remember it working anywhere.  What I can specifically remember it not working on was the fear from the patrol pack in Zeth'Gor (can't remember name offhand) that came with the wolf/worg mob.  I was stunned in Blood Furnace (normal) by the mobs that come before the second boss.  I was slowed by a night elf druid in moonkin form from their moonfire I believe.  BoF was cast from another pally in the same group.

**Comment by AnonXS** [comment]
http://wowwiki.wikia.com/wiki/Blessing_of_Freedom?oldid=1631776

Places a Blessing on the friendly target, granting immunity to movement impairing effects for 10 sec. Players may only have one Blessing on them per Paladin at any one time.

**Comment by Zraebiel** [comment]
It wasn't working for me even with no blessing.  Also, even if there is a blessing on the target what should happen is that it should remove the blessing and be replaced with BoF.  If it doesn't at least replace it then paladins would never be used in pvp or probably raids.

**Comment by Robustious** [comment]
It works as intented, i am paladin playing on this server since launch, what you are spreading is wrong.

**Comment by Zraebiel** [comment]
I'm not trying to spread false information.  I wanted to help the server out by putting a report in.  I only played in hellfire and it never worked for me.  The places I specifically mentioned need to be tested.  If you worked for you under your certain circumstances than great.

**Comment by AnonXS** [comment]
Like my source said, BoF does nothing in regards of fear spells. Only **movement impairing effects** are affected by this blessing.

**Comment by Zraebiel** [comment]
It didn't work for slow I said that also when fighting a moonkin night elf druid.

**Comment by AnonXS** [comment]
And what did the moonkin slow you with?

**Comment by Zraebiel** [comment]
Moonfire, insect swarm and I think I used BoF while he snared me.
