### ISSUE TITLE
[Karazhan] - Prince Maalchazar

### ISSUE THREAD

**Issue by Selphius** [Looking4Group/L4G_Core#3042]
He can again be disarmed, did you do perhaps some DB rollback? since I thought it was fixed here.
https://github.com/Looking4Group/L4G_Core/issues/8

**Comment by AnonXS** [comment]
```
SELECT * FROM `creature_template` WHERE `entry` = 15690;
```

`mechanic_immune_mask`='650854239'

but can also be related to the core script as some mechanics are set there too.

**Comment by Selphius** [comment]
I don't use such addons. Disarm was given and entire raid saw it on boss. Tested with 2 warriors, hard to tell about dmg though if it was reduced, since I didn't look it up when disarm was active. Still worth testing.

**Comment by hitpointt** [comment]
Yes, disarm has always worked on him on this server. It should not.

**Comment by AnonXS** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/20724587/2b42311c-b66f-11e6-9137-ecd210870c12.PNG)
