### ISSUE TITLE
Hunter's Raptor Strike cancels Autoshot

### ISSUE THREAD

**Issue by kfax** [Looking4Group/L4G_Core#3043]
I created a new thread because I think since the other one was flagged "invalid" it wouldn't be adressed anymore. I did some testing to find out when this issue was happening and I finally came up with the exact explanation.

When a hunter is shooting X using Autoshot and whatever other ranged abilities then gets in melee range and he uses Raptor Strike but it's still "waiting" for the next melee attack to cast Raptor Strike and he runs away from X before the Raptor Strike is used, then the Autoshot will be off. Also when you use your other ranged abilities like Arcane Shot/Multi Shot/etc it won't trigger the Autoshot to start again either. To add to that, if you press your Autoshot it will cancel the Raptor Strike and won't start shooting, you need to press it twice to be able to Autoshot again.

I played a hunter in retail vanilla, tbc and wotlk and never had this issue so I'm pretty confident that this is not Blizzlike.

Thanks a lot for helping.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/3013
Porting Comment with Reproduction over.
