### ISSUE TITLE
[Hunter] Steady shot and Aimed shot wrong cast time

### ISSUE THREAD

**Issue by TheVcelar** [Looking4Group/L4G_Core#3046]
Calculation of steady and aimed shot cast time is wrong.

as a BM hunter with serpent's swiftness(20% increased ranged attack speed) and quiver ( 12% increased range attack speed in my case) it should be like this for steady shot:
 

> 1.5/1.2/1.12=1.116

 
here on L4G is used this wrong formula:
 

> 1/1.2/1.12+0.5=1.244

same is aplied for aimed shot, only 3s is used instead of 1.5s cast time.

i think, that problem is here in SpellMgr.cpp: 

> uint32 SpellMgr::GetSpellCastTime(SpellEntry const* spellInfo, Spell const* spell)
> {
>     int32 castTime = SpellMgr::GetSpellBaseCastTime(spellInfo);
> 
>     // if castTime == 0 no sense to apply modifiers
>     if (!castTime)
>         return 0;
> 
>     if (spell)
>     {
>         if (Player* modOwner = spell->GetCaster()->GetSpellModOwner())
>             modOwner->ApplySpellMod(spellInfo->Id, SPELLMOD_CASTING_TIME, castTime, spell);
> 
>         if (!(spellInfo->Attributes & (SPELL_ATTR_ABILITY|SPELL_ATTR_TRADESPELL)))
>             castTime = int32(castTime * spell->GetCaster()->GetFloatValue(UNIT_MOD_CAST_SPEED));
>         else
>         {
>             if (spell->IsRangedSpell() && !spell->IsAutoRepeat())
>                 castTime = int32(castTime * spell->GetCaster()->m_modAttackSpeedPct[RANGED_ATTACK]);
>         }
>     }
> 
>     if (spellInfo->Attributes & SPELL_ATTR_RANGED && (!spell || !(spell->IsAutoRepeat())))
>         castTime += 500;  -> this is right for multishot, but wrong for steady and aimed. For aimed and steady, +500 should be added before mods reduction
> 
>     return (castTime > 0) ? uint32(castTime) : 0;
> }

some proofs of those cast times from retail: 
https://www.youtube.com/watch?v=oalbvQx_yEc - here you can see differences of cast time with different haste buffs
https://www.youtube.com/watch?v=MowAFS6hvwU
https://www.youtube.com/watch?v=3clw8tF59vg

**Comment by TheVcelar** [comment]
+ comment from EJ:

> With 15% quiver and 20% haste from Serpent's Swiftness, Steady Shot fires 1.5/(1.15*1.20) = 1.09 seconds after you start it.

https://web.archive.org/web/20141029043302/http://forums.elitistjerks.com/topic/13034-shot-rotation-illustrated/page-2

**Comment by AbaddonL4G** [comment]
"Although a quiver or ammo pouch will speed up autoshot attacks, it does not affect Steady Shot."
http://wow.allakhazam.com/wiki/shot_rotation_(WoW)


please equip a quiver (with P% haste) and tell me whats your new cast time of SS.


Also formula should be 
base_cast / (haste_multiplier1*haste_multiplier2) = new_cast

**Comment by TheVcelar** [comment]
ill use [hunter pov](https://youtu.be/00ETbfqdZ4E?t=2m51s) from this server:

his steady shot cast time showed by quartz is 1.2s ( without any active haste buffs -> only serpent swiftness (20%) and quiver (15%) affecting cast time, as there is now no pasive +haste gear now) 

if calculation was right, quartz would show 1.1s

as i said, the problem is, only 1000ms is reduced by modifiers and then is added +500ms flat, instead of whole 1500ms being reduced

**Comment by TheVcelar** [comment]
one last proof

take [this video](https://www.youtube.com/watch?v=oalbvQx_yEc) again: 
his basic cast of steady shot without any active haste buff is **1.24**s.

When improved aspect of the hawk (+15% range attack speed) is the only active haste buff (like in [this moment](https://youtu.be/oalbvQx_yEc?t=2m23s)), his SS cast drops to **1.08**s.

>  1.24/1.15=~1.08

It means,, that whole 1.5s cast time is divided by haste modifier, not just 1s. on L4G, calculation according to video would look like this:

> (1.24-0.5)/1.15+0.5= ~1.14

**Comment by AbaddonL4G** [comment]
dumb question:
why is the base casting time from ss 1s and from as 2,5s?

**Comment by AbaddonL4G** [comment]
should be fixed with https://github.com/Looking4Group/L4G_Core/pull/3104
