### ISSUE TITLE
Dead after server dc if you were in combat before

### ISSUE THREAD

**Issue by Huntardsrise** [Looking4Group/L4G_Core#3051]
Title. All the pvpers are always dead, once the server reconnects.

**Comment by Huntardsrise** [comment]
Also happens in pve etc. whenever u are in combat

**Comment by Saltgurka** [comment]
Almost certainly an intended feauture to prevent you from just alt-f4 in the middle of a bad fight and log in alive.

**Comment by AnonXS** [comment]
http://vanillagaming.org/forum/index.php?topic=16565.0 , http://www.excalibur-nw.com/forum/tracker/issue-894-disconnecting-while-in-combat-kills-the-character-automatically/

**Comment by Rushor** [comment]
you could implement it like this https://github.com/TrinityCore/TrinityCore/pull/12045
