### ISSUE TITLE
Goodnight, Gronn 

### ISSUE THREAD

**Issue by shuvit** [Looking4Group/L4G_Core#3053]
Upon looting the bag after sleeping Gronn, it's empty. It's supposed to contain Grullock's Sack.

http://www.wowhead.com/quest=10800/goodnight-gronn
http://www.wowhead.com/item=31349/grullocs-sack

**Comment by AnonXS** [comment]
most likely gobject is bugged out because of people double looting it. wait for restart / ask gm to reset it /gm.

**Comment by shuvit** [comment]
Thank you, didn't want to bother a GM since they said tickets about bugs would be deleted. Will have a go at it 👍

**Comment by AnonXS** [comment]
merged this issue as general issue to  [World Gameobjects](https://github.com/Looking4Group/L4G_Core/issues/1714)
