### ISSUE TITLE
Changing weapon for casting Holy Light and Flash of Light in combat

### ISSUE THREAD

**Issue by TristanTano** [Looking4Group/L4G_Core#3060]
Swapping  from 2H weapon to 1H and shield (including librams) with a macro for casting Holy Light and Flash of Light SHOULD NOT give a global cooldown while in combat.
Proof:
https://youtu.be/EvmxORefCss?t=1541
Min. 25:41

**Comment by Evolvee** [comment]
its EquipItembyName script

**Comment by Xadras** [comment]
https://github.com/mangosArchives/Mangos-One-server-old/issues/17

**Comment by AbaddonL4G** [comment]
abuse of marco?
Not sure but i think this is working as intended.

**Comment by AnonXS** [comment]
https://github.com/Schaka/TBC-research/issues/5

https://bitbucket.org/smolderforge/core/issues/117/scripts-proof-especially-equipitembyname

https://github.com/ccshiro/cc-buglist/issues/2151

http://www.wowhead.com/forums&topic=35644/can-you-switch-weapons-while-in-combat
