### ISSUE TITLE
melee attack through LoS

### ISSUE THREAD

**Issue by Evolvee** [Looking4Group/L4G_Core#3078]
can you give me one single evidence that melee basic auto-attacks shouldnt ignore LoS component? :D because i have like 30 videos of the exact opposite behaviour, corecrafts Nim testimony and retail PTR account

http://looking4group.eu/hellfire2/forums/showthread.php?tid=2825&pid=27115#pid27115

**Comment by Evolvee** [comment]
i guess not

**Comment by Rushor** [comment]
your videos are epic! just saying
