### ISSUE TITLE
Casting while moving (video)

### ISSUE THREAD

**Issue by Templeton1** [Looking4Group/L4G_Core#3081]
https://github.com/Looking4Group/L4G_Core/issues/3033#issuecomment-266251500

You asked me to record it, so I did

https://youtu.be/P3jYoC2T0fg

the macro is still the same

**Comment by Saltgurka** [comment]
Thank you for recording this. I'm still unable to reproduce it, but it's clearly happening in your video so I'm confirming the issue.

**Comment by AnonXS** [comment]
Dubliate https://github.com/Looking4Group/L4G_Core/issues/1547
