### ISSUE TITLE
Can't find quest 'Picking up some power converters'

### ISSUE THREAD

**Issue by Ragnorask** [Looking4Group/L4G_Core#3083]
Toshley in Toshley's station should have the quest 'Picking up some power converters', but he doesn't seem to have it. Can't find any information about earlier bug reports.
please help.

**Comment by AnonXS** [comment]
http://db.looking4group.eu/?quest=10581 -> http://db.looking4group.eu/?quest=10584

**Comment by AbaddonL4G** [comment]
Live DB says quest is available.
First you need to complete http://db.looking4group.eu/?quest=10581
