### ISSUE TITLE
Winter Veil Hats not on boss loot tables

### ISSUE THREAD

**Issue by ihcTactics** [Looking4Group/L4G_Core#3089]
http://wowwiki.wikia.com/wiki/Red_Winter_Hat
http://wowwiki.wikia.com/wiki/Green_Winter_Hat

> At the same time, the hat is also a boss drop for specific mobs based on which expansions the player owns.
> For those that own only the basic game, the hat drops from:
> Emperor Dagran Thaurissan in Blackrock Depths
> Cannon Master Willey in Stratholme
> War Master Voone in Lower Blackrock Spire
> For those that own The Burning Crusade, the boss drops change to:
> Captain Skarloc in Escape from Durnholde Keep
> Nethermancer Sepethrea in The Mechanar
> High Botanist Freywinn in The Botanica
> In 2007 the hat dropped from all six Azeroth and Outland bosses regardless of expansions owned.

Killed Cannon Master Willey (not 100% drop chance) and Heroic High Botanist Freywinn (should be 100% drop chance). Neither dropped it.

And the green hats have 6 different bosses.

**Comment by AnonXS** [comment]
Red_Winter_Hat
     Emperor Dagran Thaurissan in Blackrock Depths 9019
    Cannon Master Willey in Stratholme 10997
    War Master Voone in Lower Blackrock Spire 9237 

For those that own The Burning Crusade, the boss drops change to:

    Captain Skarloc in Escape from Durnholde Keep 17862,20521
    Nethermancer Sepethrea in The Mechanar 19221,21536
    High Botanist Freywinn in The Botanica 17975,21558

Green_Winter_Hat
For those that own only the basic game, the hat drops from:

    Darkmaster Gandling in Scholomance 1853
    Goraluk Anvilcrack in Upper Blackrock Spire 10899 
    Prince Tortheldrin in Dire Maul West 11486 

For those that own The Burning Crusade, the boss drops change to:

    Grand Warlock Nethekurse in Shattered Halls 16807,20568
    Grandmaster Vorpil in Shadow Labyrinth 18732,20653
    Exarch Maladaar in Auchenai Crypts 18373,20306

**Comment by ihcTactics** [comment]
Was it not scripted in? I just killed H Nthermancer Sepethera and no hat dropped.

**Comment by Saltgurka** [comment]
This should be fixed now? Can anyone confirm?

**Comment by ihcTactics** [comment]
Confirmed in Heroic Mech. Been running vanilla dungeons also but at 10% drop chance it's hard to confirm :P
