### ISSUE TITLE
I see dead draenei

### ISSUE THREAD

**Issue by b18bsw4** [Looking4Group/L4G_Core#3095]
I have done all quests in Terokkar minus certain dungeon quests, and Ha'lei still doesn't have a quest for me. Additionally, Greatfather Aldrimus is visible to me, although I can't interact with him. I am assuming that this is some sort of bug, since others I have spoken to have been able to pick up said quest. There doesn't seem to be a prequest - that I can find anyway. I hope someone will be able to provide either a solution or an answer to my current predicament. Thank you.

**Comment by AnonXS** [comment]
http://db.looking4group.eu/?npc=19697
http://db.looking4group.eu/?quest=10227

**Comment by b18bsw4** [comment]
That unfortunately did nothing. Ezekiel has no quest to offer me :(

**Comment by b18bsw4** [comment]
That unfortunately did nothing. Ezekiel has no quest to offer me :(

**Comment by AbaddonL4G** [comment]
can't reproduce
