### ISSUE TITLE
Pets moving while frozen or stunned

### ISSUE THREAD

**Issue by sllikdeeps** [Looking4Group/L4G_Core#3100]
Hunter's pets and warlock's demons are moving freely, even while they are stunned or frozen by mage. Thats really dissapointing while you are playing arenas and its a key to CC the pet/demon or kill it sometimes. Hunters are hiding behind pillars and are harrasing us with pet, that we cannot kill, because they are pulling and heal the stunned or frozen pet, once we decide to kill it. Please fix it, its and important think.
Thank you !

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/307

Dublicate
