### ISSUE TITLE
Akama questchain... Again...

### ISSUE THREAD

**Issue by Diverse1** [Looking4Group/L4G_Core#3110]
Just wanted to let you know that this is not fixed as described in:
https://github.com/Looking4Group/L4G_Core/issues/3107

The bug is very much still active.
Thanks

**Comment by AbaddonL4G** [comment]
Should be active after server restart/crash

**Comment by AbaddonL4G** [comment]
Atm not at home so i am only able to restart in a few hrs- sry

**Comment by Diverse1** [comment]
No problem at all, just wanted to make sure it was under control.

Happy Hollidays!

**Comment by Saltgurka** [comment]
Needs a recompile, not just a restart. Not sure if Gekirin already did that?

**Comment by AbaddonL4G** [comment]
seems like he didnt :/

**Comment by Diverse1** [comment]
All i can confirm is that my character is still stuck in the animation.
Let me know if i need to do anything...
