### ISSUE TITLE
Quest: Saving Princess Stillpine - Only one key drops, so only one person can get credit.

### ISSUE THREAD

**Issue by adnanberberovic** [Looking4Group/L4G_Core#3125]
Pretty much the title. High Chief Bristlelimb only drops one key, so only one person can get the credit. I'm not sure if it's supposed to be only one key, but when I opened the princess' cage, only I got credit for releasing her and not my friend who I'm leveling with.

Usually, for unique item quests (where you're supposed to collect one item), it drops for both people, or when you engage in an event, all the group members should receive credit.

**Comment by AnonXS** [comment]
As this is no turn in Item but a use item it seems this rule doesnt apply to the key.

http://www.wowhead.com/quest=9667/saving-princess-stillpine

http://www.wowhead.com/npc=17702/high-chief-bristlelimb

http://www.wowhead.com/item=24099/the-high-chiefs-key

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3189/commits/9df5203e8b3f6ebc7722185f017bab432d597966
