### ISSUE TITLE
Silftfin Murlocs on the north coast of Azuremyst Isle drops a recipe with 100% drop rate.

### ISSUE THREAD

**Issue by adnanberberovic** [Looking4Group/L4G_Core#3126]
Basically the title, Silftfin Murlocs drops Plans: Copper Chain Vest with 100% drop rate. At least it did when I was playing there which was 3-4 days ago I believe.

**Comment by AnonXS** [comment]
```
-- Reduce Plans: Copper Chain Vest Dropchance on Siltfin Murloc
UPDATE `creature_loot_template` SET `ChanceOrQuestChance` = 1 WHERE `entry` = 17190 AND `item` = 3609;
```

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3117/commits/f52f2613955ddfced613f745b3c0d493e5142d80
