### ISSUE TITLE
Blackslit Murlocs spawn in HUGE groups (Not sure if it's supposed to be like that)

### ISSUE THREAD

**Issue by adnanberberovic** [Looking4Group/L4G_Core#3127]
I've never leveled as a Draenei before so I'm not sure if it's actually supposed to be like that, but these murlocs that you're supposed to tag spawn in groups of 6 murlocs which would be pretty hard or impossible for solo players to deal with.

Picture: http://i.imgur.com/8RvtFF9.png

**Comment by AnonXS** [comment]
http://db.looking4group.eu/?npc=17325 http://db.looking4group.eu/?npc=17326
http://db.looking4group.eu/?npc=17327 http://db.looking4group.eu/?npc=17328
http://db.looking4group.eu/?npc=17329 http://db.looking4group.eu/?npc=17330

```
SELECT * FROM `creature` WHERE `id` BETWEEN 17325 AND 17330;
```

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3117/commits/61b7160e4db496a474e1ae06881307f2bc005a26
