### ISSUE TITLE
Quest - SMV - A Necesarry Distraction / Eine notwendige Ablenkung

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#313]
Originally reported by: **Anonymous**

----------------------------------------

Nach der Benutzung der Schriftrolle um Azaloth zu befreien, erscheint die Meldung, dass die Aufgabe abgeschlossen sei. Azaloth attackiert einen daraufhin. Im Questlog gilt die Quest leider noch nicht als abgeschlossen.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/318

**Comment by Saltgurka** [comment]
#2169
