### ISSUE TITLE
Disconnected From Server every 15 seconds

### ISSUE THREAD

**Issue by FistofKhonshu** [Looking4Group/L4G_Core#3145]
Hi! Just joined the server with a freshly downloaded client and a brand new account and well, I can't even stay connected to your server even long enough to create a character. I don't have this issue on Excalibur TBC, Korakion TBC, or any other legacy servers. When I tried to post in the Forums, it said I was entering an invalid e-mail/password combination, yet I am able to log into my account management page with the very same e-mail/password combination. I couldn't find any other way of contacting anyone, either in the community or team members of Hellfire so I quickly made this GitHub account just to try and get some information. This disconnecting is obviously preventing me from playing on the server. I even quickly made a random character and logged in to try and see if the character select screen was what was causing the disconnects and well, I disconnected in game within seconds. What exactly is going on here? Thanks for any help!

**Comment by Saltgurka** [comment]
Hello!

Your forum account is separate from your ingame account.

As for the disconnection issue, where did you download your client from?

**Comment by FistofKhonshu** [comment]
I downloaded the client through uTorrent. It works great on the other
servers. Also, how do I make a forum account? Anyway, I'd love to try the
server. Do they really care much for the ones I've tried so far. Thanks for
responding!
