### ISSUE TITLE
Quest: Warsong Supplies for Level 27

### ISSUE THREAD

**Issue by Guygmx** [Looking4Group/L4G_Core#3146]
A npc for a quest don´t speak to me, he just say his "basic" text. The quest is warsong supplies and i don´t get the item Warsong saw blades.

**Comment by AnonXS** [comment]
http://www.wowhead.com/quest=6571/warsong-supplies#comments

Warsong Saw Blades; Get a Deadly Blunderbuss - //www.wowhead.com/?item=4369 - buy one off the AH or craft it, doesn't matter. Give it to Pixel (She's next to the Flight Path in Splitertree Post) and you'll get your shipment.

http://db.looking4group.eu/?npc=12724
http://db.looking4group.eu/?quest=6581

**Comment by Guygmx** [comment]
Sry i make a mistake, the item i mean is http://www.wowhead.com/item=16745.
In Ratsched the axe i got.

**Comment by Guygmx** [comment]
I got the item from Pixel, what i miss and can't get is "It'll take a trip to Booty Bay to pick up a crate of axes from Wharfmaster Lozgil." If you talk to Wharfmaster Lougil he just wish you a good day or Stuff like that. My Character is Liss on Hellfire.
