### ISSUE TITLE
In ewiger Liebe

### ISSUE THREAD

**Issue by alector77** [Looking4Group/L4G_Core#3147]
Ich bin zur Zeit in Dunkelküste ud soll den Anhänger von Anaya Dämmerflucht holen bei Ameth Aran. Leider ist die Gute nicht da. Ich hab sie 2x kurz gesehen, als ich gegen einen Bären und einen Mondpirscher kämpfte. Das war aber ausserhalb ihrer eigentlichen Position . Sie rannte an uns vorbei , pullen unmöglich und erhob sich hoch in die Luft und sprang zwischen den Bäumen bis ins Eschental.

Geht da irgendwas um die Quest doch zu erledigen??

**Comment by AnonXS** [comment]
http://db.looking4group.eu/?npc=3667 , http://db.looking4group.eu/?item=5382

**Comment by alector77** [comment]
Danke für die schnelle Antwort. Leider ist sie dort nicht. Ich hab es inzwischen unter Bugtracker issues eingetragen. Die Gute taucht hoch in der Luft auf und springt ins Eschental. Da kommt man nicht ran und sie taucht auch schon ausserhalb von ameth aran auf inmitten von Bären und Dämmerpirschern in einem Baum. Dann springt sie ab und ist hoch oben am wegflattern


-----Ursprüngliche Mitteilung----- 
Von: AnonXS <notifications@github.com>
An: Looking4Group/L4G_Core <L4G_Core@noreply.github.com>
Cc: alector77 <ytrtir@aol.com>; Author <author@noreply.github.com>
Verschickt: Mi, 25. Jan 2017 9:58
Betreff: Re: [Looking4Group/L4G_Core] In ewiger Liebe (#3147)



http://db.looking4group.eu/?npc=3667 , http://db.looking4group.eu/?item=5382

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3117/commits/6cb0c87eb1528003d7031929896ab17fbf8f7aca

Wird die nächsten Tage eingespielt. Will be deployed the next days.
