### ISSUE TITLE
Quest: The Path of the Adept - Paladin Quest

### ISSUE THREAD

**Issue by thestranger064** [Looking4Group/L4G_Core#3149]
The Paladin Quest in Deathholme, Ghostlands - missing npc Blood Knight Dawnstar's corpse 34,81
The NPC should be spawned dead, and looting it should give Blood Knight Insignia.

Cannot complete the quest without the insignia.
The other items from the quest is working and can be obtained.

**Comment by AnonXS** [comment]
```
-- Blood Knight Dawnstar 17832
UPDATE `creature` SET `modelid` = 0 WHERE `guid` = 39681;
```

https://github.com/Looking4Group/L4G_Core/pull/3117/commits/fccf20baab60f515bb4b32e10b399d4ca3d0e5f3

**Comment by thestranger064** [comment]
I cant seem to find the npc or the corpse, is this updated ?
