### ISSUE TITLE
Elemental Mastery buff consumed without granting 100% crit chance

### ISSUE THREAD

**Issue by AdmCrunch** [Looking4Group/L4G_Core#3154]
This is related to bug #2701 , but the last dev comment didn't mention what I am reporting so I hope this helps.

If you cast the following combination, the elemental shaman elemental mastery buff is consumed without granting 100% crit chance to any spells.

Lightning Bolt -> Elemental Mastery -> Chain Lightning (while 1st Lightning Bolt is in the air)

A video of this happening is here: https://youtu.be/v2EwxrgD3aI

The elemental mastery buff should ignore the spell in the air and grant 100% crit chance to the chain lightning spell.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2701
