### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by maikale** [Looking4Group/L4G_Core#3160]
Hello all 

6>          C:\Users\PC\Desktop\L4G\L4G_Core-master\dep\ACE_wrappers\ace/Atomic_Op_T.cpp(67) : while compiling class template member function 'ACE_Atomic_Op<ACE_LOCK,TYPE>::ACE_Atomic_Op(void)'
6>          with
6>          [
6>              ACE_LOCK=ACE_Thread_Mutex,
6>              TYPE=uint32
6>          ]

6>c:\users\PC\desktop\L4G\l4g_core-master\src\game\level3.cpp(7675): warning C4715: 'ChatHandler::HandleCharacterImportCommand' : not all control paths return a value

8>Detour.lib(DetourAlloc.obj) : warning LNK4099: PDB 'vc100.pdb' was not found with 'Detour.lib(DetourAlloc.obj)' or at 'C:\Users\ico\Desktop\HellGorund\L4G_Core-master\bin\Win32_Release_PCH\lib\vc100.pdb'; linking object as if no debug info

========== Build: 9 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

not found ACE.dll :(

**Comment by AnonXS** [comment]
I dont know how to create the ace.dll but y not get it somewhere else, google might help.

**Comment by maikale** [comment]
Simple help me compile it

**Comment by Xadras** [comment]
Did you try to compile with config: Win32 Release?
If not try to ^^

**Comment by maikale** [comment]
Again gives me an error :(

**Comment by Xadras** [comment]
Same as posted above?

**Comment by maikale** [comment]
everything is fine thank my mistake

**Comment by AnonXS** [comment]
yea ace.dll is built with win32 release.
