### ISSUE TITLE
Instance level 71

### ISSUE THREAD

**Issue by maikale** [Looking4Group/L4G_Core#3166]
Hello I have a problem :(
you must be at least level 71 to enter

**Comment by Saltgurka** [comment]
To enter what?

**Comment by maikale** [comment]
sunwell plateau BT

**Comment by Xadras** [comment]
its closed on our public realm: to open it locally you can use the following query:
UPDATE `access_requirement` SET `level_min`='70' WHERE (`id`='50');

**Comment by maikale** [comment]
can not login SWP instance  go just as GM :(

**Comment by Xadras** [comment]
then .level 71 might help? :P

**Comment by maikale** [comment]
go in all instances but can not in Sunwell :(

**Comment by Saltgurka** [comment]
Intendent. Type .Gm on

/Closed
