### ISSUE TITLE
UBANTU 16.04 System startup error

### ISSUE THREAD

**Issue by boom8866** [Looking4Group/L4G_Core#3167]
I follow the Wiki Environment, but start the server, log in to select the role, the server crashes!！

Error:*** stack smashing detected ***: looking4groupcore terminated

Thank you for your open source!

**Comment by Xadras** [comment]
Can you post your server log? I guess there is a more detailed error^^

**Comment by boom8866** [comment]
[Log.txt](https://github.com/Looking4Group/L4G_Core/files/756455/Log.txt)

This is the wrong record, hope can help to you, thank you!

**Comment by boom8866** [comment]
Problems occurred in

Enter: account password

Enter the select role interface

worldserver.exe Crash

**Comment by Xadras** [comment]
Hm, thats ugly.. I never got this crash before..
It seems to be a failure in AuthCrypt but I really can't identify it.

Did you already turned on server side logging in looking4groupcore.conf?
For example:
```
LogsDir = "/home/wow-server/log/"
LogLevel = 3 
LogFile = "server.log"
DBErrorLogFile = "db_errors.log"
```
Maybe, hopefully, there is a more detailed log in these two files then.

**Comment by boom8866** [comment]
Okay！ Thank you for your reply, I am debugging
@Xadras

**Comment by boom8866** [comment]
Wrong file, but I don't seem to have any problems

[db_errors.txt](https://github.com/Looking4Group/L4G_Core/files/758372/db_errors.txt)
[Server.txt](https://github.com/Looking4Group/L4G_Core/files/758373/Server.txt)

**Comment by AnonXS** [comment]
Yea around 100kb db_errors left to be resolved.

**Comment by boom8866** [comment]
These errors will not affect the normal operation
I have no problem in win system testing

**Comment by boom8866** [comment]
So is this the only thing that has happened to me?

I'm in ubantu cannot execute

**Comment by Xadras** [comment]
Hm I cant identify the error at least.
But as far as I know we have at least one dev who is working with ubuntu, too.  Without the error you had.. mysterious.

**Comment by boom8866** [comment]
T.T 
This is a very sad question

**Comment by kuramajssken001** [comment]
@boom8866 Have you solved this problem?
https://discord.gg/TtVzmgt
