### ISSUE TITLE
CreatureFamilyAssistanceRadius Help

### ISSUE THREAD

**Issue by maikale** [Looking4Group/L4G_Core#3168]
Hello i've got an issue that I cannot solve. I want to ask how can I set my PULLED options when ever I pull a mob in an instance to be only one not all of them ? I am guessing its from the settings but there are some functions missing and it doesen't works.

Creature.Evade.DistanceToHome = 40
Creature.Evade.DistanceToTarget = 45

Rate.Creature.Aggro = 1
CreatureFamilyAssistanceRadius = 10
CreatureFamilyAssistanceDelay = 1500

Whenever I adjust them it gets worst. Thank you for the help I deeply appreciate it.

**Comment by Saltgurka** [comment]
Many mobs inside instances are linked to each other, meaning if you attack one of them the others in the same group will assist in attacking you.

Check out http://www.hellfire-tbc.com/wiki/index.php?title=Creature_formations for more information

**Comment by maikale** [comment]
Can be changed ?

**Comment by Xadras** [comment]
can only be changed via database in the above specified table - just delete the rows of the creatures you want to pull solo

**Comment by AnonXS** [comment]
SET @GUID := YOURGUID;		
DELETE FROM `creature_formations` WHERE `memberguid` = @GUID;

If you delete you delete out that line, creatures will still be pulled by the CreatureFamilyAssist System afaik. There are some Issues with the creature_formations system which are not resolved, so you might not get the wanted behavior.

**Comment by maikale** [comment]
This method does not work

Xadras
can only be changed via database in the above specified table - just delete the rows of the creatures you want to pull solo

Help pls

**Comment by AnonXS** [comment]
Tell me GUID of npc you want to have single pulled? Maybe its script related?
