### ISSUE TITLE
TBB configuration problem 

### ISSUE THREAD

**Issue by dk123546** [Looking4Group/L4G_Core#3169]
In accordance with the deployment of Wiki, the emergence of such a problem 
How to solve, please help... 

CMake Error at CMakeLists.txt:205 (message):
  This project requires TBB installed when TBB_USE_EXTERNAL is set.  Please
  download the TBB Stable Release from
  http://www.threadingbuildingblocks.org/ and install it.  If this script
  didn't find TBB and it was correctly installed please set TBB_ROOT to the
  correct path.

**Comment by Xadras** [comment]
what kind of os do you use?

**Comment by dk123546** [comment]
@Xadras  CentOS X64

**Comment by Xadras** [comment]
I don't know if there is a yum package "libtbb-dev" for centos - if yes this would be the easiest way to get it.
If not you have to download/install it by yourself https://www.threadingbuildingblocks.org/download

**Comment by dk123546** [comment]
Thank you. The problem has been solved.
