### ISSUE TITLE
first summon the pet issue。

### ISSUE THREAD

**Issue by mynew4** [Looking4Group/L4G_Core#3171]
For example，When the warlock first summon the pet，pets do not follow players。The second summon is normal。

**Comment by AnonXS** [comment]
Pets dont work if the player learend the summoning spell and summons them for the first time.

Maybe related to player has to *relog* to save some variable to the database.
Summoned Creatures doesnt have *own name* assigned, so maybe its something in the pet table.

**Comment by woiwoz** [comment]
I am a world of Warcraft enthusiasts from China, but also a developer with many years of experience in mangos development. I should be able to solve this problem. Ha ha ha

**Comment by Xadras** [comment]
I've played around a little bit with it, but didn't get it to work yet.
If you are able to solve this problem, this would be really nice. (:

**Comment by woiwoz** [comment]
Of course, I have solved this problem.

**Comment by woiwoz** [comment]
Because I am in China, push code will be very difficult.

**Comment by Xadras** [comment]
Maybe it's easier to create a patch file via git and upload it wherever you want to.
Then we can push it for you.

**Comment by woiwoz** [comment]
ok

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Database
All further Updates: https://github.com/Looking4Group/L4G_Core/tree/master/sql/updates

**Comment by woiwoz** [comment]
Index: Pet.cpp
===================================================================
--- Pet.cpp	(版本 407)
+++ Pet.cpp	(工作副本)
@@ -124,7 +124,7 @@
 
 bool Pet::LoadPetFromDB(Unit* owner, uint32 petentry, uint32 petnumber, bool current, float x, float y, float z, float ang)
 {
-    m_loading = true;
+    SetLoading(true);
 
     uint32 ownerid = owner->GetGUIDLow();
 
@@ -145,8 +145,11 @@
         //                                        0   1      2      3        4      5    6           7              8        9           10    11    12       13         14       15            16      17              18        19                 20                 21              22
         result = RealmDataDatabase.PQuery("SELECT id, entry, owner, modelid, level, exp, Reactstate, loyaltypoints, loyalty, trainpoint, slot, name, renamed, curhealth, curmana, curhappiness, abdata, TeachSpelldata, savetime, resettalents_cost, resettalents_time, CreatedBySpell, PetType FROM character_pet WHERE owner = '%u' AND (slot = '0' OR slot = '3') ",ownerid);
 
-    if (!result)
-        return false;
+	if (!result)
+	{
+		SetLoading(false);
+		return false;
+	}
 
     Field *fields = result->Fetch();
 
@@ -153,7 +156,10 @@
     // update for case of current pet "slot = 0"
     petentry = fields[1].GetUInt32();
     if (!petentry)
-        return false;
+	{
+		SetLoading(false);
+		return false;
+	}
 
     uint32 summon_spell_id = fields[21].GetUInt32();
     SpellEntry const* spellInfo = sSpellStore.LookupEntry(summon_spell_id);
@@ -162,13 +168,19 @@
 
     // check temporary summoned pets like mage water elemental
     if (current && is_temporary_summoned)
-        return false;
+	{
+		SetLoading(false);
+		return false;
+	}
 
     Map *map = owner->GetMap();
     uint32 guid = sObjectMgr.GenerateLowGuid(HIGHGUID_PET);
     uint32 pet_number = fields[0].GetUInt32();
     if (!Create(guid, map, petentry, pet_number))
-        return false;
+	{
+		SetLoading(false);
+		return false;
+	}
 
     if (!x || !y)
     {
@@ -182,7 +194,8 @@
     {
         sLog.outLog(LOG_DEFAULT, "ERROR: Pet (guidlow %d, entry %d) not loaded. Suggested coordinates isn't valid (X: %f Y: %f)",
             GetGUIDLow(), GetEntry(), GetPositionX(), GetPositionY());
-        return false;
+		SetLoading(false);
+		return false;
     }
 
     setPetType(PetType(fields[22].GetUInt8()));
@@ -193,6 +206,7 @@
     if (cinfo->type == CREATURE_TYPE_CRITTER)
     {
         map->Add((Creature*)this);
+		SetLoading(false);
         return true;
     }
 
@@ -264,7 +278,10 @@
         Tokens tokens = StrSplit(fields[16].GetString(), " ");
 
         if (tokens.size() != 20)
-            return false;
+		{
+			SetLoading(false);
+			return false;
+		}
 
         int index;
         Tokens::iterator iter;
@@ -368,7 +385,7 @@
     if (owner->GetTypeId() == TYPEID_PLAYER && isControlled() && !isTemporarySummoned() && (getPetType() == SUMMON_PET || getPetType() == HUNTER_PET))
         owner->ToPlayer()->SetLastPetNumber(pet_number);
 
-    m_loading = false;
+    SetLoading(false);
     return true;
 }
 
@@ -532,7 +549,7 @@
 
 void Pet::Update(uint32 update_diff, uint32 p_diff)
 {
-    if (m_removed || m_loading)                                           // pet already removed, just wait in remove queue, no updates
+    if (m_removed || InLoading())                                           // pet already removed, just wait in remove queue, no updates
         return;
 
     switch (m_deathState)
Index: Pet.h
===================================================================
--- Pet.h	(版本 407)
+++ Pet.h	(工作副本)
@@ -242,7 +242,9 @@
 
         DeclinedName const* GetDeclinedNames() const { return m_declinedname; }
 
-        bool    m_loading;
+		bool InLoading(){ return m_loading; }
+		void SetLoading(bool loading){ m_loading = loading; }
+
         bool    m_removed;                                  // prevent overwrite pet state in DB at next Pet::Update if pet already removed(saved)
 
     protected:
@@ -253,7 +255,7 @@
         int32   m_loyaltyPoints;
         int32   m_bonusdamage;
         uint64  m_auraUpdateMask;
-
+		bool    m_loading;
         DeclinedName *m_declinedname;
 
     private:
@@ -265,7 +267,6 @@
         {
             ASSERT(false);
         }
-
         TimeTrackerSmall focusTimer;
 };
 #endif

**Comment by woiwoz** [comment]
ty,I will push to fix this pet call problem diff

**Comment by woiwoz** [comment]
I am currently dealing with pets can not follow the master boarded the transport vehicle problem, we can refer to the https://github.com/elysium-project open source code.

**Comment by AnonXS** [comment]
that's a complicated one afaik. good luck!

**Comment by woiwoz** [comment]
I uploaded the patch you download it?

**Comment by Xadras** [comment]
yep, I've downloaded it

**Comment by woiwoz** [comment]
OK, you can test this patch to fix the problem.

**Comment by AnonXS** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/24082106/79c88a5a-0cc0-11e7-8dcc-227bfe4c3eee.PNG)
Live Server: Pet is summoned for the first time, doesnt abide to commands like /petfollow, also isnt named.

Branch with your fix applied: Pet does instantly follow and execute commands like /petfollow, still is not named on first summon. (not really a issue)
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/24082141/ed12dc7c-0cc0-11e7-8323-5716b9b05a78.PNG)

**Comment by Xadras** [comment]
https://github.com/Looking4Group/L4G_Core/commit/5e0045ee92c9bd4402966be7a616c1dde57ea6f4

**Comment by woiwoz** [comment]
good nice.
