### ISSUE TITLE
Instance Reset

### ISSUE THREAD

**Issue by maikale** [Looking4Group/L4G_Core#3172]
Hello all can you tell me how to change reset instance 
this
This raid instance is scheduled reset in 2 Days 11 Hours

to 

This raid instance is scheduled reset in 1 Days 11 Hours 

thank you very much.

**Comment by AnonXS** [comment]
map.dbc field120 defines this value, or you need to write an exception in the core.

**Comment by AbaddonL4G** [comment]
you want to reset?

.insta unbind all/ID

**Comment by maikale** [comment]
I want to reduce reset time 1 days I think it is made from DB  tell me more precisely how to do it :(

**Comment by Xadras** [comment]
`UPDATE `instance_template` SET `reset_delay`='1' WHERE (`map`='XXX');`
Replace XXX with the correct mapid for example 580 for sunwell.
Here you cann find all values: http://www.hellfire-tbc.com/wiki/index.php?title=Map.dbc#Content

**Comment by maikale** [comment]
Thank you very much all :)
