### ISSUE TITLE
Update DB 088_02_01.17.sql

### ISSUE THREAD

**Issue by maikale** [Looking4Group/L4G_Core#3177]
**088_02_01.17.sql**
:( help me pls

[Err] 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET @GUID := 190508' at line 2
[Err] INSERT INTO `waypoint_data` VALUES (190506, 26, -3929.28, -11612.4, -138.556, 0, 0, 0, 100, 0)
SET @GUID := 190508;
[Msg] Finished - Unsuccessfully

**Comment by Xadras** [comment]
I guess there is a missing ; at the end of:
INSERT INTO waypoint_data VALUES (190506, 26, -3929.28, -11612.4, -138.556, 0, 0, 0, 100, 0)

-->

INSERT INTO waypoint_data VALUES (190506, 26, -3929.28, -11612.4, -138.556, 0, 0, 0, 100, 0);

**Comment by maikale** [comment]
[Err] 1065 - Query was empty
[Err] ;
[Msg] Finished - Unsuccessfully
--------------------------------------------------

:(

**Comment by Xadras** [comment]
I guess you've made something wrong.. I'll going to fix that broken update..

**Comment by Xadras** [comment]
Update your local repo and try again (:
Should be ok now.

**Comment by maikale** [comment]
Ohh again error no inport update 

[Err] 1065 - Query was empty
[Err] ;
[Msg] Finished - Unsuccessfully

**Comment by Xadras** [comment]
hm mysterious.. maybe there is another mistake in there..

**Comment by Xadras** [comment]
Hm, I got a:

[SQL]
INSERT INTO `creature_questrelation` (`id`,`quest`) VALUES
(22113,11013);
[Err] 1062 - Duplicate entry '22113-11013' for key 'PRIMARY'

I guess somebody else must review this update ^^

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/1914e512cdc96d14cb5b59f6e0348f4d9dd4b1a4
