### ISSUE TITLE
Have a problem whit SWP 

### ISSUE THREAD

**Issue by maikale** [Looking4Group/L4G_Core#3180]
Hello Gs i have a problem whit istance SWP, i cant entry in istance, i make a raid group and  all  try to entry but enywone cant enter in istance,please help me how cann i make this.

Gs cann say me what is this     'NON SHELL PASS'. Be patient! Shattered Sun Offensive mages are trying to unseal the main entrance!  in my data base and how can repair the base and then istance working? 

Thanks
![wowscrnshot_021817_135353](https://cloud.githubusercontent.com/assets/1087826/23093072/d55f818e-f5e1-11e6-841e-1ed2fbd7aef2.jpg)

**Comment by AnonXS** [comment]
`access_requirements` or linked to swp event.

**Comment by maikale** [comment]
![default](https://cloud.githubusercontent.com/assets/1087826/23101103/c72dc90e-f695-11e6-8e79-c3eb4f5abe72.png)

:(

**Comment by Xadras** [comment]
Maybe you have not done the isle event? ^^

**Comment by maikale** [comment]
Which event should fill ? can you tell me

**Comment by Xadras** [comment]
Last time I did this was.. like a year ago... 
can't remember but if you activate all swp related events it should work i think :D

**Comment by maikale** [comment]
xaxaxa Trying friend :)

**Comment by maikale** [comment]
Please Help me with bug problem i can not get into some Sances swp old hisrband foothils i have 3 account and 1 of them enters swp the other 2 is not a friend can not enter for what reason it would not be able to enter pliz help me i need enter swp :(

**Comment by AnonXS** [comment]
try .tele swp.

**Comment by maikale** [comment]
Yes but you always have to have gm online players want their own :(

**Comment by maikale** [comment]
there reputation enter to swp Quest ?

**Comment by AnonXS** [comment]
we implemtended system similar to aq wareffort as isle and swp was not instant available on retail.

**Comment by maikale** [comment]
/*######
## npc_archmage_nethul
######*/

bool GossipHello_npc_archmage_nethul(Player *player, Creature *_Creature)
{
    if (_Creature->isQuestGiver())
        player->PrepareQuestMenu(_Creature->GetGUID());

    int32 text = 0;
    player->ADD_GOSSIP_ITEM(0, "Wie ist der aktuelle Status", GOSSIP_SENDER_MAIN,1);
    /*player->ADD_GOSSIP_ITEM(1, "SWP Event: Aktivste Gilde", GOSSIP_SENDER_MAIN,2);
    player->ADD_GOSSIP_ITEM(2, "SWP Event: Aktivste Spieler", GOSSIP_SENDER_MAIN,3);
    player->ADD_GOSSIP_ITEM(3, "SWP Event: Beliebteste Daily", GOSSIP_SENDER_MAIN,4);*/
    player->ADD_GOSSIP_ITEM(3, "Auf Wiedersehen", GOSSIP_SENDER_MAIN,5);
    player->SEND_GOSSIP_MENU(DEFAULT_GOSSIP_MESSAGE,_Creature->GetGUID());
    return true;
}

bool GossipSelect_npc_archmage_nethul(Player *player, Creature *_Creature, uint32 sender, uint32 action )
{
    if (!player)
        return false;

    switch(action)
    {
    case 1:
        {
            QueryResultAutoPtr query = GameDataDatabase.PQuery("SELECT * FROM `new_swp_event` WHERE `id`= 1");
            if (query)
            {
                Field *fields = query->Fetch();
                uint64 quests_needed_p1    = fields[0].GetUInt64(); //for SWP Opening
                uint64 quests_needed_p2    = fields[1].GetUInt64(); //for Boss 1,2 and 3
                uint64 quests_needed_p3    = fields[2].GetUInt64(); //for Boss 4 and 5
                uint64 quests_needed_p4    = fields[3].GetUInt64(); //for Last Boss
                uint64 quests_done        = fields[4].GetUInt64();
                uint64 quests_phase        = fields[5].GetUInt64();

                if (quests_phase == -1)
                {
                    player->GetSession()->SendAreaTriggerMessage("SWP Event nicht gestartet");
                }

**Comment by maikale** [comment]
Quest For enter in SWP ?

**Comment by AnonXS** [comment]
a specific amount of quests done on the isle of quel'danas. specificed amount is in the database under swp_event.
