### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#3185]
Invitation link is outdated.

**Comment by Saltgurka** [comment]
Staff or community discord?

**Comment by Xadras** [comment]
community ^^

**Comment by Saltgurka** [comment]
https://discord.gg/ZdUKjzT

**Comment by Saltgurka** [comment]
I'll ask gek to pm you staff discord invite as well, you should join us there :)

**Comment by Xadras** [comment]
hm strange one, even with the new link I get this outdated message :O
![discord](https://cloud.githubusercontent.com/assets/12048181/23218054/70db5ade-f91b-11e6-9366-5fa5663f4de5.PNG)

**Comment by Saltgurka** [comment]
Is that in the discord application or your browser?

**Comment by Xadras** [comment]
browser ^^

**Comment by Saltgurka** [comment]
Try the app https://discordapp.com/

Players are joining so the old link should be fine as well

**Comment by Xadras** [comment]
oookay I should choose another nickname, was banned by accident ;D
