### ISSUE TITLE
error compile

### ISSUE THREAD

**Issue by iraj0711** [Looking4Group/L4G_Core#3190]
9>..\..\src\scripts\scripts\zone\stratholme\boss_ramstein_the_gorger.cpp(73): error C2872: '<lambda0>' : ambiguous symbol
9>          could be '..\..\src\scripts\scripts\zone\stratholme\boss_ramstein_the_gorger.cpp(73) : `anonymous-namespace'::<lambda0>'
9>          or       'C:\Users\Iraj\Downloads\Compressed\master\L4G_Core-master\src\framework\Utilities/EventProcessor.h(70) : `anonymous-namespace'::<lambda0>'

**Comment by AnonXS** [comment]
Dont update the project to vs15, say cancel on startup.

**Comment by iraj0711** [comment]
visual 2010 or 2015?

**Comment by AnonXS** [comment]
works in both, but dont update the repo in vs2015 you are are asked on startup, vs10 works just fine.

**Comment by iraj0711** [comment]
please fix compile in visual 2010

**Comment by AnonXS** [comment]
also try win32 compile, 64 doesnt work atm.

**Comment by iraj0711** [comment]
error compile visual 2010
9>....\src\scripts\scripts\zone\stratholme\boss_ramstein_the_gorger.cpp(73): error C2872: '' : ambiguous symbol
9> could be '....\src\scripts\scripts\zone\stratholme\boss_ramstein_the_gorger.cpp(73) : anonymous-namespace'::<lambda0>' 9> or 'C:\Users\Iraj\Downloads\Compressed\master\L4G_Core-master\src\framework\Utilities/EventProcessor.h(70) :anonymous-namespace'::'

**Comment by AnonXS** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/23574518/5f0c0b44-007f-11e7-888e-ede5f460f5c5.PNG)

**Comment by AnonXS** [comment]
missing dependencys like vs10 service pack 1 maybe.

**Comment by iraj0711** [comment]
please link download vs10 ???
up link no download   https://www.microsoft.com/de-de/download/details.aspx?id=23691

**Comment by Xadras** [comment]
Hm I just found the german version of it, but no english <.<
