### ISSUE TITLE
Mage shadow bolt

### ISSUE THREAD

**Issue by maikale** [Looking4Group/L4G_Core#3201]
Hello friends

I want to ask is it good to have a mage shadow bolt :(

**Comment by maikale** [comment]
Sometimes when the mage casts Fireball after that he automatically he casts instant Shadowbolt that dose 200-400 damage

**Comment by AnonXS** [comment]
Trinket

**Comment by Xadras** [comment]
http://db.looking4group.eu/?item=34470 100% ^^

**Comment by maikale** [comment]
thank you very much :)
