### ISSUE TITLE
account registration

### ISSUE THREAD

**Issue by majer123** [Looking4Group/L4G_Core#3207]
Hi. Me and my friend  cant make account because the captcha wont load...It says: 
ERROR for owner's website:
Invalid domain for key sites
![image](https://cloud.githubusercontent.com/assets/26580727/24165690/5afbdf20-0e71-11e7-95d3-2de8a752dedb.png)

Can you pls fix it? ^^

**Comment by Saltgurka** [comment]
Make sure you're using http://hellfire-tbc.com/view/register.php and not looking4group.de
