### ISSUE TITLE
[Mage] Water Elemental

### ISSUE THREAD

**Issue by vexxedd** [Looking4Group/L4G_Core#3210]
1.  Water Elemental start next cast only when previous one hit the target.
Should not be the case. Water Elemental should chain-cast bolts.
[Screenshot.](https://i.gyazo.com/87ca2c76c2c4a741efd72f8bbbca30b8.jpg)
Proof: https://www.youtube.com/watch?v=Iy-iHZXSphs&t=206s
https://youtu.be/EZfNPWFh0K8?t=1m16s
https://youtu.be/K4WR0JW5jWM?t=3m7s

2. Water Elemental should not disappear when you are mounted up.
Proof: https://youtu.be/K4WR0JW5jWM?t=1m29s

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2587, https://github.com/Looking4Group/L4G_Core/issues/1766
