### ISSUE TITLE
compiling / sql setup / extracting issues

### ISSUE THREAD

**Issue by gathz** [Looking4Group/L4G_Core#3212]
i want to say that this is the first time i tried to compile this and im trying to understand it but i ran into some problems while following the guide

*compile
so this is the log from when i compiled, should it look like this?
https://hastebin.com/hifuwuduya.tex (log from compiling)

*sql
so when im trying to import the databases i get the following error
'mysql error 1031 when importing the sql files', i googled but didnt quite understand how to deal with it, im using windows 7 and HeidiSQL with MySQL Server 5.7 btw

also which world database to use?
https://github.com/Looking4Group/L4G_Database Or the 'world_2016-10-01.gz' in core directory

*extracting
when i run MoveMapGen it is building maps etc but also says 'No offmesh file provided' alot even tho its located in the tbc root directory, i also created the mmaps directory as it said it was missing

also should i use the dbc i extracted or the one that you uploaded 
https://github.com/Looking4Group/L4G_Dbc

appreciate any help

**Comment by AbaddonL4G** [comment]
compile log looks fine.

i would extract all the files.

use the db from the directory and run the newer sql files (DB should always be up to date)

**Comment by gathz** [comment]
when i import the L4G_Core\sql\structures\chars.sql 

`Query:
CREATE TABLE `spell_disabled` (
  `entry` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Spell entry',
  `disable_mask` int(8) unsigned NOT NULL DEFAULT '0',
  `comment` varchar(64) NOT NULL DEFAULT '',
  PRIMARY KEY (`entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='Disabled Spell System'

Error occured at:2017-03-23 07:01:35
Line no.:1529
Error Code: 1031 - Table storage engine for 'spell_disabled' doesn't have this option



Query:
INSERT INTO `spell_disabled` VALUES ('1852', '7', 'Silenced (GM Tool) Spell bugged')

Error occured at:2017-03-23 07:01:35
Line no.:2016
Error Code: 1146 - Table 'characters.spell_disabled' doesn't exist



Query:
INSERT INTO `spell_disabled` VALUES ('46642', '7', '5k gold')

Error occured at:2017-03-23 07:01:35
Line no.:2017
Error Code: 1146 - Table 'characters.spell_disabled' doesn't exist

`

**Comment by AnonXS** [comment]
Use https://github.com/Looking4Group/L4G_Database and Run all world Updates 081+

**Comment by gathz** [comment]
thx
