### ISSUE TITLE
SL Heroic/Murmur - Incorrect loot table

### ISSUE THREAD

**Issue by honeyhoney** [Looking4Group/L4G_Core#3222]
Heroic Murmur (creature entry 20657) should not drop the Belt of Depravity http://db.hellfire-tbc.com/?item=29241

This should resolve it:
```sql
DELETE FROM creature_loot_template
WHERE entry = 20657 AND item = 29241;
```

**Comment by AnonXS** [comment]
Because of 2.1 Item?

**Comment by honeyhoney** [comment]
Ah nevermind. In 2.0 it **should** drop from Murmur. In 2.1 it was added to Harbinger Skyriss's loot table. It is unconfirmed whether it was then removed from Murmur or became a drop from both. For 2.0 this change is not necessary.
