### ISSUE TITLE
Quest: Spirits of Stonemaul Hold(Dustwallow Marsh)

### ISSUE THREAD

**Issue by Avishai97** [Looking4Group/L4G_Core#3237]
The quest works by walking over the skeletons instead of using the item BUT.
I am pretty sure that if people don't use the item to "use" the skeletons the Ogres won't spawn next time someone else runs over the skeleton until a restart of the server has happened. I can't confirm it as solo player though. after about 10 minutes I tried running over the same skeleton and nothing spawned.

**Comment by Saltgurka** [comment]
Live next update
```sql
-- Issue: https://github.com/Looking4Group/L4G_Core/issues/3237
UPDATE `gameobject` SET `spawnmask`=0 WHERE `id`=186334; -- Despawn traps. It should not trigger on player vicinity, but don't know of a way to fix it
UPDATE `gameobject_template` SET `data10`=42421 WHERE `entry`=186332; -- Make the goober cast the spell instead
```
