### ISSUE TITLE
Karazhan Boss CDs --WIP--

### ISSUE THREAD

**Issue by Tomofc** [Looking4Group/L4G_Core#3239]
_This is a Work in Progress, any boss I added without any info below it means I haven't checked it yet. Any boss not listed means I didn't find any problems with it._

# _**Moroes**_

- [x] **Gouge_Timer**

_Non sped up video_

https://youtu.be/lFefTq0GoIQ?t=15

Pull at :19 Gouge opens at :47

Gouge at :47, 1:13, 1:37, 2:20, 2:50

_26s, 24s, 43s(including a vanish), 30s_

### _**Conclusion: Reduce this to a random time between 25000,30000**_

Pull :5 Gouge opens at :24 

https://youtu.be/8UUmvbKJGxw?t=8 - ***Speed up Video, sadly useless if we cant find out the speed ratio***

Gouge at 1:46, 2:02. 2:36. 2:54, 3:09 if you pause at these times you can see the debuff (he also has garrote)

https://youtu.be/8UUmvbKJGxw?t=101

Seems to be a variable cd?

---

- [x] **Blind_Timer**

_Non sped up video_

https://youtu.be/lFefTq0GoIQ?t=15

Pull at :20
Blind opens at :53

Blind at :53, 1:23, 1:58

_30s, 35s_

### _**Conclusion: Maybe reduce this down to a random time between 30000,35000**_

Blind opens at :31

https://youtu.be/8UUmvbKJGxw?t=28

Blind at :31, :57(had garrote), 1:20(had garrote), 1:42 (had garrote), 2:05(had garrote), 2:27 (had garrote), 2:48 (had garrote)

---

#  _**Maiden of Virtue**_

- [x] **Holyfire_Timer**

Holy Fire opens at :06

Holy Fire at :06, :23, :36, :47, :56, 1:04, 1:16, 1:30, 1:41, 1:51, 2:04, 2:12, 2:27, 2:43, 2:53. 3:01, 3:08 

_17s, 13s, 11s, 9s, 8s, 12s, 14s, 11s, 10s, 13s, 8s, 15s, 16s, 10s, 8s, 7s_

https://youtu.be/ojVNbLqHyew?t=3

### _**Conclusion: For 3 mins the cd never got above 17 seconds, maybe this needs to be shortened down to 8000, 20000**_

Also may want to check the size of Holyground in the video it seems much smaller in comparison to what is live on the server -- **edit: we checked this and 12y is correct**

---

#  _**Opera**_

---

_Romulo and Julianne_

## **Julianne**

https://youtu.be/g7TaQbrDa5s?t=70

- [x] **BlindingPassionTimer**

Blinding Passion opens at 1:14

Blinding Passion at 1:14, 1:30(on pally healer), 1:54, 2:08(kicked), 2:39(kicked), 2:46(kicked)

_16s, 24s, 14s, 31s, 7s_

### _**Conclusion: This one seems to be all over the place and it's hard to track in these old videos. If I were to suggest something it would be make this a random interval between 10000,30000.**_ 

---

- [x] **DevotionTimer**

Devotion Aura opens at 1:27

Devotion Aura at 1:27, 1:46. 2:18. 2:41

_19s, 32s, 23s_

### _**Conclusion: This one seems to be all over the place and it's hard to track in these old videos. If I were to suggest something it would be make this a random interval between 20000,30000.**_ 

---

- [x] **EternalAffectionTimer**

Eternal Affection opens at 1:38

Eternal Affection at 1:38, 1:49, 2:01, 2:16(kicked), 2:28(kicked)

_11s, 12s, 15s, 12s_

### _**Conclusion: If I were to suggest something it would be make this a random interval between 10000,20000. But this may need more research.**_ 

---

- [x] **PowerfulAttractionTimer**

Powerful Attraction opens at 1:44

Powerful Attraction at 1:44, 2:04, 2:26. 2:44

_20s, 22s, 18s_

### _**Conclusion: If I were to suggest something it would be make this a random interval between 20000,25000. From the video it seems like she is almost always casting something and it seems to be random, i don't really know how to script this but it's something to think about.**_ 

---

## **Romulo**

https://youtu.be/JxKvjz1waR8?t=129

- [ ] **PoisonThrustTimer**

Poison Thrust opens at 2:26(on caster)

Poison Thrust at 2:26, 2:46, 3:16

_20s, 30s_

### _**Conclusion: This one seems to be all over the place and it's hard to track in these old videos. Needs more research.**_ 

---

- [x] **DeadlySwatheTimer**

Deadly Swathe opens at 2:26

Deadly Swathe at 2:26, 2:35. 2:47, 2:58, 3:14, 3:26

 _9s, 12s, 11s, 16s, 12s_

### _**Conclusion: This one is hard to track in these old videos. If I were to suggest something it would be make this a random interval between 8000,16000.**_ 

---

 # _**Curator**_

- [ ] **hatefulBoltTimer**

### _**Conclusion: You have a note on this saying this might be incorrect and from the videos I have watched its hard to gauge the timer on this (because multiple targets get hit) but this seems to be correct.**_

---

#  _**Chess**_

 - [ ] **moveTimer = 3000;**

### _**Conclusion: This should be 12 seconds; https://www.youtube.com/watch?v=82-uAiRMgJs&feature=youtu.be&t=69**_ 

---

# _**Nightbane**_

https://youtu.be/f5ItHl86exU?t=38

**45000+rand()%15000; //timer wrong between 45 and 60 seconds**

_Flight Phase 1: Take off at 2:22/lands at 3:20 = 58s (includes take off time + landing time)
Flight Phase 2: Take off at 4:59/lands at 5:57 = 58s (includes take off time + landing time)
Flight Phase 3: They skipped this part_ 

### _**Looks as though your timer would be correct, if you factor in 2.4.3 talents I believe that the timer for his flight should be shorter than retail. I think maybe you should make it even shorter like 45000+rand()%10000 or even shorter than that. If I recall most guilds on this server with stacked ranged dps could keep him in the air for 75% of the fight. So the balance has to be either a shorter flight time or increased flight speed or both. I see that you guys have his take off speed set to 1.0:**_

// Set Flight Speed to normal at begin of takeoff
        m_creature->SetSpeed(MOVE_FLIGHT, 1.0f);

### _**while his landing speed is set to 6.0:**_

 // Set flying speed to x6.0 so doesnt take so long to land
                m_creature->SetSpeed(MOVE_FLIGHT, 6.0f);

### _**maybe setting his take off speed to 6.0 would help? I don't really know the answer to this.**_

**SmolderingBreathTimer = 20000;//timer**

Smoldering Breath opens at 1:19

Smoldering Breath at 1:19, 1:52. flight phase 1, 3:59, 4:31, flight phase 2 + ground phase 3 (hes at 25%), 7:30, 8:01

_33s, flight phase 1, 32s, flight phase 2+ ground phase 3. 31s_

**BellowingRoarTimer = 30000+rand()%10000 ; //Timer**

Bellowing Roar opens at 1:58

_Bellowing Roar at 1:58, flight phase 1, 4:14, flight phase 2 + ground phase 2 (hes at 25%), 8:26_

### _**Conclusion: I don't really remember if we saw more than 2 Bellowing Roar's in 1 phase on the server, but it seems on retail that it only happened 1 time per ground phase. You could go either way with this, either keep it how it is (more difficult) or change it to 1 time per phase (a bit easier). I would however look at the Smoldering Breath CD as it seems that it should be ~30s per Smoldering Breath.**_

_This is a Work in Progress, any boss I added without any info below it means I haven't checked it yet. Any boss not listed means I didn't find any problems with it._

**Comment by honeyhoney** [comment]
Really thorough report. Typically we'd treat these issues separately (i.e. one issue per boss, or perhaps per boss _ability_) but as these seem to be timing improvements it's fairly reasonable to keep it together.
Looking forward to seeing this update.

Good contribution thus far if everything checks out. 👍

**Comment by AnonXS** [comment]
It's also important to note down the pull time if possible as we always have a Initial Timer and a Repeated Timer in the Scripts.

**Comment by Tomofc** [comment]
Added a new video for moroes that doesnt seem sped up to me. Still seems like Gouge should be between 20-30 seconds and Blind was harder to tell when it was casted but still should be about every 30 seconds.

**Comment by Tomofc** [comment]
Ok at the moment I didn't find any problems with Prince, Illhoof, Shade, Attune the Huntsman, and Netherspite because I know that you guys have extensively worked these bosses (maybe minus Illhoof because who cares about that boss anyways).

**Comment by AnonXS** [comment]
- [ ] Rework Nightbane, that one is not simple timer changes and needs more attention to detail.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/29fbc09de291a8de6f3e1f1ab2f3efe2252b9b17
