### ISSUE TITLE
Warlock Talents

### ISSUE THREAD

**Issue by Tacotaki** [Looking4Group/L4G_Core#3249]
Improved Healthstone and Improved Imp talents in the demo tree don't seem to be working. Blood pack even though the skill says 91 stam, the buff only gives 70 like the original skill. Same goes with fire shield. Health stones when made with the talent don't show increased amount of hp and don't reward more hp then normal ones.

**Comment by vexxedd** [comment]
Talent works
![asd1](https://i.gyazo.com/2ec3619551b967ad48529d22e40ecfb5.png)

Tooltip works
![asd2](https://i.gyazo.com/8baeb34e80576da3da410b71424fd2c3.png)

Imp works as well.

**Comment by tst12** [comment]
talents work just refresh auras(for example mount-dismount), tooltip dont  work for buffs and spell "create healthsone"
