### ISSUE TITLE
Warlock mobs.

### ISSUE THREAD

**Issue by Avishai97** [Looking4Group/L4G_Core#3250]
When you attack a warlock mob, the voidwalker does not follow, and when you kill the warlock the voidwalker doesn't die.

**Comment by Avishai97** [comment]
http://db.hellfire-tbc.com/?npc=5617

**Comment by AnonXS** [comment]
This was due to people killing only the caster, new caster resummons new pet and the old pet didnt despawn, which is fixed now.
