### ISSUE TITLE
Charge

### ISSUE THREAD

**Issue by subjunction010** [Looking4Group/L4G_Core#3256]
When i charged on my warrior, i charged like 10 meters to the right of the mob. This problem was there last year as well. What is the current progress on it?

**Comment by AnonXS** [comment]
Bounding Radius Issue probably, you do not charge ontop the creature but to the furthest point of its hitbox.

**Comment by Seperest** [comment]
After some testing, it works as intended on perfectly flat terrain, but any slope (even a tiny hill) causes it to work as subjunction010 says, or in some cases you will charge 1yd forward and that's it. Seems to be a pathing issue, i believe.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/677
