### ISSUE TITLE
Hunter pets

### ISSUE THREAD

**Issue by Avishai97** [Looking4Group/L4G_Core#3258]
If you level from 1-60 as a hunter you will have to change pets very often with x3 because the quest experience sometimes gets you very far ahead of your pet meaning that your pet can end up lvl31 and you are lvl36 or numbers close to that, 

Maybe it's worth looking at increasing pet experience or speeding up loyality so taming a new appropriate level pet is alright.

**Comment by Avishai97** [comment]
Maybe wrong place to write this though as it is not a code issue, more of an experience boost consequence

**Comment by Saltgurka** [comment]
Pet experience should scale with your character's XP gain. Loyalty has been scaled up slightly as well since our old value seemed a bit too low.

If we see one or the other is still too slow, we can easily boost it more.
