### ISSUE TITLE
Warrior Rage

### ISSUE THREAD

**Issue by lugiebob** [Looking4Group/L4G_Core#3261]
Warriors are not getting rage when a priest has a bubble on them.  The damage is being absorbed and the warrior is not taking damage so no rage is given.  This is a myth that it is blizzlike. They changed it after vanilla that warriors would get rage on "hit" even if absorbed and no damage was taken.  I am sure druid bears have the same issue.

**Comment by Fleso** [comment]
Wrong. This Change took place early wrath in Patch 3.1. My brother and several other friends of Mine Who mained warrior back then confirmed me that. Also look up the Patch Notes for 3.1

**Comment by vexxedd** [comment]
https://web.archive.org/web/20080113212717/http://www.wowwiki.com/Rage#Using_Rage_Potions
> Attacks which damage a shield (such as Power Word: Shield) but not the opponent themselves do not generate rage.

**Comment by AbaddonL4G** [comment]
rage generation is fine.
no bugs here.
