### ISSUE TITLE
Abolish Poison/Disease dispelling when out of debuffs to remove

### ISSUE THREAD

**Issue by Notmittz** [Looking4Group/L4G_Core#3263]
Spells such as Druid's Abolish Poison and Priest's Abolish Disease have dispel effects, but should be castable even if target not poisoned/Diseased and the dispel effects should continue to occur every 2 seconds for the full duration of the spell's 8 second effect.  However, upon the second 'tick' of the dispel effect, if there is no poison/disease on the target, a system message displays "Nothing to Dispel" and the Abolish spell effect buff is removed.  This seems to only effect player characters and not NPCs.

How these spell should work: Immediately dispel the poison/disease effect on cast and then every 2 seconds for the next 8 seconds, attempt to cure 1 poison/disease effect even if there are is no longer any effects to remove.

**Comment by vexxedd** [comment]
Confirm. This is actually a problem.

**Comment by Ike86542** [comment]
This is still happening

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/85e08801359fafbfc63ea8f47bcbfa0165f74886
