### ISSUE TITLE
Master of Deception

### ISSUE THREAD

**Issue by Kit12345** [Looking4Group/L4G_Core#3273]
Doesn't help with stealth detection, heard it was broken waited till level 14. So I aggro a mob (invis) then put 5 points in and tried again with no difference.

**Comment by cbibejs** [comment]
Please fix this. It's ver crucial talent i don't know if any rogue can cc in dungeons without this talent. I have 5/5 Master of Deception but there is no difference i can't even get close and sap a mob.

**Comment by AnonXS** [comment]
Related to https://github.com/Looking4Group/L4G_Core/issues/3245

**Comment by AnonXS** [comment]
MOD is working, resulting in 3yard lesser detection at 5/5 points, which equals 15MOD/5per Level = 3 yards.
