### ISSUE TITLE
paladin tome of divinity quest not working

### ISSUE THREAD

**Issue by bsilva321** [Looking4Group/L4G_Core#3278]
please help. so we can get resurrection quest done for dungeons. thank u

**Comment by Saltgurka** [comment]
No steps to reproduce or even a mention of which specific quest is not working.

Closing

**Comment by bsilva321** [comment]
Lol what a dick move won't be playing on server anymore, shouldn't have to
explain what's wrong with ur shit scripting

**Comment by bsilva321** [comment]
No mention of what quest is not working Lmfao you must be retarded. Peace
out
