### ISSUE TITLE
[Quests] Quest rewards are lost if inventory is full

### ISSUE THREAD

**Issue by Xolocotzii** [Looking4Group/L4G_Core#3282]
Finishing a quest with 2 Item rewards when you only have 1 free inventory slot will cause 1 reward to be lost

**Comment by Saltgurka** [comment]
Could you give me an example of a quest where this happened? 
Cause quests can award more than one item in 2 ways. Either you have one default reward + one additional reward that the player gets to pick freely between some alternatives.

Or you have more than one default reward and no optional reward for the player.

Would be good to have that information before we start looking into the issue :)

**Comment by Xolocotzii** [comment]
Sure, its the more than one default reward case for me, happened with this quest:
http://db.vanillagaming.org/?quest=258
Had 1 free slot, got the shirt but the sword just disappeared

**Comment by tst12** [comment]
checked possibility to store only one item in a time
