### ISSUE TITLE
Blix Fixwidget - Brewfest

### ISSUE THREAD

**Issue by moonsti** [Looking4Group/L4G_Core#3291]
The Mob Blix Fixwidget is still in-game and able to sell items in exchange for brewfest currency during non-brewfest times.
![brewfist](https://cloud.githubusercontent.com/assets/15868285/24584527/6b96cc70-1725-11e7-8884-a70049c05651.png)

**Comment by Saltgurka** [comment]
```sql
DELETE FROM `game_event_creature` WHERE `guid` IN(152120,7370,12369);
INSERT INTO `game_event_creature` VALUES
(152120,26),
(7370,-26),
(12369,-26);
```
