### ISSUE TITLE
Creatures at the bottom of water always evade

### ISSUE THREAD

**Issue by Dexxon1337** [Looking4Group/L4G_Core#3295]
Water mobs such as Surf Crawlers in Durotar which are set to walk on the bottom do not swim after being attacked and evade a lot.

**Comment by Saltgurka** [comment]
Fixed next update. Report if you find more of them, we can only fix them individually.
```sql
UPDATE `creature_template` SET `InhabitType`='3' WHERE  `entry`=3107;
```
