### ISSUE TITLE
Shaman - Elemental Mastery not granting 100% crit.

### ISSUE THREAD

**Issue by Zergfest** [Looking4Group/L4G_Core#3296]
Elemental Mastery -talent does not work as intended and is not granting 100% crit chance on next nature spell. Tested with following formula:
/cast Elemental Mastery
/cast Chain lightning(rank 2)

The result is Chain Lightning being cast without mana cost, so 50% of the talent is working.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2701
