### ISSUE TITLE
once again TOME OF DIVINITY NOT WORKING SYMBOL DISAPPEARS AND CANT REZ for quest

### ISSUE THREAD

**Issue by bsilva321** [Looking4Group/L4G_Core#3298]
do i need to be even more specific or u gonna close my ticket again?

**Comment by Xadras** [comment]
would be nice to be more specific, yep ;>
Every race have got another quest, with the same name.. so there are like 10quests+ with this name

Please link the correct one with http://db.hellfire-tbc.com

**Comment by bsilva321** [comment]
http://db.hellfire-tbc.com/?item=6775 its the paladin one, starts as tome
of valor, its the second part tome of divinity im supposed to get a symbol.
the first time i tried it gave me the symbol i rezzed the guy and it
disappeared and wouldnt let me turn in the quest. now i abandoned quest
when i go back to do it it will not give me the symbol i need to rez the
dude in elwynn forest "faulk". i am only concerned because im leveling a
paladin and need it so that i can heal dungeons, without it i cant rez
people. thank u for replying

**Comment by Saltgurka** [comment]
Quest works fine for me (http://db.hellfire-tbc.com/?quest=1786)

If you lost your Symbol of Life, Duthorian Rall has a quest which gives you a new one. (http://db.hellfire-tbc.com/?quest=1790)

**Comment by Xadras** [comment]
just to verify; its the human pala quest wheerre uh have to revive Henze Faulk in Elwynn.

**Comment by bsilva321** [comment]
Yes, thank u 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Xadras <notifications@github.com> Date: 4/3/17  5:50 PM  (GMT-08:00) To: Looking4Group/L4G_Core <L4G_Core@noreply.github.com> Cc: bsilva321 <bsilva1102@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Looking4Group/L4G_Core] once again TOME OF DIVINITY NOT WORKING
  SYMBOL DISAPPEARS AND CANT REZ for quest (#3298) 
just to verify; its the human pala quest wheerre uh have to revive Henze Faulk in Elwynn.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Looking4Group/L4G_Core","title":"Looking4Group/L4G_Core","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Looking4Group/L4G_Core"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Xadras in #3298: just to verify; its the human pala quest wheerre uh have to revive Henze Faulk in Elwynn."}],"action":{"name":"View Issue","url":"https://github.com/Looking4Group/L4G_Core/issues/3298#issuecomment-291350704"}}}
