### ISSUE TITLE
Bombing quests in Outland

### ISSUE THREAD

**Issue by Nexao** [Looking4Group/L4G_Core#3299]
The birds are flying way to fast, when you bomb somewhere, you''re out of range. So the speed needs to be toned down

**Comment by AnonXS** [comment]
Source?

**Comment by Nexao** [comment]
Don't have a source on it, but if you test it out, then you can see that it goes faster than it's supposed to. 
Very noticeable as the bombs you throw very quickly gets out of range (Wasn't the case back in retail)

**Comment by AnonXS** [comment]
This is not true for sure as rare flyingmounts have 60% flying speed in tbc which is extremly slow.

No further Data provided.
