### ISSUE TITLE
Nodes for mining spawning too fast

### ISSUE THREAD

**Issue by Nexao** [Looking4Group/L4G_Core#3300]
Nodes for mining are spawning way too fast, I mine one and it re spawns within a minute again

**Comment by Nexao** [comment]
It's really gonna mess up the economy if this goes on for too long :S

**Comment by TherealTolly** [comment]
Yeah I can confirm this problem

**Comment by summitsama** [comment]
This only happens once for a given node.  After you mine it the second time, it will stay despawned.  I would guess that the respawn only checks when the node last spawned, but doesn't consider when it was mined.

**Comment by Nexao** [comment]
When I was mining in outland yesterday, I could mine the same node 4 times within 2 minutes. So I don't think that's the case

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3290
