### ISSUE TITLE
Skill cost not reduced for poison

### ISSUE THREAD

**Issue by demonkillerx** [Looking4Group/L4G_Core#3303]
Hello, i just noticed when i trained posion´s from level 20-40 that it cost me more than 10gold.
So i knew straight away that something was wrong here

Here is poison for level 44. (2G 61S)
http://i.imgur.com/1iigeQQ.jpg

Here is a normal spell for level 44
http://i.imgur.com/d4YrJNz.jpg (87S)

So i did the math 2,61/3=87. I guess this proves enough to reduce the price so we rogues can get a mount aswell? Same goes for hunter pet skills ive been told 
Regards Demonkiller

**Comment by AnonXS** [comment]
You are right, some trainers where missed out in the Update.

**Comment by AnonXS** [comment]
Fixed with next Restart since: Current time: 2017-04-04 02:16:16
