### ISSUE TITLE
Quest Items 

### ISSUE THREAD

**Issue by SalaTKaratel** [Looking4Group/L4G_Core#3305]
Up drop quest items, that just impossible...

**Comment by Saltgurka** [comment]
Could you elaborate? I'm not sure what you mean

**Comment by SalaTKaratel** [comment]
Quest items very bad fall from monsters

**Comment by SalaTKaratel** [comment]
at least it's very noticeable in start locations

**Comment by AnonXS** [comment]
you mean % chance? can you tell me some quests you have issues with?

**Comment by SalaTKaratel** [comment]
Yes % chance. At the moment, i try not to the drop items  quests.

**Comment by Saltgurka** [comment]
We can't fix it if you don't mention specific quests with too low drop rates. Search it up on http://db.hellfire-tbc.com/ and link it here.
