### ISSUE TITLE
Quest / Raptor Captor (11146)

### ISSUE THREAD

**Issue by honeyhoney** [Looking4Group/L4G_Core#3306]
http://db.hellfire-tbc.com/?quest=11146

When you weaken the raptor enough (Bloodfen Raptor looks weak enough to capture.) and use the Sturdy Rope on it (http://db.hellfire-tbc.com/?item=33069) it does not get captured.

Unsure if Core or DB script.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/1818
