### ISSUE TITLE
Mobs seem to leashed or unable to pass "Invisible wall"

### ISSUE THREAD

**Issue by imchaotic** [Looking4Group/L4G_Core#3307]
I will add comments to this as I see issues.

Hellfire Peninsula:
   34.4, 58.7 - Stonescythe Whelp (Pull from the north - like from 34.2, 58.0)
   33.5, 58.7 - Stonescythe Whelp (Pull from the north - like from 33.7, 58.1)
   
Hellfire Ramparts:
   - This happened last night, so I don't have coordinates. But it is all pulls after the 5th or so, you can pull back towards the entrance and they will eventually hit an invisible wall.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/4d46770b4979eff91ff49b7bafcfaaeba9b2c9fb
