### ISSUE TITLE
Blood Furnace Second Boss/Boss Room

### ISSUE THREAD

**Issue by fineillhealu** [Looking4Group/L4G_Core#3311]
The second boss's pathing seems to be bugged he just stands where he is spawned trying to move forward also i don't know if it was because of the server crash but both of the doors to his room closed when we were at the last boss.

**Comment by Nexao** [comment]
I'm in here now, and yes, he's just standing in there messing around

**Comment by Nexao** [comment]
The normal mobs in there behaves the same way, they just move around like there's an invisible wall http://prntscr.com/es1k1w

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/3307
