### ISSUE TITLE
Techinicans in The Bloodfurnace

### ISSUE THREAD

**Issue by Nexao** [Looking4Group/L4G_Core#3313]
The mines they put down says they hit for 900, but they actually hit 2000 ish

**Comment by Xadras** [comment]
hc/nh?

**Comment by AnonXS** [comment]
# Nonheroic:

Effect 0:
Id: 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
BasePoints = 1800
Targets (22, 15) (TARGET_CASTER_COORDINATES, TARGET_ALL_ENEMY_IN_AREA)
Radius (Id 13) 10.00

1800 Damage

# Heroic:

Effect 0:
Id: 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
BasePoints = 3500
Targets (22, 15) (TARGET_CASTER_COORDINATES, TARGET_ALL_ENEMY_IN_AREA)
Radius (Id 13) 10.00

**Comment by Nexao** [comment]
Alright cool, just the text displaying in the wow thingy that's off then
