### ISSUE TITLE
Pillar of amethyst respawn timer is way to long

### ISSUE THREAD

**Issue by Zarant** [Looking4Group/L4G_Core#3317]
Quest Broken Alliances/Tremors of Earth in Badlands requires you to loot 3 gems from 3 different pillars, 2 of those pillars instantly respawn, however, the pillar of amethyst (http://db.hellfire-tbc.com/?object=2858) have a respawn timer greater than 2hrs.

**Comment by AnonXS** [comment]
Check Loottable: http://db.hellfire-tbc.com/?object=2858

```
UPDATE `gameobject` SET `spawntimesecs` = 300 WHERE `id` = 2858;
```

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3290/commits/8e07b22fc5a98ea28780a87eef68a48a16f1917e
