### ISSUE TITLE
Ending their World - Quest

### ISSUE THREAD

**Issue by Custap** [Looking4Group/L4G_Core#3327]
In the Quest "Ending their World" on Bloodmyst Isle, the NPC that is supposed to be escorted will not move, he does not move upon taking the quest and he gives no dialog option for initiating the escort.

I read from similar servers that this specific quest has a lot of issues, one being that the pathing is in general missing. The boss NPC at the end of the quest is not engageable.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2344
