### ISSUE TITLE
King Bangalash respawn timer

### ISSUE THREAD

**Issue by Mistiqq** [Looking4Group/L4G_Core#3328]
He is needed for quest "Big game hunter" in Stranglethorn Vale. After waiting for him about 30 min, decided to leave this place, seems the respawn time is too long.

**Comment by AnonXS** [comment]
Von Matzai (5,449 – 1·8·18) am 2009.10.12 (Patch 3.2.2)		
His spawn time is around 5 mins. Maybe less.

http://www.wowhead.com/npc=731/king-bangalash#english-comments

```
UPDATE `creature` SET `spawntimesecs` = 300 WHERE `id` = 731;
```

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3290/commits/36f0df81c6967f6d1b522dce24279436739bac6b
