### ISSUE TITLE
Roque talent Cheat death

### ISSUE THREAD

**Issue by demonkillerx** [Looking4Group/L4G_Core#3330]
Ive noticed that cheat death some times does not proc nor does it give the 3s buff that should reduce 90% of dmg taken. 
http://imgur.com/a/ifmAS
In this picture u can see that it triggered cheat death on his execute but the mili sec after the execute his melee hit killed me, so i did not get 3s 90%, also after i was dead you can see "Dkx gains Cheating Death" so i guess it triggerd after i was dead already?

**Comment by AnonXS** [comment]
Scales with Resilence, doesnt work good on lowlevels in tbc

https://github.com/Looking4Group/L4G_Core/issues/2494
https://github.com/Looking4Group/L4G_Core/issues/2530
https://github.com/Looking4Group/L4G_Core/issues/2408
