### ISSUE TITLE
Elementals at Elemental Plateau have magic immunities they should not

### ISSUE THREAD

**Issue by BezawitL4G** [Looking4Group/L4G_Core#3332]
The fire elementals (Raging Fire-Soul) are immune to Nature Damage. They should only be immune to Fire Damage.

The air elementals (Storming Wind-Ripper) are immune to Arcane Damage. They should only be immune to Nature Damage.

Also the damage the fire elementals deal is much lower than it should be. They are currently hitting for 170-200 damage. They should be hitting for roughly 300 damage as seen per this video: 

https://www.youtube.com/watch?v=LEK0XPW4X8Q

**Comment by AnonXS** [comment]
http://www.wowhead.com/npc=22310/storming-wind-ripper#comments
They are not immune to nature damage, however they are immune to arcane. I used to farm these dudes on my druid and found it quite frustrating that I couldn't faerie fire or moon-spam them when I was balance. But as feral - they go down fast. Most elementals should be immune to the following schools: - Air Elementals: Arcane - Water Elementals: Frost - Fire Elementals: Fire - Earth Elementals: Nature At least that's my experience.

http://www.wowhead.com/npc=22311/raging-fire-soul#comments
By Tantou (1,139 – 12·18) on 2007/02/11 (Patch 2.0.6)		
Completely immune to poisons 

-> not all nature damage, will change to only fire immune.

Implement General Immunity for Bleeds and Poisions(Needs a DB-Flag) for Elementals.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3339/commits/2f9484f322049d3f4284f52ef7ea2d982ae22be5
