### ISSUE TITLE
Monsters with fear killing totems

### ISSUE THREAD

**Issue by Emarka** [Looking4Group/L4G_Core#3336]
Hello,
i believe this behavior is incorrect.

Whenever monster use any kind of fear ability it starts killing totems (Manaspring and tremor), ignoring Seering totem though. This makes Tremor totem basically useless, since it gets destroyed before it gets chance to tick.

**Comment by AnonXS** [comment]
If the player is feared, the npc will switch to second threat target.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/402
