### ISSUE TITLE
Items remain in Auction House after the poster deletes his character

### ISSUE THREAD

**Issue by Anteara** [Looking4Group/L4G_Core#3337]
http://i.imgur.com/qfAUYkg.jpg

Notice the name of the player that is selling the item.
You can still buy the items, so it's not very problematic.

**Comment by Saltgurka** [comment]
This is because technically we never delete any characters. They are just removed from the character selection screen and renamed, so if we ever need to restore a character we can easily do that.

**Comment by AnonXS** [comment]
No Bug, not even an Enhancement as storing the deleted characters is a good thing.
