### ISSUE TITLE
Quest: Fire at will! South cannon

### ISSUE THREAD

**Issue by aznmark** [Looking4Group/L4G_Core#3342]
Quest is broken in the south cannon.

-Invisible mob hitting us
-Cannon turning into a enemy when it's health was at half.
-Fired over 7 shots and still didn't complete the quest. Supposedly you need 7 shots only.

http://www.wowhead.com/quest=10911/fire-at-will

Need the neck for pre-bis

**Comment by AnonXS** [comment]
```
-- Death's Door North Warp-Gate, Death's Door South Warp-Gate 22471,22472
UPDATE `creature_template` SET `dynamicflags` = 8 WHERE `entry` IN (22471,22472);
```
