### ISSUE TITLE
Timed quests sometimes continually crashes the client until timer runs out

### ISSUE THREAD

**Issue by Saltgurka** [Looking4Group/L4G_Core#3344]
Sometimes when a player accepts a quest with a timer, the client will crash. Also every try to log in to the character while the timer is still running will crash the client on loading screen. 

Three examples where this is reported to be happening:
* http://db.hellfire-tbc.com/?quest=5321
* http://db.hellfire-tbc.com/?quest=9663
* http://db.hellfire-tbc.com/?quest=4491

It only happens rarely, so it's hard to reproduce.

**Comment by AnonXS** [comment]
https://wow.curseforge.com/projects/quest-helper/files/140114
Fix the timed-quest crash, hopefully

Addon related.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/1458
