### ISSUE TITLE
Death Coil breaks due to incoming damage.

### ISSUE THREAD

**Issue by bomberoqt** [Looking4Group/L4G_Core#3347]
Since i am 42 I recognized some issues with death coil and tried to reproduce the problem. So, the problem was that death coil broke sometimes before the 3 sec. horror effect ran out. The death coil works perfect if I do nothing nor my pet but as soon as I do damage while the enemy has the death coil effect up it can break, it's same as fear. But the horror effect of death coil shouldnt break.

Greetings Burn

**Comment by AnonXS** [comment]
```
// https://github.com/Looking4Group/L4G_Core/blob/449d786a8df64b59f882632f79fcd842ddbf3f6b/src/game/SpellMgr.cpp#L2997
+else if (spellInfo->SpellFamilyName == SPELLFAMILY_WARLOCK && spellInfo->SpellFamilyFlags & [ENTERSPELLFAMILYNAMEDEATHCOIL)
+ spellInfo->Attributes |= SPELL_ATTR_BREAKABLE_BY_DAMAGE;
```

SPELL_ATTR_BREAKABLE_BY_DAMAGE might be used in another way currently. 
https://github.com/Looking4Group/L4G_Core/blob/82189e34b57ad9949b6c413d88e8f22033c6b6f3/src/game/SpellAuras.cpp#L401
https://github.com/Looking4Group/L4G_Core/blob/5db29dcb30ef0d336e467f61334d8474108b09fa/src/game/UnitAI.cpp#L363

**Comment by Saltgurka** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3456
