### ISSUE TITLE
[Auction House] Usable Items option

### ISSUE THREAD

**Issue by ahlens** [Looking4Group/L4G_Core#3358]
"Usable Items" button in the Auction House is not working. After marking it, choosing armor type items and then clicking search button it should show only items that our character is able to use use (wear). Unfortunately, nothing has happend.

Screenshoot as a proof
<a href='https://postimg.org/image/y4u76krrv/' target='_blank'><img src='https://s1.postimg.org/y4u76krrv/Wo_WScrn_Shot_040617_090329.jpg' border='0' alt='postimage'/></a>

This is quite usefull option. It would be great if you could fix that :)

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2422
