### ISSUE TITLE
[Visual effects]

### ISSUE THREAD

**Issue by ahlens** [Looking4Group/L4G_Core#3361]
Just have a look at screenshoots. What this can be about?

<a href='https://postimg.org/image/h9weonvvf/' target='_blank'><img src='https://s1.postimg.org/h9weonvvf/Wo_WScrn_Shot_040617_123000.jpg' border='0' alt="WoWScrnShot_040617_123000"/></a><br/><br/>
<a href='https://postimg.org/image/akpv8najf/' target='_blank'><img src='https://s1.postimg.org/akpv8najf/Wo_WScrn_Shot_040617_123003.jpg' border='0' alt="WoWScrnShot_040617_123003"/></a><br/><br/>

**Comment by AnonXS** [comment]
Linked to https://github.com/Looking4Group/L4G_Core/issues/367
