### ISSUE TITLE
[NPC] Godan

### ISSUE THREAD

**Issue by ahlens** [Looking4Group/L4G_Core#3362]
I don't think this NPC should have Fishing Pole equipped :P

http://wowwiki.wikia.com/wiki/Godan

<a href='https://postimg.org/image/qhw1elvy5/' target='_blank'><img src='https://s22.postimg.org/qhw1elvy5/Wo_WScrn_Shot_040617_124250.jpg' border='0' alt='postimage'/></a>

Just the minor issue that surprised me when I talked to him.

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?npc=3345

**Comment by AnonXS** [comment]
```
-- Godan 3345
UPDATE `creature_template` SET `equipment_id` = 0 WHERE `entry` = 3345; -- 488 Fishing Pole now not used in any template
```

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3364/commits/edeb4a20ecccc151a6bf8c67c78d7bec04279fd0
