### ISSUE TITLE
Quest "Free from the hold"

### ISSUE THREAD

**Issue by ME121989** [Looking4Group/L4G_Core#3368]
Hello,

the Quest "free from the hold" in the Barrens (northwatch hold escort Q) seems to be bugged. The NPS runs into a mountain side (where the pirates are) and just disappears. Tried it twice now. Will try again tomorrow.

**Comment by Saltgurka** [comment]
http://db.hellfire-tbc.com/?quest=898
http://db.hellfire-tbc.com/?npc=3465

I can't reproduce the issue. Please provide some more information. 
Coordinates where he bugs out?
Screenshots/Videos?

**Comment by ME121989** [comment]
sorry tha ti did not respond. I forgot about it. I tried it a day later and it worked somehow.

**Comment by Saltgurka** [comment]
I believe this may have been caused by the pathfinding issues we had for a few days, and it should now be fine again.

If the issue reappears, we'll reopen this again.
