### ISSUE TITLE
Hellfire Ramparts: Vazruden the Herald, and Nazan is badly scripted.

### ISSUE THREAD

**Issue by adnanberberovic** [Looking4Group/L4G_Core#3369]
When the boss is pulled, Vazruden jumps off Nazan immediatly. Then another Vazruden on top of Nazan appears and lands, with the two guards at the start respawning a couple of times (maybe that last bit is supposed to be like that?).

Also Nazan despawned almost immediatly when I ran the dungeon so I couldn't loot the last quest item, please don't make monsters despawn before quest items are looted if it's somehow possible to do.

**Comment by AnonXS** [comment]
This "bug" only occures after continued wiping, encounter seems to have reset issues just like other bosses.
