### ISSUE TITLE
monster pulling / pathing

### ISSUE THREAD

**Issue by g4thz** [Looking4Group/L4G_Core#3370]
when pulling monsters and using for example arcane explosion every few yards, the monster currently does not train to you as many yards as it should, they reset to early even tho you spamm arcane explosion.

mby they are scripted so that they reset after their zone, currently but i think that something is wrong.

i know this is a vanilla footage but, you can check it out for referense of what i mean
https://www.youtube.com/watch?v=pcl7REPFimg

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/3351
