### ISSUE TITLE
Mage - Blink

### ISSUE THREAD

**Issue by g4thz** [Looking4Group/L4G_Core#3371]
can blink under stairs, also wierd blink pathing in outlands etc. 
try blink over rivers and up the hills, it is just bad imo. 

not much of an explanation but id give it 5/10 atm. Please look into it.

**Comment by Saltgurka** [comment]
https://github.com/Looking4Group/L4G_Core/issues/995

**Comment by Timira** [comment]
blinking in water makes you move further back then forward. Blink is kinda broken atm. Kinda gamebreaking for mages.
