### ISSUE TITLE
Lifebloom Burst Affect Doesn't Stack With the HoT

### ISSUE THREAD

**Issue by jarvy15524** [Looking4Group/L4G_Core#3372]
The stacking affect of lifebloom does not seem to be working properly. The heal overtime affect stacks just fine and increases with each stack but the end burst heal does not stack. If i have 1 stack, the spell will heal the target for 273 over 7 seconds. When the spell is dispelled or ends the spell heals for 600. When a second or third stack is applied the HoT of 273 is increased 2 or 3 times, depending on the number of stacks, but the burst heal remains at 600 instead of being increased 2 or 3 times as it should.

**Comment by Xadras** [comment]
afaik this is no bug, its intended ^^

**Comment by moonsti** [comment]
Bc icon.gif Patch 2.1.0 (22-May-2007): Each additional application of this spell will now include the full bonus from effects which increase healing. The final heal, however, is still unaffected by stacking multiple applications of this spell.

http://wowwiki.wikia.com/wiki/Lifebloom
