### ISSUE TITLE
The Trappings of a Vindicator

### ISSUE THREAD

**Issue by Shivanxt** [Looking4Group/L4G_Core#3374]
This Quest ( http://db.hellfire-tbc.com/?quest=10516 ) in Blades Edge has a very minor Bug.
Mugdorg http://db.hellfire-tbc.com/?npc=20726 should drop http://db.hellfire-tbc.com/?item=30415 (Shield)
Droggam http://db.hellfire-tbc.com/?npc=20731 should drop http://db.hellfire-tbc.com/?item=30413 (Sword)
Insted Droggam dropped both items at once for me. He should not Drop the Shield, but its even listed in the DB.
This just makes the Quest a bit easier.

**Comment by Saltgurka** [comment]
Solved next update. Thanks for the report!

```sql
DELETE FROM `creature_loot_template` WHERE  `entry`=20731 AND `item`=30415;
```
