### ISSUE TITLE
A Dire Situation

### ISSUE THREAD

**Issue by Shivanxt** [Looking4Group/L4G_Core#3375]
Quest http://db.hellfire-tbc.com/?quest=10506 

Rina's Diminution Powder http://db.hellfire-tbc.com/?item=30251 can be uses on the same Wolf 5 times to complete the Quest, tho it states in the items effect, that this shouldnt be possible.
The Debuff http://db.hellfire-tbc.com/?spell=36310 on the Wolf with the same name should prevent this from happening.

**Comment by Saltgurka** [comment]
Thank you for including all related IDs and database links! Makes it much easier for us :)

This is fixed with: https://github.com/Looking4Group/L4G_Core/pull/3385 (not live yet)
