### ISSUE TITLE
[Pet Skill] Boar Charge

### ISSUE THREAD

**Issue by musou-soft** [Looking4Group/L4G_Core#3376]
Pet doesn't charge its target, just continues to run at normal speed at it.
Other parts of the skill (1 sec. immobilization and damage buff for the next attack) work as intended

spell id - 7370 (rank 1)

**Comment by Seperest** [comment]
It seems to work perfectly on flat terrain, but if there is any slope it works as stated by musou-soft. Seems to be a pathing bug.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/474

**Comment by tst12** [comment]
problem in pet autocast
