### ISSUE TITLE
shattered hand assassins respawn rate

### ISSUE THREAD

**Issue by WarriorTSW** [Looking4Group/L4G_Core#3379]
Hi,

shattered hand assassins(17695) in shattered halls normal respawn very quickly. I would guess 2-5mins. 
I havent yet been to the heroic version.

**Comment by AnonXS** [comment]
The fast respawn at the endboss is inteneded, for the others https://github.com/Looking4Group/L4G_Core/pull/3364/commits/8cfad6d2117143630e842d8401ebcafc1d525ab5
