### ISSUE TITLE
Tome Of Divinity

### ISSUE THREAD

**Issue by Nebzo1** [Looking4Group/L4G_Core#3381]
I am not able to pick up this quest. I am level 40 now and none of the trainers in IF or SW will offer the quest for me. Am I able to just have the Resurrection skill given to me by a GM?

**Comment by Nebzo1** [comment]
Character name is Nebzo Dwarf Paladin

**Comment by tst12** [comment]
http://db.hellfire-tbc.com/?quest=2998

**Comment by Saltgurka** [comment]
Please make a ticket ingame and we will get this sorted for you. :)
