### ISSUE TITLE
Evade bug on mobs!

### ISSUE THREAD

**Issue by TherealTolly** [Looking4Group/L4G_Core#3396]
Hello Hellfire GM team.

So I'm not completely sure if this is a bug or if this was how it was back in the day.
But I'm having alot of trouble AOE grinding the mobs that I want to. 
You see as a leveling protection paladin I tend to gather a lot of mobs up and AOE'ing them down.
The problem I'm having is this: Even though I make sure to consistenly attack the mobs that I'm trying to gather up they seem to evade once they got far enough away from they're spawning point.
If this is a bug, I would love it if you guys could take a look at this, once you get the time.

Best regards Tolly

**Comment by g4thz** [comment]
+1

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/3351
