### ISSUE TITLE
Being rooted or nettet by mobs stops auto attack.

### ISSUE THREAD

**Issue by TherealTolly** [Looking4Group/L4G_Core#3397]
Hi again. 

Titel says it all.

Thanks
Tolly

**Comment by AnonXS** [comment]
What npc?

**Comment by TherealTolly** [comment]
I've expecianced two diffent kinds of NPC's.
First time was one of the Dark Iron Dwarf mobs in Searing Gorge. 
Second time was one of the mobs in the south region of Tanaris, the ones in the same area as the mobs that drop the quest item for the Noggenfoggers.

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?npc=1051 - wrong npc

Searing Gorge, Tanaris Npc.
