### ISSUE TITLE
Rogue quest bug (The shattered hand) lvl13

### ISSUE THREAD

**Issue by Vankie** [Looking4Group/L4G_Core#3400]
Ok so i started my first rogue quest chain and reached the shattered hand quest at lvl 13.

I was supposed to kill  karzan and retrieve his satchel. Upon return the quest giver gave me the info about gomer, another npc which i had to pickpocket  for the satchel's key which contains the quest item.

Bug: the satchel is empty and the key is lost after use ofc.You can only redo the quest after you abandon it, if you kill the npc so he spawns back, with the key, but the satchel again still, gives nothing which renders the quest unfinishable.

My poor Gazul troll is left without a prize.  :P

**Comment by Saltgurka** [comment]
http://db.hellfire-tbc.com/?quest=1963

**Comment by Vankie** [comment]
What's with the link? that's the first stage of the quest  and it's done the problem is later on. to open the satchel you need a key from a mob which you must pickpocket in OG  the satchel contains the quest item which is missing  that's the issue.

**Comment by AnonXS** [comment]
Linked to https://github.com/Looking4Group/L4G_Core/issues/901

http://db.hellfire-tbc.com/?item=7295
http://db.hellfire-tbc.com/?item=7209

**Comment by Vankie** [comment]
the follow up quest has been picked.....the quest giver gives nothing more  later on after you pick up the key...he even tells you to open it yourself and again the satchel is empty, and the quest item is missing...so there's nothing to return to the Q giver.

**Comment by AnonXS** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/25148033/cd8ea5b8-2479-11e7-8068-b41e52125750.PNG)

Got the satchel, turned it in, took followup quest which provides the closed satchel again, lookpicked it, contained item turned in, finished.

**Comment by Vankie** [comment]
For me there's no logbook inside the satchel i'm done with this you refuse to provide any help whatsoever  with this bugged quest and you  show no sign of professionalism.

Good luck.
