### ISSUE TITLE
Easy Gold: Recipe can be bought unlimited times

### ISSUE THREAD

**Issue by padomu** [Looking4Group/L4G_Core#3403]
Hi,

the Recipe: Transmute Primal Might can only be bought once an hour in shattrath. Like it should be. But you can also buy it in Exodar., there, it doesn't have any timer at all.

You see here http://de.wowhead.com/npc=16705/altaa that it should have one. The (1) says it's a timer on it.

**Comment by AnonXS** [comment]
```
-- Recipe: Transmute Primal Might Restocktime
UPDATE `npc_vendor` SET `maxcount` = 1, `incrtime` = 9000 WHERE `item` = 23574; -- 43200
```

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3364/commits/bbac0cfe8162cf3d6464bab3dfe4122f5577c303
