### ISSUE TITLE
S1 items for honor and BG-badges?

### ISSUE THREAD

**Issue by ujellyx** [Looking4Group/L4G_Core#3406]
One NPC in Shattrath sells the S1-items for arena-points as it should be and the other one sells them for honor points and BG-badges - is this intentional? Makes no sense.
If it was S2 it would be okay to sell S1 for honor + badges, but having S1 both for honor and for arena points is kinda senseless...

IIRC there shouldn't even be vendors for arena gear in Shattrath.
Maybe one needs to check the vendors in nagrand/area52/gadgetzan, as i can't check them yet.

**Comment by AnonXS** [comment]
ty removed
