### ISSUE TITLE
Drakefist Hammer Not unique!

### ISSUE THREAD

**Issue by Cuddlychina** [Looking4Group/L4G_Core#3408]
The BS maces/1h weapons should be unique and was only made not unique after 2.4.2

**Comment by AnonXS** [comment]
By GenXCub (4,499 – 11·50) on 2008/05/14 (Patch 2.4.2)		
As of 2.4.2, this weapon is now no longer Unique and it is listed as One-hand, so you may offhand and/or dual wield.

Travins on 2007/05/31 (Patch 2.1.0)
I guess the big "Unique" faield to escape your view, and thse that gave you positive ratings. Unless there is some twisted way you would want to make the tier 1 upgrade it, then make the tier 1 again... sigh....

http://wowwiki.wikia.com/wiki/Patch_2.4.2 - not documented
