### ISSUE TITLE
Stratholme Holy Water

### ISSUE THREAD

**Issue by corbindallass** [Looking4Group/L4G_Core#3409]
Hi,
I was attempting to collect the holy water from Strat for my pally mount quest, however the boxes are not lootable.  I am a dwarf and they aren't showing up on the map either.  It's as if the boxes are just part of the artistic ambiance of the dungeon as opposed to an actual crate somebody should be able to loot.  I picked up the holy water quest to see if that would change anything but to no avail.  I logged out; I reset the instance; nothing.  If I'm doing something wrong please inform me, however if there is something wrong with the quest and or the crates themselves, it'd be awesome if that could be rectified, thanks!
-corbindallass (Icyklit, level 64 female dwarf paladin)

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/1800

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?object=182063
http://db.hellfire-tbc.com/?item=24284
