### ISSUE TITLE
Leotheras the Blind

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#341]
Originally reported by: **Anonymous**

----------------------------------------

Leotheras resettet bei 9% - ohne Grund - anbei der Screen da der Dämon, der in der Splittphase kommt noch vorhanden war obwohl der Boss resettet ist - passiert mehrmals - auch wenn man Ihn pult bzw. die Adds erst machen muss resetten diese ebenfalls kurz nach dem bosspull.

http://www0.xup.in/exec/ximg.php?fid=98207455

Raid musste nach mehrmaligen resetten abgebrochen werden. 

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/345

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2821
