### ISSUE TITLE
Warlock : Free books for pets 

### ISSUE THREAD

**Issue by SalaTKaratel** [Looking4Group/L4G_Core#3411]
Add price the books, they should cost money.

**Comment by AnonXS** [comment]
Can someone get me a complete list with item id and spellcost from the ingame addons as no db seems to hold the correct data for these books.

**Comment by SalaTKaratel** [comment]
No ur db gives the wrong information
http://db.excalibur.la/?npc=5815       Example.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3364/commits/ab8092ac4fd6222879ab72bc03b50c812eaac069
