### ISSUE TITLE
Quest "Oronu the Elder" 

### ISSUE THREAD

**Issue by Gabbsan** [Looking4Group/L4G_Core#3413]
Not a 100% chance to get questitem from the mob Oronu the Elder in shadowmoon valley. Killed twice now without a drop.

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?npc=21663
http://db.hellfire-tbc.com/?item=30649

**Comment by Saltgurka** [comment]
> By murshak (713 – 1·4) on 2008/04/26 (Patch 2.4.1)		
> I had to kill this NPC about eight times before i got the Orders from Akama...
> Still high droprate though...
> 
> Strange O_o

> By galad (1,392 – 1·12) on 2007/05/22 (Patch 2.1.0)		
> I've killed him twice, both time no orders, i have the quest, im confused, will update

http://www.wowhead.com/quest=10571/oronu-the-elder#comments:id=277646
