### ISSUE TITLE
bug char look video and screenshot need help me

### ISSUE THREAD

**Issue by ufojede** [Looking4Group/L4G_Core#3415]
hello my character's every bugla lognu when I wow and the game I'il fly to wherever the dragon of tanarisu at here plz help 
https://gyazo.com/f4418eaf6fd1649c0ba43cea1a45baa5
https://gyazo.com/1e427cd8fed0133213cc329dc47f43c9
https://gyazo.com/955a2128954fe22373fb419de61d2464
https://gyazo.com/369440425e0d4f5b5608ed557ac28316
https://gyazo.com/4e6da02d4086b49677a631708dc2916a
https://gyazo.com/d42f33e4f82705ceb23b21a753887337

**Comment by AnonXS** [comment]
Saw you yesterday, thought you were a hacker, waited for some feedback as it seemed you were not in control of what happened. :)

**Comment by ufojede** [comment]
yes me no no hacker bug tanaris Q black moras startt Q

**Comment by ufojede** [comment]
:)

**Comment by Xadras** [comment]
A GM should be able to help you ingame - please create an ingame ticket.
