### ISSUE TITLE
Make unstuck spell usable while moving

### ISSUE THREAD

**Issue by Saltgurka** [Looking4Group/L4G_Core#3419]
We should make the auto-unstuck spell usable while moving to remove some of the GM ticket load related to stuck characters (http://db.hellfire-tbc.com/?spell=7355)

Do we have any easy way to make a spell usable while moving? Some attribute we can just add? I wasn't able to find any.

Additionally, increase the cast time to prevent players abusing it to get away in PvP.

**Comment by AbaddonL4G** [comment]
since its using a teleportto function and not a spell its not that easy to modify the cast while moving and the timer (atleast not for me)

**Comment by AbaddonL4G** [comment]
okay its acutally casting 
Spell ID 7355
so just modify it :P

**Comment by AbaddonL4G** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3457
