### ISSUE TITLE
Warlock: cannot do the succubus quest

### ISSUE THREAD

**Issue by warlockpick** [Looking4Group/L4G_Core#3421]
Hi, for some reason I cannot pick up the succubus quest, anyone else got this issue or is it just my char? 
Yes I know what npc gives the quest, and yes I have double checked, and my char is currently at level 58 so it's not that Im too low level either. Please help

**Comment by Xadras** [comment]
The quest itself is ok.
Maybe you've already taken the first ones? I guess its better to contact a gm ingame who is able to verify if you've begun that quest already.

**Comment by warlockpick** [comment]
No response from gm's ingame when related to "bugs" :(

**Comment by AnonXS** [comment]
Quest works, just bring the hearts man! <3
