### ISSUE TITLE
Chat Channels Not Working

### ISSUE THREAD

**Issue by LooperCooper** [Looking4Group/L4G_Core#3422]
Every time I try and join a chat channel, it'll say I joined it but it doesn't actually put me in the channel. No matter if i leave then join again, it won't work. I really need this to work for LFG and such. Is this a bug? The fourms on Hellfire only told me to leave then join back but that hasn't worked. I've also placed a ticket in-game but that hasn't been answered yet either. :(

**Comment by Xadras** [comment]
Maybe caused by some addons or whatever? There is no general problem with this.

**Comment by SlyFoxUK** [comment]
Do you use /join LookingForGroup , in that exact format?

**Comment by tst12** [comment]
@Xadras server handle channels by name, client by name for number from dbc, for none En locales channel names are difders
@SlyFoxUK its work only for EnGb/EnUs

**Comment by AnonXS** [comment]
afaik you need to /join LookingForGroup and then change zone to make it take effect.
