### ISSUE TITLE
Incandescent Fel Spark in Hellfire Peninsula are not dropping Mote of Fire.

### ISSUE THREAD

**Issue by bialbert481** [Looking4Group/L4G_Core#3424]
Farming the Incandescent Fel Spark's in Throne of Kil'Jaeden I noticed they were only yielding Mote of Shadow instead of Mote of Fire. Vast spoke with me and mentioned at one point the loot table had both Mote of Shadow and Mote of Fire. Attached are some screen grabs of my looting of these Motes of Shadow as well as my current inventory. 

![image](https://cloud.githubusercontent.com/assets/25442492/24941865/714e3e7a-1f1b-11e7-927a-953db8357d01.png)

![image](https://cloud.githubusercontent.com/assets/25442492/24941845/58ae9630-1f1b-11e7-81b3-b9ce06c58762.png)

**Comment by bialbert481** [comment]
Adding a screenshot of my bags. 
![image](https://cloud.githubusercontent.com/assets/25442492/24941910/b9ae03bc-1f1b-11e7-846e-156a7be5e1e8.png)

**Comment by AnonXS** [comment]
http://wowwiki.wikia.com/wiki/Greater_Fel-Spark
http://wowwiki.wikia.com/wiki/Incandescent_Fel_Spark

**Comment by bialbert481** [comment]
Does this apply to the Incandescent Fel Spark as well as Enraged Fel Sparks? Enraged Fel Sparks are not in Throne of Kil'jaeden as of the current patch and Incandescent Fel Sparks are continuing to drop only Mote of Shadow.

**Comment by AnonXS** [comment]
It's the same mob, was renamed by blizzard.

**Comment by imchaotic** [comment]
Can confirm Incandescent Fel Sparks are still dropping Mote of Shadow. These should be dropping Mote of Fire.

http://db.hellfire-tbc.com/?npc=22323
