### ISSUE TITLE
Heroic dungeons keys - vendor wrong tooltip

### ISSUE THREAD

**Issue by Jalapan** [Looking4Group/L4G_Core#3425]
All the heroics keys have wrong tooltips and are highlighted as buyable even tho they are not.

You need revered to get the keys buy the tooltip says honored and as soon as you hit honored the item turns from red to available.

Fix and change tooltips to display revered instead of honored and dont make the keys go from red to available on item icon untill you hit revered

**Comment by Twizzerious** [comment]
Think that is on your side. Try deleting your Cache/WDB folder. You have old server information in ur cache

**Comment by Jalapan** [comment]
I have had multiple people verify this, just as a note. will try deleting Cache/WDB and reply with results
