### ISSUE TITLE
Unmineable Small Thorium Vein in Tanaris.

### ISSUE THREAD

**Issue by TherealTolly** [Looking4Group/L4G_Core#3426]
![wowscrnshot_041217_113445](https://cloud.githubusercontent.com/assets/26859398/24951284/248d7070-1f74-11e7-8d94-f109bdc45f27.jpg)
![wowscrnshot_041217_113451](https://cloud.githubusercontent.com/assets/26859398/24951285/24905a6a-1f74-11e7-8ee8-4770d7b79722.jpg)

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2717
