### ISSUE TITLE
Ubrs -  events and doors dont work - important for druid tanks

### ISSUE THREAD

**Issue by Ike86542** [Looking4Group/L4G_Core#3427]

**Comment by AnonXS** [comment]
We will see on next restart of there are more gos in ubrs to be removed.
https://github.com/Looking4Group/L4G_Core/pull/3364/commits/93237e664e0c787f0e2366a349e3fdf42d9f2fe6

**Comment by Ike86542** [comment]
Thanks for looking in to it, i am new to this bugtracker thing, how can i find out if the problem is fixed?

**Comment by AnonXS** [comment]
Anymore Feedback?
