### ISSUE TITLE
Mage: Clearcasting (consuming) 

### ISSUE THREAD

**Issue by Blackari** [Looking4Group/L4G_Core#3435]
Mage's Clearcasting talent consuming is absolutely bugged. 
One time it is not consumed by some spells, other time it is consumed by spell but also it costs mana, sometimes spell does not cost mana but buff isnt consumed. Even counterspell (which should not consume it) consumed the clearcasting buff please fix it, it is really efficient and I would say important talent for fire during leveling and even in endgame.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3443
