### ISSUE TITLE
Spectrecles and pets

### ISSUE THREAD

**Issue by tst12** [Looking4Group/L4G_Core#3441]
http://db.hellfire-tbc.com/?item=30719
aura applies only to owner so pets cant normal detect and attack

**Comment by tst12** [comment]
https://github.com/Looking4Group/L4G_Core/issues/3398
what's the point of closing if origin issue is closed and not fixed?

**Comment by AnonXS** [comment]
Origin Issue: https://github.com/Looking4Group/L4G_Core/issues/1630

**Comment by tst12** [comment]
https://www.youtube.com/watch?v=EiktzNc2qdU
https://www.youtube.com/watch?v=x7NqsPRjDBw
