### ISSUE TITLE
Unnecessary spawns

### ISSUE THREAD

**Issue by tst12** [Looking4Group/L4G_Core#3444]
```
-- Mutanus the Devourer spawned via script
DELETE FROM creature WHERE id=3654;

-- Ishamuhale spawned via http://db.hellfire-tbc.com/?item=10338
DELETE FROM creature WHERE id=3257;
```

**Comment by AnonXS** [comment]
http://www.wowhead.com/npc=3654/mutanus-der-verschlinger, http://wowwiki.wikia.com/wiki/Mutanus_the_Devourer

https://github.com/Looking4Group/L4G_Core/blob/master/src/scripts/scripts/zone/wailing_caverns/wailing_caverns.cpp#L265

---

http://db.hellfire-tbc.com/?item=10338, http://db.hellfire-tbc.com/?spell=12199 prob Send Event (2998)
