### ISSUE TITLE
Bale

### ISSUE THREAD

**Issue by Gr33disgood** [Looking4Group/L4G_Core#3447]
The Vendor Bale got the wrong selling table
He should sell Charred Bear Kabobs and Juicy Bear Burger but he doesnt

**Comment by AnonXS** [comment]
http://wowwiki.wikia.com/wiki/Charred_Bear_Kabobs
Patch 2.4.0 (25-Mar-2008): Added

http://wowwiki.wikia.com/wiki/Juicy_Bear_Burger
Patch 2.4.0 (25-Mar-2008): Added

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/3538
