### ISSUE TITLE
Warlock/Mage: Ritual of Souls/Refreshment

### ISSUE THREAD

**Issue by Iammoot** [Looking4Group/L4G_Core#3452]
If a warlock/mage moves or otherwise interrupts their own channel of Ritual of Souls/Refreshment after the soulwell/table has been spawned, the cooldown does not properly trigger and requires a relog or reload to fix. 

* The cooldown is activated properly if one of the assisting channelers moves or otherwise interrupts the channel.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/304
