### ISSUE TITLE
Knothide Quiver

### ISSUE THREAD

**Issue by swarlee** [Looking4Group/L4G_Core#3454]
Are Knothide Quiver and Knothide Ammo Pouch not in the game?
Can't learn them at the trainer.

**Comment by tst12** [comment]
get it from faction vendors

**Comment by swarlee** [comment]
no one sells it...

**Comment by tst12** [comment]
they sell reciepe

**Comment by AnonXS** [comment]
These Quivers are not ingame atm: 34200,34201,34218
