### ISSUE TITLE
"Rescue from prison" quests in group does not register for all group members.

### ISSUE THREAD

**Issue by adnanberberovic** [Looking4Group/L4G_Core#3455]
This is quite a serious issue since every group member has to wait for the prisoner to respawn, even though everyone has acquired the key.

Most prominent in the quest chain with Corki, all three quests has this recurring.

**Comment by Saltgurka** [comment]
http://db.hellfire-tbc.com/?quest=9923
http://db.hellfire-tbc.com/?quest=9924
http://db.hellfire-tbc.com/?quest=9955
