### ISSUE TITLE
Enchanting spell "Small Prismatic Shard" does not exist in game?

### ISSUE THREAD

**Issue by adnanberberovic** [Looking4Group/L4G_Core#3459]
http://db.hellfire-tbc.com/?spell=42615

The formula is supposed to be taught by Johan Barnes among others, but I do not see it in his list of spells.
Was the spell removed to prevent blood elves from having an advantage?

**Comment by Saltgurka** [comment]
Added in 2.2.0
http://wowwiki.wikia.com/wiki/Patch_2.2.0
