### ISSUE TITLE
Shaleskin Flayer Magic Resistance

### ISSUE THREAD

**Issue by Jwest13** [Looking4Group/L4G_Core#3462]
The Shaleskin Flayers outside Area 52 sometimes have a buff called, Shale Skin, which reads "the Shaleskin Flayer has a 50% resistance to Magical Damage".  In my testing however, these buffed Shaleskins have complete immunity to magical damage, however they can still receive magical debuffs and be dispelled.  Dispel Magic works fine to fix this issue in the short term, but prevents other classes with magical damage from killing these monsters.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/1493
