### ISSUE TITLE
Forced Dismount when walking over objects on ground

### ISSUE THREAD

**Issue by wb1234** [Looking4Group/L4G_Core#3465]
I noticed that i am constantly being dismounted when walking over objects on the ground.

This is most noticeable in Tanaris around the runes while completing the water packet quest.

Not sure if this is all over the world because I recently purchased my mount. 

Please fix.

**Comment by AnonXS** [comment]
Source, these are Indoors Objects obviously which make you dismount.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2817, maybe not even an issue in this case, needs research.
