### ISSUE TITLE
Wastewander Mobs in Tanaris - Vanilla Content

### ISSUE THREAD

**Issue by Kridx** [Looking4Group/L4G_Core#3467]
Wastewander Rogues do not use backstab ability http://db.vanillagaming.org/?npc=5615#abilities
https://i.gyazo.com/68d0939c9aaa6a6ff40223e37cb8ceb6.jpg

Wastewander Shadow Mage(http://db.vanillagaming.org/?npc=5617) almost never uses spells, it acts more like a melee mob. It casts immolate but VERY rarely. Should cast shadowbolts all the time
http://db.vanillagaming.org/?spell=12746 summoned voidwalker pet only does 6-7 damage and on some spawns, there's 5-6 voidwalkers PER shadow mage.
I'm also pretty sure the voidwalkers aggro should be linked to its owner, the mage npc. Right now you can single pull the mages

**Comment by Kridx** [comment]
Should be an easy db fix for @AnonXS

**Comment by AnonXS** [comment]
```
UPDATE `creature_template` SET `faction_A` = 16, `faction_H` = 16 WHERE `entry` = 8996;

UPDATE `creature_ai_scripts` SET `event_param1` = 5000, `event_param2` = 5000 WHERE `id` = 561701;
UPDATE `creature_ai_scripts` SET `event_param1` = 0 WHERE `id` = 561703;
UPDATE `creature_ai_scripts` SET `action1_param1` = 1 WHERE `id` = 561702;

DELETE FROM `creature_ai_scripts` WHERE `entryOrGUID` = 5615;
INSERT INTO `creature_ai_scripts` VALUES
('561501','5615','1','0','100','0','1000','1000','0','0','11','22766','0','32','0','0','0','0','0','0','0','0','Wastewander Rogue - Cast Sneak OOC'),
('561502','5615','9','0','100','1','0','5','6000','10000','11','8721','1','0','0','0','0','0','0','0','0','0','Wastewander Rogue - Cast Backstab'),
('561503','5615','2','0','100','0','15','0','0','0','25','0','0','0','1','-47','0','0','0','0','0','0','Wastewander Rogue - Flee at 15% HP');
UPDATE `creature_addon` SET `auras` = NULL WHERE `guid` IN (23464,23465,23466,23467,23470,23471,23475,23479,23480,23482,23483,23484,23485,23486,23487,23488,23489,23490,23491,23492,23493,92063,92413);
```

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3364/commits/64b84acd3e89981d25f4b211a7e33a55705410d8
