### ISSUE TITLE
Area 52 Bug/Guards

### ISSUE THREAD

**Issue by Jwest13** [Looking4Group/L4G_Core#3468]
A warlock attacked me while I was reading a quest inside area 52 and the guards killed both of us.

**Comment by AnonXS** [comment]
Your Class, All Spells involved

**Comment by Jwest13** [comment]
My class: priest, defending spells: inner fire, PW Fortitude, renew, flash heal, PW shield.

Attacker: affliction warlock, attacking spells: siphon life, corruption, Curse of agony, Unstable affliction, Voidwalker pet melee

The guards attacked me before I started healing myself.

**Comment by AnonXS** [comment]
Well probably the healing shielding as self healing after getting damaged counts as act of attack.

**Comment by Jwest13** [comment]
I was attacked by a BM hunter's pet and ran into a different neutral area in Netherstorm healing and shielding myself.  The goblin area near Tempest Keep was where this took place.  When I ran into aggro range, those goblins ran over and killed the pet while I healed myself, leaving me alone before and after they killed the Hunter pet.

**Comment by AnonXS** [comment]
http://wowwiki.wikia.com/wiki/Guard
Guards are tagged for PvP combat and automatically attack players of the enemy faction on sight, regardless of whether PvP is enabled on the player. They also attack hostile creatures that come nearby. 

As for these neutral city guards, they will attack whoever player is engaged in pvp combat. but this behavior might not be right. I want to have a more detailed report about guard behavior, so we can discuss
