### ISSUE TITLE
Mog'dorg the Wizened Quest in BEM

### ISSUE THREAD

**Issue by meckyy** [Looking4Group/L4G_Core#3469]
Quest mob Mog'dorg on his tower at the pvp arena not there and with him mostly all grp quests in BEM not accessable....

**Comment by AnonXS** [comment]
http://wow.gamepedia.com/Mog%27dorg_the_Wizened
http://wowwiki.wikia.com/wiki/Mog%27dorg_the_Wizened
http://wowwiki.wikia.com/wiki/Quest:Mog%27dorg_the_Wizened
http://de.wowhead.com/npc=22941/mogdorg-der-weise#english-comments

Added in 2.1 together with Ogrila
