### ISSUE TITLE
Master of Elixirs - Unable to complete

### ISSUE THREAD

**Issue by Libina1** [Looking4Group/L4G_Core#3470]
So I completed my alchemist specialization (elixirs) some time ago. I then read online if you unlearned it for 150g you would be able to choose any other alchemy specialization without the prequest. I unlearned it, however, the 150g never got removed from my inventory. I couldn't learn another alchemy specialization without the prequest (not sure if this is something you are supposed to be able to) so I decided to pick up Master of Elixirs again. I gathered all the needed items but I am unable to turn the quest in even though I have all the stuff I need.

- Respec didn't cost 150g even though it said so
- Couldn't learn another specialization without the prequest *not sure if you are supposed to
- Can't complete the quest Master of Elixirs a second time.

**Comment by Libina1** [comment]
After abandoning the quest while leaving the essences of infinity in my bank so they wouldn't get destroyed I was able to pick up the quest again and complete it.

**Comment by AnonXS** [comment]
Questitems gathered for a quest while having the quest dont get destroyed on abandoning, only quest provided items get removed. I guess this was a case of this bug then, quest not completeable even though you have all needed items.

All together Dublicate of https://github.com/Looking4Group/L4G_Core/issues/404
