### ISSUE TITLE
Incorrect spell on Coilfang Enchantress(Slave Pens)

### ISSUE THREAD

**Issue by Heyitsbored** [Looking4Group/L4G_Core#3471]
It appears Coilfang Enchantress posses the spell Domination(http://www.wowhead.com/spell=30923/domination), even though it should only be cast by Coilfang Soothsayers. This was occuring on heroic, did not check normal. Reproduced multiple times.
http://www.wowhead.com/npc=17961/coilfang-enchantress#abilities:mode=heroic
http://db.hellfire-tbc.com/?npc=17961#abilities

**Comment by AnonXS** [comment]
http://www.wowhead.com/npc=17961/coilfang-enchantress#comments
By Dungeon (1,357 – 3·10) on 2007/02/03 (Patch 2.0.6)		
Mindcontrol like the Coilfang Soothsayers, very annoying
