### ISSUE TITLE
Underbog Lurkers not properly losing enrage buff

### ISSUE THREAD

**Issue by Iammoot** [Looking4Group/L4G_Core#3473]
Underbog Lurkers gain an enrage buff upon being pulled that should be lost after reaching 50% hp. At present, the enrage is not dropping at all in heroic mode.

**Comment by AnonXS** [comment]
Source

**Comment by Iammoot** [comment]
I can't find a source confirming my belief. All sources merely indicate that it "lasts for a short duration."
