### ISSUE TITLE
Invalid target Fel Iron Deposit

### ISSUE THREAD

**Issue by TherealTolly** [Looking4Group/L4G_Core#3482]
![wowscrnshot_041517_105417](https://cloud.githubusercontent.com/assets/26859398/25062271/e16060f2-21c9-11e7-9e57-208ac2a9f323.jpg)
![wowscrnshot_041517_105423](https://cloud.githubusercontent.com/assets/26859398/25062270/e15fed16-21c9-11e7-9051-7dc3720017b1.jpg)

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2717
