### ISSUE TITLE
Druid/Spell - Abolish Poison

### ISSUE THREAD

**Issue by Ike86542** [Looking4Group/L4G_Core#3484]
If a player has the abolish poison buff and no poison on him, the next time abolish poison trys to remove a poison it disappaers, even when there is 6 seconds left

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/2c12da8262077b179faf3a23ced7d1ecca273c94

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/85e08801359fafbfc63ea8f47bcbfa0165f74886
