### ISSUE TITLE
Colonel Jules doesnt work for some....

### ISSUE THREAD

**Issue by GrimLox** [Looking4Group/L4G_Core#3486]
Heya!

Quest http://www.wowhead.com/quest=10935/the-exorcism-of-colonel-jules
Problem: Quest doesnt work for some peeps but for others. Very strange idd but i can get it to complete and have tried it 5times changing alot of stuff like, addons, cache, abondon, relog etc.
Still when i finished the q even using necklace and killing all flying "skulls" etc. i wont get the complete anyways.

PLS SOLV! <3

//Grim

**Comment by honeyhoney** [comment]
I think every single time I've seen someone unable to complete it it has been due to user error. You need to talk to Jules when they are on the bed after the exorcism to get credit.

**Comment by GrimLox** [comment]
Thx alot m8! <3 

It actually worked when i had all my addons disabled and was targeting Jules in the end of the exorcism and then leftclicked on him several times.

Most likely addon issues before and this can be closed since it had nothing to do with scripts but it was at my end. 

Keep the good work going and continue to create the best TBC server <3
