### ISSUE TITLE
Holy nova aggro

### ISSUE THREAD

**Issue by chocochip95** [Looking4Group/L4G_Core#3490]
Hi, at the moment Holy Nova (priest spell) http://db.hellfire-tbc.com/?spell=15237 seems to give threat, when it shouldn't.

**Comment by AnonXS** [comment]
Source

**Comment by chocochip95** [comment]
Tooltip of the spell "Causes an explosion of holy light around the caster, causing 28 to 33 Holy damage to all enemy targets within 10 yards and healing all party members within 10 yards for 52 to 61**. These effects cause no threat.**

**Comment by honeyhoney** [comment]
It is worth noting that Holy Nova should generate threat if the target in question is currently out of combat.

**Comment by AnonXS** [comment]
https://bitbucket.org/oregon/oregoncore/commits/135b4930594f

```

https://github.com/Looking4Group/L4G_Core/blob/master/src/game/SpellMgr.cpp#L2984

+else if (spellInfo->SpellFamilyFlags & SPELLFAMILYFLAGHOLYNOVA
+    spellInfo->AttributesEx |= SPELL_ATTR_EX_NO_THREAT;
```

**Comment by Xadras** [comment]
else if (spellInfo->SpellIconID == 1874)  //Holy Nova
                    spellInfo->AttributesEx |= SPELL_ATTR_EX_NO_THREAT;

**Comment by AnonXS** [comment]
Issue has been resolved, even if holy nova as such could still be discussed more with its interaction with threat.
