### ISSUE TITLE
Charge & Intercept pathing.

### ISSUE THREAD

**Issue by Antss3** [Looking4Group/L4G_Core#3491]
I have a bit over 2 days /played on my warrior now and I constantly see the same problem occurring. Charge and intercept both have a tendency to either go into the wrong direction or not connect with the target. I have only once fell through the terrain so props for that, but the pathing on these spells need to be fixed specially for pvp.

**Comment by miraco** [comment]
Maybe this can help:
https://bitbucket.org/Caboon/playcore-official/commits/4d931338dd51da25cb56ada5cd3772d7d528a19f?at=default

**Comment by Jalapan** [comment]
would have been great to have it fixed.

**Comment by tst12** [comment]
@miraco I think cant

**Comment by AnonXS** [comment]
Dubliacte https://github.com/Looking4Group/L4G_Core/issues/677
