### ISSUE TITLE
The Quest "The Attack!"

### ISSUE THREAD

**Issue by demon1113** [Looking4Group/L4G_Core#3494]
I don't know if anyone has posted this or not. But the quest The Attack! in stormwind where u get the Seal of Wrynn. Every time the guys come out and they get aggressive, the guards from the Library portion come out and instant kill the two mobs, so i can't get a complete because i'm not killing them myself.

Thanks

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3364/commits/8afb85d7b376c80b6ab00a973a0651333a380bb2
