### ISSUE TITLE
Paladin Illumination talent - should offer 100% mana return. currently wrong value (patch 2.1+)

### ISSUE THREAD

**Issue by Jalapan** [Looking4Group/L4G_Core#3497]
Before Patch 2.1, the Illumination talent offered a 100% mana return. However, it was nerfed to 60% and thus changed the stat priority for Paladins in some people's opinions. Some remain adamant that even despite the nerf, stacking spell crit is better for longetivity because even without the 100% mana return it is more efficient than a constant mana per 5 second (MP5) bonus. Others argue that since it does not return the full mana cost you will burn through your mana much more quickly using Holy Light and thus MP5 is the best way to overcome this nerf.

Since we play patch 2.0 shouldnt this be changed?

**Comment by tst12** [comment]
20 mostly for PvE, players spells and talents from 2.4.3

**Comment by AnonXS** [comment]
We play on 2.0 Content with 2.4.3 Talents.

**Comment by AbaddonL4G** [comment]
dbcs are 2.4.3 and most fixes for class mechanics are 2.4.3 aswell.

and since the "never oom" paladin was nerfed on purpose we wont change it
