### ISSUE TITLE
Deathforge Tinkerer's Melee DMG

### ISSUE THREAD

**Issue by Jwest13** [Looking4Group/L4G_Core#3499]
I am being white melee hit for 1500 damage per swing by these little guys inside Shadowmoon Valley.  The melee guards next to them melee me for about 250 or so.  Seems overtuned.  I am a cloth wearing Shadow Priest.

**Comment by Jwest13** [comment]
Actually the nearbye demons with drill arms are critting me for 190

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?npc=19754

**Comment by Jwest13** [comment]
I am not being crit.  These are 1300-1500 melee hits.

**Comment by AnonXS** [comment]
As suspected its their bombs that just explode for 1k damage if not outranged.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3614/commits/0e8d3466b1ead0828e9aacf61e20b2099269f7b1
