### ISSUE TITLE
Pickpocket/stealth bug

### ISSUE THREAD

**Issue by Joall123** [Looking4Group/L4G_Core#3501]
Often when using sap/pickpocket your character instead enters combat and fails it all instead of success. Really annyoing and would love to see this resolved. Please

**Comment by AnonXS** [comment]
http://wowwiki.wikia.com/wiki/Pick_Pocket
If the skill is resisted, the monster immediately detects the rogue and aggros. Failure rates depend on relative levels, but the base failure rate seems to be around 5%.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/979
