### ISSUE TITLE
Sharth Voldoun and Stonegazer in Terokkar have an unusually long respawn timer

### ISSUE THREAD

**Issue by Zarant** [Looking4Group/L4G_Core#3507]
Sharth Voldoun (http://db.hellfire-tbc.com/?npc=18554) and Stonegazer (http://db.hellfire-tbc.com/?npc=18648) have respawn timers of 25 and 40 minutes respectively.

Wowhead comments from patch 2.0 indicates that Sharth Voldoun have a respawn timer of about 3-4 minutes (http://www.wowhead.com/npc=18554/sharth-voldoun#comments:id=83465) and Stonegazer have a 8-9min respawn timer (http://www.wowhead.com/npc=18648/stonegazer#comments:id=33647)

**Comment by AnonXS** [comment]
Stonegazer: https://github.com/Looking4Group/L4G_Core/blob/3753208fbfb1f688eea981ae3048b9ec58136472/sql/updates/world/091_4_2.sql#L2

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3364/commits/ad3bbc174a896ef54dc449791f85fd267e6c5345
