### ISSUE TITLE
Bug with my rogue quests

### ISSUE THREAD

**Issue by YoungPleb** [Looking4Group/L4G_Core#3508]
So I might be a bit on the retarded side but I think im experiencing bugs with my rogue class quests. I am having trouble with the quests "Pludering the Plunderers" and "Tools of the Trade", So with the Plundering quest the problem is that the decription says that I should go to Wrenix's Giz,ptrpmoc Apparatus to get an E.C.A.C. and Thieves' Tools. The problem is that whenever I talk to him he says following "The machine comes alive at your touch." I can't get any quest required items from him. 
And that is pretty much the same deal with the other quest "Tools of the Trade", I am supposed to go to Estelle Gendry to pick up a set of tools, when I go talk to her she says some nonsense and that is that.
Hopefully you can help me, maybe I'm just retarded and doing something wrong but I'm pretty sure its just some sort of bug,
Thanks, have a great day.

**Comment by Madnomadin** [comment]
I had the same problem, what i realised is that you dont need those tools to complete the quest at all, just buy thieves tools from a vendor and you can do it without

**Comment by YoungPleb** [comment]
Thanks :+1:

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/3503
