### ISSUE TITLE
Acid spit ability from Ghaz'an in normal underbog is not a single target ability

### ISSUE THREAD

**Issue by Zarant** [Looking4Group/L4G_Core#3512]
In normal Underbog Ghaz'an uses an acid spit ability that targets all party members. This is an heroic only mechanic i assume, this ability should be single target on normal difficulty.

Source: https://www.youtube.com/watch?v=esATfmXsHKQ
This video is from retail tbc and at the 44 second mark the mage gets hit by this ability but no one else in the party takes any damage.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2144
