### ISSUE TITLE
Ethereal Sorcerer's Summon Arcane Fiend spell behavior in normal mana tombs

### ISSUE THREAD

**Issue by Zarant** [Looking4Group/L4G_Core#3513]
Ethereal sorcerers (http://db.hellfire-tbc.com/?npc=18313) casts their summon arcane fiend way too often, he usually casts it whenever the add is killed and they only summon one add, instead of two.

Source: https://www.youtube.com/watch?v=fRphSZKeAgc
In this video, the fight starts at 2:07, the ethereal sorcerer summon 2 adds at least 10 seconds into the fight, possibly more since there is no footage of the actual pull, and he doesn't cast it again for the whole duration of the fight (about 40s). Which strongly suggests that this ability have some sort of cooldown.
I also noticed that Ethereal Spellbinders have the exact same behavior with their Summon Ethereal Wraith spell, which have no cooldown, it feels wrong and I suspect is also a bug, but its hard to dig enough evidence to support this claim.

**Comment by AnonXS** [comment]
- [ ] Change Amount of Adds summoned to 2 and Increase Cooldown.

**Comment by AnonXS** [comment]
Ethereal Sorcerer's in Heroic difficulty will summon Arcane Fiends less frequently.
http://wowwiki.wikia.com/wiki/Patch_2.1.0
