### ISSUE TITLE
Warrior Two-Handed sword skill not increasing

### ISSUE THREAD

**Issue by Lilybana** [Looking4Group/L4G_Core#3515]
No matter what weapon I use, my 2h sword skill doesn't seem to level at all, even after grinding for 30 minutes it didn't seem to increase once.

**Comment by boom8866** [comment]
Reassemble, and then find a creature of the same rank

**Comment by Lilybana** [comment]
reassemble?

**Comment by AnonXS** [comment]
No Real info provided, seems to be working fine in general.
