### ISSUE TITLE
Pristine Black Diamond - Suggestion

### ISSUE THREAD

**Issue by ilaeli** [Looking4Group/L4G_Core#3516]
I specifically moved to this server from Elysium to play my favorite combo of all time the BE Paladin. I got to work on my epic awesome Paladin mount as soon as I could only to find out that one specific reagent was all but impossible to obtain.

Many other players would be very happy if you were to find some type of workaround for the Pristine Black Diamond as the drop rate is negligible, the population isn't that high, and it's a TBC server so people don't run old content much.

I beg you please find some way to balance this and at least make it possible for all Horde Paladins to have access to something that is special to their race/class combo.

Thank you

**Comment by boom8866** [comment]
The problem is, some creatures don't fall
http://db.hellfire-tbc.com/?item=18335
You can see whether these creatures fall

**Comment by ilaeli** [comment]
No I'm saying the drop rate is incredibly low for a low population TBC server that does not have people that run level 60 content.. Therefore NO Paladins can get their diamond making it a complete waste of money and time for those that tried to get it.

**Comment by corbindallass** [comment]
I don't believe in giving it to us (I'm a pally on this server as well who was been farming for around 10 days) for free or really even increasing the drop rate.  I'm just becoming skeptical that it actually does drop.  I've picked up 4 travelers backpacks (average .5% chance to drop) and picked up or seen while in a group 7 epics drop.  Each of which has a .025% chance of dropping.  On average (not counting Alterac Valley mobs) the pristine black diamond has about a .2%-.5% chance of dropping, depending on where you are farming.  I should be finding 8 diamonds per epic that drops, not the other way around.  I had put in a ticket a few days ago about this, and was told it is a legitimate item that can drop; however with numbers like these (and I'm obviously not alone) it's starting to look a little fishy.  Not to mention, I haven't seen a single Alliance paladin with their mount, nor have I heard of anybody obtaining a diamond.  GL to all the farmers out there.

**Comment by AnonXS** [comment]
It does drop, we are discussing the general increase of droprate for this item.

**Comment by ilaeli** [comment]
I know that there is a concern for priorities in development but this change seems like a minor tweak that could be easily implemented and would be greatly appreciated by all of us paladin players.

Please consider increasing the drop rate of the item to something that is at least possible as soon as you are able.

Thank you so much for caring about your player base.

**Comment by boom8866** [comment]
DELETE FROM `creature_loot_template` WHERE `item` = 18335;
INSERT INTO `creature_loot_template` VALUES (1788, 18335, 1.1176, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (1805, 18335, 1.0583, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (1832, 18335, 1.1589, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (1836, 18335, 1.18, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (1843, 18335, 1.51, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (1846, 18335, 1.1504, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (1852, 18335, 1.5789, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (7072, 18335, 1.03, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (7461, 18335, 1.1103, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (7463, 18335, 1.1436, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (7665, 18335, 1.8065, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (7667, 18335, 1.8403, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (7734, 18335, 2.16, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (8716, 18335, 2.12, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (8717, 18335, 1.8287, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9197, 18335, 1.0631, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9216, 18335, 1.1997, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9241, 18335, 1.1102, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9259, 18335, 1.1774, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9260, 18335, 1.32, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9261, 18335, 1.215, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9262, 18335, 1.0715, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9263, 18335, 1.3132, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9264, 18335, 1.1885, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9265, 18335, 1.1457, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9266, 18335, 1.2484, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9268, 18335, 1.2906, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9269, 18335, 1.1463, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9448, 18335, 1.1407, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9583, 18335, 1.204, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9692, 18335, 1.1247, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9693, 18335, 1.2042, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9716, 18335, 0.1095, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9717, 18335, 1.2222, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9817, 18335, 1.1932, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9818, 18335, 1.2484, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (9819, 18335, 1.3806, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10201, 18335, 1.2, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10316, 18335, 1.3034, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10317, 18335, 1.4842, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10318, 18335, 1.2875, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10319, 18335, 1.165, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10381, 18335, 1.093, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10382, 18335, 1.1362, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10384, 18335, 1.1681, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10385, 18335, 1.0935, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10390, 18335, 1.38, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10391, 18335, 1.037, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10394, 18335, 1.1255, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10398, 18335, 1.1727, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10399, 18335, 1.2338, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10400, 18335, 1.15, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10405, 18335, 1.1525, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10406, 18335, 1.1223, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10407, 18335, 0.062, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10414, 18335, 1.0932, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10416, 18335, 1.0691, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10417, 18335, 1.1316, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10418, 18335, 1.1968, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10419, 18335, 1.1359, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10420, 18335, 1.1263, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10421, 18335, 1.19, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10422, 18335, 1.213, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10423, 18335, 1.3114, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10424, 18335, 1.1431, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10425, 18335, 0.1422, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10426, 18335, 1.1578, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10463, 18335, 1.0631, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10464, 18335, 1.28, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10469, 18335, 1.1214, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10470, 18335, 1.139, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10471, 18335, 1.1208, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10476, 18335, 1.1838, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10477, 18335, 1.1051, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10478, 18335, 1.0765, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10486, 18335, 1.2315, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10487, 18335, 1.2413, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10488, 18335, 1.1462, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10489, 18335, 1.1222, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10491, 18335, 1.1534, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10495, 18335, 1.1529, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10498, 18335, 1.1276, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10499, 18335, 1.0574, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10500, 18335, 1.071, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10680, 18335, 1.1592, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10681, 18335, 0.3686, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10742, 18335, 1.3325, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10762, 18335, 1.321, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (10996, 18335, 1.2288, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11032, 18335, 1.44, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11043, 18335, 1.2052, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11257, 18335, 1.2488, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11284, 18335, 1.3023, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11338, 18335, 1.0784, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11339, 18335, 1.4358, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11340, 18335, 1.299, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11350, 18335, 1.3162, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11351, 18335, 1.2619, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11352, 18335, 1.3014, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11353, 18335, 1.0322, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11356, 18335, 1.3214, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11387, 18335, 1.4785, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11388, 18335, 1.04, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11391, 18335, 1.5747, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11441, 18335, 1.1557, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11444, 18335, 1.1621, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11445, 18335, 1.4938, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11448, 18335, 0.2054, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11450, 18335, 1.0833, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11452, 18335, 1.1399, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11453, 18335, 1.1876, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11456, 18335, 1.1585, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11457, 18335, 1.1232, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11469, 18335, 1.46, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11470, 18335, 1.1946, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11471, 18335, 1.34, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11472, 18335, 0.1531, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11473, 18335, 1.1651, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11475, 18335, 1.278, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11582, 18335, 1.2203, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11657, 18335, 1.34, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11679, 18335, 0.14, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11830, 18335, 1.1803, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11831, 18335, 1.98, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11878, 18335, 1.56, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11898, 18335, 1.0773, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11947, 18335, 1.0415, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (11949, 18335, 1.048, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (12051, 18335, 1.0427, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (12128, 18335, 1.4, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (12156, 18335, 1.04, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (12157, 18335, 1.22, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (12158, 18335, 1.56, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (12339, 18335, 1.43, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (12396, 18335, 1.24, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (12457, 18335, 1.2181, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (12459, 18335, 1.5468, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13137, 18335, 1.155, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13138, 18335, 1.0457, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13139, 18335, 2.3063, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13140, 18335, 2.1369, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13143, 18335, 2.0464, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13144, 18335, 2.0505, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13145, 18335, 2.0464, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13146, 18335, 2.0383, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13147, 18335, 1.1374, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13152, 18335, 1.1382, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13153, 18335, 1.1769, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13154, 18335, 1.047, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13176, 18335, 1.08, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13179, 18335, 1.114, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13180, 18335, 1.31, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13181, 18335, 1.29, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13236, 18335, 1.96, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13284, 18335, 1.2, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13296, 18335, 1.1543, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13297, 18335, 1.0506, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13298, 18335, 2.46, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13299, 18335, 2.0433, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13300, 18335, 1.0619, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13318, 18335, 1.0699, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13319, 18335, 2.1004, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13320, 18335, 1.0487, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13437, 18335, 2.16, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13438, 18335, 1.88, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13440, 18335, 1.42, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13441, 18335, 1.94, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13443, 18335, 1.1855, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13447, 18335, 1.13, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13448, 18335, 2.36, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13449, 18335, 1.58, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13526, 18335, 2.34, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13530, 18335, 1.46, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13531, 18335, 2.5, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13576, 18335, 0.18, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13577, 18335, 0.05, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13797, 18335, 2.0585, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13957, 18335, 2.2, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (13996, 18335, 0.1756, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (14351, 18335, 2.16, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (14518, 18335, 1.72, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (14519, 18335, 1.67, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (14520, 18335, 1.5, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (14521, 18335, 1.94, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (14750, 18335, 1.4283, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (14825, 18335, 1.2584, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (14882, 18335, 2.2662, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (14883, 18335, 2.2188, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (15111, 18335, 1.2144, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (15591, 18335, 2.218, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (15980, 18335, 1.1886, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (15981, 18335, 1.1211, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (16020, 18335, 2.05, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (16022, 18335, 2.0718, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (16145, 18335, 2.0796, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (16154, 18335, 2.1376, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (16163, 18335, 2.1316, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (16193, 18335, 2.2674, 0, 1, 1, 0, 0, 0);
INSERT INTO `creature_loot_template` VALUES (16368, 18335, 1.1284, 0, 1, 1, 0, 0, 0);

Try to increase the odds of 1%

**Comment by corbindallass** [comment]
Not sure what that means...

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3364/commits/49a4b001bdd61bc8b997bd02c5bd53cd19fa507d

**Comment by boom8866** [comment]
@corbindallass  This is a very good team, they will adopt a better opinion
