### ISSUE TITLE
Tanks getting hit with Enfeeble on Prince Malchezar in Kara

### ISSUE THREAD

**Issue by Twizzerious** [Looking4Group/L4G_Core#3518]
Ran Kara this week and ran into a bug that we dont think was there last week. 

https://www.twitch.tv/videos/135967851

About 1:05 in, tank gets hit with enfeeble. It does NOT apply the healing debuff to the tank but knocks him down to 1 hp. Luckily we recovered thanks in part mostly to our tanks gear (he has alot of avoidance and was able to dodge the attacks after enfeeble) and our healers being able to top him off before the nova. If you watch you can see that before the enfeeble he doesnt get hit from alot of damage (his SCT doesnt show any big damage prior to being knocked to 1 hp) he just gets knocked down to 1 hp. 

This did not occur on our first prince kill last week, dont know what changed. Our other Kara group also did not have this happen to them on their first prince kill.

This is definitely a bug and a big one. A lesser geared raid would not be able to rely on a dodge/parry to keep him alive and their healers to top their tank off before the nova after being enfeebled. This would even wipe a geared raid if rng is not in their favor and prince hits the tank RIGHT after the enfeeble. Especially dangerous during phase 2 when he his weapons are out (had it happen to us 3:15 in vod)

Sorry for the twitch vod but its all we got for proof of what happened.

Instances of occurrence:
1:05
1:30
3:15

**Comment by miraco** [comment]
You can also see that the hunter is over the druid in thread
In the script its just looking rnd except the highest thread, the hunter were higher den the druid thats why the tank got it.

But if i remember right this were and issue on retail too.

**Comment by Kridx** [comment]
I dont remember tanks ever getting enfeeble on old L4G at least

**Comment by Twizzerious** [comment]
@miraco good catch i didnt notice this. I will make sure my raid knows about this in the future

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2246
https://github.com/Looking4Group/L4G_Core/issues/2679

"Original comment by Tr1n1ty (Bitbucket: Tr1n1ty_, GitHub: Unknown):

No, it shoud not be

    http://wowwiki.wikia.com/wiki/Enfeeble?action=history
    http://wowwiki.wikia.com/wiki/Prince_Malchezaar?oldid=618211
    (Malchezaar cannot use Enfeeble on the highest target on his aggro list. However, since aggro is not pulled until 110% of the MTs aggro for melee and 130% for ranged, it is possible for someone to be higher than the MT without pulling aggro, and thus cause the MT to be a target of Enfeeble.)

Enfeeble is fine as is, no changes needed"
