### ISSUE TITLE
Gurtogg Siedeblut [Black Tempel]

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#352]
Originally reported by: **AbaddonLoktar (Bitbucket: [AbaddonLoktar](https://bitbucket.org/AbaddonLoktar), GitHub: Unknown)**

---

During phase transitions from 1 -> 2, **he stands in place for ~1.5 seconds before he rushes the Fel Rage target**. During this time players can move away from the FR target so they don't get hit by frontal AoE dmg.
I don't know if it's possible to script in a 1.5s invisible root/for the fel rage to be a 1.5s cast but that is the main issue on the encounter right now. People getting cleaved as he rushes the FR target instantly on phase change, even if we have people spread out beforehand.

Der Boss [Gurtogg Bloodboil](http://db.looking4group.eu/?npc=22948)  wirkt den Zauber Teufelswut (http://db.looking4group.eu/?spell=40604) (http://db.looking4group.eu/?spell=40616) und danach  Sturmangriff (http://db.looking4group.eu/?spell=40602) auf den von Teufelswut betroffenen Spieler.

Wie man hier sieht: https://youtu.be/vGVKQ4RXo9Y?t=1m27s wird der boss erst groß und dann charged er (was mehr zeit zum verteilen bringt) auf unserem server charged er aber sofort (klingt zwar nach wenig aber die 1-2 Sekunden machen beim vom Ziel weglaufen deutlich was aus).

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/a746b753889b6da0133043938f710303da563697
