### ISSUE TITLE
"Showground" Quest in Blades edge

### ISSUE THREAD

**Issue by steveyphil** [Looking4Group/L4G_Core#3523]
Hello

I've killed Goc about 10 times now, after using Rexxar's battle horn. However, the problem I'm having is that it's not "completing" the quests, and nothing happens once he's dead.
I really want my quest reward as these are pre raid bis, so please can you help as soon as possible.
Regards,
Basher (Horde)

**Comment by steveyphil** [comment]
Is there anyway of knowing if the issue has been fixed, and that I can obtain the item ?

**Comment by AnonXS** [comment]
Sounds like the You need to have first hit/kill to get quest credit issue.

**Comment by steveyphil** [comment]
Anon, thank you for your wise words. I kept letting Rexxar tank the damage then I would jump in and help when he was low. I let him die and then I finished grom off (after taking first hit too) and I FINALLY got the completion! legend
