### ISSUE TITLE
Mage Arcane Concentration talent / Clearcasting proc not working while chaincasting

### ISSUE THREAD

**Issue by basteh** [Looking4Group/L4G_Core#3524]
**Class:** Mage
**Talent:** Arcane Concentration (in Arcane tree, tier 2)

The Clearcasting proc does get correctly used up on every spell cast, but if you start casting a spell and get a Clearcasting proc while casting, the spell will use up the proc but still cost mana.

Example:

1. start casting Frostbolt1
2. finish casting Frostbolt1
3. Frostbolt1 flies
4. start casting Frostbolt2
5. Frostbolt1 hits - Clearcasting proc!
6. finish casting Frostbolt2 - Clearcasting proc gets used but still costs mana

Canceling the casting of **Frostbolt2** and starting it again will correctly use up the proc without costing mana.

This basically renders the talent "Arcane Concentration" useless on very static boss fights, since chaincasting will prevent all of the Clearcasting procs being used up correctly.

**Comment by AnonXS** [comment]
Same with other Spellmods which get consumed by already casted incoming Spells.

**Comment by Pbeitelmann** [comment]
This has been fixed.
