### ISSUE TITLE
Line of Sight Bugs

### ISSUE THREAD

**Issue by Cynoqt** [Looking4Group/L4G_Core#3526]
The whole map is poorly fixed in case of Line of sight (LOS) and also Indoor / Outdoor for mounts etc.

For me (who played on several servers) this is a sign for a bad one. Please fix this especially for pvp is this just a poor thing u did there.

Greetings

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2817
