### ISSUE TITLE
Elemental Mastery bugged, Elemental spec pretty much unplayable

### ISSUE THREAD

**Issue by daca171** [Looking4Group/L4G_Core#3529]
Instead of taking the first spell the shaman casted, it just takes the first damage source, it could be from stuff like totems, lightning shields, even party members, and removes the effect, without even critting, which makes the ability impossible to use in raids/parties. Crits are the core mechanic of Elemental shamans, and woithour this talent, the spec is pretty much useless.

**Comment by sefamurat** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2701

it's an issue for 9 months now.

**Comment by Niylah** [comment]
Noticed this aswell and I really really hope that this will get fixed soon.

**Comment by AnonXS** [comment]
We have a rather root bug bypassing fix in test phase on the PTR Realm.
Problem with that is that as long as EM is active, the shaman is not able to procc anything else, so EM gets consumed, crits with chain lightening but doesnt procc clearcast, but in my opinion, working EM is alot more worth then loosing one Clearcast Procc.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2701
