### ISSUE TITLE
Skullflame Shield - not benefiting from spellpower.

### ISSUE THREAD

**Issue by Smaskfia** [Looking4Group/L4G_Core#3532]
Skullflame shield doesn't seem to benefit from spellpower, doesn't scale the damage or healing from the procs on it.

**Comment by Saltgurka** [comment]
Sources?

**Comment by Smaskfia** [comment]
Well just my own sources, let me get some screenshots for you later. Gotta go to work now.

**Comment by AnonXS** [comment]
http://www.wowhead.com/spell=18816/flamestrike, http://www.wowhead.com/spell=18818/flamestrike
http://www.wowhead.com/spell=18815/drain-life, http://www.wowhead.com/spell=18817/drain-life#comments

http://www.wowhead.com/item=1168/skullflame-shield#comments

http://wowwiki.wikia.com/wiki/Skullflame_Shield, http://wow.gamepedia.com/Skullflame_Shield

---

Still need to discuss this topic internally as it opens door for other more "abuseable" items.

**Comment by drchristie** [comment]
Can confirm, I remember being a 70 prot pally in TBC, and hobbs made it popular too indirectly (using it till 3.0.2... ill come back and confirm this.. that Spell power IS SUPPOSED to scale with the skullflame damage in 2.4.3. Idea is you use sporegear shield for AOE tanking until X spellpower on 25 mobs (243 i believe), there was a chart someone optimizing this.

**Comment by Xadras** [comment]
Well in comments on wowhead they also say, that only the heal is increased and the dmg is not.

**Comment by Smaskfia** [comment]
From what I can remember I used to be able to pull entire SM cath (as a holy paladin) with only this shield and be able to just kill them all while selfhealing from the proc. 

So from what I can remember the spelldamage also increased the damage from the proc.
