### ISSUE TITLE
City of Light quest in Shattrath

### ISSUE THREAD

**Issue by vergon6** [Looking4Group/L4G_Core#3535]
Haven't seen it reported, but the City of Light escort quest in Shattrath won't complete, I've done it 3 times today. The elemental gets to the very end, then disappears before saying his last line. Others have said they have done it 4+ times before getting credit.

**Comment by Saltgurka** [comment]
Try doing it while mounted. That will make the guardian move faster. Some players have reported that this allowed them to complete the quest 100% of the time.

**Comment by vergon6** [comment]
Was actually heading back to post this, doing it while mounted worked after someone suggested it in guild chat. Still a bug, but there is a workaround.

**Comment by Timira** [comment]
Can confir m this quest is totally bugged out. I had to to it 3 times before getting credit for completing it. The npc that shows you around even just died out of nowhere once. Other than that he has a bit of pathing issues aswell, he ran a totally different way everytime I did it, when he comes to the bridge leading out of shat.

**Comment by vergon6** [comment]
Timira, I was able to complete this quest while mounted. I did experience him phasing through things, particularly the ramp right at the beginning he seemed to go down it like 30 yards in front of where he should, I WAS able to complete this quest on the 4th try.

**Comment by AnonXS** [comment]
Increase Speed of http://db.hellfire-tbc.com/?npc=19685

**Comment by Saltgurka** [comment]
Increasing the despawn time is probably the best way to do this for now. https://github.com/Looking4Group/L4G_Core/pull/3575

@AnonXS  http://db.hellfire-tbc.com/?spell=34445 does not seem to be used atm. Leash range locally is about 50y for me
