### ISSUE TITLE
Transfering BG tokens

### ISSUE THREAD

**Issue by silasftw** [Looking4Group/L4G_Core#3539]
Since the server is quite dead when it comes to BG its impossible to get for example AV tokens, this makes it impossible to buy the very essential gloves (always having something unique for the class)

Since it dosnt look like we will get AV.s up and running in a long time a feature which can trade WSG/AB token to AB tokens would be much appriciated to be able to gear up.

Cheers

**Comment by AnonXS** [comment]
Optional AV Mark Trader will be included in these (PvP) Season.sql Files: https://github.com/Looking4Group/L4G_Core/pull/3848
