### ISSUE TITLE
[Quest] A light in Dark Places/Licht im Dunkeln

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#354]
Originally reported by: **AbaddonLoktar (Bitbucket: [AbaddonLoktar](https://bitbucket.org/AbaddonLoktar), GitHub: Unknown)**
---

http://db.looking4group.eu/?quest=9319
Die Quest Licht im Dunkeln (http://looking4group.de/database/?quest=9319) ist nicht abschließbar, da keine der 4 Flammen vorhanden ist.

[Flamme von Düsterbruch](http://looking4group.de/database/?object=181346)

[Flamme von Schwarzfelsspitze](http://looking4group.de/database/?object=181347)

[Flamme von Stratholme](http://looking4group.de/database/?object=181348)

[Flamme von Scholomance](http://looking4group.de/database/?object=181349)

WOWHEAD (http://de.wowhead.com/quest=9386/licht-im-dunkeln#english-comments):
*
The one in Dire Maul, is after Guard Slip'kik in Dire Maul North
The one in Stratholme is right before the entrance to the Scarlet side, its basicly at Timmys spawn.
The one in Blackrock Spire is in LBRS, near the Ogre Tribute pile..
The one in Scholomance is in the Viewing Room as InsaneRyu said..*
---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/358

**Comment by AnonXS** [comment]
Fixed during https://github.com/Looking4Group/L4G_Core/issues/2460
