### ISSUE TITLE
Rogue D3 4p bonus set

### ISSUE THREAD

**Issue by tst12** [Looking4Group/L4G_Core#3543]
http://db.hellfire-tbc.com/?itemset=620
reduces energy not only the required
https://www.youtube.com/watch?v=cRt3mQN9zgU
after fix
```
UPDATE `spell_affect` SET `SpellFamilyMask` = 34376646656 WHERE `entry` = 37166;
```
https://www.youtube.com/watch?v=fRKeCRbq5D0
critical for PvP and PvE

**Comment by AnonXS** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/25234275/e4bf8374-25e1-11e7-8060-ae40bd153079.PNG)
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/25234304/fad56bb0-25e1-11e7-8339-98d29b486fbf.PNG)
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/25234330/0907c1d8-25e2-11e7-8159-30b93d4f4272.PNG)

Excluded SpellFaimlyMask 8388608, only Eviscerate and Envenom Discount

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3364/commits/72a1506cdd061e9dcc2a3fd447bc021fc2af38ec
