### ISSUE TITLE
Unable to change leatherworking Specialization (Book doesn't work)

### ISSUE THREAD

**Issue by Notmittz** [Looking4Group/L4G_Core#3551]
I appreciate all the work you guys do in improving this server, but I'm still having problems with changing my leatherworking specialization (my previous thread was deleted with the below wiki link pasted in).

From http://wowwiki.wikia.com/wiki/Book_"Soothsaying_for_Dummies", it states to change leatherworking specializations to do the following:

1. Talk to one of the specialization trainers about switching (**I talked with the elemental leatherworking trainer, after completing the elemental leatherworking quest in Arathi Highlands**)

2. Pay 100g to unlearn your current specialization (**I paid the 100g to the same elemental leatherworking trainer and my specialization was removed**)

3. Go to and speak with Narain Soothfancy (**I'm in Tanaris, I am currently speaking with him**)

4. Read the book to select a new specialization (**BROKEN! I CAN'T READ THE BOOK**)

As I stated in my previous thread, I cannot access that book.  There is a gear icon on the book, but nothing happens when I try to activate it.

**Comment by Notmittz** [comment]
As a follow up, I went back to the Elemental Leatherworking Trainer.

He is offering me the original quest again, which I had previously completed.

It would appear that unlearning my specialization COMPLETELY wiped this from my character...which would explain why the book doesn't work as possibly my character would have no record of that quest being completed.

This is a problem.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/3545
