### ISSUE TITLE
Ambassador Hellmaw "Unable to zone in while an encounter is in progress"

### ISSUE THREAD

**Issue by WarriorTSW** [Looking4Group/L4G_Core#3554]
After clearing trash in Hellmaws room and releasing him, if you wipe or leave the instance and try to go back in, you wont be able to. "encounter in progress"

We did this on Heroic Mode. One wipe on trash after he was released. And again when we tried to swap a player.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2282

**Comment by Saltgurka** [comment]
Solved with https://github.com/Looking4Group/L4G_Core/pull/3582 (Not live yet)
