### ISSUE TITLE
Arena Gear Rating Requirements are off.

### ISSUE THREAD

**Issue by Lynlis** [Looking4Group/L4G_Core#3557]
Hi there.
The rating requirements for S1 Gladiator gear is currently set to the S4 rating requirements, which is 2,2k for the highest slot (shoulder) instead of 2k which it should be.

It might be a choice of yours, but i dont think 2,2k is reachable on a private server.

**Comment by AnonXS** [comment]
The Rating Requirement is inteneded, to keep the value of the arena items equivalent to the pve items. (prenerf content)

It was reached throughout season I and II of hellfire I last year, so its nowhere "overkill", but a forsight to b's introduction of arena rating req. in season IV.

As soon as a new arena season is released, the item prices will be lowered to the nerfed blizzlike value for the last season items.

**Comment by AnonXS** [comment]
http://armory.looking4group.eu/arena-ladder.xml?ts=2&b=Looking4Group&ff=realm&fv=Progress
http://armory.looking4group.eu/arena-ladder.xml?ts=3&b=Looking4Group&ff=realm&fv=Progress
http://armory.looking4group.eu/arena-ladder.xml?ts=5&b=Looking4Group&ff=realm&fv=Progress
