### ISSUE TITLE
Pristine Black Diamond

### ISSUE THREAD

**Issue by Goron123** [Looking4Group/L4G_Core#3559]
I don't have proof to validate this ticket but it seems the drop rate for the Pristine Black Diamond is very very low or bugged.  Can someone confirm this?  I have run multiple runs through Scholo, DM & Strath.

Still have not seen one and have spoken to other Paladins & Warlocks trying to get the epic mount and they have also been unsuccessful.

Thank you for feedback!

**Comment by tst12** [comment]
https://github.com/Looking4Group/L4G_Core/issues?utf8=%E2%9C%93&q=pristine

**Comment by AnonXS** [comment]
Going to check back on how many players have looted the item now after the increase of dropchance, will report back and close.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3614/commits/89a80570a46e2c24abc8cc0d42480d9f0448f048
