### ISSUE TITLE
Zul'Aman Akil'zon Gauntlet

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#356]
Originally reported by: **Anon  X (Bitbucket: [Anonx](https://bitbucket.org/Anonx), GitHub: [Anonx](https://github.com/Anonx))**

---

Das Event um sich bis an die Spitze von Akil'zons Hügel zu kämpfen funktioniert nicht ganz richtig.

Der Sturmkrieger der Amani'shi http://looking4group.de/database/?npc=24549
sollte oben auf der Treppe stehen und solange Adds spawnen, bis dieser in einen Kampf verwickelt wird.

Bei uns läuft dieser von alleine nach einer bestimmten Zeit nach unten und kann so einfach getötet werden um das Event zu beenden.

https://www.youtube.com/watch?v=y36NymVkYFE 2min 30sec

Steht dort auf der Treppe und wartet darauf gepullt zu werden sodass keine NPC Wellen mehr spawnen.

When the Tempest is engaged, new birds and Amani'shi Warriors from the gauntlet will no longer be spawned. 
http://wowwiki.wikia.com/Amani%27shi_Tempest

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/360

**Comment by AnonXS** [comment]
https://youtu.be/eczxxR7hnkQ?t=1m27s
Ok, i missunderstood how the event works, nothing with combat, the scout is not able to behave normally if triggered in combat as the combat function prevent waypoint movement.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/f90b895fb75a9ef849413e2b56fd8f5f22bc14f3
