### ISSUE TITLE
Using slice and dice on mob that's out of combat aggros it

### ISSUE THREAD

**Issue by lsajt** [Looking4Group/L4G_Core#3560]
After IE a wipe when I as a rogue have CP's up on a reset mob, if I use Slice 'n' Dice it aggros. I believe this isnt rly intended.

**Comment by AbaddonL4G** [comment]
https://github.com/Looking4Group/L4G_Core/blob/master/src/game/SpellMgr.cpp#L3112

**Comment by AbaddonL4G** [comment]
can't reproduce
