### ISSUE TITLE
Tar Lord's Disarm

### ISSUE THREAD

**Issue by lugiebob** [Looking4Group/L4G_Core#3562]
The Tar Lords in Un'Goro have a disarm and they are using it way more often than they are suppose to and even at the wrong time.  I charged one and got disarmed even though it was stunned.

**Comment by Saltgurka** [comment]
http://db.hellfire-tbc.com/?npc=6519#abilities

http://db.hellfire-tbc.com/?spell=14178
http://db.hellfire-tbc.com/?spell=14180

Proc chance is 10%. This is set in DBC's so I doubt that it's incorrect.

**Comment by Saltgurka** [comment]
![image](https://cloud.githubusercontent.com/assets/22568446/25300034/178c3c5e-2707-11e7-8102-5dbf47e4d4a3.png)
