### ISSUE TITLE
Quest: Stasis Chambers of Bash'Ir

### ISSUE THREAD

**Issue by Dooze** [Looking4Group/L4G_Core#3569]
The quest: http://db.hellfire-tbc.com/?quest=10974 seems to be bugged.
Have yet to seen a prision around the "Stasis Chamebr Alpha".

This is the questline to summon Yor in Mana-Tombs HC.

**Comment by tst12** [comment]
http://wowwiki.wikia.com/wiki/Quest:Seek_Out_Ameer

> Seek Out Ameer starts in Stormspire and kicks off a series of Consortium quests added with **patch 2.1.** The quest series ends in being able to summon an optional boss after the final boss of Heroic Mana-Tombs. You will need to be Honored or better with Consortium before starting this quest chain.
