### ISSUE TITLE
Unexpected Results Bug

### ISSUE THREAD

**Issue by Spanky123** [Looking4Group/L4G_Core#3570]
I completed the quest Unexpected Results. Now my screen won't stop displaying "Protect Apprentice Mirveda" It displays it 3 lines at a time and is pretty annoying. It displays it on screen even after relogging. It will come on the screen and disappear after around 10 seconds or so and then will return back on the screen 15ish seconds later. 

How do I stop this from showing up on my screen?

**Comment by AbaddonL4G** [comment]
https://github.com/Looking4Group/L4G_Core/blob/a50c15e2360d30823d90771d1bd0d310922684b4/src/scripts/scripts/zone/eversong_woods/eversong_woods.cpp#L535-L617

**Comment by Saltgurka** [comment]
Solved with https://github.com/Looking4Group/L4G_Core/pull/3577
