### ISSUE TITLE
Herb loot bug

### ISSUE THREAD

**Issue by Fekapinainas** [Looking4Group/L4G_Core#3571]
Hello!

Sometimes after looting a herbnode, I got nothing from it. I "cast" the herb gathering, the loot window pops up, I click on the herb and I loot nothing. I have to restart the client to try again, and sometimes it works, sometimes a third restart need aswell. Its really annyoing to restart you client after every 3 herb.
I've collected some nodes where it happened, maybe it helps you to isolate the problem.
Netherstorm (coords):
62-30.5
53.6-70.2
54.2 44.8 (I found herb at this 2 times, both were bugged)
61.5 37.8
60.8 47.7 (2 times bugged also)
69.0 45.8
68.8 40.8
67.1 60.8

In terokkar:
73.3 82.0
37.4 28.6

I hope this helps,
Fekapinainas

**Comment by AnonXS** [comment]
Dublilcate https://github.com/Looking4Group/L4G_Core/issues/2717
