### ISSUE TITLE
Shattered hand sharpshooters completely ignore line of sight mechanics

### ISSUE THREAD

**Issue by Zarant** [Looking4Group/L4G_Core#3576]
Shattered Hand Sharpshooters in shattered halls don't follow their targets if they are out of line of sight, they just stand at the same place doing absolutely nothing.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3364/commits/85b1818cec2cfebd023c98b9a6b0ed432742f311
