### ISSUE TITLE
City of Light bugged

### ISSUE THREAD

**Issue by lovro22** [Looking4Group/L4G_Core#3580]
Hello...il did the escort q for City of Light...i followed the voind for 9 times now,stucked to him,didnt louz him or any thing and i cant complate the q...at the end of the q when we get to middle of shat he is talking his story to the end and then he disapers and the q is not finish...can you help me pls?

**Comment by beepyz** [comment]
Same problem here. He does the first round properly (falls through the ground near start but that doesnt bug it) goes downstairs goes back up and a bit before scryer bank his pathing bugs and he tries to take an alternative route and then despawns.

**Comment by beepyz** [comment]
Always tried to do it mounted btw as the other thread suggested. I got slow mount though not sure if thats the reason it didnt work.

**Comment by beepyz** [comment]
Just got it completed after 10 tries or so. Problem is after the round he does on lower city and he gets back up on the bridge before the Scryer bank. Just follow him closely and maybe try it more then once if he despawns will get completed eventually.

**Comment by Saltgurka** [comment]
Solved when https://github.com/Looking4Group/L4G_Core/commit/d844cfeecbfff0366424f2a34cdf918ffa3168ba goes live. 

The base problem is that waypoint movement is not working properly right now, leading to his route taking a longer time to complete. Increasing the despawn timer solves the issue for now.
