### ISSUE TITLE
Gauging the Resonant Frequency

### ISSUE THREAD

**Issue by gnarwi** [Looking4Group/L4G_Core#3581]
quest cant be done. scanners dont create rifts or beams to each other.

**Comment by tst12** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3573

**Comment by tst12** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2003

**Comment by Saltgurka** [comment]
Duplicate of https://github.com/Looking4Group/L4G_Core/issues/2003

Solved in https://github.com/Looking4Group/L4G_Core/pull/3573
