### ISSUE TITLE
PvP Honor Vendor - Alliance - Missing S1 Boots / Belts (Paladin)

### ISSUE THREAD

**Issue by Optilasgar** [Looking4Group/L4G_Core#3584]
I've Checked every single PvP Vendor in the Game.
- SW
- Nagrand
- Area 52

None are selling ANY Boots / Bets, neither Plate nor otherwise to a Human Paladin.

EDIT:
RET Paladin S1 Bracer: http://www.wowhead.com/item=28643/generals-lamellar-bracers
RET Paladin S1 Belt: http://www.wowhead.com/item=28644/generals-scaled-belt
RET Paladin S1 Boots: http://www.wowhead.com/item=28645/generals-scaled-greaves

**Comment by AnonXS** [comment]
Sources for Items to add.

**Comment by tst12** [comment]
http://db.hellfire-tbc.com/?npc=23446

**Comment by AnonXS** [comment]
Original: http://db.hellfire-tbc.com/?npc=26304 L4G: http://db.hellfire-tbc.com/?npc=1200056
Original: http://db.hellfire-tbc.com/?npc=26305 L4G: http://db.hellfire-tbc.com/?npc=1200051

Added General's armor and Marshal's armor Vendor.

**Comment by tst12** [comment]
http://db.hellfire-tbc.com/?item=28451 i hope cost not balance related
