### ISSUE TITLE
Elixer of Water walking

### ISSUE THREAD

**Issue by Twizzerious** [Looking4Group/L4G_Core#3586]
Should be able to be crafted by alchemists. Can not find a trainer to teach me the ability anywhere. Database also doesnt list a possible place to train the craft

**Comment by AnonXS** [comment]
http://www.wowhead.com/spell=62410/elixir-of-water-walking#comments
http://www.wowhead.com/item=8827/elixir-of-water-walking#comments

By Tussi (3,745 – 1·8·16) on 2009/01/07 (Patch 3.0.3)		
On the 3.0.8 PTR this elixir can be discovered with Northrend Alchemy Research.

"You can now discover a recipe for the Elixir of Water Walking with Northrend Alchemy Research."
