### ISSUE TITLE
Quest "The Grimtotem Weapon"

### ISSUE THREAD

**Issue by ME121989** [Looking4Group/L4G_Core#3588]
Dear DEV´s,

the above mentioned Quest appears to be bugged and can not be completed.
The Totem does not work. It isnt debuffing the Mobs,

http://imgur.com/a/499bH

http://imgur.com/a/OMraY

___
Could you please fix it.
Have a nice evening.

**Comment by Saltgurka** [comment]
https://github.com/Looking4Group/L4G_Core/issues/3308
Only mottled drywallow crocolisks give credit atm
