### ISSUE TITLE
Netherspite Bugged

### ISSUE THREAD

**Issue by silasftw** [Looking4Group/L4G_Core#3589]
Hey. I see that it has been previous posts about him but from what i can tell it is from the instant server?

The bugs we have at netherspite. 

- The debuff shows instantly when you leave the beam (i think it should show after the buff is gone). However you can still enter the beam when you got the buff so its just a visual bug.

- Netherbreathe dosnt work, we cant see who he is targetting, he still targets the tank but casts it at a random person, this makes it totally impossible to move anywhere and we just run away and hope we done die (for example if he hits a guy with blue buff). 

- void zone, 2 things here.
1, visuals is totally wrong, here is a gif, i am the dead gnome to the left, this is where i stood and died.
https://gyazo.com/b322ce7165cfd1f6619d1d29efdfc1d6

2, this one i am not sure about either but it does damage instantly, if i read the forums right it shouldnt be until 1-2 sec. Because if our guy in the blue beam gets it he instant dies, like literally, no chance to blink/ice block or whatever you want to do, no reactions in the world to save him. I would be surprised if this is how its intended. 

We want to give this guy a try before reset, so i hope we can get some response to it.

Cheers
Silas

**Comment by AnonXS** [comment]
There are issues to be resolved with netherspite, but he is far from unkillable, he do a clean aggro wipe after each portal phase which atm would wipe alot of groups due to dots ticking throughout the banish phase, so he is actually easier to control than he should be.

**Comment by silasftw** [comment]
I know he should do an aggro reset, didnt know that was bugged tho, we are using destru locks so not much dots :D. And i know he isnt unkillable, we did get him down to 30-40% ish so its managable, but what we did was just run away from him (all 10 of us) and he stood there doing nothing. So we get less dmg done this phase (which is a legit strategy anwyays) But with bad luck 1-3 guys died when we ran away becsue we had no idea who we was targetting :P. 

And yeah the instand void zone dmg is just, please dont hit the blue beam guy.  

Do you have any prios on fixing these stuff?:P Just want to know so we can plan if we gonna give it another shot tomorrow. 

Cheers

**Comment by AnonXS** [comment]
Not going to change anything within a day.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2056
