### ISSUE TITLE
Warrior quest for lvl 30 bugged

### ISSUE THREAD

**Issue by Buffnuff** [Looking4Group/L4G_Core#3591]
Hi,

everytime i want to start quest "the islander" wow gets closed. I need the quest to get berserker stance, so pls fix it.

Thx

http://www.wowhead.com/quest=1718/the-islander

**Comment by AnonXS** [comment]
Disable questhelper.

**Comment by AnonXS** [comment]
Dubliacte https://github.com/Looking4Group/L4G_Core/issues/1458
