### ISSUE TITLE
Elemental Mastery gets consumed by spell hits rather than casts

### ISSUE THREAD

**Issue by Einheizgreis** [Looking4Group/L4G_Core#3592]
When you cast Lightning Bolt and Elemental Mastery right after, then your Elemental Mastery gets consumed by your Lightning Bolt hit and is not guaranteed to crit (and does not give mana back).

Elemental Mastery should only get consumed when you succesfully cast a fire frost or nature spell (and this spell has a 100% crit and costs no mana).

**Comment by AnonXS** [comment]
Dubliacte https://github.com/Looking4Group/L4G_Core/issues/2701
