### ISSUE TITLE
Elemental Focus gets consumed by spell hits rather than casts

### ISSUE THREAD

**Issue by Einheizgreis** [Looking4Group/L4G_Core#3593]
When you critically hit a target with Lightning Bolt you gain Elemental Focus. When you then cast Chain lightning and hit 2 or more targets both charges of Elemental Focus are consumed.

Another example:

When you cast Lightning Bolt and critically Earth Shock right after. Then your Lightning Bolt hit consumes one charge of Elemental Focus (without giving the mana back).

Exactly one charge of Elemental Focus should get comsumed when it succesfully reduced the mana cost of a damage spell.

**Comment by AbaddonL4G** [comment]
https://github.com/Looking4Group/L4G_Core/issues?utf8=✓&q=elemental

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/3388
