### ISSUE TITLE
Bugged quest (What came first)

### ISSUE THREAD

**Issue by Nexao** [Looking4Group/L4G_Core#3594]
"What came first, the drake or the egg" In blade's edge mountains is bugged. After you sap the dragon and it turns to something. You then kill it, but as it dies it just disappears and you don't get credit for it

**Comment by tst12** [comment]
fixed for any class https://github.com/Looking4Group/L4G_Core/commit/6244f4a9edc8e5f70b97f6647988a8bf9e23af98
loot after kill

**Comment by Saltgurka** [comment]
The fix from tst12 is not live yet, but it should resolve the problem. 

Reopen if the problem persists in a few days

**Comment by adnanberberovic** [comment]
The problem is still there.
