### ISSUE TITLE
EXP gained from Grey?

### ISSUE THREAD

**Issue by ME121989** [Looking4Group/L4G_Core#3595]
![wowscrnshot_042417_210806_li](https://cloud.githubusercontent.com/assets/27031390/25354261/a326d58a-2932-11e7-993b-166c6f97df3e.jpg)

Hello DEV´s,

Maybe there are some sort of bugs regarding the EXP gained. I just got some from a grey mob.

**Comment by tst12** [comment]
lvl diff <10,its normal

**Comment by AnonXS** [comment]
http://wowwiki.wikia.com/wiki/Experience_point

Level 48 Player gains Exp from mobs >= 38;

For character level 40-59 there is a little jump in favor of the player every 5 levels.
