### ISSUE TITLE
Quest bugged (Gauging the Resonant Frequency)

### ISSUE THREAD

**Issue by Nexao** [Looking4Group/L4G_Core#3596]
"Gauging the Resonant Frequency" In Blade's edge mountains is bugged. When I place the "Oscillating Frequency Scanners" it does nothing.

**Comment by Saltgurka** [comment]
Thank yoiu for the report! tst12 has a pending fix for this quest which will go live once we have tested it on PTR: https://github.com/Looking4Group/L4G_Core/pull/3573

**Comment by Niylah** [comment]
This quest is still bugged. I noticed on discord changelog that this quest was fixed so I tried it. I did not get complete when I had 5 buffs at the same time.
