### ISSUE TITLE
Quest in Terokkar fores named Who are they not working

### ISSUE THREAD

**Issue by wb1234** [Looking4Group/L4G_Core#3597]
This quest is supposed to disguise the player as an orc. I am not able to complete this quest

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?quest=10040, http://db.hellfire-tbc.com/?quest=10041

**Comment by AnonXS** [comment]
Dubliacte https://github.com/Looking4Group/L4G_Core/issues/2956
