### ISSUE TITLE
level 12 paladin quest 

### ISSUE THREAD

**Issue by Alpherious** [Looking4Group/L4G_Core#3598]
completed the quest to resurrect the npc, but he died almost immediately and I was unable to get the next part of my quest, ran back to stormwind to try to get another symbol and couldn't.

**Comment by Saltgurka** [comment]
Duplicate: https://github.com/Looking4Group/L4G_Core/issues/3533

To get a new Symbol of Life, please open an ingame ticket and a GM will send one to you.
