### ISSUE TITLE
Quest: What came first, the Drake or the Egg?

### ISSUE THREAD

**Issue by GrimLox** [Looking4Group/L4G_Core#3601]
Quest: What came first, the Drake or the Egg?
PROBLEM: After they turned into the form you are supposed to gather the essences from then they wont be lootable since they despawn as soon as they die.

Class: Hunter
Lvl: 70

Not sure if its cause my pet bugs them so tried to melee them down but still the same issue. Cant be looted since they despawn when they die?

Might be caused that they fall through the ground when they die but also looses target from it when it dies.

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?quest=10609

https://github.com/Looking4Group/L4G_Core/pull/3556

dk if this is already live.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/6244f4a9edc8e5f70b97f6647988a8bf9e23af98

**Comment by Niylah** [comment]
I had the same issue as Grimlox had just now.
