### ISSUE TITLE
Wrong (Missing) Mob Scripting - Shattered Halls Trash (Shattered Hand Gladiator)

### ISSUE THREAD

**Issue by Optilasgar** [Looking4Group/L4G_Core#3602]
Looking at the Atlas Instance Map, between the Boss Spots of Blood Guard Porung (3) and Warbringer O'mrogg (4):

There are 4 Packs consisting of 1 Shattered Hand Centurion and 4 Shattered Hand Gladiators each in 4 Alcoves left and right of the path.
The Gladiators are engaged in training duels in pairs of 2, with the Centurion overseeing their training.

THE CORRECT behaviour would be for the Gladiators to steadily lose health during their duels until they are in execute range in respect to their health levels, and then start to regenerate to full health.

The challenge of these packs SHOULD be to time pulling them correctly with as low health as possible, without waiting too long for them to regenerate to full health.

THE ISSUE is that while they do start in the duel animation on this server, they NEVER lose any health, so you can only pull them at 100%, which means you either have 2-3 AoE CC DPS with you, are rediculously overgeared, or will simply wipe and therefore be unable to complete the quest "Pride of the Fel Horde".

So this missing scripting makes these packs rediculously overtuned, and negates the mechanics skill check they were designed in mind with.

Refference Picture: https://puu.sh/vvKrK/d6d1ecadab.jpg

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2551
