### ISSUE TITLE
Alliance Recipe: Super Mana Potion spawn too low

### ISSUE THREAD

**Issue by vergon6** [Looking4Group/L4G_Core#3603]
I have been checking with the vendor in Telredor, Haalrun, multiple times a day for over a week, Others have said the same thing. There are always people camping this vendor and in talking to them hardly anyone seems to get it. A few people on the server have the recipe so I know it actually spawns, just seems like the spawn timer is way too low.

**Comment by AnonXS** [comment]
```
UPDATE `npc_vendor` SET `incrtime` = 10800 WHERE `item` = 22907; -- 43200
```

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3364/commits/efbe52012c63c6509c0f5fb7ed66e6ac5b2ed3ea
