### ISSUE TITLE
Character removed 

### ISSUE THREAD

**Issue by Snaai** [Looking4Group/L4G_Core#3605]
hello i have a question
I logged in today on my acc on hellfire but all my characters are gone
when i wanna change realm it says i have one character
but i don't have one in it its gone
I changed my password.

Been away for a while, logged back in and suddenly there was made a lvl 1 Dwarf on my account with the name of my main character i had that is gone now..
Clearly someone is messing around with me

**Comment by Saltgurka** [comment]
If you believe your account got hacked, please read throught he instructions here in order to request a character restoration: https://hellfire-tbc.com/forums/showthread.php?tid=2049
