### ISSUE TITLE
 Error compiling vs2010 and Linux after a fix Tst sfdc (# 3610)

### ISSUE THREAD

**Issue by coutinho2010** [Looking4Group/L4G_Core#3615]
5>spell_scripts.obj : error LNK2019: unresolved external symbol "class Aura * __cdecl CreateAura(struct SpellEntry const *,unsigned int,int *,class Unit *,class Unit *,class Item *)" (?CreateAura@@YAPAVAura@@PBUSpellEntry@@IPAHPAVUnit@@2PAVItem@@@Z) referenced in function "bool __cdecl spell_oscillating_field(class Unit *,class Unit *,class Item *,class GameObject *,struct SpellEntry const *,unsigned int)" (?spell_oscillating_field@@YA_NPAVUnit@@0PAVItem@@PAVGameObject@@PBUSpellEntry@@I@Z)
5>spell_scripts.obj : error LNK2001: unresolved external symbol "class DBCStorage<struct SpellEntry> sSpellStore" (?sSpellStore@@3V?$DBCStorage@USpellEntry@@@@A)
5>blades_edge_mountains.obj : error LNK2019: unresolved external symbol "public: static class Player * __cdecl ObjectAccessor::GetPlayer(unsigned __int64)" (?GetPlayer@ObjectAccessor@@SAPAVPlayer@@_K@Z) referenced in function "public: virtual void __thiscall npc_oscillating_frequency_scanner_master_bunnyAI::UpdateAI(unsigned int)" (?UpdateAI@npc_oscillating_frequency_scanner_master_bunnyAI@@UAEXI@Z)
5>...\hellgroundcore\L4G_Core-master\L4G_Core-master\win\..\bin\Win32_Release\lib\trinityscript.dll : fatal error LNK1120: 3 unresolved externals
========== Build: 4 succeeded, 1 failed, 4 up-to-date, 0 skipped ==========

**Comment by AnonXS** [comment]
Probably like https://github.com/Looking4Group/L4G_Core/commit/6769f230aae56b086a1f6e826e8af7a34a9a0f9f just the other way around, he inserted externals for windows, but not for linux.

**Comment by AnonXS** [comment]
Windows compile fails too.

**Comment by tst12** [comment]
@coutinho2010 try to replace
https://github.com/Looking4Group/L4G_Core/blob/a9e834d269a4534dbf8b3f07285d7c3f91e6f43e/src/scripts/scripts/zone/blades_edge_mountains/blades_edge_mountains.cpp#L2945
`if (Player* player = Unit::GetPlayer(playerGuid))`

https://github.com/Looking4Group/L4G_Core/blob/a9e834d269a4534dbf8b3f07285d7c3f91e6f43e/src/scripts/scripts/spells/spell_scripts.cpp#L222-L227
`player->AddAura(SPELL_OSCILLATION_FIELD, caster);`

**Comment by coutinho2010** [comment]
Thanks friends @tst12 and @AnonXS problem solved

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3627
