### ISSUE TITLE
Monstrous Crawlers in the Swamp of Sorrows

### ISSUE THREAD

**Issue by ME121989** [Looking4Group/L4G_Core#3616]
Hello,

the "monstrous crawlers" (those in the water) in the swamp of sorrows instantly evade if you tagged them so one cant kill them. Could you please fix that.

![wowscrnshot_042717_162144](https://cloud.githubusercontent.com/assets/27031390/25488171/a6f06538-2b66-11e7-98f0-4bd274386d7c.jpg)

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?npc=1088

```

-- Crabs should all swim
-- or add creature_template_addon: entry	0	0	16908544	0	4097	0	0
UPDATE `creature_template` SET `InhabitType` = 3 WHERE `entry` IN (1088,2232,2233,2234,2235,2236,3107,3108,3228,5439,17216,17217); 	

```

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3614/commits/690b6c13ac6f23d525fce0cfc50d07650a30546a
