### ISSUE TITLE
Stealth detection

### ISSUE THREAD

**Issue by shedslow** [Looking4Group/L4G_Core#3618]
Either the stealth detection of mobs is way too high or the rogue stealth is too weak, even with stealth talents. Mobs should not detect you if you stand behind them, i made a video where i tested it on some mobs with diffrent levels. When you Shadowstep behind a mob, it should not detect you when you don't move until it turns or you get a lot closer. You can see in the video that even lvl 40 mobs detect me when i sneak close to them... With a diffrence of around 20 levels and Stealth talents i should be able to sneak right through the mob without getting detected.

Video link will follow as soon as it's uploaded.

**Comment by shedslow** [comment]
Video: https://www.youtube.com/watch?v=9UC-VtshOA8

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/3245, https://github.com/Looking4Group/L4G_Core/issues/470

**Comment by tst12** [comment]
@shedslow in this case everything works as expected

> Enemies you are in front of will see through Stealth as you get closer
