### ISSUE TITLE
Aggro Range of low Mobs

### ISSUE THREAD

**Issue by shedslow** [Looking4Group/L4G_Core#3619]
The aggro range of mobs below my own level is way too high. It seems okay for mobs on the same level.

Video link will follow as soon as it's uploaded.

**Comment by shedslow** [comment]
https://www.youtube.com/watch?v=DFohORgMc40

**Comment by AnonXS** [comment]
You were in contact range of these npcs, due to bugged hitboxes making them aggro on you.
