### ISSUE TITLE
Game Broken, Unable to log into character

### ISSUE THREAD

**Issue by Scages101** [Looking4Group/L4G_Core#3625]
My Main character Scage bugged out or something on the way to Thunder Bluff as I was about to get on the elevator near the weapon skill trainer, I moved my camera up and my game crashed. as I tried to relaunch/ re log into my character my game keeps crashing anytime I try to log into that Character.

**Comment by Saltgurka** [comment]
Your character is not anywhere close to Thunder Bluff. It is in The Crossroads inn. I assume the issue was already resolved?
