### ISSUE TITLE
Bloodgem Crystals

### ISSUE THREAD

**Issue by Durstt** [Looking4Group/L4G_Core#3631]
The Quest Bloodgem Crystals is bugged, it  targets a smaller red crystal instead of the bigger one and doesn't siphon the crystal.

**Comment by Saltgurka** [comment]
https://github.com/Looking4Group/L4G_Core/issues/3354
https://github.com/Looking4Group/L4G_Core/issues/2173
https://github.com/Looking4Group/L4G_Core/issues/2009
https://github.com/Looking4Group/L4G_Core/issues/1555
https://github.com/Looking4Group/L4G_Core/issues/1361

Duplicate of https://github.com/Looking4Group/L4G_Core/issues/2795
