### ISSUE TITLE
Zul'Aman - Akil'Zon Birds Despawn

### ISSUE THREAD

**Issue by Quinzy** [Looking4Group/L4G_Core#3633]
Upon Akil'Zon death, the birds should despawn.

See https://youtu.be/P3-1-K-aldQ?t=6m around 6:00 mark you can see the kill and the birds above despawn

**Comment by Quinzy** [comment]
Upon Akil'Zon death, the birds should despawn. 

See https://www.youtube.com/watch?v=P3-1-K-aldQ around 6:00 mark you can see the kill and the birds above despawn

**Comment by AnonXS** [comment]
https://youtu.be/vWgt0wP4zuM?t=4m
