### ISSUE TITLE
Karazhan BoJ 2.3

### ISSUE THREAD

**Issue by Quinzy** [Looking4Group/L4G_Core#3634]
Karazhan should start dropping BoJ in 2.3, it currently doesn't on the instant server.

See patches and fixes
http://wowwiki.wikia.com/wiki/Badge_of_Justice

**Comment by AnonXS** [comment]
If you find any Karazhan Boss / Chest not having Badges in the next Raid, report back here please.

**Comment by tst12** [comment]
doodes, dont report, wait for bt, za etc or smthing similiar to 2.3 staff

**Comment by AnonXS** [comment]
This is Instant Server related in this case.
