### ISSUE TITLE
Mount Hyjal Pathing

### ISSUE THREAD

**Issue by Quinzy** [Looking4Group/L4G_Core#3636]
Trash just run however it wants to the alliance camp when a weave is incomming.

**Comment by Saltgurka** [comment]
Did this issue appear recently or was it always like this?

**Comment by ihcTactics** [comment]
The issue started in the last 2 weeks I believe.

In terms of running 'however they want': ->

In the Alliance camp, trash is supposed to start outside the camp in the Undead camp, head towards the road then travel up the road to the Alliance camp. About ~ 1/2 the mobs in each wave will do that. The other half will go directly from the spawn point towards the gate of the Alliance camp.

**Comment by Saltgurka** [comment]
If the issue started around 2 weeks ago, then this is probably related to the general issues we currently have with Waypoint Movement since the pathfinding updates a few weeks ago.

**Comment by AnonXS** [comment]
I think the change that broke this was reverted and it should be fine/better in the next raid.
