### ISSUE TITLE
Quest "Treant Muisek"

### ISSUE THREAD

**Issue by ME121989** [Looking4Group/L4G_Core#3638]
Hello,

the quest mentioned above (Feralas) appears to be bugged. I know that there is a chance not to get credit for the Q. However i searched for and killed 5 of the required mobs and each and everyone of them was "Out of Range" if i wanted to use the Q item on them. Some were even bugged so that i could not loot em.

![wowscrnshot_042917_204853](https://cloud.githubusercontent.com/assets/27031390/25557988/ceb6aea2-2d1d-11e7-99c8-d03b214b8767.jpg)

have a nice evening

**Comment by RasmusOJ** [comment]
Was trying to do this quest today but I ran into the same problem as ME121989 mentioned. 
Sadly I can't continue with the quest chain now, wanted to get the weapon from last part.

**Comment by tst12** [comment]
problem related to WP movement
