### ISSUE TITLE
Quest: Drain Schematics, Slavepens

### ISSUE THREAD

**Issue by Bearrman** [Looking4Group/L4G_Core#3643]
In order to get the main quests to Slavepens you need to get the Drain schematics, which starts a questchain. It is supposed to drops from Bloodscale nagas and overseers but it never does

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3630

**Comment by tst12** [comment]
report invalid, its drops from Bloodscales, I am farm"Steam Pump Overseer" for it and get from Bloodscales awaiting  "Steam Pump Overseer" respawn(Bloodscales have  low dropchance for it like it should be)

**Comment by Bearrman** [comment]
I spent 2 hrs farming bloodscale nagas and overseers and i didnt get any drop, and neither did any of my friends, but maybe its just extremely bad luck

**Comment by tst12** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3630 сontains enough information about this

**Comment by AnonXS** [comment]
yes as soon as #3630 is merged this has been adressed enough.
