### ISSUE TITLE
Incorrect Spawn Position on Morogrim Tidewalker

### ISSUE THREAD

**Issue by Twizzerious** [Looking4Group/L4G_Core#3650]
Right now morogrim is positioned pretty much at the entrance of his room (when entering from the right ramp). this makes it impossible to get behind him to pull the trash murlocs and clear the room for the boss fight without going to the left and having to clear through leos room. If you try to hug the wall and walk passed him he will immediately agro. 

https://www.youtube.com/watch?v=-da6FEYCoZw

Video shows that he sits more in the middle of the room of the room so that you can enter from both sides and clear the trash. He sits slioghtly behind the rocks in the video. on the server he is sitting INSIDE and infront of the rocks

It is a huge inconvenience and eats up alot of time to have to clear both leo and fathom lords room if we want to get to morogrim,

**Comment by AnonXS** [comment]
http://wowwiki.wikia.com/wiki/Patch_2.1.0

Morogrim Tidewalker has been moved to a more central location in his room.
