### ISSUE TITLE
Zul'Aman Reset Timer

### ISSUE THREAD

**Issue by ihcTactics** [Looking4Group/L4G_Core#3652]
Zul'aman is currently set to standard raid reset (7 days).

Should be 3.

http://wowwiki.wikia.com/wiki/Zul%27Aman_(original) - Check summary

**Comment by AbaddonL4G** [comment]
UPDATE `instance_template` SET `reset_delay` = '3 WHERE `map` = 568;

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3614/commits/d1090852271a586d3530dcd0ce8189d0f15c4584
