### ISSUE TITLE
Pathing Update Problem

### ISSUE THREAD

**Issue by ihcTactics** [Looking4Group/L4G_Core#3654]
Since the new pathing update posted April 30, some mobs will run under the ground. Of those that run under the ground, some stay under the ground and won't come back up.

This happened on the trash outside Illidari Council specifically with the Illidari Assassin and Illidari Archon.

**Comment by tst12** [comment]
last update not related to "under the ground" problem and not solved it

**Comment by Quinzy** [comment]
Bosses go invisible aswell when you try to move htem

**Comment by AnonXS** [comment]
It seems there was an interim version of a pathing update live on hellfire 1 which caused this.
Was reverted yesterday.
