### ISSUE TITLE
Lady Vashj Aggro Range too Small

### ISSUE THREAD

**Issue by Nykvist** [Looking4Group/L4G_Core#3660]
Hello, Currently Lady Vashj aggro range isn't wide enough.

Here is a video of the Memento Mori killing Lady Vashj (5th kill world wide)
https://www.youtube.com/watch?v=nNjDlFyXdCU
Im unsure what patch this video is from, since it states at the end that this is their 2nd Lady Vashj kill

Now if I recall correctly, yesterday when we (BIZZNO) did Lady Vashj the aggro range wasnt this wide, I may be incorrect but obviously cant test it at the moment, but will report back here when we kill her next week (probably)

Side note:
When I know looked through these videos aswell as patch notes it seems that the fight is working 'perfectly' (as they should have been working pre nerf Lady Vashj) beside from the aggro range. Correct dmg on spells, Correct hp on mobs, etc.

Thanks, Nykvist

Edit #1:
Unsure why the video was uploaded with the post at the first place, most likely I fucked up somehow, sorry, oops

Here's is the video:
https://www.youtube.com/watch?v=nNjDlFyXdCU_

**Comment by AnonXS** [comment]
Sources on how big it should be, it is already big enough to simulate blizzlike pull imo. Its about ~36yards atm.

**Comment by Nykvist** [comment]
I have now followed up on this issue in-game:
Made two Screenshots:
Hurricane with (2/2 Nature's Reach Talent) got 36yards. This is also what I felt like how wide the aggro range was when we did Vashj
http://imgur.com/a/268Nl

If we know look at the video provided by both me and AnonXS:
I have tried to replicate exactly where in the video Lady Vashj first targets the tank
http://imgur.com/a/pnYUL

It is quite clear how big the difference is... and even tho its not super precise this is the best I could do with the information given to me
I'm also unsure exactly how many yards different the two aggro ranges have, but I would estimate them to be around 25ish yards

**Comment by AnonXS** [comment]
Comparing with the POV:
![bcd4z9b](https://cloud.githubusercontent.com/assets/19734826/25898653/5084da9a-358d-11e7-9cc5-96757a8cf47a.jpg)

This is where vashj should be pulled.

**Comment by Nykvist** [comment]
I got an opportunity to try out aggro ranges because we <BIZZNO> wasn't able to clear entire SSC in one night :/
http://imgur.com/a/4BYjW

Here you can see that yes, the aggro range is further than what I provided earlier (Like AnonXS said, Hurricane is not a good ability to test aggro ranges with)

I also decided to try to find some additional videos from retail to find out what the actual aggro range should be:
https://vimeo.com/394898
https://www.youtube.com/watch?v=bvCPYRL0_g4

A great way to really see where Lady Vashj aggros is the slow down the speed of the video (Youtube gives you the ability to slow it down 0.25x) Vimeo does not provide that feature from what I've found atleast

I believe that the 2nd video ( https://www.youtube.com/watch?v=bvCPYRL0_g4 ) does really provide a good image of how far away Lady Vashj aggros

Nykvist

**Comment by AnonXS** [comment]
Okay slowing it downs makes for a good example in this case: https://youtu.be/bvCPYRL0_g4?t=12s
Its nearly as soon as you get to the top of the platform, on the level where the player corpse is located.
