### ISSUE TITLE
Mysterious Arrow Can be bought from Karazhan Vendor

### ISSUE THREAD

**Issue by Nykvist** [Looking4Group/L4G_Core#3661]
Hello

Currently you can buy Mysterious Arrows from the vendor outside of Karazhan (and maybe a vendor in Shattrath?)

These arrows are not supposed to be in the game until patch 2.3

http://www.wowhead.com/item=34581/mysterious-arrow

Thanks, Nykvist

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2364

[Mysterious Arrow](http://db.hellground.net/?item=34581) and [Mysterious Shell](http://db.hellground.net/?item=34582) were added in 2.3 and should not be sold yet by [Apprentice Darius](http://db.hellground.net/?npc=18255), [Marksman Bova](http://db.hellground.net/?npc=25195) or [Archer Delvinar](http://db.hellground.net/?npc=25196)

http://wowwiki.wikia.com/wiki/Apprentice_Darius
http://wowwiki.wikia.com/wiki/Mysterious_Arrow?oldid=969289
http://wowwiki.wikia.com/wiki/Mysterious_Shell?oldid=969281

```

DELETE FROM `npc_vendor` WHERE `item` IN (34581,34582);
-- INSERT INTO `npc_vendor` VALUES
-- (18255,34581,0,0,0),
-- (18255,34582,0,0,0),
-- (25195,34581,0,0,0),
-- (25195,34582,0,0,0),
-- (25196,34581,0,0,0),
-- (25196,34582,0,0,0);

```

You are correct, wont remove them at this point though.
