### ISSUE TITLE
Zephyr NPC in Lower City (Shattrath) shouldn't be in-game

### ISSUE THREAD

**Issue by Nykvist** [Looking4Group/L4G_Core#3662]
http://wowwiki.wikia.com/wiki/Zephyr

Patch 2.4.0 (25-Mar-2008): A representative of the Keepers of Time has been spotted at the World's End Tavern in Shattrath. Players in good standing with the faction will be granted ease of passage to the Caverns of Time.

This vendor will teleport the player on Caverns of Time

This is very much a nice addition to the game, unsure if the server wants this NPC to be in the game or not though.

Thanks, Nykvist

**Comment by Saltgurka** [comment]
I don't know if it was intentional to leave it in or not, but I personally think it is alright to leave it there since it is just a convenience thing.

We should discuss it though :)

**Comment by AnonXS** [comment]
Left it as we had a clownfiesta last year due to it.
