### ISSUE TITLE
Teaching Pet

### ISSUE THREAD

**Issue by barrok93** [Looking4Group/L4G_Core#3663]
I have tamed Echeyakee from the barrens, then went and tamed pets to give me bite and claw abilities. Yet when i go to train Echeyakee it doesnt allow me to teach him these abilites. I cant seem to find out why it wont work.

**Comment by tst12** [comment]
tame is not enough for learn abilities
http://wowwiki.wikia.com/wiki/Hunter_abilities/Pet_abilities?oldid=581998

**Comment by AnonXS** [comment]
Need to play with these new pets for some time until you learn the pet skill to learn it to your normal pet.
