### ISSUE TITLE
Warlock - is enslaved demon bugged?

### ISSUE THREAD

**Issue by silasftw** [Looking4Group/L4G_Core#3670]
Hi

When i enslave demon he dosnt get any threat/aggro, literally nothing. For example in Nagrand when i was gonna solo the elitequest at the demon camps i enslaved a Legionare and was gonna kill the overseer. But the overseer kept attacking me, without me even putting a single spell on him. No matter how long my enslaved demon hit him he would attack me. I dont know if the demon generates 0 threat or if its actual threat is transfered to me. 

Also brought to my attention on Maulgaur. when i enslaved the fel hund and attacked Olm the summoner, all of sudden i got aggro from Olm. 

+ in that case, on maulgaur i enslaved the demon but i only got one skill, (should have 3, dispels + taunt). I will check my spellbook next time we do the encounter to see if the skills are in there.

Cheers
Daniel

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/919
