### ISSUE TITLE
Broken Tooth

### ISSUE THREAD

**Issue by nenthehunter** [Looking4Group/L4G_Core#3671]
Hi,

The attack speed of the rare mob "broken tooth" is to slow. It is 2.0 now and should be 1.0 making it one of the fastest pets in the game.

Please fix if possible.

/Nen

**Comment by silasftw** [comment]
Im not 100% sure but i think they changed that, this pet was legendary in Vanilla and very rare. I was a hunter myself and camped his roaming routes every night for 2 weeks.

**Comment by tst12** [comment]
its 2.4.3 for classes

**Comment by AnonXS** [comment]
http://wowwiki.wikia.com/wiki/Broken_Tooth

However, since pet speed normalization in patch 2.0.1 he has lost this ability and is no longer considered a pet to strive for.
