### ISSUE TITLE
Bloodgem Crystals quest in Netherstorm does not work.

### ISSUE THREAD

**Issue by Popmycherry** [Looking4Group/L4G_Core#3672]
As title says, the quest does not work. When you get a shard and try to siphon them, it channels for like half a second and you don't get it completed.

**Comment by AnonXS** [comment]
Dubliate https://github.com/Looking4Group/L4G_Core/issues/2795

Just use more than one without turning camera.

**Comment by Popmycherry** [comment]
Alright, this did work.
