### ISSUE TITLE
Quest: Showdown.

### ISSUE THREAD

**Issue by Bearrman** [Looking4Group/L4G_Core#3679]
The previous Rexxars spawned from blowing the horn wont despawn and just stand there, they help in the fight but once you kill Groc you do not get the quest completed.

**Comment by AnonXS** [comment]
Dubliacte https://github.com/Looking4Group/L4G_Core/issues/1832

You need to get first hit.

**Comment by Bearrman** [comment]
I tried that the second time, didnt work
