### ISSUE TITLE
Quest: Fire at will!

### ISSUE THREAD

**Issue by Bearrman** [Looking4Group/L4G_Core#3682]
Can't fire the cannon from the petbar, nothing happens when you click fire.

**Comment by AnonXS** [comment]
I think this is linked to https://github.com/Looking4Group/L4G_Core/commit/c4d8e6c7dff372b3ab2ffd96e94cc7f251dfafd1.

**Comment by ivanlink** [comment]
Bump for fix!

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/eb5dd4622844a9306584e91ab5863be8885062b2

**Comment by Bearrman** [comment]
It works now, fixed in latest pet patch
