### ISSUE TITLE
SSC Lurker Below

### ISSUE THREAD

**Issue by Bzmode** [Looking4Group/L4G_Core#3688]
Lurker's Whirl is off center from the middle of the circle of water where he is fished up.

**Comment by Twizzerious** [comment]
To add to this (maybe it is part of the same problem). It is extremely hard to find a spot to fish his pool. You constantly get "that cannot be used here" when trying to fish his pool unless u water walk to the center and fish in one particular place towards the outside of the pool.

**Comment by AnonXS** [comment]
http://www.wowhead.com/spell=37363/whirl

https://github.com/Looking4Group/L4G_Core/blob/00f6dc9da8db02cfdaa8a5f939075069a5f806d0/src/scripts/scripts/zone/coilfang_resevoir/serpent_shrine/boss_lurker_below.cpp#L67

https://github.com/Looking4Group/L4G_Core/blob/5e41e70ab15e210faffc6effce79fb7339540dfa/src/game/SpellMgr.cpp#L3451

- Reset his position to the original sniff value

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3614/commits/d5602299cf61a36acfbf6c00541cd812ea654f54
