### ISSUE TITLE
Karazhan Illhoof

### ISSUE THREAD

**Issue by Bzmode** [Looking4Group/L4G_Core#3689]
Demonic Chains spawn where the player was before being teleported to the sacrifice rune.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/blob/master/src/scripts/scripts/zone/karazhan/boss_terestian_illhoof.cpp#L302

SPELL_SACRIFICE should as commented by robinsch port the player to the middle and then the chains should be spawned ontop.

**Comment by Saltgurka** [comment]
This started happening after the falldamage/teleport fix. 

However the way we are summoning the chains are incorrect either way, and using the correct spell solved the issue.

Fixed in https://github.com/Looking4Group/L4G_Core/pull/3692 (not live yet)
