### ISSUE TITLE
[Question] Custom enchant NPC

### ISSUE THREAD

**Issue by markvetwow** [Looking4Group/L4G_Core#3690]
Hello guys, i have a little question,if i can ask you about your custom NPCs here.

So,i found your custom enchanter NPC in scripts and DB. So,this NPC is great. But i have a question.
I tried to make all chants,that he offers,for money. So, i changed ADD_GOSSIP_ITEM to EXTENDED one.

It looks like this:
`Player->ADD_GOSSIP_ITEM_EXTENDED(9,"12 Agility ",EQUIPMENT_SLOT_BACK,34004,"Are you sure?",300000,0);`

But there is a problem. If you accept this offer,NPC don't modify your money,even if value setted in code.
I guess,it's because there is no ModifyMoney code in script,so,how can i pull money modify into NPCs script? :)

**Comment by Xadras** [comment]
Go to Player.cpp and find this function:
void Player::EnchantItem(uint32 spellid, uint8 slot) 
 just add or whatever [here](https://github.com/Looking4Group/L4G_Core/blob/master/src/game/Player.cpp#L22854): ModifyMoney(-2000);

**Comment by markvetwow** [comment]
But if i want to make a specific values for specific chants? What should i do?

**Comment by Xadras** [comment]
check for `pItem->GetProto()->InventoryType`

**Comment by markvetwow** [comment]
Thanks, that worked out!

I'll leave a code that i applied into script(for someone,who can need this too.)

`if (pItem->GetProto()->InventoryType == Id From InventoryType)
		ModifyMoney(MoneyValue in Copper);`
