### ISSUE TITLE
[Crash] Core crashes when you logout or using a command in instances.

### ISSUE THREAD

**Issue by markvetwow** [Looking4Group/L4G_Core#3691]
Well, all issue description in title.

Core version - eb5dd46

Two crash logs:

1) When i typed .revive in a dungeon(on myself of course) - 
[d8467382e9f9426aee9d793a9b06663f3b4f884f_Looking4GroupCore.exe_[5-5_16-29-55].txt](https://github.com/Looking4Group/L4G_Core/files/979181/d8467382e9f9426aee9d793a9b06663f3b4f884f_Looking4GroupCore.exe_.5-5_16-29-55.txt)

2) When i logged out,while in a dungeon - 
[d8467382e9f9426aee9d793a9b06663f3b4f884f_Looking4GroupCore.exe_[5-5_16-34-10].txt](https://github.com/Looking4Group/L4G_Core/files/979182/d8467382e9f9426aee9d793a9b06663f3b4f884f_Looking4GroupCore.exe_.5-5_16-34-10.txt)

Core compiled in x86. When i tried to compile in x64,there was a too many errors. And according to guide,x64 is not supported(but i don't know for sure).

**Comment by AnonXS** [comment]
thats y only x32 compile is supported at the moment.

**Comment by Xadras** [comment]
Hm I really hate those windows crashlogs, I can't find any useful information in there ;D

Did you get some more informations in the Server.log?

**Comment by markvetwow** [comment]
Well,yes. There you will find some info. Something wrong with Database.cpp

[PasteBin.com](https://pastebin.com/RyLq1Hm1)

**Comment by Xadras** [comment]
go to L4G_Core/sql/updates/chars and run the three updates in your characters database ;)

**Comment by markvetwow** [comment]
Yeap,already did that. Everything is okay. Sorry for disturbance,guys. My inattention...

**Comment by Xadras** [comment]
Alright, no problem (:
