### ISSUE TITLE
Pet Abilities

### ISSUE THREAD

**Issue by Lowbird89** [Looking4Group/L4G_Core#3693]
Pet does not (consistently) use its abilities. That applies to long cooldown abilities like Felguard Intercept or Voidwalker aoe-taunt, short cooldown abilities work just fine.

Note: Resummoning does not help/ Autocast does not help/ manual activation of ability does not work either
Note 2: Relogging seems to make those abilities useable *once*

Thanks in advance, kind regards

**Comment by tst12** [comment]
check torment rev https://github.com/Looking4Group/L4G_Core/commit/d8467382e9f9426aee9d793a9b06663f3b4f884f - not confirmed

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3656
