### ISSUE TITLE
Quest:Against the Legion

### ISSUE THREAD

**Issue by MikeStinse** [Looking4Group/L4G_Core#3696]
against all odds and against the illdari work just fine but, against the legion is not available 
http://wowwiki.wikia.com/wiki/Quest:Against_the_Legion

**Comment by tst12** [comment]
prequest Forge Camp: Annihilated

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?quest=10641
Requires

    Forge Camp: Annihilated
