### ISSUE TITLE
Quest Mob: Stonetalon mountains Cenarius mob spawning too many treants

### ISSUE THREAD

**Issue by maliciousrabbit** [Looking4Group/L4G_Core#3697]
The cenarius' mobs in Stonetalon Peak, Stonetalon Mountains is only supposed to have 1 Treant guardian, yet there are spawning up to like 7 or 8. This is making one of the first quests in stonetalon impossible for any class that is not able to kite the mobs in order to kill the 4 cenarius mobs needed for quest.
IGN: swissarmyorc, horde shaman

**Comment by Saltgurka** [comment]
Please look up the creature and/or quest that is not working correctly in the web db: http://db.hellfire-tbc.com/
And then post the link here

**Comment by tst12** [comment]
common problem: the presence of a summoned(pet) dont checked(master killed,pet dont killed - master respawn and summon new pet; master evade and summon new pet) 
https://github.com/Looking4Group/L4G_Core/issues/3467

**Comment by AnonXS** [comment]
Yes, correct core implementation would be, spell summoned creatures (most of them) should despawn when summoner (spellcaster) dies.

But sadly our DB is still at the point where certain pet creatures are now double summoned due to static spawns + eventai based summoning.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3755/commits/1cafaecd6933b0776eab78ea8e269c087be62457
