### ISSUE TITLE
Leothras the blind keeps Resetting/evading

### ISSUE THREAD

**Issue by Twizzerious** [Looking4Group/L4G_Core#3699]
https://www.twitch.tv/videos/140438835
1:21:40 is an example and 1:42:00

Leothras reset on us sub 15% twice ruining out pull. we are tryuing to stay away from the barrels and tents and campfires but they are literally everywhjere in the room and one of the main mechanics is to run away from the whirlwind. Major problem that caused us 3 wipes that should of been a one shot. Completely ruined our progress toniught

It seemed to be resseting around the same time each time. Around 600k health

**Comment by Bzmode** [comment]
make it 3 times it happened

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2821
