### ISSUE TITLE
OHF Heroic: Wrong Loot Table

### ISSUE THREAD

**Issue by Selphius** [Looking4Group/L4G_Core#3700]
My guildmate dropped on OHF hero [The Fel Barrier](http://www.wowhead.com/item=32082/the-fel-barrier) from Last Boss which is a drop from Mana Tombs Heroic Last boss. He said it happened two times already to him.

Aside from that this item is from 2.1.0 patch so it shouldn't be in-game.

**Comment by AnonXS** [comment]
As these items were inserted to balance the preraid gear for classes we decided to leave them in, will correct epoch hunter loottable though, thanks for the report.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3614/commits/70516addde39c14f0ef107f41e3b470e1203fc8b
