### ISSUE TITLE
Ressurection - ressurected person catches combat

### ISSUE THREAD

**Issue by Selphius** [Looking4Group/L4G_Core#3701]
No idea how to properly name this bug, so I will leave it as it is. Problem occurs mostly when "dead" person died in range 1-30yards to mobs/boss. After ressurecting him and he stands up (even 50yards away from this boss/mobs) they catch instantly combat with said person, when on this range it shouldn't be possible. It makes wipe recovery longer and annoying especially on boss fights. If said person leaves the body and you ress him it works fine, but it does not if he stays in the body.

It happened at least 20 times to us in Karazhan raid and some heroics, so it isn't just a temp occurence.

**Comment by Saltgurka** [comment]
Probably related to https://github.com/Looking4Group/L4G_Core/commit/cc165d3ca2f9603945bbef59b940f5f67a18b36c

After that commit it seems like teleports are slightly delayed, causing problems with things like chains in Illhoof fight (https://github.com/Looking4Group/L4G_Core/issues/3689). 
I'm thinking it might be the same issue here, that the small delay is enough for the player to get in combat on ress.

**Comment by AleskiWeb** [comment]
I've had this too. It seems they stand up, then are teleported to you so your theory @Saltgurka would hold some likelyhood.

**Comment by Xadras** [comment]
should be fixed by #3707
