### ISSUE TITLE
Quest: Ledger from Tanaris

### ISSUE THREAD

**Issue by Skarnbob** [Looking4Group/L4G_Core#3702]
I obtained all the required mats for the quest, but it cannot be turned it regardless.
I tried to deposit the Q-items in the bank and take them out - no fix
Tried to relog/reload/reboot WoW - no fix

Screenshot attached -
![wowscrnshot_050617_165651](https://cloud.githubusercontent.com/assets/28487502/25773426/6b887706-327d-11e7-968e-93ef6f7724d7.jpg)

**Comment by ME121989** [comment]
try to abandon the q and take it again

**Comment by Saltgurka** [comment]
Duplicate of https://github.com/Looking4Group/L4G_Core/issues/3479
Abandon and retake quest to solve the issue.
