### ISSUE TITLE
pickpocket

### ISSUE THREAD

**Issue by rayes93** [Looking4Group/L4G_Core#3704]
there is an issue with detection about pickpocketing. Mobs can detect you when u pickpocket them, depends on ur stealth level so thats why lower lv mobs detects you harder.  And usually when you are behind them its realy hard to detect you. 
The problem here is that when you pickpocket from behind mobs detects u regularly and the even more bugged is that mobs detect you while you have sapped them which is totally wrong.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/979
