### ISSUE TITLE
Ruins of Karabor bug

### ISSUE THREAD

**Issue by Balander** [Looking4Group/L4G_Core#3710]
Hey guys. Noticed a bug on Ruins of Karabor on top of BT. 

On the spot where the Demon Hunter training grounds are on the far right side where Netharel patrols there is a tent (?). 

Apparently mages and i assume other classes also can park on top of the hut safe spot pull the npcs they can reach and just aoe them safely. 

Mobs should reset or not be able to be pulled at all from a safe spot but that's not the case here so its pretty much free gold and rep. Should look into it extend the invisible walls so mobs aren't reachable or make them reset properly when pulled like this.

**Comment by Balander** [comment]
You have changed a bit Netharels path compared to old realm btw and the demon hunters act a tad funny also up there at times don't know if its related. Was way smoother on old Hellfire.

**Comment by AnonXS** [comment]
Add mmap ignore flag due to the hugh abuseability of this spot.

**Comment by AnonXS** [comment]
Going to resolve this in https://github.com/Looking4Group/L4G_Core/issues/3728
