### ISSUE TITLE
Quest: Battle of the Crimson Watch

### ISSUE THREAD

**Issue by Bearrman** [Looking4Group/L4G_Core#3712]
The mobs will not spawn after you accept the quest, nothing happens

**Comment by GrimLox** [comment]
Same issue for me and all the other 4 players in my party. It wont start the event and u will keep the q in your log but nothing else.

//DunRingill

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2262
