### ISSUE TITLE
Intervene bug

### ISSUE THREAD

**Issue by Wam93** [Looking4Group/L4G_Core#3714]
Intervene ping pongs you towards your target, back to your original position and then about 3/4 of the way towards the target again. It happens on pretty much every Intervene and is really annoying and just makes tanking as a warrior more of a pain. This seemed to have come about with a pathfinding update a couple days ago.

**Comment by Nykvist** [comment]
bump bump, this is a major thing imo

**Comment by Saltgurka** [comment]
Should be fixed with https://github.com/Looking4Group/L4G_Core/pull/3716
