### ISSUE TITLE
Still unfriendly with Aldor and Scryer

### ISSUE THREAD

**Issue by jace9** [Looking4Group/L4G_Core#3715]
I did the quests to finally pick Aldor or Scryer but when I picked Aldor, I am still unfriendly. Send help!

**Comment by Xadras** [comment]
Let me guess, you are a bloodelf?

**Comment by jace9** [comment]
yes how do i fix it 😂😩

**Comment by AnonXS** [comment]
Reputation gains with the Aldor correspond with a 10% greater loss of reputation with the Scryers. All characters start off as neutral with the Aldor, with the exception of Draenei and Blood Elf characters. Draenei are automatically friendly with the Aldor and unfriendly with the Scryers, whereas blood elf characters are automatically unfriendly with the Aldor and friendly with the Scryers. However, this does not mean that either character is restricted to or prohibited from the Aldor: they may choose to join the Aldor just like any other race of character by completing Neutral 15 [65] Allegiance to the Aldor. 

http://wowwiki.wikia.com/wiki/Aldor
