### ISSUE TITLE
Quest: Frankly, It Makes No Sense

### ISSUE THREAD

**Issue by Bearrman** [Looking4Group/L4G_Core#3718]
Nothing happens when you click the Arcano control units

**Comment by tst12** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2910
https://github.com/Looking4Group/L4G_Core/pull/3549

**Comment by Saltgurka** [comment]
Duplicate of: https://github.com/Looking4Group/L4G_Core/issues/2910
Proposed fix: https://github.com/Looking4Group/L4G_Core/pull/3549

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2910
