### ISSUE TITLE
Can't load Character

### ISSUE THREAD

**Issue by TheLittleLemniscate** [Looking4Group/L4G_Core#3723]
Hello,
My main character on my account is Dreïd a druid.
I took the boat from theramore to menethil and during the downloading phase, The game freeze for 5 min. So i forced the shutdown of the game and restart it. And now I was in Feralas close to Dire Maul.
So earthstone to the temple of Thelhamat and take the fly to the dark portal. 
Then i take the fly from Nethergarde to go to SW. During the fly my game freeze. After waiting 5 min i forced the game to close and now i can't load the character.

**Comment by Xadras** [comment]
I guess an ingame ticket from another character would be better for future but for now I've teleported you to menethil.

The game freezes seems to occur very often at your client, did you try to deactivate addons?

**Comment by TheLittleLemniscate** [comment]
Thank you very much. 

Yes i try to desactivate addon but did nothing.

I did make an ingame but after an hour I try here.

Thanks again
