### ISSUE TITLE
Bug: Feared and/or crowd controlled mobs dont pull/aggro other packs/mobs nearby

### ISSUE THREAD

**Issue by Jalapan** [Looking4Group/L4G_Core#3727]
If you fear a mob in an instance or in the world or sheep/shackle/banish etc and it runs into a pack of similar mobs or if a patrol walks near them , they should be pulled.

Currently when a feared/sheeped etc mob runs around and runs into a patrol or a stationary pack in an instance for example it does not pull them.

**Comment by tst12** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3648

**Comment by AnonXS** [comment]
As far as i know, the formation system http://wiki.looking4group.eu/index.php/Creature_formations messes with the faction aid mechanic, so if you pull a patrol nearby linked creature pack, the faction aid system will not pull the formation, as they only react to if a creature in the pack is pulled.
