### ISSUE TITLE
Demon Hunter Supplicant - Spell cooldowns

### ISSUE THREAD

**Issue by nathanielgarneau** [Looking4Group/L4G_Core#3728]
The Demon Hunter Supplicant outside black temple have a much too low cooldown on their abilities. It should be 60 seconds on the 'reduces the effects of magic abilities' and 60 seconds on the evasion. It appears to be about 10-15 seconds on both currently.  

This reduces this location from being a top farm spot to almost impossible to aoe farm for all classes.

**Comment by Saltgurka** [comment]
Source for timers?

**Comment by nathanielgarneau** [comment]
https://www.burning-crusade.com/database/?spell=36073
Retail experience 
https://youtu.be/kPhODXtyI-g

This is currently impossible as all spell DMG is reduced by 75%. Mobs also evasion much too often.

**Comment by nathanielgarneau** [comment]
Sourcing the exact timer for the spell appears to be difficult. Wowhead has 75seconds but there are multiple ranks with different timers . unsure of which it is or if wowhead is accurate to TBC

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?npc=21179
http://www.wowhead.com/npc=21179/demon-hunter-supplicant
http://www.wowhead.com/spell=37683/evasion

```

DELETE FROM `creature_ai_texts` WHERE `entry` = -1459;
INSERT INTO `creature_ai_texts` VALUES
('-1459','begins intensely dodging incoming attacks.','0','2','0','Demon Hunter Supplicant','0');

-- Demon Hunter Supplicant 21179
DELETE FROM `creature_ai_scripts` WHERE `entryOrGUID` = 21179;
INSERT INTO `creature_ai_scripts` VALUES
('2117901','21179','2','0','100','0','50','0','0','0','1','-1459','0','0','11','37683','0','0','0','0','0','0','Demon Hunter Supplicant - Cast Evasion at 50% HP'),
('2117902','21179','2','0','100','0','25','0','0','0','11','32720','0','0','0','0','0','0','0','0','0','0','Demon Hunter Supplicant - Cast Sprint at 25% HP');

```

Should be hardcoded, just as the Gladiator Packs in SHH, fighting each other to 50% hp and reset.
