### ISSUE TITLE
BUGGED QUEST IN BLADE EGDE MOUNTIONS

### ISSUE THREAD

**Issue by FroggeRa** [Looking4Group/L4G_Core#3729]
[What Came First, the Drake or the Egg?] CANT COMPLETE FIX THIS PLEASE

**Comment by FroggeRa** [comment]
Open egg - Ues item on dragon, turns into big dragon og boss if boss he fly away if big dragon u cant loot GGWP

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/3752

**Comment by FroggeRa** [comment]
Maybe Warmane gonna fix it in 6 days
