### ISSUE TITLE
[Dungeon] Several issues in dungeons

### ISSUE THREAD

**Issue by markvetwow** [Looking4Group/L4G_Core#3732]
Greetings guys,once again!

Found a several issues when i was testing a 5ppl dungeons.

1) Blackheart the Inciter encounter - Shadow Labs - Incite Chaos spell

Tested this in 5 clients(5 windows :D)

It works really-really well in normal mode, but when boss uses this ability in heroic mode,players just standing still and do nothing,while Incite Chaos is active.

2) Laj - Botanica - Resistances problem

So, Laj doesn't apply immunity masks on himself.

No matter of form. Even in his "starting" form - black,he doesn't immune to shadow damage(tested by shadow priest).

Strange issue,all resistances applied through script,on each form.

3) Grandmaster Vorpil - Shadow Labs - Void Traveller effects

Same issue as on Inciter, in heroic mode, Traveller have only 1 effect(1.5k shadow damage explode), Travelers don't heal Vorpil and don't apply shadow damage buff.

I can provide you with video proofs on bosses,if needed.

**Comment by AnonXS** [comment]
1. doesnt matter if heroic or nonheroic uses the same spell: https://github.com/Looking4Group/L4G_Core/blob/5db29dcb30ef0d336e467f61334d8474108b09fa/src/scripts/scripts/zone/aunchindoun/shadow_labyrinth/boss_blackheart_the_inciter.cpp#L28 also Dublicate https://github.com/Looking4Group/L4G_Core/issues/836

2. might be correct Core Script needs adjustments

3. Issue related to Vorpils Adds: https://github.com/Looking4Group/L4G_Core/issues/1896

---

Create a seperate issue for Laj with Sources on how it should be and what color has what spell school immunity.

**Comment by markvetwow** [comment]
I understand that spells are the same in case 1 and 3. But in normal mode, they work correct. checked that
4 times. Adds stacking shadow buff and healing Vorpil, Incite Chaos working on normal mode. Maybe it's a instance difficulty issue?

**Comment by AnonXS** [comment]
afaik players mostly only attack pets (maybe because of hp), but that can be discussed in the respective issues.

Thanks for opening an issue for laj as i suspect that there is a bug as the little plants also have spell school immunities.
