### ISSUE TITLE
Edwina Monzor

### ISSUE THREAD

**Issue by lukasaronsson** [Looking4Group/L4G_Core#3734]
nothing major..edwina monzor in menethil harbor probably doesnt have the right pathing coded in or whatever....keeps on walking around in the air on her cart

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?npc=1462

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3614/commits/1cd3e8fde27821b2db6369a803b93ffefd48878f
