### ISSUE TITLE
[Dungeon] Botanica - Laj. Issue with resistances.

### ISSUE THREAD

**Issue by markvetwow** [Looking4Group/L4G_Core#3735]
In addition to #3732,#1541

According to [WoWWiki.com](http://wowwiki.wikia.com/wiki/Laj),
Laj will also randomly change color. When he does this, he will be resistant to certain types of magic (just like the mobs on both sides of the Botanist). The following are the colors/resistances he can change to:

Blue (Frost Resistant)
Red (Fire Resistant)
Green (Nature Resistant)
Black (Shadow Resistant)
White (Arcane Resistant)

Same info on [WoW.Gamepedia.com](http://wow.gamepedia.com/Laj)

By the way,WoWWiki says that is a resistances,not immunities.

**Comment by markvetwow** [comment]
Well, i tried to change ApplySpellImmune to SetResistance and it looks like "kind of proper" fix.

It looks like this,don't know about correctness of this code. But,it looks better now.
`m_creature->SetResistance(SPELL_SCHOOL_SHADOW, 410);
		m_creature->SetResistance(SPELL_SCHOOL_ARCANE, 0);
		m_creature->SetResistance(SPELL_SCHOOL_FIRE, 0);
		m_creature->SetResistance(SPELL_SCHOOL_NATURE, 0);
		m_creature->SetResistance(SPELL_SCHOOL_FROST, 0);`

410 resistance on each active form.

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?search=Laj idk if these templates are just for show or if we can find info on the resistance value in http://wow.gamepedia.com/The_World_of_Warcraft_Bestiary. But i remember the whole bossfight to be harder and different on retail. It's kinda lacking atm.

**Comment by Xadras** [comment]
I guess the second link is a wrong one ;D

**Comment by AnonXS** [comment]
Well is it available anywhere online?

**Comment by AnonXS** [comment]
No further Info provided.
