### ISSUE TITLE
Vmaps extracted

### ISSUE THREAD

**Issue by joinjold** [Looking4Group/L4G_Core#3743]
Vmaps can not extract. Prompt 547 path, modified, still can not extract.
Hope that good people can send out a good SkyDrive link.

**Comment by Xadras** [comment]
I guess you are doing something wrong, normally the extractors work as intended

**Comment by AbaddonL4G** [comment]
just c&p the extractor in your wow folder - working flawless for me

**Comment by joinjold** [comment]
2017年05月13日  2:31:44: Start extraction of vmaps...
Extract V3.00 2010_07. Beginning work ....

Game path: E:\547\Data\

Adding data files from locale directories.
Scanning patch levels from data directory.
Scanning patch levels from locale directories.

no locale found
Opening E:\547\Data\common.MPQ
Opening E:\547\Data\expansion.MPQ
Opening E:\547\Data\patch.MPQ
Opening E:\547\Data\patch-2.MPQ
Read LiquidType.dbc file...Fatal error: Invalid LiquidType.dbc file format!
2017年05月13日  2:31:44: Extracting of vmaps finished
mkdir: cannot create directory ‘vmaps’: File exists
2017年05月13日  2:31:44: Start assembling of vmaps...
Could not read dir_bin file!
exit with errors
2017年05月13日  2:31:45: Assembling of vmaps finished

**Comment by AnonXS** [comment]
Maybe Client related, idk.

**Comment by joinjold** [comment]
Did you extract it properly? Can you send me a map file?

**Comment by AnonXS** [comment]
Extractor Tools have to be used in the folder where the wow.exe is located.

Maybe follwing this guid helps you out: https://wiki.oregon-core.net/index.php/Extracting_client_data_(DBC,_Maps,_VMaps,_MMaps).
