### ISSUE TITLE
Karazhan: Nightbane Skeleteon adds wont despawn on whipe

### ISSUE THREAD

**Issue by Jalapan** [Looking4Group/L4G_Core#3746]
If party whipes while on phase 2 on Nightbane the Adds that spawn wont despawn and will stay there untill next fight.

http://www.wowhead.com/npc=17261/restless-skeleton

**Comment by AnonXS** [comment]
Spell summoned, not hardcoded. http://db.hellfire-tbc.com/?spell=30170
Spell does not have duration so they are spawned permanently/despawned otherwise.

---

Resolve with EAI
