### ISSUE TITLE
Rampars (heroic) endboss adds respawm infight - boss can be spawmed twice

### ISSUE THREAD

**Issue by padomu** [Looking4Group/L4G_Core#3748]
Hi,

today in ramps hc teh following happened.

Our pala tank pulled the 2 adds from the endboss at ramps heroic. He then sat down and drank. The boss was dropped by the dragon but didn't attack him. He kept drinking and suddendly the adds repsawmed and he instantly added them - so we killed them again. Then, the dragon dropped a second one of this boss.

**Comment by AnonXS** [comment]
Should not be able to drink, boss should instant aggro the group when he comes down.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/916, Core Scripts needs some savety adjustments.
