### ISSUE TITLE
[Raid Instance] Karazhan - Chess Event - Prepare Chess Desk pos.

### ISSUE THREAD

**Issue by markvetwow** [Looking4Group/L4G_Core#3750]
Greetings,once again.

There is no many to describe about issue. Just a little wrong chess figures pos calculation on prepare stage.

There is a screenshot.

![wowscrnshot_051317_072258](https://cloud.githubusercontent.com/assets/24928567/26022395/47da7e82-37ad-11e7-9a10-9bf0fd72a1c2.jpg)

**Comment by AnonXS** [comment]
Its related to the pathing change which brings hugh stability.

**Comment by AnonXS** [comment]
Going to Dublicate all these Issues to a Master Issue https://github.com/Looking4Group/L4G_Core/issues/2817
