### ISSUE TITLE
Hunter Pet Loyalty not functional

### ISSUE THREAD

**Issue by Russet0** [Looking4Group/L4G_Core#3756]
No pets are gaining loyalty, no matter how much they are fed (happiness is max green) and how much experience is gained (pets are always Loyalty Level 1 even after both hunter/pet gain multiple levels after taming).

This pet had gained levels from 19 to 29 and ran away about 1 minute after this screenshot was taken: http://i.imgur.com/OS59UDs.jpg

This has persisted from level 10 up through level 55, and is extremely debilitating, since no pet skills can be trained at level 1 and going around finding new pets is a big time sink. New pets are also underleveled and can't hold aggro.

Reference character is "Russet" on Hellfire Realm II (Progressive).

**Comment by AnonXS** [comment]
Maybe linked to: https://github.com/Looking4Group/L4G_Core/commit/a9e834d269a4534dbf8b3f07285d7c3f91e6f43e

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/3241
