### ISSUE TITLE
Bug: Paladin resistance aura and motw/gotw dont stack

### ISSUE THREAD

**Issue by Jalapan** [Looking4Group/L4G_Core#3760]
When a paladin resistance aura is active it gives 70 resistance to that school.
Then with druid buff mark of the wild or gift of the wild it gives you 25 more resistance.

However with both the druid buff and paladin aura it still yields only 70 resistance to that school.

And the mark of the wild and gift of the wild gives 0 resistance to all school instead of 25 at max rank

**Comment by AnonXS** [comment]
Maybe linked to: https://github.com/Looking4Group/L4G_Core/commit/a9e834d269a4534dbf8b3f07285d7c3f91e6f43e, worked befor.

**Comment by Xadras** [comment]
nonono.
Resistances never ever stacked from buffs / auras.

Mark of the wild:
"The resistance benefit of any rank of this spell does not stack with other resistance buffs. See Resistances for more information."
-- http://wowwiki.wikia.com/wiki/Mark_of_the_Wild?oldid=1641765

**Comment by AbaddonL4G** [comment]
working as intended
