### ISSUE TITLE
Warrior quest auto screen freez

### ISSUE THREAD

**Issue by gaara10** [Looking4Group/L4G_Core#3762]
I get the warrior quest in Redrige Mountains and i get instantly screen freez even if i relog i get again and i cant do anything :/

**Comment by Xadras** [comment]
In most scenarios this is caused by addons. Try without.
If this does not help, please provide the quest: http://db.hellfire-tbc.com

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/1458
