### ISSUE TITLE
Quest : Plundering the Plunderers

### ISSUE THREAD

**Issue by Wodjee** [Looking4Group/L4G_Core#3769]
1) from quest description : "Do not forget to get an E.C.A.C. and Thieves' Tools from Wrenix's Gizmotronic Apparatus."
--> It does not give me anything, no thieves tools and no E.C.A.C

2) When I lockpick the chests on the boat after a few tries per chest (~3) they stay open and I can no longer train the lockpicking

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/3503
