### ISSUE TITLE
Bug: Parched Hydra & Writered Gaint/Bog Lord

### ISSUE THREAD

**Issue by bwehrke** [Looking4Group/L4G_Core#3771]
I couldn't find anything via the search at the top for Parched Hydra

These mob seems to overspam their respective abilities.
Parched Hydra - Heat Wave
Bog Lord - Osmosis
Withered Giant - Osmosis

Video showing how they interacted with a warlock.
https://www.youtube.com/watch?v=xD9ywbSm51Y

https://www.burning-crusade.com/database/?npc=20324
https://www.burning-crusade.com/database/?npc=19402
https://www.burning-crusade.com/database/?npc=18124

**Comment by AnonXS** [comment]
```

-- Parched Hydra
('2032401','20324','9','0','100','1','0','10','9000','14000','11','35236','0','0','0','0','0','0','0','0','0','0','Parched Hydra - Cast Heat Wave'),

-- Withered Bog Lord
('1940201','19402','9','0','100','1','0','5','12000','16000','11','35238','1','0','0','0','0','0','0','0','0','0','Withered Bog Lord - Cast War Stomp'),
('1940202','19402','0','0','100','1','6000','11000','8000','14000','11','35235','0','0','0','0','0','0','0','0','0','0','Withered Bog Lord - Cast Osmosis'),

-- Withered Giant
('1812401','18124','0','0','100','1','6000','11000','8000','14000','11','35235','0','0','0','0','0','0','0','0','0','0','Withered Giant - Cast Osmosis'),

```

Compare to current EAI

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3755/commits/83acaf8307c099a181d85b692a6d07cf4c6a57be
