### ISSUE TITLE
Cat Carrier (Siamese)

### ISSUE THREAD

**Issue by kferguso** [Looking4Group/L4G_Core#3772]
The cat carrier received from Deadmines does not activate when used.

Right clicked, it says "Using this item will bind it to you" then I click ok and it does nothing after that point

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?item=8490

**Comment by AnonXS** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/26446361/fe1a9232-4143-11e7-9ee5-b13b6c43e0ef.PNG)

works without issues, accepting the bounding, it gets cast, cat is summoned and follows, if it doesnt work for you, try deactivating some addons.
