### ISSUE TITLE
Bug: Dire Raven in Blade's Edge cannot teach Screech (Rank 5)

### ISSUE THREAD

**Issue by Russet0** [Looking4Group/L4G_Core#3782]
I tamed a Dire Raven level 68 in the Raven's Wood area of BEM in order to try to learn Screech on my Hunter.

I spent 20-30 minutes attacking mobs while using screech and not attacking with my character. Spam used screech manually and left it auto-cast. Never learned any ranks.

I went to Nagrand and tamed a Greater Windroc and learned Screech (all 5 ranks) within seconds (2-3 casts).

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?npc=21042, http://db.hellfire-tbc.com/?npc=17129

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3755/commits/c0762f05d699af99bf05d7b34605bab3877cd8c7
