### ISSUE TITLE
[Pattern: Quiver of a Thousand Feathers] not at the Lower City rep vendor

### ISSUE THREAD

**Issue by Maxmekker2** [Looking4Group/L4G_Core#3790]
Noticed that [Pattern: Quiver of a Thousand Feathers] is not an option to buy from Nakodu <Lower City Quartermaster>, as of today i dinged revered with Lower City, and was looking forward to craft myself a new Quiver, but he is not selling it.

**Comment by AnonXS** [comment]
Patch 2.3.0 (13-Nov-2007): Added.

http://wowwiki.wikia.com/wiki/Pattern:_Quiver_of_a_Thousand_Feathers
