### ISSUE TITLE
Recipe: Major Dreamless Sleep Potion (unavailable?)

### ISSUE THREAD

**Issue by Blaicey** [Looking4Group/L4G_Core#3792]
Hey guys,

"Recipe: Major Dreamless Sleep Potion" is usually bought from vendor Daga Ramba in Blade's Edge (H). I've been there multiple times now and it has no slot, nor is it even greyed out. I'm pretty sure this item was included pre-2.4.3, and maybe even at launch. The recipe creates a level 70 item (which I'm not at yet) but I didn't think this would make a difference to its availability for purchase. Any clarification would be appreciated.

Greetings from Australia

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3755/commits/e1d5f2798053624bfd315f5772452904c7e16fc5
