### ISSUE TITLE
Bug: Farahlon Breaker does not shrink and create adds when brought below threshholds

### ISSUE THREAD

**Issue by Russet0** [Looking4Group/L4G_Core#3793]
The Farahlon Breaker giant elites in Netherstorm (objective of the quest "In Search of Farahlite") do not shrink and spawn an add as they are supposed to when brought below 75%/50%/25% HP (3 adds in total) when not stunned.

If stunned while crossing these HP markers the mob should not spawn an add. If all 3 adds spawn the Breaker will be the same size as the tiny crumblers once below 25% HP.

Quest: http://db.hellfire-tbc.com/?quest=10290
Mob: http://db.hellfire-tbc.com/?npc=18886
Add: http://db.hellfire-tbc.com/?npc=21077 (does not spawn)

Wowhead versions:
http://www.wowhead.com/npc=18886/farahlon-breaker
http://www.wowhead.com/npc=18886/farahlon-breaker
http://www.wowhead.com/npc=21077/farahlon-crumbler

**Comment by Russet0** [comment]
Also, the comparable mob in Hellfire Peninsula, Raging Colossus, does split and spawn adds as this mob should be doing. Can look at that code for the proper behavior.

http://db.hellfire-tbc.com/?npc=19188
http://db.hellfire-tbc.com/?quest=10134

**Comment by AnonXS** [comment]
https://github.com/TrinityCore/TrinityCore/blob/a249d86b00eb0854cb925f8bea76ddbb364208df/sql/old/3.3.5a/TDB41_to_TDB42_updates/world/2011_07_01_00_world_waypoint_data.sql#L1756

```
SELECT * FROM `creature_template` WHERE `entry` IN (18886,21077,18885,21078);

DELETE FROM `creature_ai_scripts` WHERE `entryOrGUID` = 18886;
INSERT INTO `creature_ai_scripts` VALUES
('1888601','18886','0','0','100','1','3000','6000','4000','8000','11','11428','1','0','0','0','0','0','0','0','0','0','Farahlon Breaker - Cast Venom Knockdown'),
('1888602','18886','9','0','100','1','0','5','3000','6000','11','33688','1','0','0','0','0','0','0','0','0','0','Farahlon Breaker - Cast Crystal Strike'),
-- ('1888603','18886','2','0','100','0','20','0','0','0','11','18501','0','0','1','-46','0','0','0','0','0','0','Farahlon Breaker - Cast Enrage When Below 20% HP'),
('1888604','18886','2','0','100','0','75','0','0','0','12','21078','1','0','0','0','0','0','0','0','0','0','Farahlon Breaker - Summon Farahlon Shardling on 75% HP'),
('1888605','18886','2','0','100','0','50','0','0','0','12','21078','1','0','0','0','0','0','0','0','0','0','Farahlon Breaker - Summon Farahlon Shardling on 50% HP'),
('1888606','18886','2','0','100','0','25','0','0','0','12','21078','1','0','0','0','0','0','0','0','0','0','Farahlon Breaker - Summon Farahlon Shardling on 25% HP');

```

http://www.wowhead.com/npc=18886/farahlon-breaker#comments
http://www.wowhead.com/npc=21078/farahlon-shardling

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3755/commits/b61c790d299cc368ce4c7ca84be68b38602df066
