### ISSUE TITLE
Bug: Torching Sunfury Hold Tents/Ballistas do not get burned

### ISSUE THREAD

**Issue by Russet0** [Looking4Group/L4G_Core#3796]
The Torching Sunfury Hold quest in Netherstorm (from Image of Archmage Vargoth) is bugged, when you use a torch to get quest credit the object is not destroyed/"used up."

This means that you can just spam the same 2 objects and complete the quest, rather than 8 as is intended.

Quest: http://db.hellfire-tbc.com/?quest=10233

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?npc=19723, http://db.hellfire-tbc.com/?npc=19724 interaction with spell http://db.hellfire-tbc.com/?spell=34526

EAI to Despawn on Spellhit.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3755/commits/81b809642f9aaa845fc10d515844c4fbc37ce56f
