### ISSUE TITLE
Bug: Feign Death becomes inactive if used right before player death

### ISSUE THREAD

**Issue by Russet0** [Looking4Group/L4G_Core#3797]
Hunter spell bug. I have had this happen to me 3 or 4 times now, and I think I've narrowed it down to a probable cause. The situation is that sometimes after dying and resing, Feign Death will bug and become unable to be activated forever. "That ability is not ready yet."

The only way to fix it and allow feign death to be used again is to log out and back in.

I believe the bug happens when you attempt to use feign death and then die very soon after (like to a spell that is midair). More testing can hopefully reveal a specific reason why this happens, but I believe it is reproducible.

Screenshot of before relogging: http://i.imgur.com/aNDetwK.jpg

Screenshot of after relogging: http://i.imgur.com/X1rNIHC.png

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/304
