### ISSUE TITLE
Missing Formula / Plan?

### ISSUE THREAD

**Issue by Beat0204** [Looking4Group/L4G_Core#3805]
Hi
I am a blacksmith and enchanter and i went out there to farm for some 3ish hour on each mob to get some formula / plan. I asked other players for the last week and none had one of the 3 formula / plan.

1) Voidshrieker in Netherstorm for [Formula: Enchant Cloak - Greater Shadow Resistance](http://www.wowhead.com/item=28277/formula-enchant-cloak-greater-shadow-resistance#dropped-by)
2) Sunfury Bloodwarder in Netherstorm for [Plans: Greater Ward of Shielding](http://www.wowhead.com/item=23639/plans-greater-ward-of-shielding)
3) Eclipsion Archmage in Shadowmoon Valley for [Formula: Enchant Cloak - Greater Arcane Resistance](http://www.wowhead.com/item=28276/formula-enchant-cloak-greater-arcane-resistance)

All formula / plans were added in 2.0.1.6180, so they should be available. Can you please check this?
Thanks

**Comment by AnonXS** [comment]
I looked up 28277 just recently and it does drop, will check 23639 and 28276.

**Comment by Beat0204** [comment]
Thanks for the fast response. Can you maybe check what droprate the formula / plan have? It feels like below 1%

**Comment by AnonXS** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/26521759/a2747f0c-42f0-11e7-83be-2612862c347d.PNG)
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/26521760/b7c6165e-42f0-11e7-9af6-5095336e70f8.PNG)
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/26521764/d00ff036-42f0-11e7-847e-118fd8d86f7e.PNG)
