### ISSUE TITLE
Respec Token only usable at 1 NPC

### ISSUE THREAD

**Issue by padomu** [Looking4Group/L4G_Core#3807]
Hi,

as a Nightelf Rogue I have to go toDarnassus to the Male NPC to use my respec token. I was told it should be usable at any teacher, so this might be a bug. If it isn't, change it anyway since this just sucks and is unfair since Darnassus is just an useless city.

**Comment by Saltgurka** [comment]
The reason is this shitty script that most rogues have: https://github.com/Looking4Group/L4G_Core/blob/5db29dcb30ef0d336e467f61334d8474108b09fa/src/scripts/scripts/npc/npcs_special.cpp#L785

It overwrites the default class trainer gossip menus

**Comment by Saltgurka** [comment]
Solved with https://github.com/Looking4Group/L4G_Core/pull/3819 (Not live yet)
