### ISSUE TITLE
Grand Commander Ruusk is friendly even without a disguise

### ISSUE THREAD

**Issue by Russet0** [Looking4Group/L4G_Core#3811]
Grand Commander Ruusk is the NPC that needs to be talked to during the quest "What Illidan Wants, Illidan Gets..." in Shadowmoon Valley, which is part of the Borak's charge segment of the Cipher of Damnation quest line.

The player is given a Blood Elf Disguise quest item which they are supposed to use in order to be able to talk with Ruusk.

However, Ruusk is friendly to both factions even without the disguise active. He should only be friendly when the disguise buff is active on the player.

Quest can be completed in current state.

Quest: http://db.hellfire-tbc.com/?quest=10577
Ruusk: http://db.hellfire-tbc.com/?npc=20563
Disguise: http://db.hellfire-tbc.com/?item=30639

**Comment by AnonXS** [comment]
As the Disguise works for the other Bloodelves, (except the dragonhawks maybe bug or because they are animals) it seems save to change his faction and test if it still works or if he needs some special faction to be interactable.

**Comment by Xadras** [comment]
That the dragonhawks are unfriendly even with the buff is intended ^^

**Comment by AnonXS** [comment]
There is also quite alot pathing missing in that area.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3755/commits/a7974c30fdeb376654d614c9e9828e5a8bd39956
