### ISSUE TITLE
Quest : Dimensius the all devouring

### ISSUE THREAD

**Issue by palenius** [Looking4Group/L4G_Core#3813]
There is a problem with the player not getting the quest progress for the object "Dimensius the all devouring slain 0/1"

Tried 5x times killing him. Not single time did get the progression. Neither did mates in the party of mine. We tried killing him without killing the adds that spawn and with killing the adds. We also killed him 3x with US engaging the fight. not the captains crew.

**Comment by Xadras** [comment]
maybe you were in a battlegroup?

**Comment by palenius** [comment]
nope

**Comment by palenius** [comment]
Edit: tried after server reset, still doesnt work

**Comment by palenius** [comment]
Edit: if u go 5man party full nuke the boss in 1min. you will get objective. lol what a noob quest u cant even 2man it (well u can, but u cant)
