### ISSUE TITLE
Item : Mage-Fury Girdle - No sell price

### ISSUE THREAD

**Issue by honeyhoney** [Looking4Group/L4G_Core#3814]
http://db.hellfire-tbc.com/?item=27742
No sell price in-game.

**Comment by AnonXS** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/26528963/1fbf5a9c-43b7-11e7-8f08-b35106e8fb9a.PNG)
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/26528967/3bf2a584-43b7-11e7-9469-7a518907ed5a.PNG)

You were tricked by your selling price addon.
