### ISSUE TITLE
Incorrect droprate on Gorefiend's Truncheon from Ghostriders of Karabor

### ISSUE THREAD

**Issue by Russet0** [Looking4Group/L4G_Core#3815]
Ghostriders of Karabor patrol Shadowmoon Valley in a counterclockwise path around the main road loop. They need to be killed for Divination: Gorefiend's Truncheon.

The drop rate on the quest item is supposed to be 100%, as the Wowhead comments here indicate: http://www.wowhead.com/quest=10636/divination-gorefiends-truncheon

In the current version I had to kill 7 or 8 of them before the item dropped. (Problematic since there are only 4 of them at a time.)

Quest: http://db.hellfire-tbc.com/?quest=10636
Target NPC: http://db.hellfire-tbc.com/?npc=21784
Item drop: http://db.hellfire-tbc.com/?item=30800

Separate issue: They also have trouble sticking together. I traveled clockwise to meet them head-on and encountered them in 3 different bunches, separated by quite some distance (hundreds of yards at least). They are supposed to be a pack.

**Comment by AnonXS** [comment]
formation moving looks exremly bad at higher speeds, thats y i took it out but as rather formations should be fixed than "hackfixing" single groups, i am putting it back in.

Also increasing the droprate

**Comment by AnonXS** [comment]
```

-- Gorefiend's Truncheon 
UPDATE `creature_loot_template` SET `ChanceOrQuestChance` = -80 WHERE `entry` = 21784 AND `item` = 30800;

```

Just because one guy states that it dropped for him on first npc, doesnt mean its 100%, so only increasing to 80%.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3755/commits/e7f14117e85693c5448af4dcfb251c28393795f5
