### ISSUE TITLE
Shattered Necklase - Drop-item that gives quest never dropped (Uldaman)

### ISSUE THREAD

**Issue by Valerate** [Looking4Group/L4G_Core#3817]
Hi

I tried to get every quest ready for when I was doing Uldaman, and this was the only one I couldn't get. I farmed mobs outside for a couple of hours (they drop a load of silk aswell which was nice) but I never got one.

Issue: The "Shattered Necklace" drop-quest from Uldaman never dropped
Where: Outside/inside Uldaman dungeon in Badlands.

http://db.vanillagaming.org/?item=7666#dropped-by
http://www.wowhead.com/quest=2198/the-shattered-necklace
You didnt have the item in the Hellfire wiki either

I read that they removed it in Wotlk, but I assumed it should still exsist on a tbc server?

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?item=7666

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3843/commits/356a8d9b4b9395156bf1218012c40a7d3012650a
