### ISSUE TITLE
Heroic epic gems.

### ISSUE THREAD

**Issue by Quinzy** [Looking4Group/L4G_Core#3818]
So It seems that heroic epic gems are removed from the loottable, altough they should be ingame already

http://wow.gamepedia.com/Beaming_Fire_Opal
http://wow.gamepedia.com/Vivid_Chrysoprase
http://wow.gamepedia.com/Inscribed_Fire_Opal
Etc.

See the patch they where added.

**Comment by AnonXS** [comment]
http://www.wowhead.com/item=30583/timeless-tanzanite#comments
http://wow.gamepedia.com/Inscribed_Fire_Opal
http://www.wowhead.com/item=30584/inscribed-fire-opal#comments

By Gruffian (1,445 – 13·11) on 2007/02/15 (Patch 2.0.8)		
Dropped from Heroic Mana Tombs. Nexus-Prince Shaffar.

http://www.wowhead.com/item=30585/polished-fire-opal#comments

It seems they were added pre 2.1 so i guess we could activate them.

**Comment by Russet0** [comment]
Confirmed, they were available at launch.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3755/commits/b3d0cc76eba8a2dfbc3f0647bcef077090e54acb
