### ISSUE TITLE
Bug: Some NPC chatter text in Shattrath has a bad reference ("$G")

### ISSUE THREAD

**Issue by Russet0** [Looking4Group/L4G_Core#3823]
The "Vagrant" NPC chatter text in Shattrath (Lower City) can show up incorrectly: http://i.imgur.com/BPpiudj.png

"Hey, $G man:lady;? Got some money? I got five kids to feed!"

Very small bug, but since it's Shattrath and a lot of people will be spending a lot of time in the city and will therefore see this chat a lot, it seemed worth documenting.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/467
