### ISSUE TITLE
Clever Traps

### ISSUE THREAD

**Issue by Silbotronic** [Looking4Group/L4G_Core#3827]
**How it currently works:** The hunter talent Clever Traps only increases the duration of Frost Trap and Freezing Trap.

**How it should work:** It should also increase the damage of Immolation Trap and Explosive Trap by 30% as well as increasing the amount of snakes summoned by Snake Trap by 30%.

http://db.hellfire-tbc.com/?spell=19245

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/2409
