### ISSUE TITLE
Bug: Outlands Leatherworking trainers missing certain recipes

### ISSUE THREAD

**Issue by Russet0** [Looking4Group/L4G_Core#3828]
The following spells are listed in the database as being available from the Master Leatherworking trainers in outlands (4), but are not able to be trained regardless of LW skill:

Knothide Quiver: http://db.hellfire-tbc.com/?spell=44344
Knothide Ammo Pouch: http://db.hellfire-tbc.com/?spell=44343
Heavy Knothide Armor Kit: http://db.hellfire-tbc.com/?spell=44970
Glove Reinforcements: http://db.hellfire-tbc.com/?spell=44770

The trainers are:
Darmari: http://db.hellfire-tbc.com/?npc=19187
Barim Spilthoof: http://db.hellfire-tbc.com/?npc=18754
Grikka: http://db.hellfire-tbc.com/?npc=21087
Brumman: http://db.hellfire-tbc.com/?npc=18771

**Comment by AnonXS** [comment]
Most likely all taken out due to patch.

**Comment by AnonXS** [comment]
All Patch 2.3.0 Items / Trainer Spells.
