### ISSUE TITLE
Recipe: Charred Bear Kabobs

### ISSUE THREAD

**Issue by rdouze** [Looking4Group/L4G_Core#3829]
Recipe: Charred Bear Kabobs are no script for HORDE
Recipe: Juicy Bear Burger are no script too for HORDE

Bale (npc=2806) don't sell this 2 recipe

**Comment by rdouze** [comment]
felwood in 34/53

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/3538
