### ISSUE TITLE
Bug: Goblin Sponsorship

### ISSUE THREAD

**Issue by Senedra** [Looking4Group/L4G_Core#3830]
been trying to do this quest,i can loot the key from Foreman Cozzle,but when i try to open the chest for the blueprints it just *poff*gone,even if i team up with someone i ca´t loot it it´s annoying

**Comment by AnonXS** [comment]
It works but there is sometimes bad interaction while looting gameobjects, maybe related to looting from too far away, it works with either autoloot on or off.

**Comment by AnonXS** [comment]
Anyways Dublicate https://github.com/Looking4Group/L4G_Core/issues/3399
