### ISSUE TITLE
Quest: Showdown (Rexxar) Blades Edge

### ISSUE THREAD

**Issue by Virtago** [Looking4Group/L4G_Core#3831]
Completed the quest showdown in blades edge from Rexxar and I had selected Clefthoof hide leggings the icon was 100% selected/highlighted and it gave me the oilcloth breeches instead? Prior to this Rexxar was disappearing and reappearing, I was freezing when he was appearing and had him targeted and I had to run back and forth from him to the inn and log in and out several times before I could even turn in the last part of the quest to him.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/1832
