### ISSUE TITLE
Bug: The Second Trial

### ISSUE THREAD

**Issue by popefreedom** [Looking4Group/L4G_Core#3832]
On my paladin, doing this questline, i go to Kelerun Bloodmourn, i'm supposed to turn in a quest to him but when i interact with him, the quest thing is not there and all I get is "greetings." Relogged, even deleted my WTF and cache folder too.

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/3417
