### ISSUE TITLE
Paladin´s second Class quest: The Second Trial Unable to Complete

### ISSUE THREAD

**Issue by kelinicus** [Looking4Group/L4G_Core#3836]
I got my second Paladin class quest at lvl 21 in Silvermoon. The quests consist into finding an Npc Master Kelerum Bloodmourn and reporting to him in order to advance in the quest chain. However once I reach, find the npc and talk to him I am unable to complete, therefore unable to advance in the class quest chain. Ill attach an screenshot were you can check coordinates and see the issue
![wowscrnshot_052817_180603](https://cloud.githubusercontent.com/assets/29028498/26532883/feec47d2-43d2-11e7-8342-b758e411fa69.jpg)

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/3417
