### ISSUE TITLE
vein and random repop

### ISSUE THREAD

**Issue by rdouze** [Looking4Group/L4G_Core#3838]
in vanilla
bc
tlk
all vein are fix, repop at same location.

in your server, repop are random =bug

**Comment by AnonXS** [comment]
Source

**Comment by rdouze** [comment]
don't existe any source in this time.
but if you have play at WoW since vanilla, you use gatherer for remember vein, on vanilla, bc and tlk (after i have stop)
so why use gatherer if vein have random repop ...

**Comment by rdouze** [comment]
okk nice search hellfire
i understand why all people leave x')
refus real script
lot of bug
continue it's good

**Comment by AnonXS** [comment]
https://www.gamefaqs.com/boards/534914-world-of-warcraft/53740197

**Comment by rdouze** [comment]
your link isn't SOURCE but if you have eyes you can see
7 years ago
thanks for defend my ticket

people use gathere there are 7years so in 2010 > cataclysme
