### ISSUE TITLE
Unchained Doombringer isn't dropping anything. He should drop rare BS plans which sucks. 

### ISSUE THREAD

**Issue by moyaspeed** [Looking4Group/L4G_Core#3847]
Hello. 

So, in Arcatraz there are 2 Unchained Doombringer mobs before the last boss. 
Those two mobs drop Plans: Felsteel Leggings and many other trash stuff. 
http://www.wowhead.com/npc=20900/unchained-doombringer 

I have ran that instance quite some times and noticed they never drop anything. Always empty, not even trash items. It sucks because people wan't to get those plans which are very useful in the game. 

Please fix this. : )

**Comment by AnonXS** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/26766280/98b414ec-498e-11e7-85e0-0359ce9adcc8.PNG)

**Comment by moyaspeed** [comment]
Hum, I had killed them at least 10 times. NOT EVEN TRASH DROPPED
I understand the plans have a low drop rate but they should drop trash items often. 
Something is bugged there and it should be checked.

**Comment by AnonXS** [comment]
yes these simply dont have "trash" items as loot implemented.

**Comment by moyaspeed** [comment]
I see. If I may ask, how many runs did it took you to get the plans? Also, you are alliance right? Never seen a horde with it

**Comment by AnonXS** [comment]
Well just to test i teleported myself in and killed the npc a few times.

**Comment by moyaspeed** [comment]
Oh you have admin rights. Alright, thanks for the info, I will continue my farm runs then :)

**Comment by AnonXS** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/19734826/26766465/9f13b366-4992-11e7-938e-b0b32f48aace.PNG)

much better.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3843/commits/b4cf648a1752a4f9ef44da040c365a2a726c5a7b
