### ISSUE TITLE
Pet abilities tab missing

### ISSUE THREAD

**Issue by Priym** [Looking4Group/L4G_Core#3850]
I can´t see my pet´s abilities or select it in the abilities tab. I´m not able to use my pet´s growl, cobra reflexes or any of them. Help please:)

**Comment by AnonXS** [comment]
Need to learn them by playing with different pets.

http://www.tentonhammer.com/guides/wow-hunter-guide-pet-skill-list-page-1

**Comment by Priym** [comment]
I leveled up with a boar and a cat I got the claw abilities from the cat. But now i have a ravager and it's abilities and the one from my cat are no longer visable. I can't but any of the abilities from any off the pets I used because when I open up the abilities tab for me the tab for my pet is missing. I checked with my pet trainer and my pet (ravager) has learned cobra reflexes and growl but I can't use them because there is no tab bar to set it on my action bar.
