### ISSUE TITLE
stack smashing detected

### ISSUE THREAD

**Issue by joinjold** [Looking4Group/L4G_Core#3852]
WORLD: World initialized

TC> *** stack smashing detected ***: ./looking4groupcore terminated
Aborted (core dumped)

It crashes when my client logs in
I checked the log without information.

**Comment by Xadras** [comment]
Well, it's hard to even make suggestions without a log :|
Did you check the server.log and db_errors.log, too?

**Comment by joinjold** [comment]
I checked the database today and found the db_errors.log bug. I don't know if it's here.
TSCR: Entry -1811004 in table `script_texts` has Type 7 but this Chat Type does not exist

Database script_texts data I also sent up.
	(-1811004, 'takes a deep breath', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 7, 0, 0, 'felmyst EMOTE_BREATH'),
Is there anyone who can give me a reply?

**Comment by AnonXS** [comment]
type 7 was never excluded from being outputted in the error log, same as other false errors like GUID as ID in creature_ai_scripts.

**Comment by Xadras** [comment]
Well, whatever, that's not the crash-issue. Just a guess: Did you apply all the realm & char database updates?

**Comment by Rapth** [comment]
hi friend .have you found a solution of this？
