### ISSUE TITLE
Loot Disappearing

### ISSUE THREAD

**Issue by Bbenna** [Looking4Group/L4G_Core#3853]
Quest: http://www.wowhead.com/quest=11059/guardian-of-the-monument
Mob: Apexis Guardian

The corpse disappeared 20 seconds after he died.
Because of this, the loot as well disappeared with it, where you did not get the time to talk about loot, or even have everybody Greed/Need/Pass.
This led to losing a Depleted Badge that drops.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/search?p=2&q=TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT&type=&utf8=%E2%9C%93

https://github.com/Looking4Group/L4G_Core/blob/2cb1c7753162fbb405b46b360ea1b12d3c7368f8/src/scripts/scripts/zone/blades_edge_mountains/blades_edge_mountains.cpp#L1220

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/commit/5f56b6e982788e7ef2665a3b246f36c2f0a98257
