### ISSUE TITLE
Gordunni Back-Breaker applies Enrage buff to player

### ISSUE THREAD

**Issue by Kogud** [Looking4Group/L4G_Core#3854]
Sometimes (but not always) these ogres will apply their Enrage buff to the player instead of to themselves.

![enrage buff](https://user-images.githubusercontent.com/29239473/26853638-cc673730-4ae0-11e7-9359-7c19449d33d5.png)

**Comment by Kogud** [comment]
Just kidding, this seems intentional. The more you know!

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?npc=22143

**Comment by AnonXS** [comment]
better than fine.
