### ISSUE TITLE
Missing - Design: Steady Talisite  

### ISSUE THREAD

**Issue by Aussiebobba** [Looking4Group/L4G_Core#3855]
The quartermaster in Halaa should have it for 4 Research Tokens, but it is not there.
This was a patch 2.03 recipe.
Thanks

TBC Patch 2.0.3 (2007-01-09): Added.
http://wow.gamepedia.com/Design:_Steady_Talasite

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?item=33783

**Comment by AnonXS** [comment]
```
DELETE FROM `npc_vendor` WHERE `item` = 33783;
INSERT INTO `npc_vendor` VALUES (18821, 33783, 0, 0, 2236);
INSERT INTO `npc_vendor` VALUES (18822, 33783, 0, 0, 2236);
```

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3851/commits/74e541041d54e7aaa0b97d4b71f785d05f2ff6e3
