### ISSUE TITLE
Razorthorn Ravagers - Not Tameable

### ISSUE THREAD

**Issue by Liquidsoap** [Looking4Group/L4G_Core#3858]
Unable to tame Razorthorn Ravagers: [http://db.hellfire-tbc.com/?npc=24922#drop](url)

**Comment by Xadras** [comment]
Its intended I think.
http://de.wowhead.com/npc=24922/messerdornfelshetzer#english-comments
"This ravager is NOT tameable as of right now"

**Comment by Liquidsoap** [comment]
Ah, okay. Thanks
