### ISSUE TITLE
Daily quests cap bugged at 10 daily quests.

### ISSUE THREAD

**Issue by Demianl** [Looking4Group/L4G_Core#3860]
For two days in a row the daily quest limit caps at after completing 10 daily quests. When you hand in the 10th it says "You can complete 15 more daily quests today". When you try hand in the 11th it suddenly changes to "You have already completed 25 daily quests today".

**Comment by AnonXS** [comment]
Patch 2.4.0 (25-Mar-2008): The Daily Quest limit has been increased to 25.

**Comment by Demianl** [comment]
Well rip then :(
