### ISSUE TITLE
Wintersaber Trainers - Item is currently sold out

### ISSUE THREAD

**Issue by Breacher2017** [Looking4Group/L4G_Core#3878]
Hi, 
Just godt exalted with wintersaber trainers, and can access the buy menu.
The item-tab - "Reins of the Winterspring Frostsaber" (its the only one he is selling) is grayed out.
The message is: "That item is currently sold out."
![wowscrnshot_061817_194802](https://user-images.githubusercontent.com/29522853/27262831-16f66532-545f-11e7-891c-3688f9b51538.jpg)

**Comment by Breacher2017** [comment]
Update.
Was able to buy it now. The vendor had 1 item so it must be on a cooldown for the mount.

**Comment by AnonXS** [comment]
http://www.wowhead.com/item=13086/reins-of-the-winterspring-frostsaber
http://www.wowhead.com/npc=10618/rivern-frostwind

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3876/commits/da7bd6f07ed0edd98b83c369e6905e784c6418ba
