### ISSUE TITLE
MIDSUMMER FIRE FESTIVAL FOOD: MIDSUMMER SAUSAGE

### ISSUE THREAD

**Issue by skitzo1** [Looking4Group/L4G_Core#3880]
Copy paste from last years midsummer event:
The vendor for the Mid Summer Festival currently sells all the foods in stacks of 5, whereas the sausages are sold in stacks of 1 for the same price. I'm to understand that this was the case in retail but it wasn't fixed until right after the Mid Summer Festival actually ended.

Could we possible get the fix before the festival ends so the casters could stock up on food?

Cheers,

taken from: 
https://github.com/Looking4Group/L4G_Core/issues/2464

**Comment by AnonXS** [comment]
Vendor Name

**Comment by skitzo1** [comment]
Midsummer Supplier, multiple locations
http://db.hellfire-tbc.com/?npc=26123

**Comment by AnonXS** [comment]
Finally: https://github.com/Looking4Group/L4G_Core/pull/3876/commits/c3f118a43485afc62a7bc8cc7778a9e0dc962f47
