### ISSUE TITLE
Plans: Khorium belt drop rate

### ISSUE THREAD

**Issue by Falanien** [Looking4Group/L4G_Core#3884]
Hi, I farmed around 3 hours on Murkblood raiders for the plans: Khorium belt, killing roughly 400 mobs without seeing the plans drop. During this time I looted around 15 Putrified Draenic water which have the same drop rate according to database. My BS skill is 363.

Item in question: http://db.hellfire-tbc.com/?item=23608
The mob: http://db.hellfire-tbc.com/?npc=18203

**Comment by Falanien** [comment]
Oh, and to add, earlier I have grinded for the plans: felsteel gloves in AC crypts, killing roughly 200 monks in a span of a couple of days. This made me wonder if there is a bug regarding me rerolling to BS after having another main profession before and the game not using the correct loottable for me because of that. 

Item in question: http://db.hellfire-tbc.com/?item=23605

**Comment by AnonXS** [comment]
http://www.wowhead.com/item=23608/plans-khorium-belt#comments

```Gnomepally on 2008/10/25 (Patch 3.0.2)
Man, this drop rate is bogus. According to the database, I should get one every 500 kills. Well, after a day or two I started counting and I've killed 783 Murkblood Raiders. Not one single drop. I'm gonna have a coronary. EDIT: I got the plans after about 2572 kills. Thats only what I counted, so probably about 3k or so.```

seems to be indeed very low.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3891/commits/be96716eed28d17ae45220a565cf2e23cc4f233e
