### ISSUE TITLE
Sounds loop to crash

### ISSUE THREAD

**Issue by Wodjee** [Looking4Group/L4G_Core#3889]
When walking domes in Netherstorm, I often get a sound loop for 10-30 sec, then Game client crashes on Error 134. Not sure if it shall be reported here and how it can be solved...

**Comment by AnonXS** [comment]
Most likely related to your game client. Try with a fresh installed one or another computer.

**Comment by Wodjee** [comment]
Is there a way to get a fresh install but keep the config ? Like keybindings, addons settings etc?

**Comment by AnonXS** [comment]
Save WTF and Interface Folder to the new client.
