### ISSUE TITLE
i need mmaps

### ISSUE THREAD

**Issue by pakhmolkosh** [Looking4Group/L4G_Core#3894]
pls upload mmaps for me .. 

i have problem with extractor  

![untitled](https://user-images.githubusercontent.com/30008583/27988792-98b8fb34-6440-11e7-85e4-b16db91d38cf.jpg)

**Comment by AnonXS** [comment]
```MoveMapGen.exe --offMeshInput offmesh.txt``` offmesh.txt has to be placed in the same folder.

**Comment by pakhmolkosh** [comment]
i need all of them .. 

if you have .. upload for me

**Comment by AnonXS** [comment]
![unbenannt](https://user-images.githubusercontent.com/19734826/27997446-8b44ae0e-64f8-11e7-9d88-e9cffa2963c4.PNG)

gg

**Comment by pakhmolkosh** [comment]
hi ty my bro


pls take me code for this action ...

i cant remmber ...

**Comment by pakhmolkosh** [comment]
and ... I want everyone rank join the server

what value required_permission_mask set on realm table ...

sorry for bad english ...

**Comment by pakhmolkosh** [comment]
[image: Inline image 1]
