### ISSUE TITLE
Gm and player rank on realm table

### ISSUE THREAD

**Issue by pakhmolkosh** [Looking4Group/L4G_Core#3896]
I want everyone rank join the server 

what value required_permission_mask set on realm table ... 

sorry for bad english ...

**Comment by AnonXS** [comment]
http://wiki.looking4group.eu/index.php/Adding_a_player_account

**Comment by pakhmolkosh** [comment]
How connect Gm and player ... 

i set value 1 ... just player can connect to server .. for gm rank show server offline :|

**Comment by Xadras** [comment]
what did you insert?
try with 2819 for example

**Comment by pakhmolkosh** [comment]
Ty my bro 

i try this  http://wiki.looking4group.eu/index.php/Adding_a_player_account
http://wiki.looking4group.eu/index.php/Realms 

...
