### ISSUE TITLE
all player rank 1 read ticket :| and hp show % 

### ISSUE THREAD

**Issue by pakhmolkosh** [Looking4Group/L4G_Core#3897]
all player rank 1 read tickets .. 

and hp all creature and player show % .. 

how i can fix it

**Comment by Xadras** [comment]
play = rank 0
hp % is a conf setting

**Comment by pakhmolkosh** [comment]
where is the conf setting this option ? .. 

cant find that

**Comment by AnonXS** [comment]
HealthInPercents = 0

**Comment by pakhmolkosh** [comment]
ty  men
