### ISSUE TITLE
Ubuntu make error

### ISSUE THREAD

**Issue by kuramajssken001** [Looking4Group/L4G_Core#3907]
`[ 39%] Linking CXX shared library libtrinityscript.so
/usr/bin/ld: CMakeFiles/trinityscript.dir/include/precompiled.cpp.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
CMakeFiles/trinityscript.dir/include/precompiled.cpp.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/scripts/CMakeFiles/trinityscript.dir/build.make:10338: recipe for target 'src/scripts/libtrinityscript.so.4.2.0' failed
make[2]: *** [src/scripts/libtrinityscript.so.4.2.0] Error 1
CMakeFiles/Makefile2:637: recipe for target 'src/scripts/CMakeFiles/trinityscript.dir/all' failed
make[1]: *** [src/scripts/CMakeFiles/trinityscript.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/root/core/src/Looking4GroupCore/CliRunnable.cpp: In function ‘void utf8print(const char*)’:
/root/core/src/Looking4GroupCore/CliRunnable.cpp:102:15: warning: format not a string literal and no format arguments [-Wformat-security]
     printf(str);
               ^
[ 40%] Linking CXX executable looking4groupcore
/usr/local/lib/libreadline.so: undefined reference to `tgetstr'
/usr/local/lib/libreadline.so: undefined reference to `tputs'
/usr/local/lib/libreadline.so: undefined reference to `BC'
/usr/local/lib/libreadline.so: undefined reference to `tgetent'
/usr/local/lib/libreadline.so: undefined reference to `tgetflag'
/usr/local/lib/libreadline.so: undefined reference to `tgoto'
/usr/local/lib/libreadline.so: undefined reference to `UP'
/usr/local/lib/libreadline.so: undefined reference to `tgetnum'
/usr/local/lib/libreadline.so: undefined reference to `PC'
collect2: error: ld returned 1 exit status
src/Looking4GroupCore/CMakeFiles/looking4groupcore.dir/build.make:185: recipe for target 'src/Looking4GroupCore/looking4groupcore' failed
make[2]: *** [src/Looking4GroupCore/looking4groupcore] Error 1
CMakeFiles/Makefile2:697: recipe for target 'src/Looking4GroupCore/CMakeFiles/looking4groupcore.dir/all' failed
make[1]: *** [src/Looking4GroupCore/CMakeFiles/looking4groupcore.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
root@ubuntu:~/core/bin# 
`

**Comment by Rapth** [comment]
kura，this problem solved?

**Comment by kuramajssken001** [comment]
yes @Rapth

**Comment by Rapth** [comment]
Can you write a step-by-step guide for me ? I am totally new with Linux(Ubuntu). I can pay you,Bro.

**Comment by kuramajssken001** [comment]
Of course! I'm glad I could help you. @Rapth 
Discord        ! kurama     #3968
