### ISSUE TITLE
Any one can write a step by step guide for me to compile this core in Ubuntu desktop? I can pay for it

### ISSUE THREAD

**Issue by Rapth** [Looking4Group/L4G_Core#3913]
I can pay for it

**Comment by AnonXS** [comment]
This Repository is no longer supported, i'd suggest you try https://github.com/cmangos/mangos-tbc

**Comment by Rapth** [comment]
Anon,appreciated your reply.but i really love this L4G core,i checked cmangos before but many dungeon/instances didnt work normally.

**Comment by AnonXS** [comment]
Well, then maybe help us ironing out these issues, so we can move forward?

**Comment by Rapth** [comment]
i  want to compile it on Ubuntu , i search the WiKi file but the link is offline  http://wiki.looking4group.eu

**Comment by Rapth** [comment]
@AnonXS  Can you redirect the WIKI link? i would appreciated your help very much
