### ISSUE TITLE
NPC Respawn Issue

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#413]
NPCs do not reset their movement speed on respawn.

Casting (mana) NPC do not reset their AI on respawn. (hackfix by xadras)

**Comment by AnonXS** [comment]
And those which flee on low hp dont reset their speed to normal movementspeed on respawn.

**Comment by AnonXS** [comment]
More Descriptive Issue https://github.com/Looking4Group/L4G_Core/issues/3321
