### ISSUE TITLE
npc reaction during player invulnerability or player cc or npc movement restriction

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#419]
Prenerf Mechanics:

[ENG] During Player invulnerability or cc all npcs who have this player as highest threath target should switch to the second and so on. During root effects, npcs should always attack the highest threath target that is in melee range.

[GER] Wenn ein Spieler einen Unverwundbarkeitseffekt oder CC auf sich wirken hat sollten alle NPCs von diesem Spieler ablassen und stattdessen Pets und andere Gruppen / Schlachtzugsmitglieder angreifen welche auch in der Aggro geführt werden, bzw die mit dem NPC infight sind.
---

Eisblock will remove threat for the duration of Ice Block. When Ice Block wears off, some threat is restored. 

http://www.wowhead.com/spell=45438/ice-block#comments

By Tehsteve (3,945 – 6·30) on 2007/02/15 (Patch 2.0.7)  
Just a little something to add. Mob's aren't quite as stupid as we think they are. If they notice that their attacks aren't affecting you because you're invulnerable they'll look for something nearby to attack. This can be anything from a teammate to an escort NPC. You've been warned...

Rarehunter on 2007/12/09 (Patch 2.3.0)
The thing is, enemy AI actually depends on aggro. If you run in, and you're the only one on their aggro list, your Ice Block WILL cause the mob to continually attack you, even though you are 'Immune' to their attacks. If a party member or escort NPC helps/assists you or does anything to the mob in any way the mob will instead target the party member or NPC.

By TheMuffinMan (40,558 – 7·38·187) on 2008/12/03 (Patch 3.0.3)
Ice Block simply makes you an invalid target, causing all mob AI to ignore you (assuming there is a viable target engaged to them), but it will not alter your threat. Be warned that your tank still needs to be able to taunt the mob away from you.
---

Segen des Schutes (Nur Physical attacking NPCs)

For paladin tanks, if Righteous Defense is on cooldown, or the mob is immune to taunt, a paladin tank can cast Blessing of Protection on the one who pulled aggro (usually with a macro similar to that of Righteous Defense). In that case, if the paladin tank is the second on the threat list, the mob will come back to him immediately. 
---

Gottesschild

will cause mobs to ignore you for the duration of its effect, but only if you are not alone in an encounter.

Göttlicher Schutz 

will cause mobs to ignore you for the duration of its effect, but only if you are not alone in an encounter.

LongD
Geschrieben: 29 October 2009 - 10:16
JEp sobald du die Bubbel benutzt wird der Mob auf den nächsten in der Aggroliste gehen. Sobald du sie abschaltest hast du deine Ursprüngliche Aggro wieder. 

http://forum.buffed.de/index.php/topic/130508-gottesschild/
---

CC Effekte:

 If certain abilities apply a debuff to a character that cause the mob to consider the player an invalid target. Usually these debuffs have a chance (or certainty) to break on damage, but there are some that don't but still cause the mob to consider the character an invalid target. Examples include Polymorph, Gouge, Fear, etc. These aggro reduction effects are temporary in most situations. When the ability wears off, previous aggro levels are restored immediately. Dazu zählen:

Verwandlungseffekte und was einen sonst noc so die Kontrolle über den eigenen Charakter verlieren lässt

Desorientierungseffekte

Alle Arten von Furcht
---

NPCs die in ihrer Bewegung eingeschränkt sind versuchen Ziele anzugreifen, die für Sie erreichbar sind. Bsp.: Gruul -> Painful Strike -> kein 2ter Melee in Range -> Trifft MT.
oder: MH Trash Monstro wird gewurzelt, Healer ist aufgrund der Healaggro höchster in der Aggro, Stoffi läuft an der Monstro vorbei und bekommt 1Hit, weil die Monstro switched.

If certain abilities impair the access of the mob to its higher threat-ranked targets (e.g., root spells), the mob will attack the highest threat-ranked target in its ability range (usually visible for melee mobs or silenced casters, which have a combat range of 5 yards) 
---

Da das 3 Sachen sind ( Immunisierungszauber / Player CC / NPC CC ) kann man diese Mechanikbugs auch auf 3 Issues splitten.

http://wowwiki.wikia.com/wiki/Aggro

**Comment by Xadras** [comment]
Didn't Gerkirin fixed this CC behavior, so that NPCs now selecting an other target if tank is cc'ed?

**Comment by AnonXS** [comment]
Yea i guess we should compose two new issues with

npc behavior when Player has Immune Aura and 
npc behavior when NPC is CCed but still can act.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2895 - npc behavior when NPC is CCed but still can act.
