### ISSUE TITLE
Erste Hilfe / First Aid -  Repeated Usage of Bandages should not be possible

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#431]
Originally reported by: **Anon  X (Bitbucket: [Anonx](https://bitbucket.org/Anonx), GitHub: [Anonx](https://github.com/Anonx))**

---

Verbände können genutzt werden, obwohl man den Debuff Kürzlich bandagiert http://looking4group.de/database/?spell=11196 auf sich wirken hat.

Bandagen für die Erste Hilfe können nun nicht mehr auf Spieler angewendet werden, die vom Effekt 'Kürzlich bandagiert' betroffen sind. Gleichzeitig wird nun die folgende Fehlermeldung angezeigt: "Es kann kein zweiter Verband angelegt werden".

Erste Hilfe http://eu.battle.net/wow/de/game/patch-notes/2-4-3

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/435

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/blob/30774d28b74250033040cc79bdb03b803ca7e261/src/game/SpellEffects.cpp#L3063 - Remove here, not working/anymore

https://github.com/AnonXS/Trinitycore_Azshara_2.4.3/commit/e7cc2f0e77261c0675b8b637c39e091444bc7dd0

```
// https://github.com/Looking4Group/L4G_Core/blob/30774d28b74250033040cc79bdb03b803ca7e261/src/game/Spell.cpp#L3959

     if (target)
     {
         if (m_customAttr & SPELL_ATTR_CU_CHARGE)
             if(!m_caster->MonsterChargeByPath(target, 25, GetSpellMaxRange(m_spellInfo)*2, false, true))
                 return SPELL_FAILED_NOPATH;
 
-        if (m_spellInfo->Mechanic == MECHANIC_BANDAGE && m_caster->HasAura(11196,0))
+        if (m_spellInfo->Mechanic == MECHANIC_BANDAGE && target->HasAura(11196,0))
             return SPELL_FAILED_TARGET_AURASTATE;
 
         if((!IsPositiveSpell(m_spellInfo->Id) && !(m_spellInfo->Id == 7266)) && target->GetTypeId() == TYPEID_PLAYER 
             && m_caster->GetTypeId() == TYPEID_PLAYER &&m_caster != target && !m_caster->canAttack(target)
             && m_caster->ToPlayer()->GetSession()->GetSecurity() < SEC_MODERATOR)
         { // 7266 = duel request, if there is more spells that are blocked by this. i'll prolly remove it.
             // anti faction hack
             return SPELL_FAILED_BAD_TARGETS;
         }
         // target state requirements (not allowed state), apply to self also
         if (m_spellInfo->TargetAuraStateNot && target->HasAuraState(AuraState(m_spellInfo->TargetAuraStateNot)))
return SPELL_FAILED_TARGET_AURASTATE;

```

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3740/commits/7d686fba38a656f3e47f4b77bfadd42df3ab25ac
