### ISSUE TITLE
Procs: SPELLMOD_COST & fakecasting

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#445]
Originally reported by: **robinsch (Bitbucket: [robinsch](https://bitbucket.org/robinsch), GitHub: [robinsch](https://github.com/robinsch))**

---

Procs wie Clearcasting (SPELLMOD_COST) werden beim fake casten removed.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/449

**Comment by AnonXS** [comment]
Would be nice to have a list of still not working spell mods which are consumed when the / a spell is cancelled.
