### ISSUE TITLE
Quest - The Warp Rifts

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#449]
Originally reported by: **robinsch (Bitbucket: [robinsch](https://bitbucket.org/robinsch), GitHub: [robinsch](https://github.com/robinsch))**

---

Quest: http://www.wowhead.com/quest=10278/the-warp-rifts

Trigger NPC: http://www.wowhead.com/npc=20143/void-spawner-quest-warp-rifts

Summoned NPC: http://www.wowhead.com/npc=20145/unstable-voidwalker

- [ ] Trigger NPC should cast Blue Beam channel on unstable voidwalker http://db.looking4group.eu/?search=blue+beam (unimportant)

- [ ] should be able to summon more than one at at time (core spell summon related)

- https://www.youtube.com/watch?v=UQZ1qNSzPpg

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3755/commits/a1e868bec3327f57d2a716941f96e090eecfc230
