### ISSUE TITLE
Oberster Kriegsfürst Naj'entus [Black Tempel] #2

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#484]
Originally reported by: **Anon  X (Bitbucket: [Anonx](https://bitbucket.org/Anonx), GitHub: [Anonx](https://github.com/Anonx))**

---

Man sollte als Spieler nicht fähig sein, sich selber Naj'entus' Stachel http://looking4group.de/database/?object=185584 zu ziehen.

Man sollte als Spieler, wenn man den Stachel hat garnichts machen können, da man gestunnt ist. Man kann sich hier aber selbst den Stachel ziehen. (Case was as Druid in Treeform)

Evtl sogar ein Corebug, wenn man als gestunnter Spieler mit Objecten interagieren kann, obwohl man einen Effekt auf sich wirken hat der einen die Kontrolle über den Char verlieren lässt.

BG Flagtapping while stunned? 

Wenn man dies macht, aus Versehen oder mit Absicht verschwindet der Dmg-Debuff nicht und der Spieler stirbt unweigerlich.

Das Object welches man als Spieler mit Stachel nicht anklicken können darf:

http://de.wowhead.com/object=185584

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/488

**Comment by Saltgurka** [comment]
Please translate the issue to English

**Comment by AnonXS** [comment]
Recheck if it is possible to successfully click object=185584 as Druid in Treeform.
But causing the Debuff to not properly being removed.
