### ISSUE TITLE
Akil'zon - Abbruch Elektrischer Sturm

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#534]
Originally reported by: **Anon  X (Bitbucket: [Anonx](https://bitbucket.org/Anonx), GitHub: [Anonx](https://github.com/Anonx))**

---

Wenn man bei seiner Fähigkeit Elektrischer Sturm http://looking4group.de/database/?spell=43648 irgent etwas besonderes macht bricht er den Sturm wieder ab was die Timer verschiebt.

Müsste genauer getestet werden vlt liegt es an:
- Resist
- Boss wird gezogen
- Irgentwelche Timer überlappen

---

http://de.wowhead.com/spell=43648/elektrischer-sturm

Q: http://wowwiki.wikia.com/Akil%27zon_%28original%29

Q: http://de.wowhead.com/npc=23574/akilzon#english-comments

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/538

**Comment by AnonXS** [comment]
Hopefully https://github.com/Looking4Group/L4G_Core/blob/630f754c891f101248c9650972d2cd994fc93334/src/game/SpellMgr.cpp#L3907 was enough to mitigate the issue enough for it to appear much less frequently, might be related to movechase etc.
