### ISSUE TITLE
Halaa Bombs

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#537]
Originally reported by: **Anonymous**

---

[ger] Die Flugbombe mit der man die Wachen von Halaa töten um die Stadt in Nagrand einzunehmen machen keinen Schaden.

[eng] The Bombs do no dmg.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/541

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/blob/dd78ce5ece3c1bc81180f85373e4a418debc64dc/sql/updates/world/092_5_1.sql#L211
