### ISSUE TITLE
Waypoints - Arklon Ruins

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#542]
Originally reported by: **Anon  X (Bitbucket: [Anonx](https://bitbucket.org/Anonx), GitHub: [Anonx](https://github.com/Anonx))**
---

In den Arklon Ruins befinden sich Teufelsklingenverdammniswache 
http://looking4group.de/database/?npc=19853 und Artefaktsucher http://looking4group.de/database/?npc=19852 , welche sich teilweise bewegen sollten um den Ruinen mehr Dy­na­mik zu verleihen.
---

https://www.youtube.com/watch?v=u6cS3XM9yOM

https://www.youtube.com/watch?v=i1o_zTFMnK4

https://www.youtube.com/watch?v=N16mPJ-8RqE
---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/546

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2975/commits/c4af580b0fa283ab7a62aa8d2f4a15b55068227f
