### ISSUE TITLE
Waypoints - Bach'lor

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#549]
Originally reported by: **Anon  X (Bitbucket: [Anonx](https://bitbucket.org/Anonx), GitHub: [Anonx](https://github.com/Anonx))**

---

Bach'lor bewegt sich mit seiner Herde im Westen Nagrands auf und ab, fehlende Herde und Waypoints für Bach'lor anpassen. 

---

http://www.wowhead.com/npc=18258/bachlor

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/553

**Comment by Saltgurka** [comment]
Live next update:

https://gist.github.com/Saltgurka/adecfcc5d189938c748a792a233ae873
