### ISSUE TITLE
Respawnt von begrenzten Items bei Händlern

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#564]
Originally reported by: **Anonymous**

----------------------------------------

Wenn keiner in der nähe des Händlers ist, respawnen die mengenmäßig begrenzten items (z.b. ur-partikel auf der sturmsäule) in weniger als 15minuten. ist seit der nacht vom 16.11 auf den 17.11 so

-böhsling

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/568

**Comment by AnonXS** [comment]
#1807
