### ISSUE TITLE
Hunter Pet Avoidance / Vermeidung

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#578]
Originally reported by: **Anonymous**

----------------------------------------

Beim Rat der Illidari funktioniert dei Fähigkeit Vermeidung nicht vollständig. Lediglich die Explosion des Magiers die er auslöst wenn man in Melee-Range geht wird um die im Tooltip genannten 50% verringert.
Die Weihe, der Blizzard und der Flamestrike skallieren aber nicht mit dem Petskill und machen vollen Schaden und nicht den um 50% verringerten Schaden den das Tooltip verspricht.
Denke mal muss hier keine Quellen angeben da es ja zweifelsohne eine Flächenfähigkeit ist von denen in der Fähigkeitsbespreibung die Rede ist.

"Reduziert den von eurem Begleiter  durch Effekte, die auf einen Bereich wirken, erlittenen Schaden um zustätzliche 50%."

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/582

**Comment by AnonXS** [comment]
#1055
