### ISSUE TITLE
Grand Warlock Nethekurse - Event can be broken

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#580]
Originally reported by: **Anon  X (Bitbucket: [Anonx](https://bitbucket.org/Anonx), GitHub: [Anonx](https://github.com/Anonx))**

---

[GER] Manchmal startet die Boss AI von Großhexenmeister Nethekurse nicht.

Er macht dann nichts und lässt sich einfach so töten ohne was zu machen, nichtmal Autohits.

Hat wohl was damit zu tun, wie man die Adds tötet die am Anfang des Bossfights gepullt werden.

[ENG] Sometimes the Core scripted AI of the Boss doesnt work properly as the Event doesnt start. Connected to Killing the Adds of the Boss befor Engaging him and starting his Pre Combat Event.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/584

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3872
