### ISSUE TITLE
Quest Sphärenrisse

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#620]
Originally reported by: **Anonymous**

----------------------------------------

blablabla sammeln sie 3 spährennether 

drück instabiler Sphäremrossgenerator => dunklewolke spant => die beschwört eles die töten looten enthalten Spährennether

jetzt aber

drück instabiler Sphäremrossgenerator => komischer mob spannt und macht garnix quest geht nicht mehr

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/624

**Comment by AnonXS** [comment]
#449
