### ISSUE TITLE
Vorakem Doomspeaker

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#651]
Originally reported by: **Anonymous**

----------------------------------------

Rare mob in Hellfire peninsula https://www.youtube.com/watch?v=yJu99yoLsI4
i think he is supposed to cast the fire wave, which he is not doing. He is doing it instantly. 
You can also see a little infernal when he is sending out the fire wave which is not supposed to happen i think http://imgur.com/fPDwOC0. The infernal is not there every time though.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/655

**Comment by AnonXS** [comment]
Isolated the trigger npc and set the trigger flags.

spell 3sec casttime, 10-15sec

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2920/commits/56bff0f97e5cc87f9f72f2f8e17edf06bc4929ce
