### ISSUE TITLE
Mordenai

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#681]
Originally reported by: **Anonymous**

----------------------------------------

His patrol is in need of fix. At the moment he's standing still. Health needs to scale higher, check wowhead link for the exact. 

http://www.wowhead.com/npc=22113/mordenai#comments

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/685

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2891/commits/97a38f850562586c1d4b1ec1a478ed4af6df356c
