### ISSUE TITLE
Ruul the Darkener

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#682]
Originally reported by: **Anonymous**

---

His patrol is in need of fix. At the moment he's standing still. HP might be considered to low, check the Wowhead link.  

http://www.wowhead.com/npc=21315/ruul-the-darkener#comments

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/686

**Comment by Saltgurka** [comment]
This is already fixed I think?
