### ISSUE TITLE
Escape from the Coilskar Cistern

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#697]
Originally reported by: **Anonymous**

---

Bugged, took the quest, she walked fine, had her first spoken words and then died randomly. 

http://www.wowhead.com/quest=10451/escape-from-coilskar-cistern

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/701

**Comment by AnonXS** [comment]
Never had her bug out, cave is populated in upcoming update.

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/blob/9a485125f40a3cb6d3653a7972d4a51b5660774d/sql/updates/world/065_U_14.09.16_Creature_Gameobject.sql

**Comment by Wodjee** [comment]
Not sure if it supposed to be solved or not, but I just got the issue of the escort to run all around until getting into a wall and nothing happens anymore.
