### ISSUE TITLE
Need Improvement check out.

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#707]
Originally reported by: **rekt123 (Bitbucket: [rekkt](https://bitbucket.org/rekkt), GitHub: Unknown)**

----------------------------------------

GUID: 23494F130
Scriptmiss:SMART_ACTION_RANDOM_MOVE 

GUID: 64406F130
Scriptmiss:SMART_ACTION_RANDOM_MOVE

GUID: 23495(i respawn it in the right position but it miss only have the [0]Idle script cant update in game)

GUID: 63512(i moved it with NODEL command but she dont respawn)

obj ID: 182069 mature sac need smart script despawn(disppear)/respawn(appear)

GUID: 64647
Scriptmiss:SMART_ACTION_RANDOM_MOVE

GUID: 64558F130
Scriptmiss:SMART_ACTION_RANDOM_MOVE

GUID: 72333F130
Scriptmiss:SMART_ACTION_RANDOM_MOVE

GUID: 72420F130 (need to remake a path for this guy)

GUID: 76076F130(walk too fast)

GUID: 6101F130(he blacksmith the forge)

GUID: 75407F130(need to make a path for this guy)

GUID: 77645 (need to make a path for this guy)

GUID: 66268
Scriptmiss:SMART_ACTION_RANDOM_MOVE

GUID: 69293
Scriptmiss:SMART_ACTION_RANDOM_MOVE

GUID: 69292
Scriptmiss:SMART_ACTION_RANDOM_MOVE

GUID 64399
Scriptmiss:SMART_ACTION_RANDOM_MOVE

GUID: 64401 
Scriptmiss:SMART_ACTION_RANDOM_MOVE

GUID: 69283
Scriptmiss:SMART_ACTION_RANDOM_MOVE

GUID: 64383
Scriptmiss:SMART_ACTION_RANDOM_MOVE

Guid: 76799 (checkout position)

Guid: 24492(mobs dublicated)

entryID: 19191(need to be immune to stuns and at 20% it start cast infernals all over the platform)

entryID: 19188(need to be immune stun/any form of cc)

entryID: 16888(check position they dont move, questgivers)

GUID: 69051(check position he walk down the stairs and stop move for 10min, then he go back where he spawned and turn facing the stairs for another 10min)

GUID: 23639(the shield buff should only reduce physical dmg not magical)

GUID: 59463(check position move it abit cause it go on the wall)

GUID: 59454(check position move it abit cause it go on the wall)

GUID: 59455(check position move it abit cause it go on the wall)

GUID: 58905(check position move it abit cause it go on the wall)

entryID: 16951 (check position all of them, duplicated mobs)

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/711

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2920/commits/c6335391ec6b7f653a646bc4c7e3380bf30abfca
