### ISSUE TITLE
Bonechewer Marauder / Bonechewer Messenger not patrolling

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#708]
Originally reported by: **Anonymous**

----------------------------------------

http://www.wowhead.com/npc=21245/bonechewer-marauder
http://www.wowhead.com/npc=21244/bonechewer-messenger

They should patrol into Shadowmoon Valley and trigger an event where they are killed by elite mobs. They currently spawn at the correct place but do not move. If they are not fixed they need to be removed as there is currently a pack of 5 lvl69 mobs in the middle of other 63-64 mobs.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/712

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2878/commits/76fd119b31e8ba8003d3f7d4477eb611f28b2257
