### ISSUE TITLE
NPC - Kiting?

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#721]
Originally reported by: **Jawohl (Bitbucket: [Jawohl](https://bitbucket.org/Jawohl), GitHub: [Jawohl](https://github.com/Jawohl))**

----------------------------------------

You are able to " Outrun " monsters. When they reach the range to perform Attack, they dont instantly cast it, they wait for swingtimer or something causing them to stop for a millisecond. This chain of events allows you to outrun MAJORITY of the monster on the server.

[Proof of a sort this happening](https://www.youtube.com/watch?v=91ifjevw6X4)

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/725

**Comment by AnonXS** [comment]
#485
