### ISSUE TITLE
Savage fury - Druid bug

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#752]
Originally reported by: **Anonymous**

---

I believe savage fury is not working as intended
Mangle when specced give too much % weapon damage and i think bonus damage also.

Without savage fury: 160% weapon damage
with savage fury(20% buff) : 230% weapon damage

160x1.2=192% weapon damage

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/756

**Comment by Saltgurka** [comment]
Lots of "I think" and "I believe" in this bugreport. Reopen if real proof is provided
