### ISSUE TITLE
Thrallmar NPCs missing paths

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#775]
Originally reported by: **Bulldoze (Bitbucket: [Legitcow](https://bitbucket.org/Legitcow), GitHub: Unknown)**

----------------------------------------

Some Thrallmar grunts need to their walkingpaths fixed

[Grunts 1](http://i.imgur.com/bHBYlLH.jpg)

[Grunts 2](http://i.imgur.com/WTb6LW5.jpg)

[Grunt 3](http://i.imgur.com/DhrnlxT.jpg)

[Grunt 4](http://i.imgur.com/lgFX8tR.jpg)

[*Bug report from corecraft*](https://github.com/ccshiro/cc-buglist/issues/1692) 

Edit; this report now only contains grunts.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/779

**Comment by Saltgurka** [comment]
Thrallmar Grunts waypoints and HP fixed in the next update.
