### ISSUE TITLE
Prince Malchezaar Can be disarm

### ISSUE THREAD

**Issue by boom8866** [Looking4Group/L4G_Core#8]
npc=15690 (Prince Malchezaar)

Should not be disarmed.

UPDATE `creature_template` SET `mechanic_immune_mask`='650854239' WHERE (`entry`='15690');

**Comment by AnonXS** [comment]
I personally think he should be disarmable in Phase 2 with the axes and may be immune in P1 and P3.

Do you have any kind of source?

**Comment by AbaddonL4G** [comment]
Checked the web - think he is right no source about possibility to disarm the boss.
There are a lot of tips to survive P2 but no source mentions disarm.

Should not be disarmed.

UPDATE creature_template SET mechanic_immune_mask='650854239' WHERE (entry='15690');

**Comment by AnonXS** [comment]
Ok, as this is indeed enough evidence i will add it to the next sql updates. /closed

**Comment by AnonXS** [comment]
https://youtu.be/szA9LXNG0sQ?t=1m39s
