### ISSUE TITLE
Bladespire Brute - Missing abilities

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#807]
Originally reported by: **Jawohl (Bitbucket: [Jawohl](https://bitbucket.org/Jawohl), GitHub: [Jawohl](https://github.com/Jawohl))**

---

Blades edge mountains
[Bloodmaul Intoxication, Cleave](http://www.wowhead.com/npc=19995/bladespire-brute#abilities)

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/811

**Comment by AnonXS** [comment]
Dublicate https://github.com/Looking4Group/L4G_Core/issues/870
