### ISSUE TITLE
Vision Guide - Quest ( Blades edge mountain )

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#815]
Originally reported by: **Jawohl (Bitbucket: [Jawohl](https://bitbucket.org/Jawohl), GitHub: [Jawohl](https://github.com/Jawohl))**

---

[Vision Guide](http://www.wowhead.com/quest=10525/vision-guide)  <-- The marker for objective "Final thunderlord artifact discovered" is in wrong location, dont bother about that.

In the quest Vision Guide, player transforms into a ball of fire and travels all the way back to the Draenethyst Mine to discover the last Artifact. After the discovery is being made, the player should return back to the original spot he used the Quest item at.

Best i could do to provide with proof for my claim is a [Leveling guide](http://www.wow-pro.com/leveling_guides/jame039s_horde_leveling_guide_chapter_vi_6570) made at 2008 with Quote :

   Stay in front of the NPC where you turned in the last quest, Rokgah Bloodgrip and right-click the Fiery Soul Fragment from your inventory. Let yourself be guided by the wisp. After 2 minutes you'll be back to your character, turn in the quest [66] Vision Guide, get the follow up [67] The Thunderspike.

Quest itself is working and this is not game breaking. However, it might be considered as " annoying " to be teleported into the cave, where you must then run back to the Thunderlord Stronghold, take the followup [Thunderstrike](http://www.wowhead.com/quest=10526/the-thunderspike) and then run back to the mine you was miss-teleported to.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/819

**Comment by Saltgurka** [comment]
Solved with https://github.com/Looking4Group/L4G_Core/pull/3001
