### ISSUE TITLE
Zalazane: Missing walkpath, abilities

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#827]
Originally reported by: **Bulldoze (Bitbucket: [Legitcow](https://bitbucket.org/Legitcow), GitHub: Unknown)**

---

Abilities - http://wowwiki.wikia.com/wiki/Zalazane
 Spell shadow antishadow  [Shrink]—Reduces an enemy's Strength and Stamina for 2 min.
 Spell nature magicimmunity  [Healing Wave]—Heals a friendly target for 64 to 78.

Walkpath - a comment from http://www.wowhead.com/npc=3205/zalazane#comments
 He walks up onto the same ledge as the one where you get Minshina's skull   (//www.wowhead.com/?quest=808), and you can walk up the ledge from behind.

Everything can be seen here : https://www.youtube.com/watch?v=h3pBIJMYEa8

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/831

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3030/commits/a51429b2d76e569feb0f1e8aab70eba382a883cd
