### ISSUE TITLE
Shadowmoon Technician's Proximity Bomb (Blood Furnace Normal)

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#847]
Originally reported by: **Curly (Bitbucket: [Curlyfry](https://bitbucket.org/Curlyfry), GitHub: Unknown)**

---

The Proximity Bomb will explode even though no one is near it and will deal its damage twice.

Proof: http://puu.sh/ovYfe/319703eed6.jpg

Happens every pull and its even wiped us multiple times because of the insane amount of damage it deals. We had the mob stunned and were standing on the other side of it and the Proximity Bomb still exploded and hit me and the tank twice each/

Spell 30846,32784

http://db.looking4group.eu/?spell=30846 , http://db.looking4group.eu/?spell=32784#

gameobjects which cast dmg spell:

http://db.looking4group.eu/?object=181877 http://db.looking4group.eu/?object=182607 

Bomb Spells: 30844 32786

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3202
