### ISSUE TITLE
Quest "You're Fired!"

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#848]
Originally reported by: **Anonymous**

----------------------------------------

When using a key, the boss doesn't appear

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/852

**Comment by Saltgurka** [comment]
Can't reproduce. 
You need to activate all 5 pillars, which means you need 5 keys. 

"When using a key, the boss doesn't appear"
That suggests you only used one key.

Reopen if there is still a problem
