### ISSUE TITLE
Leashing Range

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#857]
Originally reported by: **Anonymous**

----------------------------------------

Mobs are unable to be kited or killed very far from their orignal patrol points. They reset at roughly 50-60 Yards, even with constant spamming of Instant Abilities. (Such as Ice Lance).

You should be able to keep mobs in combat and kite / kill them away from their orignal spawn. 

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/861

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/2925
