### ISSUE TITLE
Some NPC groups in nagrand

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#877]
Originally reported by: **Bulldoze (Bitbucket: [Legitcow](https://bitbucket.org/Legitcow), GitHub: Unknown)**

---

Windrocs, They are meant to fly together in the air

[Pack 1](http://i.imgur.com/ogjXAIT.jpg)

[Pack 2](http://i.imgur.com/Mwb8Jnz.jpg)

[Pack 3](http://i.imgur.com/qrUE4Lj.jpg)

Talbuks, meant to run together in a group:

[Pack 1](http://i.imgur.com/5GcoHmi.jpg)

[Pack 2](http://i.imgur.com/B7ViB4E.jpg)

Will update if I find more packs.

_You probably want some proof for these, but as it would be very hard to find that since these are some very minor things in world of warcraft. So its up to you if you wanna fix these, but if you don't since I dont add any further proof, it is ok to me. I just wanna report everything that looks bugged to me._

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/881

**Comment by Saltgurka** [comment]
The windrocs were removed from the DB at some point. They were removed from retail in 2.2 so I won't bother readding and giving them a path.

The Talbuks will be fixed in the next update (https://gist.github.com/Saltgurka/003639441a3fc7d7133f31595282c4bf)
