### ISSUE TITLE
Zeth'gor must burn! - can only get on torch

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#887]
Originally reported by: **Larde (Bitbucket: [Larde](https://bitbucket.org/Larde), GitHub: Unknown)**

----------------------------------------

If you are doing the Zeth'gor must burn! quest you can have only one Bleeding Hollow Torch at a time in your inventory. The mobs won't drop any more. 
What I searched in wowhead, in live it should drop more torches even though you got one in your inventory.

After blazing it (Kappa) and using the lit torch on a building I get an instant drop from an peon.

----------------------------------------
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/891

**Comment by AnonXS** [comment]
-- Quest Convenience 
UPDATE `item_template` SET `stackable` = 4 WHERE `entry` = 31346; -- 1
