### ISSUE TITLE
Omor the Unscarred - Knockback on melee

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#915]
Originally reported by: **Larde (Bitbucket: [Larde](https://bitbucket.org/Larde), GitHub: Unknown)**

---

Time to time Omor the Unscarred hits the main target with melee and it knocks the tank back to africa.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/918

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3205
