### ISSUE TITLE
No death animation on players

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#920]
Originally reported by: **Anonymous**

---

Hey, just to let you know the death animations of players does not work.
Also Shattered hand Grunt is only walking, they dont run

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/923

**Comment by Saltgurka** [comment]
https://github.com/Looking4Group/L4G_Core/issues/1088
