### ISSUE TITLE
Mining nodes

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#921]
Originally reported by: **Anonymous**

---

The mining nodes in searing gorge for example will stack up to each other. There can be 1xmithril node, 1xtruesilver node, 1xdark iron node on top of each other. 

Also, small thorium vein dropped me an arcane crystal.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/924

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/blob/master/sql/updates/world/088_03_02.17.sql
