### ISSUE TITLE
Felguard intercept bug

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#937]
Originally reported by: **Anonymous**

---

Felguard intercept spell just stuns and damages the target, the felguard does actually move when charging.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/940

**Comment by Saltgurka** [comment]
General charge animation issue. Refer to https://github.com/Looking4Group/L4G_Core/issues/474
