### ISSUE TITLE
Windfury Totem

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#957]
Originally reported by: **yoritomo (Bitbucket: [Fashionspine](https://bitbucket.org/Fashionspine), GitHub: Unknown)**

---

The extra attack from the windfury totem buff is not procing off of instant attacks.  It does proc off of "on next swing attacks" like heroic strike.

Spent about 700 rage with a stopcasting macro testing it with hamstring and saw 0 procs.

thanks

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/960

**Comment by Saltgurka** [comment]
Comments on this issue are all over the place about different issues.

Closing this since the original issue was proven invalid. Create separate issues for everything else
