### ISSUE TITLE
Sunstrider Isle bugs (minor)

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#962]
Originally reported by: **Anonymous**

---

Warlock pet ain't following sometimes, specially in buildings. There is a noticeable bug with the ramps, despite having perfectly good LoS it says you don't and have to be in melee range when there is a mob in any kind of ramp (buildings or natural as ramps), doesn't matter it almost has no degree. And in the Academy there was one wraith on the top, I think it was the first one, that despite dead you can't loot him and still hits you. 

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/965

**Comment by Saltgurka** [comment]
These sounds like general issues that are not specific to Sunstrider Isle. Maps need to be fixed etc.

Closing this
