### ISSUE TITLE
[QUEST] Administering the salve

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#964]
Quest: http://db.hellfire-tbc.com/?quest=9447

You're supposed to use Healing Salve on Debilitated Mag'har grunts. That's supposed to turn them into healthy Clan Grunts. It also states this on the items tooltip description: http://db.hellfire-tbc.com/?item=23394

You can use the salve on the same grunt an infinite amount of times. It stays Debilitated and you still get quest progression.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/967

**Comment by Saltgurka** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3472
