### ISSUE TITLE
Spirit of redemption can be healed

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#968]
Originally reported by: **meme (Bitbucket: [homemer](https://bitbucket.org/homemer), GitHub: Unknown)**

---

Spirit of redemption does not spawn at full health and is a valid target for heals. Spirit of redemption should not be a valid target for spells.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/971

**Comment by Saltgurka** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3029
