### ISSUE TITLE
Gathering Node Pooling (Gameobjects)

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#991]
Originally reported by: **Novin (Bitbucket: [Novins](https://bitbucket.org/Novins), GitHub: Unknown)**

---

It seems to be that all possible spawn locations are always 'used'. Many times i see multiple nodes on the exact same spot. Or 5-6 nodes just a few steps from each other.
Also when the server restarts/crahes all the nodes are back instantly.
I haven't confirmed if it''s the same in outland, but all of vanilla nodes al bugged this way.
This might destroy the economy if not fixed.

---
- Bitbucket: https://bitbucket.org/looking4group_b2tbc/looking4group/issue/994

**Comment by AnonXS** [comment]
https://github.com/Looking4Group/L4G_Core/pull/3175/commits/c5c3a31b6eafbac6304bad1ff10c3a81aacae6b6
